### ISSUE TITLE
Hash the File

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#10]
## AIM

Create a Script that can hash a given file using specific algorithms like MD-5, SHA-256 and SHA-512.

## Languages

- Python
- Javascript

## Details

In this Script, you have to make use of File Handling and Hashing Functions to hash the given file.

**Comment by sanket143** [comment]
we already have a tool for that.
```sh
$ md5sum filename # will give hash of that file
```

**Comment by HarshCasper** [comment]
But it is not available for Windows Users. I am looking at a script which can make use of specific libraries and take user's choice to hash the file and produce the output.

**Comment by sanket143** [comment]
Can I work on this?

**Comment by HarshCasper** [comment]
Surely. I have assigned you the Issue.
