### ISSUE TITLE
Scrap Devpost Project

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#1002]
# Description

Create a Script to scrap DevPost Project. The script should get a Hackathon Page as a dynamic argument and it should extract the following: 

- Name of the Project (Title)
- Technology Stack of the Project (Built with)
- Images/Videos linked
- Subtitle of the Project

Even better would be a utility where all the projects can be randomly allocated in separate spreadsheets by passing a value which denotes the number of partitions needed for the same. But it can be kept as an optional in the final PR.

## Language

- [X] Golang
- [X] Javascript
- [X] Python

**Comment by jhamadhav** [comment]
> Even better would be a utility where all the projects can be randomly allocated in separate spreadsheets by passing a value which > denotes the number of partitions needed for the same. But it can be kept as an optional in the final PR.

Hey @HarshCasper the first 4 requirements are clear, can you please elaborate more on the last part?

**Comment by HarshCasper** [comment]
> > Even better would be a utility where all the projects can be randomly allocated in separate spreadsheets by passing a value which > denotes the number of partitions needed for the same. But it can be kept as an optional in the final PR.
> 
> Hey @HarshCasper the first 4 requirements are clear, can you please elaborate more on the last part?

Subtitle means the basic project pitch.

**Comment by jhamadhav** [comment]
// Even better would be a utility where all the projects can be randomly allocated in separate spreadsheets by passing a value which > denotes the number of partitions needed for the same. But it can be kept as an optional in the final PR.

No this part..

**Comment by HarshCasper** [comment]
> // Even better would be a utility where all the projects can be randomly allocated in separate spreadsheets by passing a value which > denotes the number of partitions needed for the same. But it can be kept as an optional in the final PR.
> 
> No this part..

Ah! This is an interesting use-case. 

I have mentored and judged at a lot of Hackathons and usually we are passed a sheet where we have to rank the projects developed by these teams. 

So whatever projects are scrapped, divide them randomly across multiple sheets. You can take the number of sheets required and the number of projects in each sheet from the user. 

Hope that helps :)

**Comment by jhamadhav** [comment]
> > // Even better would be a utility where all the projects can be randomly allocated in separate spreadsheets by passing a value which > denotes the number of partitions needed for the same. But it can be kept as an optional in the final PR.
> > 
> > No this part..
> 
> Ah! This is an interesting use-case. 
> 
> I have mentored and judged at a lot of Hackathons and usually we are passed a sheet where we have to rank the projects developed by these teams. 
> 
> So whatever projects are scrapped, divide them randomly across multiple sheets. You can take the number of sheets required and the number of projects in each sheet from the user. 
> 
> Hope that helps :)

It is only if the hackatons has finished, right?

**Comment by HarshCasper** [comment]
> > > // Even better would be a utility where all the projects can be randomly allocated in separate spreadsheets by passing a value which > denotes the number of partitions needed for the same. But it can be kept as an optional in the final PR.
> > > No this part..
> > 
> > 
> > Ah! This is an interesting use-case.
> > I have mentored and judged at a lot of Hackathons and usually we are passed a sheet where we have to rank the projects developed by these teams.
> > So whatever projects are scrapped, divide them randomly across multiple sheets. You can take the number of sheets required and the number of projects in each sheet from the user.
> > Hope that helps :)
> 
> It is only if the hackatons has finished, right?

Yeah. Once the projects are submitted and the judging round would start.

**Comment by jhamadhav** [comment]
oh ok, that's what I thought.
Can I work on this?
