### ISSUE TITLE
Script to download Tweet Images

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#1003]
# Description

Create a Script to download all the Images associated with your tweets. All the Images should be download locally along with a CSV file accompanying them, which contains the Image ID and the tweet they were linked with.

## Language

- [X] Go
- [X] Javascript
- [X] Python

**Comment by SalmaZakaria** [comment]
Could you please assign this to me?
I am GSSOC 21 Participant

**Comment by YashKandalkar** [comment]
@HarshCasper any chance this can be assigned to me?

**Comment by HarshCasper** [comment]
Sure @YashKandalkar
