### ISSUE TITLE
Script to find Twitter Followers overlap

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#1004]
# Description

Create a Script to find Twitter Followers overlap. The Script should take two Twitter usernames and find any overlap between their followers in an efficient way.

## Language

- [X] Go
- [X] Javascript
- [X] Python

**Comment by jhamadhav** [comment]
This sounds really interesting to work on. 
@HarshCasper please assign me this issue, I would love to work on this.
