### ISSUE TITLE
Script to return random YouTube videos

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#1005]
# Description

Create a Script to return random YouTube videos. You may use YouTube Data v3 API to achieve the same.

## Language

- [X] Go
- [X] Javascript
- [X] Python

**Comment by reshchat** [comment]
Hey, I am a GSSOC'21 participant . can you please assign this issue to me @HarshCasper

**Comment by vybhav72954** [comment]
> Hey, I am a GSSOC'21 participant . can you please assign this issue to me @HarshCasper

Sure thing

**Comment by harshakhmk** [comment]
@reshchat  are u still working on it, if not @HarshCasper  can you assign me this

**Comment by realhunter7869** [comment]
Hey, I am not a GSSOC'21 Participant but I would love to contribute on this feature in python. Can you assign me this task?

**Comment by realhunter7869** [comment]
@HarshCasper

**Comment by Sukriti-sood** [comment]
@realhunter7869 Just comment  /assign you will get assigned to this issue .

**Comment by realhunter7869** [comment]
Yes @Sukriti-sood I knew that but was wanting a confirmation from @HarshCasper since I am not a GSSOC Participant

**Comment by Sukriti-sood** [comment]
> Yes @Sukriti-sood I knew that but was wanting a confirmation from @HarshCasper since I am not a GSSOC Participant 

Anyone can Contribute, no need to be a part of any program and moreover GSSOC21 is already over.

**Comment by realhunter7869** [comment]
Alright! Thanks @Sukriti-sood
