### ISSUE TITLE
Scrap Good First Issues from GitHub Repositories

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#1006]
# Description

Create a Script to scrap Good First Issues from GitHub Repositories. We can have the GitHub repositories in the following ways: 

- Having a JSON File where all the repositories are stored.
- Scrapping from the top repositories that are trending on GitHub Explore 
- Scrapping from the repos that we/or someone else has starred 

You can have better ways of taking the inputs, but these three are the most important ones, that we are looking for.

## Language

- [X] Golang
- [X] Javascript
- [X] Python

**Comment by jhamadhav** [comment]
Hey, @HarshCasper I'm almost done with my previous issues can I work on this?
