### ISSUE TITLE
Sending SMS using FAST2SMS

### ISSUE THREAD

**Issue by prathimacode-hub** [HarshCasper/Rotten-Scripts#1008]
# Description

This script sends SMS promptly using FAST2SMS API with GUI Interface.  

## Language

- [x] Python

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Sending SMS using FAST2SMS | This script sends SMS promptly using FAST2SMS API with GUI Interface to any number efficiently with user specified text message | GSSOC'21, python | @prathimacode-hub |

**Comment by prathimacode-hub** [comment]
I'm a GSSOC'21 participant. Can you assign this issue to me? @HarshCasper

**Comment by prathimacode-hub** [comment]
Can you please add GSSoC'21 label? So that I could create a pull request. @HarshCasper

**Comment by vybhav72954** [comment]
We don't accept GUI-based scripts!
Closing the Issue, feel free to take another issue
