### ISSUE TITLE
bug in Email_Scrape_From_Webpage

### ISSUE THREAD

**Issue by ireneelizabethsabu** [HarshCasper/Rotten-Scripts#1011]
# Description 
the code produce a traceback on line number 52

## Checklist

|name|about|labels|assignees|
|----|-----|------|---------|
|Email_Scrape_From_Webpage|traceback in line number 52|GSSOC21 |@ireneelizabethsabu|

**To Reproduce**
1. Go to terminal
2. Run the code 
3. See error

**Expected behavior**
![Screenshot from 2021-04-22 12-21-47](https://user-images.githubusercontent.com/56963461/115669020-72eb9c00-a365-11eb-9cdd-165ca8a3ca35.png)

**Screenshots**
![Screenshot from 2021-04-22 12-21-12](https://user-images.githubusercontent.com/56963461/115669009-6ebf7e80-a365-11eb-93bb-0f532bc10cac.png)

**Comment by ireneelizabethsabu** [comment]
\assign

**Comment by ireneelizabethsabu** [comment]
@HarshCasper Can you please assign this issue to me.

**Comment by vybhav72954** [comment]
Thanks for this issue. Looking forward to the solution

**Comment by ireneelizabethsabu** [comment]
Can you please add the level tag @vybhav72954 .
