### ISSUE TITLE
Disconnect LinkedIn Connections

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#1019]
# Description

Given a list of first-degree connections in CSV/JSON, disconnect them on LinkedIn through an automation script. You can go a step ahead, to provide the users with an option to unfollow them instead of disconnecting, however, this feature is entirely optional.

## Language

- [X] Go
- [X] Javascript
- [X] Python
- [X] BASH

**Comment by Sukriti-sood** [comment]
I would like to work on this.

**Comment by Sukriti-sood** [comment]
@HarshCasper  @vybhav72954 For  unfollow or disconnecting Options. Script should ask options for every user or for one time ony...?
