### ISSUE TITLE
Script to download LinkedIn Learning Videos

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#1021]
# Description

Create a Script to download LinkedIn Learning Videos. This Script should be good enough to download videos as of now, not entire courses. P.S: Let me know if you need access to any LinkedIn Learning Course to try your script out. 

## Language

- [X] Golang
- [X] Javascript
- [X] Python
- [X] BASH

**Comment by jayant766** [comment]
Please assign me this issue under LGMSOC'21

**Comment by Sukriti-sood** [comment]
@HarshCasper Can I Create a PR for this issue?

**Comment by HarshCasper** [comment]
> @HarshCasper Can I Create a PR for this issue?

Be careful with your credentials now :wink:
