### ISSUE TITLE
Script to scrap Alumni Network through LinkedIn

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#1023]
# Description

Create a Script to scrap Alumni Network through LinkedIn. 

## Language

- [X] Go
- [X] Javascript
- [X] Python
- [X] BASH

**Comment by jhamadhav** [comment]
Alumni network as in?

**Comment by HarshCasper** [comment]
> Alumni network as in?

Scrap the LinkedIn Profiles who have studied in the same College/University as you. We are looking to capture the following data points through them: 

- Name
- Current Job 
- Skills 
- Degree of Connection

**Comment by rahulraikwar00** [comment]
> > Alumni network as in?
> 
> Scrap the LinkedIn Profiles who have studied in the same College/University as you. We are looking to capture the following data points through them: 
> 
> - Name
> - Current Job 
> - Skills 
> - Degree of Connection

And what about the working people? @HarshCasper

**Comment by jhamadhav** [comment]
> 
> 
> > Alumni network as in?
> 
> Scrap the LinkedIn Profiles who have studied in the same College/University as you. We are looking to capture the following data points through them:
> 
>     * Name
> 
>     * Current Job
> 
>     * Skills
> 
>     * Degree of Connection

oh I see so we first get a LinkedIn profile and we scrap data about the people related to the user connect via college, cool 👍

**Comment by HarshCasper** [comment]
> > > Alumni network as in?
> > 
> > 
> > Scrap the LinkedIn Profiles who have studied in the same College/University as you. We are looking to capture the following data points through them:
> > 
> > * Name
> > * Current Job
> > * Skills
> > * Degree of Connection
> 
> And what about the working people? @HarshCasper

Well this Script is about getting the profiles about working people itself. We can add additional data points about their year of graduation but keep that as optional as of now.

**Comment by rahulraikwar00** [comment]
> > > Alumni network as in?
> > 
> > 
> > Scrap the LinkedIn Profiles who have studied in the same College/University as you. We are looking to capture the following data points through them:
> > ```
> > * Name
> > 
> > * Current Job
> > 
> > * Skills
> > 
> > * Degree of Connection
> > ```
> 
> oh I see so we first get a LinkedIn profile and we scrap data about the people related to the user connect via college, cool 👍

 Reinventing the wheel is  bit messy here.. I mean it can be done with any third party Api or LinkedIn Library In python in couple line of code I guess.
@HarshCasper what do you think?

**Comment by HarshCasper** [comment]
> > > > Alumni network as in?
> > > 
> > > 
> > > Scrap the LinkedIn Profiles who have studied in the same College/University as you. We are looking to capture the following data points through them:
> > > ```
> > > * Name
> > > 
> > > * Current Job
> > > 
> > > * Skills
> > > 
> > > * Degree of Connection
> > > ```
> > 
> > 
> > oh I see so we first get a LinkedIn profile and we scrap data about the people related to the user connect via college, cool +1
> 
> Reinventing the wheel is bit messy here.. I mean it can be done with any third party Api or LinkedIn Library In python in couple line of code I guess.
> @HarshCasper what do you think?

You are free to pick whatever you feel is good for the job. If the script is too basic, we can add more features to make it a full-fledged CLI.

**Comment by iamakkkhil** [comment]
@Wittty-Panda any updates?

**Comment by Wittty-Panda** [comment]
@iamakkkhil I have started on it but having some error in code still working on them
