### ISSUE TITLE
Script to collect spam/invalid Pull Requests across GitHub Repositories

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#1025]
# Description

Create a Script to collect spam/invalid Pull Requests across GitHub Repositories. The Script should analyze the repositories stored in a CSV/JSON File and should capture the following data points: 

- Link of the PR 
- PR Author 
- Number of Files changed 
- Number of PR Comments 
- PR Reviewer(s) 

You can also add features to have the dataset collected in a CSV/JSON across all repositories or having separate CSV/JSON for each repository.

## Language

- [X] Go
- [X] Javascript
- [X] Python

**Comment by vybhav72954** [comment]
I can do this XD

I have a script for this already XD

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by rahulraikwar00** [comment]
> I can do this XD
> 
> I have a script for this already XD

I was gonna comment the same..XD

**Comment by vybhav72954** [comment]
@AshuKV Updates?

**Comment by AshuKV** [comment]
@vybhav72954  I am currently working on this issue, will send PR within 3 days.

**Comment by Wittty-Panda** [comment]
Guess the guys didn't have the script ready after all, I won't go boasting that I have the script already but I would like to try my hand at finding and implementing the solution for the problem. Kindly assign this task to me and provide me with an opportunity to find a solution for this.

**Comment by sumitgsh** [comment]
@HarshCasper @vybhav72954 Could You please assign this to me Would love to work on that..
Just one question regarding the issue is like the details of repositories like the username n all will be taken from the csv/json file right?

**Comment by HarshCasper** [comment]
> @HarshCasper @vybhav72954 Could You please assign this to me Would love to work on that..
> Just one question regarding the issue is like the details of repositories like the username n all will be taken from the csv/json file right?

Prefer a JSON file.
