### ISSUE TITLE
Reddit Scraper

### ISSUE THREAD

**Issue by RohiniRG** [HarshCasper/Rotten-Scripts#1045]
# Description

Describe the new feature you are proposing.

| name           | possible solution  | assignees                                                      |
| ---------------  | ------- | -------------------------------------------------------------- |
| Reddit Scrapper  | Using Python to scrape the post of a particular subreddit to obtain information of author and content upvotes and so on | @RohiniRG  |

**Comment by RohiniRG** [comment]
@vybhav72954 @HarshCasper could you please have a look and let me know if I can work on this.

**Comment by vybhav72954** [comment]
@RohiniRG LGTM, eel free to make a PR, i am extremely sorry I was a bit busy, Review process wont take long from now.
