### ISSUE TITLE
QR based python Excel Attendance system

### ISSUE THREAD

**Issue by Yuvraj-kadale** [HarshCasper/Rotten-Scripts#1048]
# Description

- This project will be done in two steps. 

1. QR Generation 
2. QR Scanning

### QR Generation

Database of students will be provided in "Name - Roll number" format.
The QR code will store the values of "Name-Roll number" as UID
This script on run will generate the QR codes of all the students and save that as per their UID

### QR Scanning

Here the students will scan their QR codes.. and their attendance will be logged , separating the name and roll numbers along with the time of log.

The GUI will ask for the class details such as :
1. Couse name
2. course code
3. teachers names 
4. time of class 
5. Email, etc. 

Once the Qr Codes are scanned .. the Attendance sheet will be mailed to the mail ID provided in the GUI.

 
## Language

- [x] Python

## Checklist:

- **Details on the Script**
[x] Automated Excel Creation
[x] Auto Generation of QR codes
[x] Automated mailing system

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| QR-Attendance | This Script is automation for attendance using QR codes | Gssoc21 | @Yuvraj-kadale |

**Is your feature request related to a problem? Please describe.**: 

During this pandemic classes are going online and manual system of attendance eats up lot of time.

**Describe the solution you'd like**: 

How cool will it be to have automated attendance based on the QR codes provided to each students. This will be also helpful for offline classes.

**Comment by vybhav72954** [comment]
Hey @Yuvraj-kadale We generally dont accept GUI-based scripts here.

**Comment by vybhav72954** [comment]
> @vybhav72954 oh.. I can remove the GUI then .. can do this on terminal itself.
> I have edited the Issue. Let me know if that works, or do I need to create a new issue?

Sounds good

**Comment by HarshCasper** [comment]
We don't need management apps. They require to have a good user experience, server and database layers that don't add up in a simple script.
