### ISSUE TITLE
Script to convert Image to Pencil Sketch

### ISSUE THREAD

**Issue by Manasi2001** [HarshCasper/Rotten-Scripts#1050]
# Description

The script can be used to convert a RGB image to pencil sketch in 4 easy steps.

## Language

- ✅ Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Image to Pencil Sketch | Convert RGB image to pencil sketch. | GSSoC'21 python | @Manasi2001 |

**Comment by vybhav72954** [comment]
@Manasi2001 We already have a similar script [here](https://github.com/HarshCasper/Rotten-Scripts/blob/master/Python/Image_Sketch/Sketch.py)

If you want you can update the README for the script, but I cant accept this as of now

**Comment by Manasi2001** [comment]
@vybhav72954 mine is so much better, nicely put and refined than the one that's present. You can check out my PR for the screenshots. 😅
If nothing can be done, then I'll do the README part.

**Comment by vybhav72954** [comment]
TBH that fair

> @vybhav72954 mine is so much better, nicely put and refined than the one that's present. You can check out my PR for the screenshots. 😅
> If nothing can be done, then I'll do the README part.

Counter proposal.

- I will reopen the PR.
- Replace your script/README, and remove the out-of-date directory. (Please don't delete the original directory, just replace everything with your updated files, so that the commit history is maintained).
- The script is kind of the same, but your README is still much better, so this would be a great update for us.

Sounds good?

**Comment by Manasi2001** [comment]
So basically, once you reopen the PR, all I need to do is remove that old code from 'Image_Sketch' folder and add mine there right?
That'll be great. Thanks!
