### ISSUE TITLE
Stalker

### ISSUE THREAD

**Issue by Sukriti-sood** [HarshCasper/Rotten-Scripts#1053]
# Description

Like If we want to search or stalk any Person, First We google, Then We search it on Any or every social platform with Information we know like Physical Appearance, Place of residence, Education, Age.
We can have a script that will automate the task of Stalking.

## Language
- [x] Go
- [x] Javascript
- [x] Python

## Checklist:

- **Details on the Script**

 ## Stalker

 #### Script to Stalk any Person, This Script will use Face Recognition feature and Outputs all the information in CSV format.

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Stalker  | Script to Stalk  | GSSOC21 |  |

**Comment by vybhav72954** [comment]
Sounds good

**Comment by Sukriti-sood** [comment]
@vybhav72954 Sorry by Mistake I removed my assignment, Please Assign me again

**Comment by YashKandalkar** [comment]
_Modern problems require modern solutions xD_

**Comment by HarshCasper** [comment]
@Sukriti-sood Are you planning to work on this further? 

(I have a similar script as part of my downstream fork :laughing: )

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood Are you planning to work on this further?
> 
> (I have a similar script as part of my downstream fork  )

Currently No
