### ISSUE TITLE
Python-Telegram bot

### ISSUE THREAD

**Issue by Namyalg** [HarshCasper/Rotten-Scripts#106]
A telegram bot that can send memes, jokes, riddles and much more. A python-telegram wrapper is used.

**Comment by HarshCasper** [comment]
I have assigned you the Issue @Namyalg 

You can make a PR on that

**Comment by bagofcodes** [comment]
Is the issue still available? @HarshCasper

**Comment by DevChoganwala** [comment]
@HarshCasper I would like to work on this issue if still available.
