### ISSUE TITLE
Blood Content Alcohol in python 

### ISSUE THREAD

**Issue by soumik2012** [HarshCasper/Rotten-Scripts#1064]
# Description

it tell you how amount of alcohol you drink and what is percentage of alcohol content in the blood

## Language

- [x] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Blood Alcohol Content   | it tells you how the amount of alcohol you drink and what is the percentage of alcohol content in the blood | GSSOC'21 | /assign  |

**Is your feature request related to a problem? Please describe.**: 

 This is a feature for a person when somebody is really drunk want to know how they drunk this will help you.

**Describe the solution you'd like**: 

Using the BAC formula I will calculate the blood in the person.

**Comment by vybhav72954** [comment]
Sounds good
