### ISSUE TITLE
Pdf2VideoConverter

### ISSUE THREAD

**Issue by Sukriti-sood** [HarshCasper/Rotten-Scripts#1069]
# Description
Take a PDF file, extract the text from it, convert it to audio format and attach that audio to the video provided by the user. 

- [x] Python

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
|Pdf2Video Converter | In Description above | feature  | [Sukriti-sood]( https://github.com/Sukriti-sood)|

**Comment by vybhav72954** [comment]
Nice idea. Though pretty specific. But LGTM

**Comment by kskrao219** [comment]
i can work on this, please assign me this

**Comment by HarshCasper** [comment]
Hi @kskrao219 

A PR for this is open. Kindly wait for it to be closed/merged.
