### ISSUE TITLE
Send SMS using FAST2SMS in python

### ISSUE THREAD

**Issue by prathimacode-hub** [HarshCasper/Rotten-Scripts#1086]
# Description

This project is SMS sender using FAST2SMS API promptly with user defined text message

## Language

- [ ] Go
- [ ] Javascript
- [x] Python
- [ ] Other (Please specify)

## Checklist:

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| SMS Sender using FAST2SMS in Python | Sends SMS promptly with user defined message | GSSOC21 | @prathimacode-hub |

**Comment by prathimacode-hub** [comment]
I have added up a related PR (#1087) to this concerned issue. Kindly got through it. @vybhav72954

**Comment by harshakhmk** [comment]
I would like to work on this issue @HarshCasper
