### ISSUE TITLE
Dictionary in Python

### ISSUE THREAD

**Issue by akash435** [HarshCasper/Rotten-Scripts#1103]
Want to add a Dictionary created under tkinter GUI in python.
In this for data, I will be using a json file which will be imported in python code.
In this code I will also be implementing the case 
 i.) giving multiple meaning is there are many meanings
 ii.) giving meaning of closest word, if entered something wrong.

The dicitonary gui windows will look like this,
![1](https://user-images.githubusercontent.com/57003737/121775124-5a4c7500-cba3-11eb-8239-bc8cd3dea86f.png)

**Comment by akash435** [comment]
@HarshCasper , can you please assign me this under LGM SOC

**Comment by akash435** [comment]
@HarshCasper , can you please add the LGM SOC label, as i want to contribute under it.

**Comment by HarshCasper** [comment]
We don't accept GUI Apps. Kindly read the Contribution Guideline and study the existing code before contributing.
