### ISSUE TITLE
TIC TAC TOE game in python

### ISSUE THREAD

**Issue by akash435** [HarshCasper/Rotten-Scripts#1104]
Want to add TIC TAC TOE game in python.

The game will be single player mode.

The player has to play with computer , and computer also makes optimal moves by analyzing the moves of player.

The game will be totally played on console by running the source code.

**Comment by akash435** [comment]
@HarshCasper , can you please add LGM SOC label, as i want to contribute under it.

**Comment by HarshCasper** [comment]
We don't need games that doesn't add any productivity value or whatsoever.
