### ISSUE TITLE
Minesweeper

### ISSUE THREAD

**Issue by Nihir2904** [HarshCasper/Rotten-Scripts#1106]
------------------------------------------------------------------------------------------------------------------------------------
Title | About | Name | Label
---|---|---|---
Minesweeper | Play minesweeper on your command line | Nihir Shah | Feature Request

Define You:
- [x] Participant
- [ ] Mentor

LGM-SOC'21 

Using oops in python, play minesweeper on your command line.

**Comment by HarshCasper** [comment]
We don't need games that doesn't add any productivity value or whatsoever.
