### ISSUE TITLE
Want to add Library Management system(Python script)

### ISSUE THREAD

**Issue by Hardikpoudel** [HarshCasper/Rotten-Scripts#1108]
# Library management system created using python script

Work on importing modules on python where user can borrow or return the book from the library

| Library management system | Help keeping track of borrowed book and generate bill/ invoice in library                                                | possible solution  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Display the list of books along with its availability | Helps library for managing their customer track | Do you have a possible solution in your mind? | self-assign if you want to work on this feature else blank |

![image](https://user-images.githubusercontent.com/60287100/121803222-3b5fe880-cc60-11eb-9e4e-f0143fe4935d.png)

**Comment by HarshCasper** [comment]
We don't management apps. They require to have a good user experience, server and database layers that don't add up in a simple script. As a librarian, I will not rely on a script to manage the library and manage the customer track.
