### ISSUE TITLE
Guess The Game(Cricket Game) Using Bash Scripting

### ISSUE THREAD

**Issue by Hardikpoudel** [HarshCasper/Rotten-Scripts#1109]
### Guess the game is simple program developed using bash scripting where you are provided with the list of countries and need to find select the correct answer, may be this didn't excites you but when you play it surely will

![image](https://user-images.githubusercontent.com/60287100/121803357-dfe22a80-cc60-11eb-99f0-91df54f88c5b.png)

**Comment by HarshCasper** [comment]
We don't need games that doesn't add any productivity value or whatsoever.
