### ISSUE TITLE
Mass-Email-Sender

### ISSUE THREAD

**Issue by deepraj1729** [HarshCasper/Rotten-Scripts#111]
# Mass-Email-Sender

A Python script to send mass emails by :
1. Reading all the list of email ids from CSV and sending it in a loop
2. As well as by making a list of email ids inside the script and then sending it

# Later
Can be converted into a Python package 

Mentions:
@HarshCasper

**Comment by HarshCasper** [comment]
Thanks for raising this Issue @deepraj1729 

I am assigning you this Issue. Please follow the `CONTRIBUTIONS` guidelines before making a Pull Request 🙌🤗

**Comment by abhishekgupta368** [comment]
can I do it?

**Comment by deepraj1729** [comment]
@abhishekgupta368 I have already started building the Python package. You colab with me if u wish. I'm not launching it here for licensing purposes.

**Comment by mrpandya** [comment]
@HarshCasper can i work on this issue if no one is working on it??

**Comment by vybhav72954** [comment]
@HarshCasper Is this still open in python?
