### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [HarshCasper/Rotten-Scripts#1117]
Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@HarshCasper pls assign me this issue.

**Comment by ishitakapoor26** [comment]
Like this 

![score card](https://user-images.githubusercontent.com/78542333/122355049-32785b00-cf6f-11eb-9522-60f7ca59d3dd.PNG)

**Comment by HarshCasper** [comment]
Hi @ishitakapoor26 

We won't add the scorecard in README.md. The project is a part of many OSS program and we don't wish to add them up specific to one program. I will put the labels accordingly after which we can score the contributions.
