### ISSUE TITLE
speech recognizer using python

### ISSUE THREAD

**Issue by Umesh-01** [HarshCasper/Rotten-Scripts#1148]
# Description

I want to make a speech recognizer using Python. With this human voice can be converted into text. It uses speech recognition module to do this job.

| name            | problem/motivation                                                  | possible solution  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| speech recognizer | to convert speech into text | yes, I will be using a speech recognizer api for this task | self-assign |

**Comment by Umesh-01** [comment]
@HarshCasper should I work on this also??

**Comment by iamakkkhil** [comment]
Hey @Umesh-01 Issue no #1150 looks same to me. Can I know the difference between the two?

**Comment by Umesh-01** [comment]
no @iamakkkhil they are different, some code is common between the two..
It is a speech recognizer that will recognize our speech and will tell us what we said by speaking the sentence or dialogue...
But in issue #1150 I am using pywikihow library so that the user can ask **how to** questions using voice and then it will speak up the results, so for recognizing and speaking up the results the code is same...

That's the reason the code looking same to u, but they are different issues... 
I hope it make sense 🙂
