### ISSUE TITLE
asking "how to" type questions

### ISSUE THREAD

**Issue by Umesh-01** [HarshCasper/Rotten-Scripts#1150]
# Description

I want to add a feature in which the user can ask (using voice) how to questions. It uses the voice recognizer to process the voice command and then a library/API to get the answers of how to type questions.

| name            | problem/motivation                                                  | possible solution  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| ask how to questions | to get answers of how to type questions easily in seconds using voice commands | I will be using python to add this feature with the help of voice recognizer api and a library for how to questions. | self-assign |

**Comment by Umesh-01** [comment]
@HarshCasper should I work on this??

**Comment by Kumaravinash9** [comment]
> @HarshCasper should I work on this??

Of Course @Umesh-01! you can go ahead.
