### ISSUE TITLE
Brute Force ZIP File Passwords using Python.

### ISSUE THREAD

**Issue by CYB3R-G0D** [HarshCasper/Rotten-Scripts#1166]
# Description

Brute Force ZIP File Passwords using Python.

## Language

- [x] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Brute Force ZIP | A python script to brute force zip file passwords | python | @cyb3r-g0d |

**Comment by iamakkkhil** [comment]
@CYB3R-G0D, Try to describe to issue appropriately by following the issue template. I request to edit the issue template first so that it can be easy for us to review, and understand what's the exact functionality of the code is

**Comment by CYB3R-G0D** [comment]
> @CYB3R-G0D, Try to describe to issue appropriately by following the issue template. I request to edit the issue template first so that it can be easy for us to review, and understand what's the exact functionality of the code is

Done ✌
