### ISSUE TITLE
Golang: Scrap Hackernews Comments

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#1170]
# Description

Create a Golang Script to scrap Hackernews comments from a thread. The script should return JSON / YAML data containing all the comments on the thread.

Use this: [Colly](http://go-colly.org/)

## Language

- [X] Go
- [ ] Javascript
- [ ] Python
- [ ] Other (Please specify)

**Comment by Sukriti-sood** [comment]
@HarshCasper I am little confused  about thread in HackerNews , Can u explain?

**Comment by HarshCasper** [comment]
We would need to scrap individual threads on Hacker News (HN) website for news at https://news.ycombinator.com

The threads look something like this: 

https://news.ycombinator.com/item?id=27750040

https://news.ycombinator.com/item?id=27744255
