### ISSUE TITLE
Python: Fetch all the Pull Requests created by a User on a GitHub Organization and store it in a Markdown Table

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#1171]
# Description

Create a Script to fetch all the Pull Requests created by a User on a GitHub Organization and store it in a Markdown Table.

The script should take the username and the organization name as an argument and result in a markdown file with a table with the following content: 

- Title of PR
- Link of PR
- Status (Merged/Closed)

## Language

- [X] Python

**Comment by payaldutta** [comment]
@HarshCasper Can I work on this?

**Comment by kadatatlukishore** [comment]
@HarshCasper , I am a newbie to contribution. Can you please tell me about the script that you want, are you going to consider any user inputs or as such.  I've done working on a script to fetch for "https://github.com/HarshCasper/Rotten-Scripts/pulls?q=is%3Apr+sort%3Acreated-desc". Should I fork and add the file and pull request if it's fine?

**Comment by kadatatlukishore** [comment]
![alt](https://raw.githubusercontent.com/kadatatlukishore/Contribution/main/git.jpg)

**Comment by HarshCasper** [comment]
Hi @kadatatlukishore

Are you working on this?

**Comment by Sukriti-sood** [comment]
@HarshCasper I am also in the queue if this issue is not assigned.

**Comment by kadatatlukishore** [comment]
Yes @HarshCasper I'm working on this. But can you please tell me if we are passing **username and the organization name as an argument** , Can you please provide me an example ? I am a newbie to contribution

**Comment by HarshCasper** [comment]
> Yes @HarshCasper I'm working on this. But can you please tell me if we are passing **username and the organization name as an argument** , Can you please provide me an example ? I am a newbie to contribution
> Like if you've worked on any organization, can you please name it. It will be helpful

Use Argument Parsers for the purpose: https://docs.python.org/3/library/argparse.html

I would like to see it as a CLI which can be fired like this: 

```
python3 fetch_contributions.py --username HarshCasper --organization moja-global
```

Use `harshcasper` as my username and `moja-global` as the organization I have worked with.

**Comment by kadatatlukishore** [comment]
Thanks @HarshCasper 
Will complete the work.

**Comment by kadatatlukishore** [comment]
Hey @HarshCasper , 
Is it ok to mention filename in the argument ?
**python fetch_contributions.py --username HarshCasper --organization moja-global --file markdown_file**
because the program returns string saying "Markdown File is successfully stored"
If it's I'll PR

**Comment by vybhav72954** [comment]
> Hey @HarshCasper ,
> Is it ok to mention filename in the argument ?
> **python fetch_contributions.py --username HarshCasper --organization moja-global --file markdown_file**
> because the program returns string saying "Markdown File is successfully stored"
> If it's I'll PR
> The sample file you'll find here - [Markdown File](https://github.com/kadatatlukishore/Contribution/blob/main/README.md)

If the only reason to have that argument is the statement `Markdown File is successfully stored`, then I doubt there is any need for that. If the argument Is essential for functionality, use the default argument maybe?

**Comment by kadatatlukishore** [comment]
Thanks @vybhav72954
