### ISSUE TITLE
Image Resizer

### ISSUE THREAD

**Issue by Cosine42** [HarshCasper/Rotten-Scripts#1187]
# Description

I want to add an Image Resizer script using Python.

## Language

- [x] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Image_Resizer | A script to resize images to any dimension | LGM-SOC | @Cosine42  |

**Describe the solution you'd like**: 

Resizing a given image according to new dimensions provided.

**Comment by Amankesarwani2202** [comment]
Hey I am interested in this issue can you please assign it to me.

Thanks in advance!
