### ISSUE TITLE
tic-tac-toe game 

### ISSUE THREAD

**Issue by Umesh-01** [HarshCasper/Rotten-Scripts#1195]
# Description

Describe the new feature you are proposing.

| name            | problem/motivation                                                  | possible solution  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| tic-tac-toe |  I want to create a tic-tac-toe game using python programming | yes | self-assign |

## Contributing As
- [x] LGM-SOC'21 Participant
- [x] Contributor

**Comment by whyadiwhy** [comment]
hey i want to work
