### ISSUE TITLE
Create a Subtitle Downloader

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#12]
## AIM

Create a Subtitle Downloader Script that can download Subtitles in specific Languages, for any Movie or an Online Show straight from your Command-Line.

## Languages

- Python

## Details

You can make use of a Database like [Subdb](http://thesubdb.com/) for your purpose and specific libraries like Requests and Beautiful Soup for scrapping the Subtitles and storing them.

**Comment by seema1711** [comment]
Can I work on this?

**Comment by HarshCasper** [comment]
You can complete the Issues that have been assigned to you currently. At a single time, only two issues can be assigned to a single person.

**Comment by ArvindAROO** [comment]
Is this done, Can I contribute

**Comment by HarshCasper** [comment]
@ArvindAROO This Issue is for the participants of ```Student Code-In``` Program.

**Comment by ArvindAROO** [comment]
Oh, Ok. Is it open, am I allowed to join

**Comment by seema1711** [comment]
Can I work on this?

**Comment by HarshCasper** [comment]
I have assigned you the Issue @seema1711 

You can work on this now

**Comment by HarshCasper** [comment]
Are you working on this @seema1711 ?

**Comment by seema1711** [comment]
Yes, it's a long procedure I need some time.
