### ISSUE TITLE
Script to bruteforce Admin Panels

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#124]
# Description

Create a Script that can brute-force Admin Panels on a Target Website.

## Language

- [X] Javascript
- [X] Python
- [X] Bash
- [X] Golang

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Adding a Script to Bruteforce Admin Panels|I'm looking to add more Scripts for Penetration Testing. This would allow me to find the Admin Panels on Websites|Python, JS, BASH, Golang, Medium, Student Code-In|`Open for Student-Code in Participants`|

**Is your feature request related to a problem? Please describe.**: I'm looking to add more Scripts for Penetration Testing. This would allow me to find the Admin Panels on Websites

**Describe the solution you'd like**: A Script to can fetch me the Admin Panel URL by brute-forcing all possible options.

**Additional context**: None

**Comment by mbcse** [comment]
Is it like we need to find admin login page link for a given website

**Comment by HarshCasper** [comment]
Yes @mbcse

**Comment by mbcse** [comment]
Okay would like to work on this

**Comment by HarshCasper** [comment]
I have assigned you the Issue @mbcse
