### ISSUE TITLE
Find list of E-Mail in a Webpage

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#125]
# Description

Create a Script that can find me the list of E-Mails on a Webpage.

## Language

- [X] Javascript
- [X] Python
- [X] Bash
- [X] Golang

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Find list of E-Mail in a Webpage|To scrap all the E-Mails in a Webpage|Python, JS, BASH, Golang, Medium|`Open to SCI-2020 Participants`|

**Is your feature request related to a problem? Please describe.**: I want a script that can scrap a Webpage and find all the E-Mails on that particular Webpage and display it on the Console.

**Describe the solution you'd like**: A Script that can showcase me all the E-Mail present on a Webpage.

**Comment by seema1711** [comment]
I want to work on this issue.

**Comment by HarshCasper** [comment]
Assigned to you @seema1711

**Comment by amandp13** [comment]
@HarshCasper I also want to work on this issue.

**Comment by amandp13** [comment]
@HarshCasper Please Review #257

**Comment by keshavnath** [comment]
I would like to work on this
