### ISSUE TITLE
[script request]: Background_Filler

### ISSUE THREAD

**Issue by S8s8Max** [HarshCasper/Rotten-Scripts#1264]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the script

Background_Filler will fill background of your terminal with poems or other texts.
The way of filling is like human-typing, so this is gonna be using while you are working to concentrate on your work. 

### Language

Python

### Is the feature request related to a problem? Please Specify.

no

### Describe the solution you'd like.

Using random module to choose speed of sleep function to make filling more human-like.

### Anything else?

DEMO is here. <a href="https://imgur.com/a/O5hifOi">Imgru post</a>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vybhav72954** [comment]
@HarshCasper What do you think about this idea?
