### ISSUE TITLE
Script to scrap an Instagram User's Followers and Following.

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#127]
# Description

Create a Script to scrap an Instagram User's List of Followers and Following.

## Language

- [X] Javascript
- [X] Python
- [X] Golang

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Scrap Instagram's User's Followers and Follwoing|Store the List of Followers and Following in a CSV-File|Python, JS, Golang, Hard, CH-2020|`Open for CH-2020 Participants`|

**Comment by aastha985** [comment]
I would like to work on this.

**Comment by aastha985** [comment]
I would like to work on this issue.

**Comment by HarshCasper** [comment]
I have assigned you the Issue @aastha985

**Comment by avinashkranjan** [comment]
@aastha985 Which language are you using to build the script? I'd like to build a script fro the same But I don't want both building it on the same language..

**Comment by aastha985** [comment]
> @aastha985 Which language are you using to build the script? I'd like to build a script fro the same But I don't want both building it on the same language..

I am doing it in Python

**Comment by avinashkranjan** [comment]
@aastha985 Okay..Then I'm left with JavaScript and Golang..
I'll be building this in JavaScript..  
Happy Coding.  👨🏻‍💻
@HarshCasper If you could assign me that'd be great

**Comment by HarshCasper** [comment]
I have assigned to you @avinashkranjan in Javascript
