### ISSUE TITLE
Create a Script to fetch Comments from a Code

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#128]
# Description

Create a Script to fetch Comments in a Code and save them in a `README` markdown file for easy display and understanding the Project Details.

## Language

- [X] Javascript
- [X] Python
- [X] Bash
- [X] Golang

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Script to fetch Comments from a Code|Save the Documentation Time with this Script|Python, JS, BASH, Golang, Hard, SCI-2020|`Open to SCI-2020 Participants`|

**Comment by gpsyrou** [comment]
Seems very interesting for my first time working in an open source. Can I work on this ? :)

**Comment by HarshCasper** [comment]
Hello @gpsyrou 

I am exhilarated to see that you are interested in taking up this Issue. Although this Issue is for `SCI-2020 Participants`, you can work on this in a specific language (Python/JS/Golang/BASH). Let me know the language on which you want to work, and I will assign it to you 🤗

**Comment by mbcse** [comment]
would like to work on this

**Comment by gpsyrou** [comment]
> 
> 
> Hello @gpsyrou
> 
> I am exhilarated to see that you are interested in taking up this Issue. Although this Issue is for `SCI-2020 Participants`, you can work on this in a specific language (Python/JS/Golang/BASH). Let me know the language on which you want to work, and I will assign it to you 🤗

Awesome, thanks a lot! I wound like to use Python for this.

**Comment by HarshCasper** [comment]
@gpsyrou I would assign you this Issue in Python

@mbcse Would you want to work on this in Javascript?

**Comment by mbcse** [comment]
Yes

**Comment by HarshCasper** [comment]
I have assigned the Issue in Python @gpsyrou and in JS to @mbcse

**Comment by vybhav72954** [comment]
@HarshCasper Is this issue open in Python?
