### ISSUE TITLE
Restructure the whole Project Codebase

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#129]
# Description

I'm looking to restructure the Whole Codebase to improve the readability and manage all the Scripts together. We have had a large number of contributions from `SCI-2020` and `PSoC-2020` Participants and we are looking for an even larger number of Contributions which needs to be managed now and upheaved before we move further.

## Language

- [X] Markdown

## Type of issue

*Please delete options that are not relevant.*

- [X] Enhancement

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Restructure the Project|To improve Readability and enhance the Codebase|No-Code, Markdown|'Open to SCI-2020 and PSOC-2020 Participants'|

**Is your feature request related to a problem? Please describe.**:  With a large number of Scripts now part of the Codebase, it is difficult to manage. We need to restructure the Project to make it readable and comprehend.

**Describe the solution you'd like**: I am looking for a Short Proposal in the form of a `Google Doc` before proceeding ahead.

**Additional context**: The Participant who would like this Issue be assigned should submit a 'Google Doc' in the comments below so that I can get a clear idea on how to proceed next. Once approved, the participant can move ahead with the Assignee.

**Comment by seema1711** [comment]
I think we can add an index page like structure in the readme file.

**Comment by HarshCasper** [comment]
@seema1711 It would be great if you can submit a short proposal for the same.

**Comment by HeroicHitesh** [comment]
@HarshCasper today is the last date of PSoC'20. Please take a look at the PR and let me know if any update is required
