### ISSUE TITLE
[script request]: Add a box playground

### ISSUE THREAD

**Issue by AshutoshDash1999** [HarshCasper/Rotten-Scripts#1293]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the script

- A user can add border-radius, change colour, change the height, width and others to a box and copy css
![image](https://user-images.githubusercontent.com/46455250/156123924-30783f58-62dd-4f73-a090-0ab2b9902962.png)

### Language

JavaScript

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HarshCasper** [comment]
Hi @AshutoshDash1999 

This is not a script but a UI application. I don't think we need full-fledged apps to be a part of the project. Closing this issue now.
