### ISSUE TITLE
Download all Instagram Posts

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#13]
## AIM

Create a Script that can download all Pictures from a Public Instagram Profile using Web Scrapping and store them in your Local System.

## Languages

- Python
- Javascript

## Details

You can make use of Web Scrapping Libraries to download the Pictures from any Instagram Profile Page. Optionally you can mention options like the pictures that you want to be downloaded, or should videos be excluded.

**Comment by sanket143** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
You have been assigned this Issue @sanket143 

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also, reference this Issue in your PR so that it becomes easy for us to review.
