### ISSUE TITLE
Create a Script to find Similar Images in the Directory

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#130]
# Description

Create a Script to find Similar Images in the Directory

## Language

- [X] Javascript
- [X] Python
- [X] Golang

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Find Similar Images in Directory|Find Similar Images and remove duplicated Images|Hard, Python, JS, Golang, PSOC'2020|`Open to PSOC'20 Participants`|

**Is your feature request related to a problem? Please describe.**: I always find similar Images in my Directory and I am looking for a way to flush out the duplicated messages.

**Describe the solution you'd like**: You can check out this [Stackoverflow Thread](https://stackoverflow.com/questions/75891/algorithm-for-finding-similar-images) to find the perfect solution to this issue.

**Additional context**: None

**Comment by srimani-programmer** [comment]
I will work on this issue with Python. Can you please assign it for me.

**Comment by HarshCasper** [comment]
I have assigned you the Issue in Python @srimani-programmer

**Comment by vybhav72954** [comment]
@HarshCasper Please assign this to me. Python
