### ISSUE TITLE
Download all Python Libraries for Data Science and Machine Learning

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#132]
# Description

Create a Script to download all Python Libraries for Data Science and Machine Learning

## Language

- [X] BASH

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Download Python Libraries for ML/DS|Eliminate the need to download every library individually|Medium, BASH|`Open to PSOC'20 Participants`|

**Is your feature request related to a problem? Please describe.**: A Shell Script to automatically set up all the libraries and modules without manually installing it via `pip` every now and then.

**Additional context**: None

**Comment by srimani-programmer** [comment]
Can you please assign this issue for me. I want to work it in python.?

**Comment by HarshCasper** [comment]
I have added a section for Python as well. You can start working on it in Python @srimani-programmer
