### ISSUE TITLE
Download Project Euler Problems 

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#133]
# Description

Create a Script to scrap and download Project Euler Problems.

## Language

- [X] Javascript
- [X] Python
- [X] Bash
- [X] Golang

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Download Project Euler Problems|Save all Project Euler Problems locally|Python, JS, Golang, BASH, Medium|`Open to PSOC'20 Participants`|

**Comment by Namyalg** [comment]
I would like to take this up.
