### ISSUE TITLE
[script request]:Generate silly sentence

### ISSUE THREAD

**Issue by Muhammad-Galhoum** [HarshCasper/Rotten-Scripts#1330]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Python Script 

I will create  a Script to generate a **random silly sentence** using python 

### Language

Python

### Describe the solution you'd like.

If you wanna generate a random **silly sentence which has not meaningful**, you can use my script to achieve your goal

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Muhammad-Galhoum** [comment]
I am a GSSOC22 participant 
can you assign me this @HarshCasper

**Comment by Muhammad-Galhoum** [comment]
Can you tell me, please 
Are you agree on this issue to start work on it ? @HarshCasper

**Comment by MaNaN-3** [comment]
I have solve this issue with the help of rapid API in python. Will that be fine @HarshCasper ?
