### ISSUE TITLE
[script request]: Want to add snake game in Python

### ISSUE THREAD

**Issue by Rushijaviya** [HarshCasper/Rotten-Scripts#1337]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the script

Python snake Game using Turtle library. The game will open in a new window. 

### Language

Python

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HarshCasper** [comment]
Why would a snake game be a part of a script repository? I'm sorry but it makes no sense to me. Please read the contributing guidelines before picking up an issue.
