### ISSUE TITLE
Download Mangas as save as PDF

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#134]
# Description

Create a Script to download Mangas from [Kissmanga](https://kissmanga.com/) and save them as PDF.

## Language

- [X] Javascript
- [X] Python
- [X] Golang

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Manga Downloader|Download Mangas and save as PDF|Python, JS, Golang, Hard| @Prahitha |

**Is your feature request related to a problem? Please describe.**: I always want to browse through interesting Mangas. I specifically wanted a Script to help me download Mangas as PDF which I can read later during offline hours.

**Describe the solution you'd like**: Script which can download the Manga given the URL which can be passed of as a flag. You can make flags to either download them as Chapters or with all the Chapters clubbed them together.

**Additional context**: Make sure to pass over arguments as Flags to help the User pass out the exact specification.

**Comment by Prahitha** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
I have assigned you the Issue @Prahitha 

You can start working on this
