### ISSUE TITLE
Show important Telegram messages

### ISSUE THREAD

**Issue by mbcse** [HarshCasper/Rotten-Scripts#135]
# Description
As telegram use is increasing day by day, There are lots of communities operating on Telegram, but due to this we sometimes join a lot of groups which results in skipping some important messages that can be helpful for us. So want to make a script that will get all messages of the groups you have joined and show you only the relevant messages that you want to see!

## Language

- Javascript
-  Python

**Comment by mbcse** [comment]
@HarshCasper

**Comment by HarshCasper** [comment]
This was something that I needed 😁

I am assigning you this Issue @mbcse and I am assigning it in the `Hard` category.

**Comment by vybhav72954** [comment]
Can you explain what an important message mean here? @HarshCasper
