### ISSUE TITLE
Create a Script to check who is Online

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#138]
# Description

Create a Script to check who is online on WhatsApp.

## Language

- [X] Python
- [X] Golang

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Check who is Online|A Script which can check your Contacts on who is Online at the given time and |Python, Golang|`Open to PSoC'20 Participants`|

**Is your feature request related to a problem? Please describe.**: A Script which can find which Contact of mine is online and notify me on the Command-Line.

**Describe the solution you'd like**:  Display the Names of my Contact who are online and notify me accordingly.

**Additional context**: If you are using Python, make use of Selenium to access WhatsApp Web and notify accordingly.

**Comment by Sanketwable** [comment]
I want to work on this

**Comment by HarshCasper** [comment]
I have assigned you the Issue in Python @Sanketwable
