### ISSUE TITLE
Increase YouTube Views

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#139]
# Description

Create a Script which can inflate the number of views on a given YouTube video.

## Language

- [X] Javascript
- [X] Python
- [X] Golang

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Increase YouTube Views|Inflate the number of views on any YouTube Video as specified by the User|Python, JS, Golang|`Open to PSoC'20 Participants`|

**Comment by srimani-programmer** [comment]
I want to work on this issue Can you please Assign it to me.
