### ISSUE TITLE
Get memes from reddit !!

### ISSUE THREAD

**Issue by YatinAdityaT** [HarshCasper/Rotten-Scripts#14]
AIM

Create a Script that can download all pictures of memes from any of these subreddits r/deepfriedmemes, r/surrealmemes, r/nukedmemes, r/bigbangedmemes, r/wackytictacs, r/bonehurtingjuice using Web Scrapping and store them in your Local System.
Languages

    Python

**Comment by HarshCasper** [comment]
This is a Cool Idea 😂

I am assigning you to work on this issue.

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also, reference this Issue in your PR so that it becomes easy for us to review.

**Comment by HarshCasper** [comment]
Are you working on this @YatinAdityaT ? Let me know if you need any help.

**Comment by YatinAdityaT** [comment]
@HarshCasper Yes, I am... unfortunately our end sems are approaching so I can't dedicate enough time to it... The barebones code is ready but I am not satisfied with its performance. For instance, the program downloads files one after another. I want to add multiprocessing to speed up this process. Also, the videos downloaded don't contain sound in them so I am looking into it...

Thank you for asking, I will let you know if I need any help... 😄

**Comment by HarshCasper** [comment]
@YatinAdityaT You can take your time on this. Let me know if you need any help with this!

**Comment by nimit2801** [comment]
Hey! @HarshCasper can I work on this issue and is this open for MWoC?
I'll make a PR soon anyways very cool idea actually.

**Comment by nimit2801** [comment]
Why do we need to web scrap? We already have Reddit's API for that. @HarshCasper can we use that. And I would like to use Javascript/Python.

**Comment by HarshCasper** [comment]
> Why do we need to web scrap? We already have Reddit's API for that. @HarshCasper can we use that. And I would like to use Javascript/Python.

Sure. Go ahead

**Comment by nimit2801** [comment]
@HarshCasper I've researched a bit and found out to use the Reddit API, I need OAuth Token. I can do things with OAuth and get memes. But it will need a secret each time you make a request. Do you think I should use Reddit's API or try to scrape data with some python/js library.

**Comment by HarshCasper** [comment]
> @HarshCasper I've researched a bit and found out to use the Reddit API, I need OAuth Token. I can do things with OAuth and get memes. But it will need a secret each time you make a request. Do you think I should use Reddit's API or try to scrape data with some python/js library.

Both the approaches are okayish for me. Please go ahead with the one that you find the most customizable.
