### ISSUE TITLE
[script request]: automated git commit script in Python

### ISSUE THREAD

**Issue by wthrajat** [HarshCasper/Rotten-Scripts#1410]
### Is there an existing issue for this?

- [ ] I have searched the existing issues.

### Describe the script

This script will commit some changes automatically to a desired github repo for a perfect commit streak.
However it can be misused too. Let me know if I can add a PR for this idea or not! Thanks! 

### Language

Python

### Is the feature request related to a problem? Please Specify.

No it is not

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ClasherKasten** [comment]
There is already a [script](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Automate_Commiting_using_Git) in this repository whose idea sounds very similar. So if you have an idea that this existing script does not implement, feel free to open a PR for it, but I think a new script would be unnecessary noise in the project.

**Comment by geekabhinav007** [comment]
> There is already a [script](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Automate_Commiting_using_Git) in this repository whose idea sounds very similar. So if you have an idea that this existing script does not implement, feel free to open a PR for it, but I think a new script would be unnecessary noise in the project.

I am going To enhance the script.
