### ISSUE TITLE
[Discussion] We should start implementing class based module

### ISSUE THREAD

**Issue by mohitacecode** [HarshCasper/Rotten-Scripts#144]
Hey Mohit here,

I think it's high time that we should start writing our scripts in the form of class so that the user can directly import the script and use it instead of running the whole file.

I know that it will take time to shift to this pattern but we should start it in near future as it will be required as codebase will increase.

for example:
```
import abc_script from RottenScript

abc_script(rows = 2, ....)

**Comment by HarshCasper** [comment]
That is a brilliant suggestion here @mohitacecode 

I saw a similar proposal from @Sanketwable who has worked a lot on integrating Go Scripts with this Project. I would love to see a proposal coming up to be able to achieve this.

**Comment by HeroicHitesh** [comment]
@mohitacecode @HarshCasper I liked this idea, and would love to contribute towards this shift. Let me know if I can help with anything.
Also, I have some small doubts
1. > import abc_script from RottenScript

in this line does it mean `RottenScript` will be a package/module which is imported? If so, do we need to publish it somewhere?

2. Can we have all language script under one class or do we need to create separate classes for different languages.

**Comment by mohitacecode** [comment]
> Can we have all language script under one class or do we need to create separate classes for different languages.

Great Question. Let's Brainstorm on this @HarshCasper @HeroicHitesh.
It seems that we need to create seprate packages for each language.

for example:
we have `qt` package for desktop application development which is available in different languages such as Python, C. for instance in python it is call PyQT5,  QT in C.

**Comment by mohitacecode** [comment]
>in this line does it mean RottenScript will be a package/module which is imported?
Yes
>If so, do we need to publish it somewhere?

Need to see it myself

**Comment by mohitacecode** [comment]
Most probably we will start this once `Student Code-in` and `PSOC` is over so that new contributor does not have to struggle to implement scipts in `classes`.

**Comment by mohitacecode** [comment]
It seems we can assign this issue `High Priority` tag. @HarshCasper

**Comment by HarshCasper** [comment]
That would be great. Thanks for the fruitful debate up here, because this has clarified many ideas for my side @mohitacecode @HeroicHitesh

**Comment by vybhav72954** [comment]
@HarshCasper WHy don't we modify the guidelines a bit? That for experienced programmers, they can already start using of Object-based programming. This way in the future if we try to implement this idea, it would be easier for us. Moreover, we can link a script in the guidelines as well which follows a similar approach, this was we can also give them a static demo of how a script shld look like.
