### ISSUE TITLE
Script to merge PDF files

### ISSUE THREAD

**Issue by AnkitaxPriya** [HarshCasper/Rotten-Scripts#152]
# Description

Develop a script for merging PDF files. 

## Language

- [x] Python

## Type of issue

- [x] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Merge PDF files|We have many PDF files of our course at college |Python| |

**Is your feature request related to a problem? Please describe.**: We generally have many PDF files related to the same subject of our course. So why not simply merge them into one and get rid of finding them every time we need it?

# Update

The script is open to all in Golang and JavaScript.

For python we have a script [here](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Merge_2_PDFs). Kindly suggest improvements then only this can be assigned to you 😄

**Comment by kushal98** [comment]
Hey,

Can I work on this?

Thanks

**Comment by HarshCasper** [comment]
@kushal98 I would like you to wait for sometime before any Project Admin/Mentor assigns you the Issue. Also currently this repo is being used by SCI-2020 and PSoC-2020 Participants hence Issues made by the individual participations would be solved by them.

Since you have already made a PR, I would like to know from @AnkitaBIT whether she wants to continue with this Issue or can I take into account @kushal98 's PR for this particular Issue.

**Comment by AnkitaBIT** [comment]
No worries @HarshCasper, I will work on other issue.

**Comment by sujal111** [comment]
Allow me to work this issue please

**Comment by HarshCasper** [comment]
Hello @sujal111 

Assigned to you 👍

**Comment by HarshCasper** [comment]
Are you still working on it @sujal111 ? 

If not, I will assign it to someone else.

**Comment by temitayopelumi** [comment]
Hi @HarshCasper, can I work on this issue?

**Comment by HarshCasper** [comment]
> Hi @HarshCasper, can I work on this issue?

Hello @temitayopelumi 

Welcome to Rotten Scripts! Glad to have you here 🚀 

You can definitely work on this. I guess we already have a Script in Python Directory, so you can test it out to see if it matches to what you are looking for. If not, you can improve it.

Otherwise, we are looking for similar scripts in JS or Golang. Do let me know what you feel about this. If you are comfortable on working on any of them, use `/assign` and a Github Bot will automatically assign it to you.

**Comment by iamakkkhil** [comment]
Is this issue open yet? If yes, I would love to work on this issue because I have worked on projects involving PyPDF2 module of python. Also I am a GSSOC' 21 Participant

**Comment by vybhav72954** [comment]
Hi there, we already have a script for this [here](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Merge_2_PDFs).

If you can upgrade this script somehow, throw me your suggestions and i will assign this to you.

**Comment by a7medayman6** [comment]
Hello,
I would like to work on this issue, Also I'm a GSSOC21 Participant.

**Comment by vybhav72954** [comment]
Like i said, we already have a script for the purpose. Please explain what you want to change in the existing script!

> Hi there, we already have a script for this [here](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Merge_2_PDFs).
> 
> If you can upgrade this script somehow, throw me your suggestions and i will assign this to you.

@a7medayman6

**Comment by a7medayman6** [comment]
> Like i said, we already have a script for the purpose. Please explain what you want to change in the existing script!
> 
> > Hi there, we already have a script for this [here](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Merge_2_PDFs).
> > If you can upgrade this script somehow, throw me your suggestions and i will assign this to you.
> 
> @a7medayman6

@vybhav72954 I haven't noticed your comment sorry, thank you.

**Comment by vybhav72954** [comment]
@samrudhi0909 

> Like i said, we already have a script for the purpose. Please explain what you want to change in the existing script!
> 
> > Hi there, we already have a script for this [here](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Merge_2_PDFs).
> > If you can upgrade this script somehow, throw me your suggestions and i will assign this to you.
> 
> @a7medayman6

**Comment by iamakkkhil** [comment]
I would like to work on this issue @vybhav72954 @HarshCasper. 
As I have already contributed script of pdf pages rearrangement through python. So it will be an easy task to go for it.
Can I do solve this issue with python ? If yes, kindly assign me the same.

**Comment by harshita2319** [comment]
Hey, I'm a Gssoc participant. I'd like to work on this issue, I'm comfortable with writing a script in JS and for Python, I've worked on various projects using the PyPDF2 library so I can submit another script for that as well if you want me to as the one you attached needs to be updated.

**Comment by vybhav72954** [comment]
> Hey, I'm a Gssoc participant. I'd like to work on this issue, I'm comfortable with writing a script in JS and for Python, I've worked on various projects using the PyPDF2 library so I can submit another script for that as well if you want me to as the one you attached needs to be updated.

You can take this in JS, confirm and I will assign

**Comment by harshita2319** [comment]
> > Hey, I'm a Gssoc participant. I'd like to work on this issue, I'm comfortable with writing a script in JS and for Python, I've worked on various projects using the PyPDF2 library so I can submit another script for that as well if you want me to as the one you attached needs to be updated.
> 
> You can take this in JS, confirm and I will assign

Yes, I'm in!

**Comment by vybhav72954** [comment]
@harshita2319 Best of luck, for any queries, feel free to comment here!

PS a #731 had a PR for the same, in case you find it useful!

**Comment by harshita2319** [comment]
> @harshita2319 Best of luck, for any queries, feel free to comment here!
> 
> PS a #731 had a PR for the same, in case you find it useful!

Hey, I've made a pr. Please have a look and let me know if there are any issues from my end!
