### ISSUE TITLE
Substitution Cipher

### ISSUE THREAD

**Issue by mohitacecode** [HarshCasper/Rotten-Scripts#154]
# Description

Create a Script to implement Substitution Cipher

## Language

- [x] Python

## Type of issue

*Please delete options that are not relevant.*

- [x] Feature
- [ ] Bug

## Details
In this Script, you have to implement the concept of Substitution Cipher and encrypt/decrypt a text based on the User-choice.

**Comment by mohitacecode** [comment]
Please assign this issue to me and also assign specific labels to it. @HarshCasper

**Comment by HarshCasper** [comment]
Assigned to you @mohitacecode 

You can work on this
