### ISSUE TITLE
Number of posts, followers and following on Instagram given username

### ISSUE THREAD

**Issue by Namyalg** [HarshCasper/Rotten-Scripts#155]
# Description

Please include a summary of the issue.

## Language

- [ ] Javascript
- [x] Python
- [ ] Bash
- [ ] Powershell
- [ ] Other (Please specify)

## Type of issue

*Please delete options that are not relevant.*

- [ ] Feature
- [ ] Bug

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Feature request|Details (Motivation behind) about your feature request|feature|self-assign if you want to work on this issue else leave blank|

**Is your feature request related to a problem? Please describe.**: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**: A clear and concise description of what you want to happen.

**Additional context**: Add any other context or screenshots about the feature request here.

- **For Bug**

|name|about|labels|assignees|
|----|-----|------|---------|
|Bug|Found a bug! File it using this template!|bug|self-assign if you want to work on this issue else leave blank|

**Steps to reproduce**: List out the steps to reproduce the steps

**Expected results**: What were the expected results

**Actual results**: What you got

**Additional context**: Add any other context or screenshots about the bug here.

**Comment by kushal98** [comment]
Hey,

I would like to take this issue.

Thanks

**Comment by HarshCasper** [comment]
@kushal98 I would like you to wait for sometime before any Project Admin/Mentor assigns you the Issue. Also currently this repo is being used by SCI-2020 and PSoC-2020 Participants hence Issues made by the individual participations would be solved by them.

**Comment by vybhav72954** [comment]
@HarshCasper Is the Issue till up?
