### ISSUE TITLE
Whatsapp Bot that gives statistics of COVID cases given a country

### ISSUE THREAD

**Issue by Namyalg** [HarshCasper/Rotten-Scripts#161]
# Description

This script aims at building a bot that can be used by all and provides the statistics of COVID cases in a country 

## Language

- [ ] Javascript
- [x] Python
- [ ] Bash
- [ ] Powershell
- [ ] Other (Please specify)

## Type of issue

*Please delete options that are not relevant.*

- [ ] Feature
- [ ] Bug

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Feature request|Details (Motivation behind) about your feature request|feature|self-assign if you want to work on this issue else leave blank|

**Is your feature request related to a problem? Please describe.**: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**: A clear and concise description of what you want to happen.

**Additional context**: Add any other context or screenshots about the feature request here.

- **For Bug**

|name|about|labels|assignees|
|----|-----|------|---------|
|Bug|Found a bug! File it using this template!|bug|self-assign if you want to work on this issue else leave blank|

**Steps to reproduce**: List out the steps to reproduce the steps

**Expected results**: What were the expected results

**Actual results**: What you got

**Additional context**: Add any other context or screenshots about the bug here.

**Comment by Namyalg** [comment]
I would like to work on this. Will extend functionality to all Indian States also.

**Comment by HarshCasper** [comment]
Assigned to you @Namyalg 

You can work on this
