### ISSUE TITLE
Send Connection Requests on LinkedIn

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#164]
# Description

Create a Script that can send Connection Requests on LinkedIn with a personalized note as given by the User.

## Language

- [X] Javascript
- [X] Python
- [X] Golang

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Send Connection Request|Script to send personalized Connection Requests on LinkedIn with a note|SLoP, Python, JS, Golang|`Open for SLoP Participants`|

**Comment by mohitacecode** [comment]
Please assign this issue to me

**Comment by HarshCasper** [comment]
I have assigned this to you @mohitacecode

**Comment by SANKET7738** [comment]
If open, I would like to work on this.

**Comment by vybhav72954** [comment]
@HarshCasper Is this still open in python?

**Comment by HarshCasper** [comment]
I am assigning this to you @vybhav72954

**Comment by vybhav72954** [comment]
@HarshCasper This issue is solved in `Python`, [here](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Automate-LinkedIN)

I'll solve this using JS.

This might take some time as JS is not my forte.

**Comment by HarshCasper** [comment]
Hello @vybhav72954 

Let me know if you are still working on the same. Otherwise, I will open the Issue for NJACK Participants

**Comment by vybhav72954** [comment]
The issue is solved using python. And am unable to solve it using JS. I will unassign myself. Sorry i kept you waiting
