### ISSUE TITLE
Scrap Latest Torrents

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#165]
# Description

Create a Script that can scrap the latest torrents as per the labels given.

## Language

- [X] Python
- [X] Golang

## Type of issue

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Scrap Latest Torrents|Get Latest Torrents straight on your CLI as per the labels given|PSoC-2020, Python, Golang, Hard|`Open for PSoC-2020 Participants`|

**Comment by Prahitha** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
I have assigned this to you @Prahitha

**Comment by kritikaparmar-programmer** [comment]
Hey @HarshCasper , I want to work on this issue.. Please assign me..

**Comment by HarshCasper** [comment]
Assigned to you @kritikaparmar-programmer

**Comment by kritikaparmar-programmer** [comment]
Hey @HarshCasper , Sorry for so delay.. But I want to ask one question.. what does torrents mean here?
Like the torrents file which we download for movies ? I'm facing issue with them
Please clarify about the word torrent here.. Also I'll try to solve this fast.. Again sorry for delayed work.

**Comment by HarshCasper** [comment]
@kritikaparmar-programmer 

The main purpose here was to scrap Torrent categories given the arguements, scrap relevant data that match our keywords and category, download the .torrent file.

**Comment by imakash3011** [comment]
If you would provide me the actual link to the website whose data we have to scrape then it will be easy for me to work on this issue. So kindly provide me the link.

**Comment by DiegoCaraballo** [comment]
Hello @HarshCasper 
I would like to work on this issue.

**Comment by DiegoCaraballo** [comment]
Hello @HarshCasper 
It had occurred to me to do a search in google, example: "MR. Robot" filetype: torrent
And from there collect the .torrent files. Or should I search specific pages?

**Comment by HarshCasper** [comment]
> Hello @HarshCasper
> It had occurred to me to do a search in google, example: "MR. Robot" filetype: torrent
> And from there collect the .torrent files. Or should I search specific pages?

Your approach seems doable.

**Comment by DiegoCaraballo** [comment]
Hello @HarshCasper 
I was analyzing and it was not possible to extract the torrents using Google.
I find it more productive to use a website like: https://thepiratebay.org/search.php
Can I extract the torrents from here?
