### ISSUE TITLE
Bomb WhatsApp Messages

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#166]
# Description

Create a Script to bomb your WhatsApp Contacts with one message. You can take a message content from a user and bomb that same message to all your Contacts. You can optionally add an option to bomb the same message multiple times to the same user.

## Language

- [X] Javascript
- [X] Python
- [X] Golang

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

**Comment by amandp13** [comment]
Please assign this to me

**Comment by bagofcodes** [comment]
I would like to try this in python

**Comment by HarshCasper** [comment]
I have assigned you the Issue @bagofcodes

**Comment by bagofcodes** [comment]
I have completed the task for this issue...Thanks for this lovely issue..Really enjoyed doing it....Will be happy if you review it...
