### ISSUE TITLE
Build an Amazon Price Tracker

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#167]
# Description

Create a Script that can track the price of a specific product for me.

## Language

- [X] Javascript
- [X] Python
- [X] Golang

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Script to track Amazon Prices|Log the Changes in price made over the time and give a notification (push) once the Prices have decreased|PSOC-2020, Hard, Python, Javascript, Golang|`Open to PSoC'20 Participants`|

**Comment by Namyalg** [comment]
I would like to work on this

**Comment by aastha985** [comment]
I would like to work on this issue in JavaScript.
