### ISSUE TITLE
Shows Desktop Notifications

### ISSUE THREAD

**Issue by Anushka-S10** [HarshCasper/Rotten-Scripts#171]
# Description

A desktop notifier app runs on your system and it will be used to send you notifications after every specific interval of time.

## Language

- [ ] Javascript
- [X] Python
- [ ] Bash
- [ ] Powershell
- [ ] Other (Please specify)

## Type of issue

*Please delete options that are not relevant.*

- [ ] Feature
- [ ] Bug

## Checklist:
Name | About
:------------------ | :------------------
Desktop Notifier | Shows the news on the desktop at the specific interval of time.

**Comment by simarpreetsingh-019** [comment]
@Anushka-S10 I am a bit confused, could you please elaborate what type of notification message should we send to the user, news type that we should fetch, or anything else?
