### ISSUE TITLE
Update Interesting Facts

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#18]
## AIM

Create a Script that can flash up my Desktop Notifications with an interesting facts in a specific period of time.

## Languages

- Python

## Details

I am a Reddit Fan, and I love scrolling through specific Sub-Reddits, especially the ```/r/todayilearned``` Sub-Reddit which has got something to amaze every time. I want to automate this whole process and get interesting updates straight from the Sub-Reddit to my Desktop as a Notification. Create a Script to automate the whole process. You can make use of [Reddit API](https://www.reddit.com/dev/api/) and ```Requests``` Module for this Script.

**Comment by mohitacecode** [comment]
Please assign this issue to me @HarshCasper

**Comment by HarshCasper** [comment]
I have assigned you the Issue @mohitacecode

**Comment by HarshCasper** [comment]
Are you working on this @mohitacecode ?

**Comment by mohitacecode** [comment]
Will submit a pr soon @HarshCasper .

**Comment by kaustubhgupta** [comment]
I would like to work on this😃 @HarshCasper

**Comment by HarshCasper** [comment]
Assigned to you @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@HarshCasper made a pull request. PR #219
