### ISSUE TITLE
Adding a common Secret Manager script to get the secret string.

### ISSUE THREAD

**Issue by sameersrivastava13** [HarshCasper/Rotten-Scripts#194]
**AIM**

To add a python script to retrieve the decrypted secret value from an AWS Secrets Manager secret.

**Languages**

- [ ] Python

**Details**

To add a python script to retrieve the decrypted secret value from an AWS Secrets Manager secret with custom exception handling.

**Comment by HarshCasper** [comment]
Hello @sameersrivastava13 

Would you like to work on this for Contributor's Hack 2020?

**Comment by sameersrivastava13** [comment]
yes @HarshCasper .
Please assign me this i have the script ready with me.

**Comment by sameersrivastava13** [comment]
@HarshCasper Assign me this.

**Comment by sameersrivastava13** [comment]
@HarshCasper assign me this issue.
