### ISSUE TITLE
Web Crawler in Python

### ISSUE THREAD

**Issue by Anushka-S10** [HarshCasper/Rotten-Scripts#196]
# Description

Automated program script that browses the world-wide-web and it can look and store the contents of the web page.

**Comment by harshareddy794** [comment]
Please assign me this issue @HarshCasper

**Comment by amandp13** [comment]
@HarshCasper Please assign this issue to me

**Comment by alazar-w** [comment]
hey please assign me to this issue

**Comment by amoghatsunil** [comment]
I would like to work on this
