### ISSUE TITLE
Lorem Ipsum Generator

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#2]
## AIM

Create a Script that can generate Lorem Ipsum Text given the number of Paragraphs that are needed by the User.

## Languages 

- Python [ Assigned to @seema1711 ]

## Details

Lorem Ipsum is a popular text placeholder text. In this Script, we are removing the need for a Developer to copy-paste Lorem Ipsum Texts repeatedly and instead create a Script that can generate Lorem Ipsum Paragraphs, given the number of Paragraphs needed by the User.

**Comment by seema1711** [comment]
Can I work on this?

**Comment by HarshCasper** [comment]
You have been assigned this issue @seema1711 

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.

Best of luck with your Open-Source Journey :)
