### ISSUE TITLE
Script to convert all HTML Files to Markdown Format

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#202]
# Description

Create a script which can convert all HTML Files to Markdown Format.

## Language

- [X] Javascript
- [X] Python
- [X] Bash

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

**Comment by tejan-singh** [comment]
I want to work on this

**Comment by HarshCasper** [comment]
Assigned to you @tejan-singh 

You can work on the same now

**Comment by tejan-singh** [comment]
What's the deadline to complete this assignment ?

**Comment by HarshCasper** [comment]
7 Days @tejan-singh

**Comment by eternal-dreamer** [comment]
I also want to work on this .Can I ?

**Comment by HarshCasper** [comment]
@eternal-dreamer You can but on some other languages like Javascript, Golang or BASH

**Comment by eternal-dreamer** [comment]
Okay , I will try to do it using JavaScript.

**Comment by HarshCasper** [comment]
I have assigned you the Issue in Javascript @eternal-dreamer
