### ISSUE TITLE
Create a Script to convert a JSON to a YAML

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#203]
# Description

Create a script which can convert a JSON File to a YAML File.

## Language

- [X] Javascript
- [X] Python
- [X] Bash

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

**Comment by AdityaJ7** [comment]
I would like to work on this issue in Python

**Comment by sahanabalappa** [comment]
I would like to work on this issue in Python

**Comment by HarshCasper** [comment]
I have assigned the Issue to you @AdityaJ7 

@sahanabalappa If you would like, you can work on this in JS

**Comment by amandp13** [comment]
@HarshCasper I would like to work on this issue
