### ISSUE TITLE
Create a Script to download Slides from Slideshare

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#204]
# Description

Please include a summary of the issue.

## Language

- [X] Javascript
- [X] Python
- [X] Bash

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Script to download Slideshows|The primary purpose of the Script would be to download LinkedIn SlideShare as PDF Files for later references using a CLI Tool|Medium, Python, JS, BASH, CH-2020|`Open for CH-2020 Participants`|

**Comment by AkM-2018** [comment]
I would like to work on this with python.

So, we input the url, and the python program downloads the file for us, rgt? Can I use Selenium for this?

**Comment by HarshCasper** [comment]
You can use any tool you like fits the purpose @AkM-2018 

I have assigned you the Issue in Python

**Comment by AkM-2018** [comment]
Hey! I'm done with the code. I'm including the chromeDriver and requirements.txt with it. Should I write README file for it??
