### ISSUE TITLE
Clone the Whole Website

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#211]
# Description

Create a Script that can clone an entire Static Website and save it on my Root Directory.

## Language

- [X] Javascript
- [X] Python
- [X] Bash

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

**Comment by avinashkranjan** [comment]
I'd Like to work on this issue in python

**Comment by avinashkranjan** [comment]
Hey @HarshCasper, I can use **pywebcopy** and bring down the code to max 5 lines. I can also use multiple libraries like **bs4**, **urlib**, **cssutils** and code in an more elaborate way..How do you want to push the code..or _Should I push both the versions??_

**Comment by HarshCasper** [comment]
Use both of them @avinashkranjan

**Comment by avinashkranjan** [comment]
Ok..will Push both the scripts today..
