### ISSUE TITLE
Telegram Channel Activity Evaluation

### ISSUE THREAD

**Issue by alazar-w** [HarshCasper/Rotten-Scripts#214]
# Description
This python Script is used to analizing telegram channel activity like how many active users to help advertisers choose best channel to advertise on.
## Language

- [x] Python

## Type of issue

*Please delete options that are not relevant.*

- [x] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Telegram Channel Activity Evaluation|analize the over all activity of telegram channel number|python|self-assign|

**Comment by alazar-w** [comment]
@HarshCasper ;; i want to do it

**Comment by HarshCasper** [comment]
You can start working on this @alazar-w

**Comment by alazar-w** [comment]
thank u @HarshCasper

**Comment by vybhav72954** [comment]
@HarshCasper @alazar-w Is this issue open in python?

**Comment by HarshCasper** [comment]
Since @alazar-w has not made any PR for this Issue, you can work on this @vybhav72954

**Comment by alazar-w** [comment]
hello @HarshCasper when the program is ended i thought u won't recive any pull request that why i was too late,sorry for my delay ,but now the task is done and ready to review.

**Comment by vybhav72954** [comment]
@alazar-w Kindly ensure that either you are updating the status of your work here, or privately to @HarshCasper 

I had just finished my Flask App for this :D

Would be great if you can ensure that your issues/PR are not going stale

**Comment by alazar-w** [comment]
hellow @vybhav72954 

> @alazar-w Kindly ensure that either you are updating the status of your work here, or privately to @HarshCasper
> 
> I had just finished my Flask App for this :D
> 
> Would be great if you can ensure that your issues/PR are not going stale

hellow @vybhav72954 check out the pull request i made!!

**Comment by alazar-w** [comment]
alazar-w:telgramChannelDiscoveryFixed

**Comment by alazar-w** [comment]
hello @HarshCasper please check out my pull request?

**Comment by HarshCasper** [comment]
Hello @alazar-w 

I'm going through your files right now. There is a lot of code which will take me some time to review and update.

**Comment by alazar-w** [comment]
> Hello @alazar-w
> 
> I'm going through your files right now. There is a lot of code which will take me some time to review and update.

hey @HarshCasper still waiting your reply???
