### ISSUE TITLE
Make Contributors Guideline

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#22]
## AIM

Create Contributors Guideline to help new Contributors get started with this Project.

## Features

- Add a ```CONTRIBUTING.md``` to allow new users to get started with knowing how to contribute.
- Add Screenshots wherever possible. 
- Add the basic information about creating Issues, Pull Requests and Branching.
- Mention tutorials related to Git and Github to help them better understand.

**Comment by AnkitaBIT** [comment]
Can I work on this @HarshCasper ?

**Comment by HarshCasper** [comment]
I have assigned you the Issue @AnkitaBIT 

You can start working on it!

**Comment by HarshCasper** [comment]
Are you working on this @AnkitaBIT ?

**Comment by AnkitaBIT** [comment]
Yes @HarshCasper
