### ISSUE TITLE
Create an Issue + Pull Request Template

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#23]
## AIM

Create a custom Issue and Pull Request Template.

## Features

- Make an Issue Template. Any new Contributor must be able to specify if it is a new script or enhancement to an older one. It should also be specified which language he is coding it in.

- Make a Pull Request Template. Any new Contributor must be able to specify if he has met all the requirements like Clean Code, proper README and Documentation, Screenshots (If any) attached and more.

**Comment by HeroicHitesh** [comment]
@HarshCasper I am interested in this, please assign it to me. Also, I have a doubt as far as I know it can be done from settings tab which is not accessible to contributors. So, how should I proceed with this issue?
One solution I am thinking of is I can create `issue_template.md` file and it can be used as a template but I am not sure it will work as required.

**Comment by HarshCasper** [comment]
@HeroicHitesh You can add the templates in a separate Directory and I will integrate them with the Repository.
