### ISSUE TITLE
Script to convert Video to Frames

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#230]
# Description

Create a Script to convert Video to Frames.

## Language

- [X] Javascript
- [X] Python

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

**Comment by kaustubhgupta** [comment]
I would like to take up this issue @HarshCasper

**Comment by kaustubhgupta** [comment]
made PR #236 @HarshCasper
