### ISSUE TITLE
Script to convert Frames to Videos

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#231]
# Description

Script to convert Frames to Videos

## Language

- [X] Javascript
- [X] Python

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

**Comment by AkM-2018** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
Assigned to you @AkM-2018

**Comment by AkM-2018** [comment]
Sorry for being unclear. I want to work only on python
