### ISSUE TITLE
Script to convert folders to Zip file

### ISSUE THREAD

**Issue by Puneet-Pal-Singh** [HarshCasper/Rotten-Scripts#233]
# Description
Create a Script using Python to convert folders or a directory to Zip file.

## Language

- [ ] Javascript
- [x] Python

## Type of issue

*Please delete options that are not relevant.*

- [x] Feature
- [ ] Bug

**Comment by akshaysonawaneS** [comment]
I will like to work on it if no on one is working on it

**Comment by Puneet-Pal-Singh** [comment]
Akshay this Script has already been merged, you can work on other issues.

**Comment by kushal-g** [comment]
Shouldn't this issue be closed then?
