### ISSUE TITLE
Script to find all links in a Web Page

### ISSUE THREAD

**Issue by Puneet-Pal-Singh** [HarshCasper/Rotten-Scripts#235]
# Description

Create a Script that extract all the links from a Web page.

## Language

- [ ] Javascript
- [x] Python

## Type of issue

*Please delete options that are not relevant.*

- [x] Feature
- [ ] Bug

**Comment by HeroicHitesh** [comment]
@Puneet-Pal-Singh Yes, you can close this issue.
