### ISSUE TITLE
Linkedin video downloader

### ISSUE THREAD

**Issue by kaustubhgupta** [HarshCasper/Rotten-Scripts#256]
# Description

Download videos from Linkedin given the link of the video.

## Language

- [ ] Javascript
- [x] Python
- [ ] Bash
- [ ] Powershell
- [ ] Other (Please specify)

## Type of issue

*Please delete options that are not relevant.*

- [x] Feature
- [ ] Bug

**Comment by kaustubhgupta** [comment]
@HarshCasper can you assign this issue to me and apply appropriate labels of CH20 to it? I think it can be considered as medium level else it's your call

**Comment by simarpreetsingh-019** [comment]
@HarshCasper I would like to work on this issue.
as I see @kaustubhgupta created this issue, I think we both can work on this issue if it is allowed.
If possible, please assign me this issue

**Comment by kaustubhgupta** [comment]
I will be working in Python language, you can work in another language @simarpreetsingh-019

**Comment by simarpreetsingh-019** [comment]
Well I work in python..😅 I think we both can make different scripts in same language doing same process..

**Comment by kaustubhgupta** [comment]
let's see what harsh says

**Comment by HarshCasper** [comment]
I am assigning this to you @kaustubhgupta 

@simarpreetsingh-019 Let @kaustubhgupta make a PR. If you can provide a more efficient code, feel free to make an Issue and then a PR

**Comment by kaustubhgupta** [comment]
@HarshCasper made PR #271
