### ISSUE TITLE
Create a README for Golang Language Directory

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#260]
# Description

Create a README for Golang Language Directory. Add these specific parts in it: 

- A brief introduction about Golang
- List of all Scripts in Golang in form of a table
- Add three columns: `Name of Script`, `Directory Link` and `Author` (if mentioned).

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by AdityaAshvin** [comment]
I would like to work on this @HarshCasper

**Comment by HarshCasper** [comment]
Assigned to you @AdityaAshvin
