### ISSUE TITLE
Create a README for Python Language Directory

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#261]
# Description

Create a README for the Python Language Directory. Add these specific parts in it: 

- A brief introduction about Python
- List of all Scripts in Python in form of a table
- Add three columns: `Name of Script`, `Directory Link` and `Author` (if mentioned).

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by AdityaJ7** [comment]
I would like to work on this issue.

**Comment by SANKET7738** [comment]
I would like to work on this issue.

**Comment by HarshCasper** [comment]
@AdityaJ7 Assigning to you
