### ISSUE TITLE
Create a README for Javascript Language Directory

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#262]
# Description

Create a README for Javascript Language Directory. Add these specific parts in it: 

- A brief introduction about Javascript 
- List of all Scripts in Javascript in form of a table
- Add three columns: `Name of Script`, `Directory Link` and `Author` (if mentioned).

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by AkM-2018** [comment]
I would like to do this

**Comment by HarshCasper** [comment]
Assigned to you @AkM-2018
