### ISSUE TITLE
Question: Can we have a Website for this Project?

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#263]
## Question

Can we have a Website for this Project? The minimum features I am looking for is: 

- Static Landing Page which mentions the Core Objective of the Project 
- A-List of Scripts in different Languages mentioned along with their description
- Contributors List 

I will manage the deployment part on an AWS Instance, but this Issue is simply too large to be assigned to one person. It would be further broken up into multiple issues, but I need an overview if this would be feasible for our current timeline.

**Comment by kaustubhgupta** [comment]
@HarshCasper I think it can simply be done in markdowns, and then deployment using GitHub pages. Why I am saying markdowns is that because all the GitHub actions can be easily integrated on markdowns. The contributors list, project files and all. As the website you want is mainly static, no requirement of hardcore backend. As far as timeline is concerned, I think it can be covered in our current CH20 period.

**Comment by kaustubhgupta** [comment]
I am not well versed with GitHub actions but I would love to experiment with them.

**Comment by SANKET7738** [comment]
@HarshCasper I think it would be great to have a website. I think the task is doable and can be done within the timeline period. What framework are you suggesting for this or would simple HTML + CSS + JS website? According to me using a framework would be beneficial in the long run and it would be easy to manage and scale as per the future needs.

**Comment by kritikaparmar-programmer** [comment]
@HarshCasper , I think we can use flask for making a website and for frontend - HTML, CSS or Bootstrap.. What say?

**Comment by codePerfectPlus** [comment]
If you are thinking about a static website [Jekyll](https://jekyllrb.com/) is a good Idea.

**Comment by ExpressHermes** [comment]
I agree a static website using github pages is much better idea. Is someone working on this? I am interested to work on this.

**Comment by codePerfectPlus** [comment]
@ExpressHermes I am working on Github pages site. check here - https://github.com/Py-Contributors/py-contributors.github.io

**Comment by avinal** [comment]
A static website using SSG will be great without much bell and whistles. Easy to manage and you can tweak the theme to personalize them. I have experience with many SSGs (Sphinx, Pelican, Jekyll) and GitHub Actions. Let me know if I can be a contributor :)

**Comment by HarshCasper** [comment]
> A static website using SSG will be great without much bell and whistles. Easy to manage and you can tweak the theme to personalize them. I have experience with many SSGs (Sphinx, Pelican, Jekyll) and GitHub Actions. Let me know if I can be a contributor :)

Hello @avinal 

I don't have much experience with SSG, so I would like to know if you would like to carry it forward. If possible you can create a separate issue to pitch in how this can be made possible.

**Comment by avinal** [comment]
Ok @HarshCasper, I will create an issue for this and let you know further details there.
