### ISSUE TITLE
Optimize/Modify the README File for the Project

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#275]
# Description

Optimize/Modify the README for the Project. The end results I am looking for: 
- An Attractive Header with good Markdown Badges (I love them) 
- Proper Section for all Languages 
- Proper Instructions on how new Contributors can contribute. Link this to `CONTRIBUTING.md` and `Code of Conduct`
- Instructions on how everyone can use the Scripts

`NOTE: Don't change the Contributors and Project Admin Section.`

## Language

- [X] Markdown

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by AdityaAshvin** [comment]
Can i work on this? @HarshCasper
