### ISSUE TITLE
Generate Public Keys

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#276]
# Description

Create a Script to create a private/public keypair for SSH-authentication for password-less connecting to a remote server. 

## Language

- [X] Bash
- [X] Go
- [X] Javascript
- [X] Powershell
- [X] Python

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by tejan-singh** [comment]
I would like to work on it in python.
