### ISSUE TITLE
Send LinkedIn Connection Requests

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#278]
# Description

Create a Script to send LinkedIn Connection Requests in bulk from this [endpoint](https://www.linkedin.com/mynetwork/) with an argument as a Custom Connection Message. You can specify how many people you may want to send the Connection Request. 

## Language

- [X] Bash
- [X] Go
- [X] Javascript
- [X] Python

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by Namyalg** [comment]
I would like to work on this

**Comment by Namyalg** [comment]
From the endpoint mentioned, there is an option only to connect , so how will the custom message work?

**Comment by Namyalg** [comment]
I have been able to automate the process where a searches for a name and the connection will be sent a custom message

**Comment by avinashkranjan** [comment]
I'd Like to take this issue in Python.. @HarshCasper

**Comment by SANKET7738** [comment]
I would like to work on this in Javascript.

**Comment by HarshCasper** [comment]
Assigned this to you @SANKET7738 in Javascript
