### ISSUE TITLE
Generate QR Codes

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#281]
# Description

Create a Script to generate QR Codes in bulk.

## Language

- [X] Javascript
- [X] Python
- [X] Golang 

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by mandirarama** [comment]
I would like to work on it [Python]. Please let me know the preferred mode of input, if there is any, and assign.

**Comment by HarshCasper** [comment]
I am assigning it to you @mandirarama 

You can take in inputs from a CSV file for the purpose.
