### ISSUE TITLE
Create a Script to implement Steganography

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#282]
# Description

Create a Script to implement Steganography

## Language

- [X] Python
- [X] Javascript
- [X] Golang

**Comment by AkM-2018** [comment]
Steganography seems super interesting. I would like to take this up

**Comment by simarpreetsingh-019** [comment]
If its just for adding the text using stegnography, I would like to work on this issue, with python language.
I would try to implement the vice versa also if possible.

**Comment by HarshCasper** [comment]
@AkM-2018 I am assigning this to you

@simarpreetsingh-019 If you would like to work in JS, I can assign this to you.

**Comment by simarpreetsingh-019** [comment]
> @AkM-2018 I am assigning this to you
> 
> @simarpreetsingh-019 If you would like to work in JS, I can assign this to you.

Actually I don't work on js, I only work on python.
If @AkM-2018 could work on it in Js, as he haven't mentioned in which language he will work, would you assign this to me for doing this in python?

**Comment by AkM-2018** [comment]
Sorry @simarpreetsingh-019, but even I work on python. I don't know JS.
