### ISSUE TITLE
Script to scrap Amazon Reviews

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#283]
# Description

Create a Script to scrap Amazon Reviews for a particular product and save them in a CSV. 

## Language

- [X] Python
- [X] Javascript
- [X] Golang

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by tejan-singh** [comment]
I would like to work on this in python.

**Comment by SANKET7738** [comment]
I would like to work on this in Javascript

**Comment by HarshCasper** [comment]
Assigned to you @tejan-singh and @SANKET7738

**Comment by kaustubhgupta** [comment]
@HarshCasper is this issue is available in Python I would like to take it up!
