### ISSUE TITLE
Hacker News Scrapper

### ISSUE THREAD

**Issue by srimani-programmer** [HarshCasper/Rotten-Scripts#289]
# Description
Develop a script to scrape the hacker news latest articles.

## Language

- [x] Python

## Type of issue

- [x] Feature

**Comment by AdityaJ7** [comment]
I would like to work on this issue

**Comment by rutujadhanawade** [comment]
I would like to work on this issue

**Comment by amoghatsunil** [comment]
I would like to work on this issue

**Comment by srimani-programmer** [comment]
@AdityaJ7 you can work on this issue.

**Comment by AdityaJ7** [comment]
with articles, you mean  titles and links of top 30 articles right @srimani-programmer

**Comment by srimani-programmer** [comment]
@AdityaJ7 No I mean the scrapper should scrape the title. When user asks for title it should scrape the article content as well. please let me know if you have any questions.

**Comment by AdityaJ7** [comment]
> @AdityaJ7 No I mean the scrapper should scrape the title. When user asks for title it should scrape the article content as well. please let me know if you have any questions.

So  I have to scrape the content of the latest hacker news article right?
But the problem is the articles on hacker news are sometimes present in the form of pdf and sometimes even videos.

**Comment by srimani-programmer** [comment]
if PDF format just download the PDF file. If it is video intimate the user to visit the webpage by providing an appropriate link. or else for video content use the selenium driver to load the article in the chrome browser.

**Comment by AdityaJ7** [comment]
> if PDF format just download the PDF file. If it is video intimate the user to visit the webpage by providing an appropriate link. or else for video content use the selenium driver to load the article in the chrome browser.


> if PDF format just download the PDF file. If it is video intimate the user to visit the webpage by providing an appropriate link. or else for video content use the selenium driver to load the article in the chrome browser.

ok will do that
