### ISSUE TITLE
Build a Github Username Checker and Generator

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#29]
## AIM

Build a Github Username Checker and Generator.

## Languages

- Python
- Javascript
- Go

## Details

I want to check if a particular Username exists on Github or not. I enter a name and the Script should generate a list of Usernames possible out of my Initial Name and my Title and check which Username is available. In Python, you can make use of ```requests``` and ```random_word``` while in Javascript you can make use of a variety of HTTPS libraries for this purpose.

**Comment by Sanketwable** [comment]
I want to work on this

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it.

**Comment by Sanketwable** [comment]
Generated a PR for this issue : https://github.com/HarshCasper/Rotten-Scripts/pull/43
@HarshCasper,  Please review
