### ISSUE TITLE
IMDB Scapper

### ISSUE THREAD

**Issue by srimani-programmer** [HarshCasper/Rotten-Scripts#290]
# Description

Develop a script that should scrape the following details with the given movie name

1. Move Name
2. Movie Length in minutes
3. Movie Release year
4. Movie Cast and Crew
5. Movie Director
6. Movie Writer
7. Movie Story Line
8. Movie Genres

## Language

- [x] Python

## Type of issue

- [x] Feature

**Comment by AdityaJ7** [comment]
I would like to work on this issue

**Comment by srimani-programmer** [comment]
Yes.! You can proceed with this issue. @AdityaJ7
