### ISSUE TITLE
CodeForces Problem Scrapper

### ISSUE THREAD

**Issue by srimani-programmer** [HarshCasper/Rotten-Scripts#291]
# Description
Develop a python script that should scrape the problem statement into a PDF File with a given problem code from the code forces website. The script should scrape the following items:

1. Problem Statement
2. Images (If any are mentioned in the problem statement)
3. Given Input and Output of the problem statement. 

## Language

- [x] Python

## Type of issue

- [x] Feature

**Comment by AkM-2018** [comment]
I would like to do this. I've done a similar thing with geeksforgeeks

**Comment by srimani-programmer** [comment]
Yeah.! Sure You can work on this issue @AkM-2018

**Comment by AkM-2018** [comment]
Hey! I'm facing some issues solving this. Firstly, I'm using beautiful soup instead of selenium now. The thing is all the text in the codeforces website is inside div tags. Now due to its natural block styling, they appear in separate lines. When I scan for the text using beautiful soup, they appear on a single line with spaces. Any help would be really appreciated.

**Comment by keshavnath** [comment]
I would like to work on this issue, I've been practicing BeautifulSoup and I think I can solve your problem as I had encountered a similar issue while scraping emails from a certain website
May I be assigned to this?

**Comment by srimani-programmer** [comment]
@AkM-2018 Use some regex techniques and string formatting techniques before printing it on to the console. Try this out to get the desired results if not please reach me. I'm happy to help you.

**Comment by srimani-programmer** [comment]
@keshavnath, No already this issue is assigned to @AkM-2018. So please find some other open issues in this project. Thank you

**Comment by keshavnath** [comment]
Okay, thank you

**Comment by AkM-2018** [comment]
I'm stuck with it for too long, @srimani-programmer . Better reassign the issue.

**Comment by srimani-programmer** [comment]
@AkM-2018 Can you please send me the files that you are worked till now. I want to have a look at it. If it meets at least the minimum criteria then I will merge it.

**Comment by keshavnath** [comment]
I'm still ready to work on it, if it needs re-assignment :)

**Comment by AkM-2018** [comment]
@srimani-programmer, I had made a pull request for it but with that method, you can't copy the text. Then I tried BeautifulSoup but the webpage has too many divs and some of the divs have img tag so I didn't know how to handle it.

**Comment by iamakkkhil** [comment]
I would like to work on this issue, also I am a GSSoC'21 Participant. If assigned can you change the label accordingly?

**Comment by vybhav72954** [comment]
@iamakkkhil Sure thing, try to reply within a week

**Comment by iamakkkhil** [comment]
Hey there are total of 6 things :
1. Heading (Name of pblm statement, time , std input and output)
2. Problem statement (with images if any)
3. Input
4. Output
5. Example
6. Note

So how many of them I need to scrape ? 
and will it be fine if I scrape <li> tags as get_text() or do you need it separately?

**Comment by iamakkkhil** [comment]
Also, can you help me out that how to deal with mathjax code.
Suppose if N is in mathjax format and after scraping it becomes $$$n$$$. how to solve this

**Comment by iamakkkhil** [comment]
@vybhav72954 @HarshCasper @seema1711 could you please have a look at the PR and let me know if there is something I need to work on
