### ISSUE TITLE
Codechef Problem Scrapper

### ISSUE THREAD

**Issue by srimani-programmer** [HarshCasper/Rotten-Scripts#294]
# Description
Develop a script that should scrape the problem statement with the help of the problem Code.

## Language

- [x] Python
## Type of issue

- [x] Feature

**Comment by AdityaJ7** [comment]
I would like to work on this issue

**Comment by srimani-programmer** [comment]
Yeah sure, you can work on this issue @AdityaJ7

**Comment by amoghatsunil** [comment]
I would like to work on this issue
