### ISSUE TITLE
Document Scanner to Scan the tables and Convert it into Excel/CSV Files

### ISSUE THREAD

**Issue by srimani-programmer** [HarshCasper/Rotten-Scripts#296]
# Description
Develop a script that should scan any kind of document and convert all the tables in the document into an either excel/CSV file.

## Language
- [x] Go
- [x] Javascript
- [x] Python

## Type of issue

- [x] Feature

**Comment by rutujadhanawade** [comment]
I would like to work on this issue.

**Comment by srimani-programmer** [comment]
@rutujadhanawade you are assigned for this issue.

**Comment by rutujadhanawade** [comment]
@srimani-programmer will you please tell me how can I proceed with this as I can scan pdf files and convert it into csv.
But how to scan any kind of docs?

**Comment by kana800** [comment]
hey! , I would love to work on this :smile:

**Comment by HarshCasper** [comment]
I am assigning this to you @kana800

**Comment by kana800** [comment]
Quick Question:
files that we are using, does it contains only the table, or other information as well ?

**Comment by kaustubhgupta** [comment]
@HarshCasper I would like to contribute to this issue in Python under Hacktoberfest! 😃😃

**Comment by vybhav72954** [comment]
@HarshCasper If still open, Assign me please

**Comment by vybhav72954** [comment]
@HarshCasper @srimani-programmer Just a doubt, these files contain information other than the table also? Or these files just have a bunch of tables?
