### ISSUE TITLE
Random password generator.

### ISSUE THREAD

**Issue by seema1711** [HarshCasper/Rotten-Scripts#299]
# Description

Write a Python script to generate a random password.

## Language

- [x] Python

## Type of issue

- [x] Feature

**Comment by sameersrivastava13** [comment]
i would like to work on this. Please assign me this issue.

**Comment by seema1711** [comment]
Sure, assigned to you @sameersrivastava13

**Comment by amoghatsunil** [comment]
I would like to work on this issue
