### ISSUE TITLE
Cryptocurrency Prices

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#3]
## AIM

Create a Script that can retrieve Cryptocurrency Prices from the [Coinbase Database](https://www.coinbase.com/price).

## Languages

- Python
- Javascript
- Go

## Details

Cryptocurrency Prices are subject to market changes and in this Script, we are giving the option to Developers to track them straight from their Command-Line. The Script should make use of Web Scrapping Options to get the prices of the Cryptocurrencies and report to the User.

**Comment by mbcse** [comment]
would like to work on this

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can work on this now @mbcse
