### ISSUE TITLE
Create a Script to send Mails 

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#30]
## AIM

Create a Script to send E-Mails to a list of Users.

## Languages

- Python
- Javascript

## Details

Make use of variety of libraries available in Python and JS like ```smtplib``` and ```nodemailer``` respectively to send E-Mails.

**Comment by Namyalg** [comment]
I would like to work on this.

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @Namyalg

**Comment by Namyalg** [comment]
I have written scripts in both python and JS. Have both been considered?
