### ISSUE TITLE
Twitter Tweet Scrapper

### ISSUE THREAD

**Issue by srimani-programmer** [HarshCasper/Rotten-Scripts#301]
# Description
Develop a script that should scrape the tweets from twitter using Tweet Tag.

## Language

- [x] Javascript
- [x] Python

## Type of issue

- [x] Feature

**Comment by AkM-2018** [comment]
I would like to take this up :D

**Comment by basketcase03** [comment]
Would it be alright to use Tweepy?

**Comment by srimani-programmer** [comment]
@basketcase03 Sorry I am not able to merge this because without intimating to us you should not proceed with the issue. first please follow the guidelines properly.

**Comment by basketcase03** [comment]
> @basketcase03 Sorry I am not able to merge this because without intimating to us you should not proceed with the issue. first please follow the guidelines properly.

Sure, I thought asking would suffice for intimating. But I'll adhere more strictly from now on. Thanks!

**Comment by HarshCasper** [comment]
Assigning this to you @AkM-2018

**Comment by AkM-2018** [comment]
@srimani-programmer, since @basketcase03 is already done with the code, I am unassigning myself from this issue.

**Comment by srimani-programmer** [comment]
@basketcase03 please make a new PR for the issue. I will merge it.

**Comment by basketcase03** [comment]
Sure, will do it
