### ISSUE TITLE
Twitter Bot

### ISSUE THREAD

**Issue by srimani-programmer** [HarshCasper/Rotten-Scripts#302]
# Description

Develop a script in python that should run in the system background and intimate us when we got any new message for us. This script should start automatically when the system is started and the script should manage processes properly without using many resources while running in the system background.

## Language

- [x] Python

## Type of issue

- [x] Feature

**Comment by Namyalg** [comment]
I would like to work on this

**Comment by srimani-programmer** [comment]
@Namyalg issue is assigned to you.!

**Comment by Namyalg** [comment]
What are the exact functionalities that need to be implemented?

**Comment by srimani-programmer** [comment]
The main required functionalities are:
- The script should start automatically when the system is started.
- It should send us a notification when any person sends us a message.
- It should not consume more RAM. Process management must be good.

**Comment by Namyalg** [comment]
Okay.

**Comment by Namyalg** [comment]
Does the notification have to be an email, or a desktop notification?

**Comment by srimani-programmer** [comment]
Desktop Notification.
