### ISSUE TITLE
Create a File Organizer Script

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#31]
## AIM

Create a File Organizer Script.

## Languages

- Python

## Details

My Download Folder is a typical mess with files of all extensions like ```.mp4```,  ```.pdf```,  ```.docx``` and more. I want to group them in separate folders according to their Extension. Create a Script that can help me in that purpose.

**Comment by Puneet-Pal-Singh** [comment]
Hi Harsh, I like to work on this script.

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @Puneet-Pal-Singh
