### ISSUE TITLE
Google Drive Content Downloader

### ISSUE THREAD

**Issue by srimani-programmer** [HarshCasper/Rotten-Scripts#318]
# Description
Develop a script that should download the content that is stored in the google drive. The script should download the entire folder or a particular file based on the given link. The script should use multithreading to download the large files very easily. 

## Language

- [x] Go
- [x] Javascript
- [x] Python

## Type of issue

- [x] Feature

**Comment by akshaysonawaneS** [comment]
I will like to work on this.

**Comment by srimani-programmer** [comment]
@akshaysonawaneS issue is assigned to you.!

**Comment by vybhav72954** [comment]
@HarshCasper @srimani-programmer Is this still open in Python?

**Comment by HarshCasper** [comment]
@xenowits Kindly let me know if you are ready to take it up in Golang. I will assign it to you. 

@vybhav72954 The Issue is open in Python, but you can take it up once the rest Issue assigned to you are resolved.

**Comment by sujal111** [comment]
Please allow me to work this issue

**Comment by HarshCasper** [comment]
Hello @sujal111 

Please go ahead in working on this!

**Comment by HarshCasper** [comment]
Are you working on this @sujal111 ? 

If not, I will assign this to someone else.

**Comment by vybhav72954** [comment]
@HarshCasper Is this open?
