### ISSUE TITLE
Convert image into cartoonified image 

### ISSUE THREAD

**Issue by sharur7** [HarshCasper/Rotten-Scripts#319]
# Description
**HackinCodes2020 Participant**
Computer Vision as we know is a very powerful tool with immense possibilities.
So, why not to use it?
Here, I want to implement a script that will read the original image and convert the original image into cartoonified image.

## Language

- [x] Python

## Type of issue

_Please delete options that are not relevant._

- [x] Feature

## Checklist:

- **For Feature**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Cartoonifying Image | To reduce efforts of actually painting a cartoon image | feature | @sharur7 |

**Is your feature request related to a problem? Please describe.**:  This feature can be implemented to reduce the efforts to paint the actual cartoon picture.

**Describe the solution you'd like**: This script will convert the original image into cartoonified image.

@HarshCasper @srimani-programmer @seema1711  I want to take up this issue.

**Comment by srimani-programmer** [comment]
Cartoonified image means what? is it related to converting an image into Sketch Image. please let me know @sharur7

**Comment by sharur7** [comment]
> Cartoonified image means what? is it related to converting an image into Sketch Image. please let me know @sharur7

Yes, it is similar to sketch image @srimani-programmer

**Comment by srimani-programmer** [comment]
Yeah.! You can work on this issue.! issue is assigned to @sharur7
