### ISSUE TITLE
Create a Script to download Instagram Videos

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#32]
## AIM

Create a Script to download Instagram Videos

## Languages

- Python
- Javascript

## Details

The User should pass in the ```Post``` ID and the Script should download the Video and save it in the Root Directory.

**Comment by Prahitha** [comment]
I would like to work on this.

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @Prahitha
