### ISSUE TITLE
Adding retry mechanism code for the database connection 

### ISSUE THREAD

**Issue by sameersrivastava13** [HarshCasper/Rotten-Scripts#325]
# Description

Sometimes errors can occur when you are connecting to a Database, because network connections to a database are never 100% perfect. Therefore i would like to add a python script in which the retry mechanism will be implemented so that if suppose first time it fails to connect with the DB then at least 3 times it should try reconnecting with the database.

## Language

- [x] Python

## Type of issue

_Please delete options that are not relevant._

- [x] Feature

## Checklist:

- **For Feature**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Feature request |Adding retry mechanism code for the database connection. | feature, CH-20, medium | self-assign |

**Comment by sameersrivastava13** [comment]
@HarshCasper Please add the CH-20 label and assign this issue to me.

**Comment by srimani-programmer** [comment]
@sameersrivastava13 You can work with this issue now.!
