### ISSUE TITLE
Check the timing of a program.

### ISSUE THREAD

**Issue by seema1711** [HarshCasper/Rotten-Scripts#327]
# Description

Check how long a program has been running and offer the user a chance to cancel tasks that are taking too long.

## Language

- [x] Python

## Type of issue

- [x] Feature

**Comment by eternal-dreamer** [comment]
I want to work on this issue.

**Comment by seema1711** [comment]
Sure.

**Comment by Akshi149** [comment]
@seema1711 I would like to work on this issue
