### ISSUE TITLE
Create a Script to find a Phone Number in a Text

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#33]
## AIM

Create a Script to find a Phone Number in a Text.

## Languages

- Python
- Javascript
- Go

## Details

This is an interesting use case where you make use of Regular Expressions and try to find the Phone Number in a Text.

**Comment by sanket143** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
I have assigned you the Issue @sanket143

**Comment by HarshCasper** [comment]
Sorry, @sanket143 

This Issue was for PSoC'2020 Participants and I mistakenly assigned you the Issue without looking at the Tags. Sorry for Misunderstanding.

**Comment by Sanketwable** [comment]
@HarshCasper  how is it supposed to work?

**Comment by HarshCasper** [comment]
@Sanketwable Well, the User can input a text file and the Script should make use of Regular Expressions to spit out all the Valid Phone Numbers in the Text

**Comment by Sanketwable** [comment]
for checking whether a number is valid or not, we have to use an API. 
but none of the API is public.

**Comment by HeroicHitesh** [comment]
@HarshCasper I am interested to work on this if no one is assigned.

**Comment by HeroicHitesh** [comment]
> @Sanketwable Well, the User can input a text file and the Script should make use of Regular Expressions to spit out all the Valid Phone Numbers in the Text

@HarshCasper What is meant by `valid Phone Numbers` here? Is it a number having 10 digits with the first digit being one of the digits from 7, 8, or 9? or any other specific conditions need to be satisfied in order to qualify as a valid no?

**Comment by HarshCasper** [comment]
@HeroicHitesh It is a simple Regex Problem where you have to validate if a Phone Number is a valid number or not. You don't need an API to check if that number exists or not. 

If you are still interested, I can assign this to you @HeroicHitesh

**Comment by HeroicHitesh** [comment]
@HarshCasper actually I knew about the use of RE to solve this issue but I was curious about knowing what format is valid in our context? 
There are different type of valid number formats available out there like - xxx-xxxx-xxx or xxx-xxx-xxxx, here x means a digit.
If you can clarify this doubt it will be easy for me to proceed.
Also, you can assign me this issue I am interested in it.

**Comment by HarshCasper** [comment]
@HeroicHitesh You can handle this in context for Indian Phone Numbers in the format of both AAAAA-BBBBB (For Mobile Phones) and AAA-BBBBBBB (Landlines)
