### ISSUE TITLE
Audio Steganography

### ISSUE THREAD

**Issue by srimani-programmer** [HarshCasper/Rotten-Scripts#333]
# Description
Implement the concept of steganography to send and receive confidential information using audio files.

## Language

- [x] Bash
- [x] Go
- [x] Javascript
- [x] Python

## Type of issue

- [x] Feature

**Comment by rohankumawat** [comment]
I would like to work on this (Python). Can you please assign me this?

**Comment by rohankumawat** [comment]
> I would like to work on this (Python). Can you please assign me this?

**Comment by DevChoganwala** [comment]
@HarshCasper I would like to work on this issue in python under SLOP if still not resolved.

**Comment by DevChoganwala** [comment]
@rohankumawat If you are still working on this issue I can take another one. Please confirm.

**Comment by rohankumawat** [comment]
> @rohankumawat If you are still working on this issue I can take another one. Please confirm.

I'm working on it!

**Comment by DevChoganwala** [comment]
> > @rohankumawat If you are still working on this issue I can take another one. Please confirm.
> 
> I'm working on it!

Ok ill take up another issue then.
