### ISSUE TITLE
Video Steganography

### ISSUE THREAD

**Issue by srimani-programmer** [HarshCasper/Rotten-Scripts#334]
# Description
Implement the concept of steganography for transferring confidential information using Video files.

## Language

- [x] Bash
- [x] Go
- [x] Javascript
- [x] Python

## Type of issue

- [x] Feature

**Comment by vvHacker007** [comment]
I want to work on this issue, can you assign it to me.

**Comment by srimani-programmer** [comment]
@vvHacker007 issued is assigned to you. Good luck with this issue.

**Comment by vvHacker007** [comment]
I want to work with Python

**Comment by srimani-programmer** [comment]
Okay then go ahead

**Comment by vvHacker007** [comment]
Thank You

**Comment by vvHacker007** [comment]
I have created a python program for video steganography, should i also create an application for it.

**Comment by vvHacker007** [comment]
I have given the pull request for the python script.

**Comment by eeshashetty** [comment]
Hey I'd love to work on this Bash! Could you assign this to me?
