### ISSUE TITLE
Make a customized blog header. 

### ISSUE THREAD

**Issue by seema1711** [HarshCasper/Rotten-Scripts#336]
# Description

When writing technical blogs, we need some images to tell about the blog, and it's hard to find relatable pictures sometimes, and they are sometimes copyrighted. So, make a customized program that can generate images for your blogs.

## Language

- [x] Javascript
- [x] Python

## Type of issue

- [x] Feature

**Comment by kaustubhgupta** [comment]
the script should get images related to the topic given and saved as jpeg?

**Comment by kaustubhgupta** [comment]
> the script should get images related to the topic given and saved as jpeg?

if this is the case I would like to take this issue

**Comment by seema1711** [comment]
No, It can be a simple template that can be applied to any blog, and if you want to add some more options to customize it, that'd be great too.

**Comment by kaustubhgupta** [comment]
I am not able to understand, you mentioned this:

> So, make a customized program that can generate images for your blogs.

and now saying template. Can you explain the issue again in detail?

**Comment by seema1711** [comment]
![image](https://user-images.githubusercontent.com/48756444/92730652-b3c41100-f391-11ea-9ba3-ac9ad1f19474.png)
Like this.

**Comment by kaustubhgupta** [comment]
okay got it. I would like to work for this issue in Python

**Comment by gupta-piyush19** [comment]
@seema1711 II would like to work on this issue in JavaScript, but need some more insight.

**Comment by seema1711** [comment]
Sure, tell me. @gupta-piyush19

**Comment by kaustubhgupta** [comment]
@seema1711 @HarshCasper made PR #341

**Comment by gupta-piyush19** [comment]
> 
> 
> Sure, tell me. @gupta-piyush19

@seema1711 Do I have to use some API and search image of any genre and download them? or something else

**Comment by HarshCasper** [comment]
You can use anything that fits the purpose @gupta-piyush19
