### ISSUE TITLE
Base64 Encoder and Decoder

### ISSUE THREAD

**Issue by gupta-piyush19** [HarshCasper/Rotten-Scripts#346]
# Description

Add script which can encode as well as decode any string

## Language

- [x] Javascript
- [x] Python

## Type of issue

- [x] Feature

**Comment by gupta-piyush19** [comment]
I would like to add the script in JavaScript

**Comment by narayan2111** [comment]
I would like to work on this issue in python, kindly assign this issue to me @HarshCasper

**Comment by HarshCasper** [comment]
Assigned to you @narayan2111
