### ISSUE TITLE
Create a Medium Article Downloader

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#35]
## AIM

Create a Medium Article Downloader.

## Languages

- Python
- Javascript
- Golang

## Details

Since most of the Medium Articles are behind a paywall, it would be quite better if you can create a Script that can privately downloaded Medium Article and save them in your Downloads Folder.

**Comment by Namyalg** [comment]
I would like to try this.

**Comment by HarshCasper** [comment]
You can start working on this @Namyalg

**Comment by HarshCasper** [comment]
Are you working on this @Namyalg ?

**Comment by Namyalg** [comment]
Yes, I need a little assistance on this. We will know the URL of the
article that needs to be downloaded here right?

**Comment by HarshCasper** [comment]
Yes, of course. The User will pass the URL of the Blog that needs to be downloaded.

**Comment by Namyalg** [comment]
Okay, will continue working on it then.

**Comment by Namyalg** [comment]
Is is necessary to download and include all the images included in the article ?
