### ISSUE TITLE
text to speech / Stort teller

### ISSUE THREAD

**Issue by simarpreetsingh-019** [HarshCasper/Rotten-Scripts#355]
# Description

This will be a storyteller that will read and speak from txt file or pdf file depending upon which you are redirecting.

## Language

- [ ] Python

**Comment by brtymn** [comment]
Hello! I can work on this if you assign me!

**Comment by simarpreetsingh-019** [comment]
@brtymn Actually I created this issue because I wanted to work on it using python. 
If the admin says, I think you can work on same issue using different language if possible.
Wait for response.

**Comment by brtymn** [comment]
Oh. That is fine. I have a script that kinda does this already. I can share it with you if you want.
