### ISSUE TITLE
Wifi Speed tester

### ISSUE THREAD

**Issue by vvHacker007** [HarshCasper/Rotten-Scripts#356]
# Description

Please include a summary of the issue.
This is a wifi-speed-tester that would provide the download speed, upload speed and the ping of the connected network.

## Language

- [x] Go
- [x] Javascript
- [x] Python

## Type of issue

_Please delete options that are not relevant._

- [x] Feature

**Comment by brtymn** [comment]
Hello! Can you assign me please?

**Comment by vvHacker007** [comment]
The issue will be assigned to you soon. Can you tell me in which language do you want to work with.

**Comment by HarshCasper** [comment]
I am assigning this to you @vvHacker007 

@brtymn You can work on this in JS/Golang if you would like to
