### ISSUE TITLE
Find the Current City Weather

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#36]
## AIM

Find the Current City Weather

## Languages

- Python
- Javascript

## Details

You can make use of an ```OpenWeather Map API``` to fetch the Weather of a City and display it on the CLI itself.

**Comment by Prahitha** [comment]
I would like to work on this.

**Comment by Namyalg** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
You can work on the Python Implementation @Prahitha 

Would you like to work on implementation in Javascript @Namyalg ?

**Comment by Namyalg** [comment]
I have already done the python implementation.  I can try javascript.

**Comment by Namyalg** [comment]
Hey,
I wanted to know if I can improve my script for accessing github content
given username. I have created a pull request.

Regards,
Namya LG
