### ISSUE TITLE
Shift Script to appropriate Folder

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#360]
# Description

Some of the Scripts have been added to the Root. Please shift them in the apt folder according to their Language and Purpose. The Scripts are: 

- [Automate LinkedIn](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Automate-LinkedIN)
- [Automate Telegram](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Automate-Telegram)
- [HTML to Markdown](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Html%20to%20markdown)

Please fix this issue.

**Comment by kaustubhgupta** [comment]
I would like to take this issue

**Comment by kaustubhgupta** [comment]
@HarshCasper fixed the issue in #362
