### ISSUE TITLE
Get Cricket Scores

### ISSUE THREAD

**Issue by Preetesh21** [HarshCasper/Rotten-Scripts#361]
# Description

The script should give information about the teams and the scores if the match has started.
## Language
- [ ] Python

**Comment by importhuman** [comment]
Hello! 

I'd like to work on this if possible, can you please provide more details about the desired script?

**Comment by Preetesh21** [comment]
@importhuman I had made the issue to get a script which could retrieve the latest cricket matches score. @importhuman the task would be assigned by the admin.

**Comment by importhuman** [comment]
Do you just want the script or do you want it to be assigned to you and work on it?

**Comment by Preetesh21** [comment]
I wanted it to work on it in Python.

**Comment by importhuman** [comment]
I see, I misunderstood earlier. Good luck!
