### ISSUE TITLE
Scrap E-Mail Links from a LinkedIn Post

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#366]
# Description

Scrap E-Mail Links from a LinkedIn Post. The basic features I am looking at from this Script include: 
- Enter the Link of the Post 
- Scrap the E-Mail of specified subdomains (G-Mail, Yahoo, Outlook, ProtonMail).
- Store them on a CSV File and output the same. 

## Language

- [X] Go
- [X] Javascript
- [X] Python

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by kaustubhgupta** [comment]
I would like to work on this issue

**Comment by HarshCasper** [comment]
Damn, that's quick! 

Assigned!

**Comment by rishabhvarshney14** [comment]
Can I do that in python?

**Comment by kaustubhgupta** [comment]
@HarshCasper made PR #380
