### ISSUE TITLE
Add a Github Action to mark issues as "Stale"

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#367]
## Type

Advancement

## Description

Add a Github Action to mark stale Issues with a Tag. Issues which are not assigned, or has not been mentioned anywhere for more than 7 Days should be tagged with a "Stale" tag automatically.

## Tools

- Github Actions

**Comment by kritikaparmar-programmer** [comment]
I want to work on this issue @HarshCasper

**Comment by HarshCasper** [comment]
Assigned to you @kritikaparmar-programmer
