### ISSUE TITLE
Create a Script to hunt for Usernames across Social Channels

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#369]
# Description

Create a Script to hunt for Usernames across Social Channels. You can take in a Username though CLI and find whether the particular Username exists on the given Social Media Channels or not. You can take in popular Social Channels (Github, Reddit, Instagram and more) and see if the User exists on any of these Social Channels given the Username.

## Language

- [X] Go
- [X] Python
- [X] Javascript

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by pradyyadav** [comment]
I want to work on this

**Comment by HarshCasper** [comment]
Assigned @pradyyadav

**Comment by pradyyadav** [comment]
I am done with the script. Do I need to make any kind of checklist like others or just creating a PR will work? Issue : #369

**Comment by HarshCasper** [comment]
Hello @pradyyadav 

Please make a PR

**Comment by Blastoise** [comment]
Assign this to me, I will be doing it using Bash.

**Comment by Blastoise** [comment]
@HarshCasper Please add SWOC label in this issue so that my contribution is counted.
