### ISSUE TITLE
Ping your Servers

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#37]
## AIM

Create a Script that can ping a remote server and notify you if it is down.

## Languages

- Python
- Javascript
- Golang

## Details

I sometimes need to take a look if my Servers on platforms like ```Heroku``` are still operational after a time. You can create a Script that can ping your server and check if it is still functional or not.

**Comment by sanket143** [comment]
`ping` is available for all Operating Systems. We can just `ping google.com`. :grey_question:

**Comment by HarshCasper** [comment]
@sanket143 This Issue is for PSoC'2020 Participants and serves as a Good First Issue for them to start over.

**Comment by Sanketwable** [comment]
@HarshCasper How is this supposed to work??

**Comment by HarshCasper** [comment]
The Web Apps deployed on Heroku sometimes get non-operational when they are not in use for few days. This Script can ping that Heroku Server in a fixed interval and notify you when it has become non-operational and even 'force' it to wake up.
