### ISSUE TITLE
Script to Scrape Reddit

### ISSUE THREAD

**Issue by kritikaparmar-programmer** [HarshCasper/Rotten-Scripts#371]
# Description
I want to add script to scrape reddit. 

## Language
- [x] Python

## Type of issue
- [x] Feature

**Comment by kritikaparmar-programmer** [comment]
Hey @HarshCasper Take a look at this issue. I want to work on it..

**Comment by HarshCasper** [comment]
Hello @kritikaparmar-programmer 

We already have few Reddit Scripts. Can you be specific on what type of content you want to scrap from Reddit?

**Comment by kritikaparmar-programmer** [comment]
Hey @HarshCasper I can write script to scrape subreddits top 10 or 20 posts and if you want it user friendly I can add an option that will enable user to choose the type of the posts he/she want.

**Comment by HarshCasper** [comment]
Looks good! I am assigning this to you.
