### ISSUE TITLE
Add a Github Action to unassign Issues

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#372]
# Description

Add a Github Action to unassign Issues. The Action should do the following: 
- On 7 Days of inactivity, unassign the person that has been assigned the Issue. 
- Remove the `Assigned` Label and add `Up-for-Grab` Label. 

## Tools

- Github Action

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by kaustubhgupta** [comment]
I would like to take this issue, I have made PR for one of the issues, and for the second one I am making it soon

**Comment by bharxhav** [comment]
I want to take this issue. I have experience with Github actions. And obviously, I will finish within the deadline. 😁

**Comment by bharxhav** [comment]
I tried a lot to make that action, but every time I do that I find that there is no other way that to create this action from scratch. And only another possibility was octokit, which has been deprecated and broken for 2 Years for now. I am sorry but, this has to be done manually.

**Comment by vybhav72954** [comment]
@HarshCasper Assign this to me, please

**Comment by vybhav72954** [comment]
@HarshCasper If I change the duration to 14 days or 10 days. I hope it won't be a problem
