### ISSUE TITLE
Add a Github Action to add Contributor

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#373]
# Description

Create a Github Action to add First-Time Contributors to the Project by invoking the @all-contributors bot. All new Contributors should be added for `code` and `documentation` and a PR should be raised for that.

## Tools

- Github Action

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by kritikaparmar-programmer** [comment]
I want to work on this @HarshCasper.. Please assign me.

**Comment by HarshCasper** [comment]
Done @kritikaparmar-programmer

**Comment by Abjcodes** [comment]
Hey @HarshCasper, I would like to work on this issue.

**Comment by HarshCasper** [comment]
Assigned @Abjcodes

**Comment by HarshCasper** [comment]
Hello @Abjcodes 

Are you working on this? If not, I will assign this to someone else.

**Comment by Abjcodes** [comment]
> Hello @Abjcodes
> 
> Are you working on this? If not, I will assign this to someone else.

Yes. I will raise a PR within 2-3 days.

**Comment by Abjcodes** [comment]
Hey @HarshCasper, sorry for the delay. I am facing some troubles regarding the implementation of this action. Can you mention the approach towards creating the action? Should this be done with a python script?

**Comment by HarshCasper** [comment]
> Hey @HarshCasper, sorry for the delay. I am facing some troubles regarding the implementation of this action. Can you mention the approach towards creating the action? Should this be done with a python script?

Take a look at this: https://github.com/HarshCasper/Rotten-Scripts/issues/641

**Comment by vybhav72954** [comment]
@Abjcodes Actually a Python script is useless here, you need to make a YAML file. The language is easy, but very strict, if you face trouble you can see #698 

All these are GitHub actions only. You need to make a GitHub action that will trigger the `bot` used in this Repo.

The actions in my PR are working, but the PR is open as Harsh is yet to review
