### ISSUE TITLE
Add a Github Action to run Python PRs through PyLint

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#374]
# Description

Add a Github Action to run Python PRs through PyLint. Recently the Code Quality of the recent PRs has been quite poor. We can make use of PyLint to improve the Code Quality and provide necessary pointers on what can be the changes done. The Github Action must install the requirements and run the code through PyLint and invoke the code quality.

## Tools

- Github Actions

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by AdityaJ7** [comment]
Hi @HarshCasper I would like to work on this
