### ISSUE TITLE
Script to scrap LinkedIn Connections

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#375]
# Description

Create a Script to scrap LinkedIn Connections. The Script should scrap the following and store them in a CSV File: 
- Name
- LinkedIn URL 
- Latest Job Position
- Skills 

## Language

- [X] Python
- [X] Javascript
- [X] Golang

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by kritikaparmar-programmer** [comment]
Hey @HarshCasper I want to do this issue in Python.. Please assign me.

**Comment by HarshCasper** [comment]
You are on a roll! Assigned!

**Comment by kritikaparmar-programmer** [comment]
Hey @HarshCasper I've one doubt do I have to scrap all the connections or the user will give me the url of the connection which he want to scrap??

**Comment by HarshCasper** [comment]
@kritikaparmar-programmer On LinkedIn, you can specify a particular endpoint where you can scrap from. The User doesn't need to give in the URL of the Profile which we wishes to scrap.

**Comment by sujal111** [comment]
Allow me to work on this issue

**Comment by HarshCasper** [comment]
Hello @sujal111 

Assigned to you. You can create a PR for this now 👍

**Comment by Purvanshsingh** [comment]
Hey, Please assign me this issue for SWOC 21.

**Comment by amandp13** [comment]
@HarshCasper Please assign me this issue for SWOC 21.

**Comment by Purvanshsingh** [comment]
I am working on it.

**Comment by pritamp17** [comment]
@HarshCasper please assign this issue to me in python.

**Comment by Sukriti-sood** [comment]
@HarshCasper I would like to work on

**Comment by vybhav72954** [comment]
Sure thing, In case you need any help, feel free to ask me.

**Comment by Sukriti-sood** [comment]
@vybhav72954 Should I use Linkedin API or automate it using selenium.

**Comment by vybhav72954** [comment]
@Sukriti-sood 
Though I will prefer API, you can use Selenium as well. As per my understanding, it's better to use API.

**Comment by Sukriti-sood** [comment]
@vybhav72954  I have confusion regarding skills , Do I need to scrap skills which are endorsed by someone or everything which written in Skill and Endorsement Section in Linkedin Profile, And Sorry for delay ,I will do this soon.

**Comment by vybhav72954** [comment]
Endorsed ones only. If skills arent endorsed, a message depicting the same will do the job

**Comment by Sukriti-sood** [comment]
@vybhav72954  I have added PR but it failed many checks, Can you help me to resolve them

**Comment by HarshCasper** [comment]
> @vybhav72954 I have added PR but it failed many checks

No worries about that!
