### ISSUE TITLE
Script to find size of Github Repository + List of Contributors 

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#378]
# Description

Create a Script to find the size of Github Repository + List of Contributors 

## Language

- [X] Python
- [X] Javascript

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by kaustubhgupta** [comment]
I would like to take this issue

**Comment by kaustubhgupta** [comment]
@HarshCasper made PR #383

**Comment by gupta-piyush19** [comment]
@HarshCasper I would like to work on this issue in JavaScript, can you please guide me? 
In which form do I have to display my result? On an HTML page? or in some external file? 
and please tell me the way to take input(username, repo name) should I use hardcode and always change from there or use prompt?
