### ISSUE TITLE
Fetch Github Information

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#38]
## AIM

Create a Script that can fetch Github Information.

## Languages

- Python
- Javascript
- Golang

## Details

Make use of the ```Github API``` to fetch the Github Information of any particular User given the Username.

**Comment by Namyalg** [comment]
Hello,
I would like to work on this issue

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @Namyalg

**Comment by Namyalg** [comment]
How exactly am I supposed to submit the solution?

**Comment by HarshCasper** [comment]
- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

For any doubts and queries, drop a message on the Communication Channel.

**Comment by HarshCasper** [comment]
@Namyalg Are you working on the same?

**Comment by Namyalg** [comment]
I have already contributed,  it has been reviewed and merged.
