### ISSUE TITLE
Script to bomb Pull Requests on a Github Repository

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#381]
# Description

Create a Script to bomb Pull Requests. The Script should: 
- Fork and Clone a Repository and create branches automatically. 
- Add Spaghetti Code and commit-push it on the Forked Repo.
- Raise malicious PRs intended for bombing the Pull Request section. 

You can add further customizations to that, as per your need. 

## Language

- [X] Python
- [X] Golang
- [X] Javascript

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by kaustubhgupta** [comment]
I would like to work on this issue @HarshCasper

**Comment by shubhamcodez** [comment]
Could anybody guide me how to make this ?

**Comment by vybhav72954** [comment]
@HarshCasper Assign me this issue, please. Also, I think bash is the best fit, but you haven't added it, is it on purpose? If yes then ill work on python.

**Comment by HarshCasper** [comment]
@vybhav72954 There is already a PR for the same using Python and JS. 

If you would like to work on BASH, I will assign the same to you. Kindly let me know if you like to work on BASH and I will assign it to you.
