### ISSUE TITLE
Add a Github Action to label all Issues as "Hacktoberfest"

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#382]
# Description

Add a Github Action to label all Issues as "Hacktoberfest". The Issues should be visible from October 1 and must be automatically revoked on October 31st to reduce the manual work in labelling Issues.

## Tools

- Github Actions

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by AdityaJ7** [comment]
Hi, @HarshCasper I would like to work on this issue

**Comment by AdityaJ7** [comment]
Sorry, for the delay but I guess know rather than creating a separate action for this We can just edit the existing issue labeller to add the hacktoberfest label  to all the existing issues

**Comment by seema1711** [comment]
@HarshCasper I would like to work on this issue.

**Comment by HariAcidReign** [comment]
Is @AdityaJ7 doing it, or can I be assigned to this issue, please?
I know how to do it and I can get it done within this week if assigned. 😄

**Comment by seema1711** [comment]
I think he is not doing that, you can start working on this issue. @HariAcidReign

**Comment by vybhav72954** [comment]
dear @HariAcidReign Are you currently working on this?
Can this be assigned to me too?
I have made a similar Action once. And I think I can sort this really quickly.
