### ISSUE TITLE
Script to bomb Issues on a Pull Request 

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#384]
# Description

Create a Script to bomb Issues on a Github Repository. The Script should: 
- Go over a Repository and create Issues automatically. 
- Add Spaghetti Text to the Issue.
- Raise malicious Issues intended for bombing the Issue Section.
You can add further customizations to that, as per your need. 

## Language

- [X] Python
- [X] Golang
- [X] Javascript

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by rohankumawat** [comment]
Can I work on this @HarshCasper? 
*Python*

**Comment by eeshashetty** [comment]
I'd love to work on this in Python! @HarshCasper

**Comment by HarshCasper** [comment]
@eeshashetty This Issue has already been issued in Python now. If you want you can work on Javascript!

**Comment by eeshashetty** [comment]
Okay I don't mind Javascript!

**Comment by xenowits** [comment]
@HarshCasper Can i take this for go??

**Comment by rohankumawat** [comment]
> # Description
> Create a Script to bomb Issues on a Github Repository. The Script should:
> 
> * Go over a Repository and create Issues automatically.
> * Add Spaghetti Text to the Issue.
> * Raise malicious Issues intended for bombing the Issue Section.
>   You can add further customizations to that, as per your need.


@HarshCasper What did you mean by Spaghetti Text and Raise malicious issues also? Can you please explain this more?

**Comment by HarshCasper** [comment]
@rohankumawat 

You can make use of Lorem Ipsum Placeholder Texts for the purpose. You have to raise random issues depending on the number specified by the user and populate the Issue purpose with these placeholder texts.
