### ISSUE TITLE
Develop a Screen Grabber

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#39]
## AIM

Create a Screen Grabber which captures the screen and saves it in a Folder.

## Languages

- Python

## Details

Often whiling Video Lectures, I wish to capture the Screenshots and save it. This process can be automated by creating a Script that can be launched which runs in the background, and with one press of a key, this snap can be captured.

**Comment by sanket143** [comment]
For which Operating System?

**Comment by HarshCasper** [comment]
Primarily for Windows OS but if the accessibility is extended to Linux and OSX as well. That would be better. Currently, Windows Users can grab a screen with ```Windows+Prt Sc``` but this capability can be diluted to a simple click of a button like ```Shift```

**Comment by AnkitaBIT** [comment]
@HarshCasper  I would like to work on this.

**Comment by mohitacecode** [comment]
Would love to work on it.

**Comment by HarshCasper** [comment]
@AnkitaBIT You can work on this.

**Comment by SwagataJ** [comment]
Can I work on this? Do I also need to add a gui to it?

**Comment by HarshCasper** [comment]
@SwagataJ This Issue is for ```SCI-2020``` Participants. You can take a look at ```Open-to-All``` Issues.
