### ISSUE TITLE
script for scraping IMDB top movies

### ISSUE THREAD

**Issue by rutujadhanawade** [HarshCasper/Rotten-Scripts#394]
# Description

I want to add a Python script to scrape IMDB top 250 movies from the [link](https://www.imdb.com/chart/top/?ref_=nv_mv_250) saving the result in a csv file

## Language

- [x] Python

## Type of issue

- [x] Feature

**Comment by rutujadhanawade** [comment]
@HarshCasper Please add relevant labels and assign this issue to me.

**Comment by vighneshdeepweb** [comment]
@HarshCasper Interested to work on this issue could u pls assign this issue to me sir...

**Comment by rutujadhanawade** [comment]
@vighneshdeepweb  I have already created a PR for this issue.
