### ISSUE TITLE
Make a Banner Image for the Repository

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#398]
# Description

Make a Banner Image for the Repository. The Banner Image can be simply the title of this Project with an awe-striking background. This Issue can be assigned to any number of participants but only one would be accepted as the Main Banner.

You need to submit: 

- The Raw File of the Banner 
- A JPEG/PNG File of the Output

## Tools

- [X] Adobe XD
- [X] Figma 
- [X] Photoshop

## Type of issue

_Please delete options that are not relevant._

- [X] Feature
- [ ] Bug

**Comment by SuvamPrasd** [comment]
I would like to work on this issue to create an awesome banner design. @HarshCasper

**Comment by HarshCasper** [comment]
Assigned to you @SuvamPrasd

**Comment by SuvamPrasd** [comment]
@HarshCasper Thanks for assigning me this issue, already started the design.

**Comment by SuvamPrasd** [comment]
@HarshCasper Could you please review my PR?

**Comment by Cheemashyper** [comment]
Hello @HarshCasper  ,
I am a GFX Artist and would love to work on this. 
Kindly assign the issue to me and I will start working on it right away!

**Comment by srimani-programmer** [comment]
@Cheemashyper You can work on this issue.

**Comment by samriddhisv** [comment]
Hey, I would like to work on this issue. I can work with Photoshop and Canva.

**Comment by HarshCasper** [comment]
Hello @samriddhisv 

Let me know if you would like to work on it

**Comment by Pranav016** [comment]
I would like to work on this issue.

**Comment by HarshCasper** [comment]
@Pranav016 Glad to have you here! 

Are you participating on behalf of NJACK Winter of Code? If yes, I will put the apt labels and you can start the work on the Banner Image.

**Comment by Pranav016** [comment]
> @Pranav016 Glad to have you here!
> 
> Are you participating on behalf of NJACK Winter of Code? If yes, I will put the apt labels and you can start the work on the Banner Image.

Yes, I'll be working on this as a part of NJACK.

**Comment by HarshCasper** [comment]
Assigned to you @Pranav016
