### ISSUE TITLE
RSA Key Pair Generator

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#4]
## AIM

Create a Script that can generate an RSA Key Pair.

## Languages

- Python
-Javascript

## Details

Create a Script that can generate a [RSA Key Pair](https://en.wikipedia.org/wiki/RSA_(cryptosystem)) giving us a Public and a Private Key.

**Comment by mbcse** [comment]
Would Like to work on this

**Comment by HarshCasper** [comment]
You have been assigned this Issue @mbcse 

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by mbcse** [comment]
There are already some js libraries that generate RSA keys, so what different we have to do ??
