### ISSUE TITLE
Download all Repositories

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#40]
## AIM

Create a Script to download all Repositories.

## Languages

- Python
- Javascript

## Details

Sometimes, I need to backup all my Repositories on my Local Machine. Create a Script that can automatically download all the Remote Repositories from Github onto my Local Machine.

**Comment by mbcse** [comment]
would like to work on this

**Comment by HarshCasper** [comment]
I have assigned you the Issue @mbcse 

You can work on the same

**Comment by HarshCasper** [comment]
@mbcse Are you working on the same?
