### ISSUE TITLE
Check a valid YAML file.

### ISSUE THREAD

**Issue by seema1711** [HarshCasper/Rotten-Scripts#401]
# Description

We often use YAML, but there are times it can confusing in terms of the wrong indentation, so this script will help to validate the YAML file.

## Language

- [x] Python

## Type of issue

- [x] Feature

**Comment by seema1711** [comment]
@HarshCasper I want to work on this issue.

**Comment by mitul3737** [comment]
I want to work on this issue

**Comment by rishabh-28** [comment]
I would like to work on this. Please allow me to do this

**Comment by HarshCasper** [comment]
Assigned to you @mitul3737

**Comment by vybhav72954** [comment]
@HarshCasper My action for checking a valid Markdown is ready. I will be solving this issue as well in the same PR, cause I think my Linter can help ina achieving that, I hope that won't be a problem!!!!

**Comment by HarshCasper** [comment]
> @HarshCasper My action for checking a valid Markdown is ready. I will be solving this issue as well in the same PR, cause I think my Linter can help ina achieving that, I hope that won't be a problem!!!!

Go ahead! I will assign this to you.
