### ISSUE TITLE
Covid-19 Predictor Machine learning model using Jupyter Notebook & flask

### ISSUE THREAD

**Issue by vighneshdeepweb** [HarshCasper/Rotten-Scripts#403]
# Description
It is a Covid-19 Predictor which basically accepts some parameters from the patient and determines the patient's vulnerability to Covid-19
## Language

- [x] Jupyter Notebook for traning and testing 
- [x] Flask

**Comment by vighneshdeepweb** [comment]
i want to work on this issue...

**Comment by vighneshdeepweb** [comment]
#428

**Comment by vighneshdeepweb** [comment]
pls take a review....

**Comment by HarshCasper** [comment]
@vighneshdeepweb The Core Tenet of this Project is the collection of Scripts that can be used for various purposes around Automation and all. We don't exactly need ML Models for the purpose who certainty for critical matters cannot be decided in any way.
