### ISSUE TITLE
COVID 19 Data Analysis and Predictions

### ISSUE THREAD

**Issue by rutujak24** [HarshCasper/Rotten-Scripts#407]
# Description
COVID 19 Data Analysis and Predictions. 

## Language

- [ ] Bash
- [ ] Go
- [ ] Javascript
- [ ] Powershell
- [x] Python
- [ ] Other (Please specify)

## Type of issue

_Please delete options that are not relevant._

- [x] Feature

## Checklist:

- **For Feature**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Feature request | To live track the statistics of COVID Patients | hacktoberfest | @rutujak24 |

**Is your feature request related to a problem? Please describe.**:  It is an urgent need to keep track of COVID data Researchers has launched a new database to advance the international research efforts studying COVID-19. The publicly-available, free-to-use resource can be used by researchers from around the world to study how different variations of the virus grow, mutate and make proteins.

**Describe the solution you'd like**: This project explains the statistical analysis of COVID data its visualization and further assumptions and predictions

**Additional context**: 
![Screenshot (236)](https://user-images.githubusercontent.com/56619747/94889269-30ca3e00-0499-11eb-80f2-6de31769b3ba.png)

**Comment by rutujak24** [comment]
I want to take this issue.

**Comment by HarshCasper** [comment]
Hi @rutujak24  The Core Tenet of this Project is the collection of Scripts that can be used for various purposes around Automation and all. We don't exactly need Statistical Models for the purpose who certainty for critical matters cannot be decided in any way.
