### ISSUE TITLE
Remove the Charger

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#41]
## AIM

Create a Script that can notify that the Laptop has fully charged

## Languages

- Python

## Details

I never get a notification on my Windows when my Laptop Battery has completely charged. We can create a Script for this purpose which automatically pops a notification when the Laptop Battery is charged.

**Comment by mbcse** [comment]
would like to work on this

**Comment by sanket143** [comment]
I had a similar issue. My laptop used to get shut down without even notifying me. So I created [battery-notifier](https://github.com/sanket143/battery-notifier) to help me with that. It notifies us with custom messages that get triggered whenever it reaches a certain percentage of the battery and also depending on the status of the battery i.e Charging/Discharging.

Here is the default [config](https://github.com/sanket143/battery-notifier/blob/master/docs/config.json) file of messages, percentages and status.

**Comment by HarshCasper** [comment]
This is a Cool Tool that you have built @sanket143. But since Rust is out of the Project Language, I don't have much idea on whether we can implement the same with this Project.

@mbcse You can work on the same.

**Comment by HarshCasper** [comment]
@mbcse Are you working on the same?

**Comment by mbcse** [comment]
yes, created pull request
