### ISSUE TITLE
Convert BibTex/URL/DOI text to Citation text directly using JS

### ISSUE THREAD

**Issue by sohamsshah** [HarshCasper/Rotten-Scripts#422]
# Description

To provide citations in a review paper or a research paper is a menace for everyone as different journals follow different rules and methods. Doing it manually is difficult. The best way could be a Script that can parse DOI strings, URLs, Bibtex formats or other kind of details and directly return the citation in desired form. It can be implemented by making use of npm packages; but well written script covering variety of applications and example can be useful. The script can be made reusable to develop websites that can help authors, researchers etc. to get citations automatically by just a click! 

## Language

- [x] Javascript
- [ ] Powershell

## Type of issue

- [x] Feature

## Checklist:

- **For Feature**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Script to convert BibTex/DOI/URL link of Research Paper to Citation text  | It is a menace to manually write the Citations in manuscript  | feature, hacktoberfest | @sohamsshah |

**Is your feature request related to a problem? Please describe.**: 
I and my team were working on a research paper yesterday and it was really difficult for me to write the citation texts for adding references in my paper manually (they are 50 of them!). So, there must be a better way of doing it and I thought that script can help a lot of people!

**Describe the solution you'd like**: 
Using citation.js npm package for tackling this issue is a good option. But this script will cover various features of this package and many corner cases too!

**Comment by sohamsshah** [comment]
Please assign me this issue. I would love to work on this!

**Comment by HarshCasper** [comment]
Assigned you @sohamsshah !

**Comment by sohamsshah** [comment]
@HarshCasper Please find the PR relating to this at #447 ! Thank you so much!
