### ISSUE TITLE
Node Script to find all Environment Variables in a Codebase

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#424]
# Description

Create a JS Script to find all Environment Variables in a Codebase. It is usual to entirely forget about documenting the Environment Variables in your Project. Your Script should parse the entire codebase and find all the necessary environment variables and create a `env.example` file as the output.

## Language

- [X] Javascript

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by sohamsshah** [comment]
@HarshCasper Can you elaborate the issue? Do you mean that we have to search for process.env.VAR s in a file and parse all of them into a seperate .env file with those env VARs? 
OR we have search for common environment vars like API key, etc. and replace them with process.env. VAR and make a seperate .env to tackle that?

I would like to work on this issue. Please provide more detail on this.

**Comment by HarshCasper** [comment]
@sohamsshah This Issue is open only for SLoP Participant. I would love to assign it to you if you are a participant of the same.

**Comment by sohamsshah** [comment]
@HarshCasper Oh man, I actually missed the SLOP registration date...But thought to contribute even if I am not a participant! No issues brother, I am working on the BibTex Script issue! Thanks!

**Comment by HarshCasper** [comment]
@sohamsshah Feel free to create more Issues if you have more ideas. Would love to have you contribute up here!

**Comment by HarshCasper** [comment]
@sohamsshah I am opening this Issue for everyone. Let me know if you would like to work on this.

**Comment by ashishcas** [comment]
@HarshCasper it's my first time trying to contribute to open source, but I have good experience in nodejs can u assign this issue to me

**Comment by HarshCasper** [comment]
Hi @ashishcas 

Would you like to take it up now? If yes, please let me know about the same.
