### ISSUE TITLE
Python Script to initialize a Flask Folder Structure

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#425]
# Description

Create a Python Script that can be used to initialize a Flask Folder Structure. Your Script should take arguments from the User on what should be the name of the Project, the Folder Location and create a Virtual Environment for the same. The Folder Structure for majority of the Flask Projects looks something like this: 
```
~/FlaskApp
    |-- run.py
    |-- config.py
    |__ /env             # Virtual Environment
    |__ /app             # Our Application Module
         |-- __init__.py
         |-- /module_one
             |-- __init__.py
             |-- controllers.py
             |-- models.py                
         |__ /templates
             |__ /module_one
                 |-- hello.html
         |__ /static
         |__ ..
         |__ .
    |__ ..
    |__ .

```

## Language

- [X] Python

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by varuntumbe** [comment]
hey I have worked with flask. If this issue is open i would love to contribute and assign it to me.
Thanks in advance

**Comment by varuntumbe** [comment]
@HarshCasper can you please assign it to me ?

**Comment by HarshCasper** [comment]
@varuntumbe If you are a participant at SLoP, I can assign you then. Issues with the tag `SLoP` are open only for the Program Participants.

**Comment by varuntumbe** [comment]
How should i participate in SLop ? where should i register ?
Thanks in advance

**Comment by DevChoganwala** [comment]
@HarshCasper I would like to work on this issue. Please assign this to me.
Thank you.

**Comment by HarshCasper** [comment]
Assigned to you @DevChoganwala 

@varuntumbe SLoP is a program by DSC-DAIICT. The Registrations are over. If you wish to contribute, I will kickstart some beginner-friendly issues which are open for all
