### ISSUE TITLE
Script to launch an EC2 Instance

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#433]
# Description

Create a Script that allows you to create any number of AWS EC2 Instances that you wish to create. You need to specify all your Credentials in a `.env` file which includes your Access Key, Secret Key, Region, Zone, Instance Type and more.

## Language

- [X] Python
- [X] Javascript
- [X] Golang

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by rohankumawat** [comment]
@HarshCasper Can you assign me this?
***Using Python***

**Comment by frbimo** [comment]
i'll take Golang

**Comment by HoussemCharf** [comment]
I'll take the python if it's still not delivered.
