### ISSUE TITLE
Script to scan a Github Repository for Leaks

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#434]
# Description

Create a Script that would allow the user to scan a particular Github Organizations for Leaks which include Secret Information that should not have been passed ideally. Some of the Leaks can include: 
- Github API Tokens
- AWS/Azure Credentials 
- API Credentials 
- Firebase Private Keys 
- Secret Access Keys 

## Language

- [X] Python
- [X] Golang
- [X] Javascript

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by seema1711** [comment]
I want to work on this issue. @HarshCasper

**Comment by HarshCasper** [comment]
Hello @seema1711 

Let me know if you would like to work on this. Otherwise, I will open the Issue for NJACK participants.
