### ISSUE TITLE
Script to scrap Internship Details from Internshala

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#435]
# Description

Create a Script to scrap Internship Details from Internshala. You can actually hardcode the specific Internships you would like to scrap (Computer Science, Management et al) and scrap specific details like: 
- Heading
- Company
- Stipend
- Description 

These details should be saved in a `csv` file and passed to the user.

## Language

- [X] Javascript
- [X] Golang
- [X] Python

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by narayan2111** [comment]
I would like to work on this issue in python, kindly assign this issue to me @HarshCasper

**Comment by SANKET7738** [comment]
I would like to work on this issue in javascript

**Comment by twozero88** [comment]
Made a Python script to do this @HarshCasper

**Comment by twozero88** [comment]
To run the bot yes. You can get one from BotFather

**Comment by HarshCasper** [comment]
@twozero88 This Issue is tagged with `SLoP` and only `SLoP` Participants can work on this. Also you should not be making any PRs since Issues are assigned on First Come, First Serve. I am closing your PR for now.

I am assigning this to you @narayan2111

**Comment by twozero88** [comment]
@HarshCasper I was doing it for Hacktoberfest. The tag was also present here. Was not aware of the working here.
Have already made the program so if possible, do help me out here.
Thanks

**Comment by HarshCasper** [comment]
@twozero88 I will open your PR. If @narayan2111 is not able to complete it, I will review your PR

**Comment by twozero88** [comment]
Thank you!
