### ISSUE TITLE
Script to download a Torrent File to Google Drive

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#436]
# Description

Create a Script to download a Torrent File to Google Drive. You can make use of specific libraries and modules like `libtorrent` and use Google Collab as an intermediary tool for the purpose.

## Language

- [X] Python

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by tapish2000** [comment]
I would like to do contribute to this issue. Please assign it to me.

**Comment by HarshCasper** [comment]
@tapish2000 This Issue is open only for `SLoP` Participants

**Comment by vybhav72954** [comment]
Can you assign this to me? I am a SLoP Participant as well.
