### ISSUE TITLE
YouTube audio/video downloader

### ISSUE THREAD

**Issue by namanshah01** [HarshCasper/Rotten-Scripts#443]
# Description
A python script that downloads audio, video or both of a provided YouTube video link from user

## Language
- [x] Python

## Type of issue
- [x] Feature

## Note
Writing this script should be easy, but I can also try and convert it into a telegram bot.

**Comment by namanshah01** [comment]
@HarshCasper can you assign this issue to me please? I would like to work on it

**Comment by namanshah01** [comment]
Yes I did follow the guidelines. Can you assign this issue to me please?

**Comment by HarshCasper** [comment]
Assigned to you @namanshah01
