### ISSUE TITLE
Python - Test data generator (CSV)

### ISSUE THREAD

**Issue by seanjpmccarron** [HarshCasper/Rotten-Scripts#444]
# Description

A python script/file which will provide a CSV of generated test data 

## Language

- [ ] Python

## Type of issue

- [ ] Feature

## Checklist:

- **For Feature**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| test data generator (CSV) | Provide a simple script which can generate test data in CSV file format | feature | I would self-assign this |

**Is your feature request related to a problem? Please describe.**: I spent a while looking for test data generation options that could easily be fitted in to projects and re-used

**Describe the solution you'd like**: I would like to create a useful script which can generate test data in a CSV file, containing multiple options around the included content that the user can add/remove

**Comment by HarshCasper** [comment]
Thanks for creating the Issue @seanjpmccarron 

I have assigned you the same!

**Comment by paramsiddharth** [comment]
I would like to work on this issue. May I be assigned?

**Comment by HarshCasper** [comment]
Hello @paramsiddharth 

This Issue is open for assignment. Let me know if you are an NJACK participant so that I can give it the necessary labels.

**Comment by paramsiddharth** [comment]
@HarshCasper Yes, I am an NJACK participant and I wish to work on this test data generation script.

**Comment by paramsiddharth** [comment]
@HarshCasper Is this issue still available to take?

**Comment by aawasthi3008** [comment]
@HarshCasper I am a participant of KWoC. Is this issue still available? Has it been assigned to someone? I would like to work on it.

**Comment by paramsiddharth** [comment]
@aawasthi3008 The issue seems inactive at the moment.

**Comment by HarshCasper** [comment]
Hello @aawasthi3008 

This Issue is open for KWOC and NJACK Participants. 

@paramsiddharth Would you like to work on this in Python while @aawasthi3008 would you be able to work on JS/BASH ? 

Let me know the prospects of the same, so that I can assign you the same.

**Comment by paramsiddharth** [comment]
Sure! I would love to work on that in Python.
I have a question in mind. Am I allowed to use libraries in the script?

**Comment by HarshCasper** [comment]
> Sure, @HarshCasper ! I would love to work on that in Python.
> I have a question in mind. Am I allowed to use libraries in the script?

Of Course! I am not asking to develop stuff from scratch 😄 

If you are done with this, please make a PR.

**Comment by srimontidutta** [comment]
Hello, can I please work on this issue as a part of GSSoC 21?

**Comment by srimontidutta** [comment]
Should I submit it in .ipynb or .pdf format?

**Comment by vybhav72954** [comment]
@srimontidutta Jupyter will work

**Comment by srimontidutta** [comment]
I have added the Jupyter and readme file. Please check it @vybhav72954
