### ISSUE TITLE
Extract Background from a Static Video feed 

### ISSUE THREAD

**Issue by sohamsshah** [HarshCasper/Rotten-Scripts#448]
# Description

This Script can extract the overall Background of the input video feed. This can be done by using Image Processing Filtering methods and the background can be extracted of the Video feed. Example: A video feed at the traffic signal has a lot of moving objects, but to get the background of the cross-road(maybe for further training or model building), this script can filter that and return the background image from the feed. 

## Language
- [X] Python

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

## Checklist:

- **For Feature**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| add Background_Extracter | Getting background image of the video feed | python, hacktoberfest | @sohamsshah |

**Is your feature request related to a problem? Please describe.**: 
It can be used for analyzing the video feeds in a better way and can be used further to train specific object detection models that  are related to particular background. Alternatively, it can help to make the dataset more effectively from the Video feed instead of random capturing of the images from it for making dataset. 

**Describe the solution you'd like**: 

Can use an effective filtering technique on the Video feed using cv2 library.

**Comment by sohamsshah** [comment]
@HarshCasper I would like to work on this issue.

**Comment by HarshCasper** [comment]
Hello @sohamsshah 

Please let me know if you are still working on the same.

**Comment by sohamsshah** [comment]
Yes @HarshCasper I am working on it.

**Comment by HarshCasper** [comment]
Opening this Issue for Script Winter of Code participants!

**Comment by snake-arch** [comment]
I would like to work on this issue (SWOC'21 participant)

**Comment by sohamsshah** [comment]
@snake-arch Yes sure, go ahead. Let me know if you need any tips on performing this task. Best of luck for your competition!🙌

**Comment by snake-arch** [comment]
Pull request made for Issue #448 Background extractor for static video feed
