### ISSUE TITLE
Script to Scrap Community Website

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#452]
# Description

Create a Script to scrap the Community Website for [Developer Students Club](https://dsc.community.dev/). The DSC Community Website lists various Events that are happening across the globe. Scrap them and save them as a CSV File.

## Language

- [X] Python
- [X] Javascript
- [X] Golang

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by DevChoganwala** [comment]
@HarshCasper Can I work on this issue under SLOP? If so I would like to work on this issue in python.

**Comment by HarshCasper** [comment]
Yes. I will tag them aptly and you can work on this.
