### ISSUE TITLE
Fetch BBC News Using API

### ISSUE THREAD

**Issue by SKAUL05** [HarshCasper/Rotten-Scripts#457]
# Description

Please include a summary of the issue.

## Language
- [x] Python

## Type of issue

_Please delete options that are not relevant._

- [x] Feature

## Checklist:

- **For Feature**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Fetch News  |  Script to Fetch BBC News and display it using News API | Python, Hacktoberfest'2020| @SKAUL05 |

**Is your feature request related to a problem? Please describe.**:  We need to read news daily, but it would be a fun way if we could fetch the top news anytime a day.

**Describe the solution you'd like**:  We will use News API to fetch news from BBC Source and then display it according to our needs. We can also use email script to send these news over a Email.

**Comment by SKAUL05** [comment]
@HarshCasper Would like you to assign me this issue.

**Comment by KhushalPShah** [comment]
@HarshCasper 
Can you assign this to me?
I have already prepared and tested the code.

**Comment by HarshCasper** [comment]
@SKAUL05 If you would like to work on this, I can assign it to you on Python

**Comment by SKAUL05** [comment]
Sure @HarshCasper

**Comment by KmrAnish04** [comment]
Hi @HarshCasper, I have worked on this issue, So give me a chance to contribute by assigning this issue to me.

**Comment by KhushalPShah** [comment]
This is already solved 
https://github.com/HarshCasper/Rotten-Scripts/pull/460

**Comment by HarshCasper** [comment]
@SKAUL05 I have assigned this to you in Javascript
