### ISSUE TITLE
Script to get a Football Player's Club History from Wikipedia

### ISSUE THREAD

**Issue by keshavnath** [HarshCasper/Rotten-Scripts#466]
# Description

A Script to get the Club History (with noteworthy years, if any are specified in Wikipedia) of a Football Player by scraping that footballer's Wikipedia Page.

## Language

 [✔] **Python**

## Type of issue

[✔] Web-Scraping Script

**Comment by keshavnath** [comment]
I have created a script for this, and I would like to be assigned to this issue.
Thank you.

**Comment by srimani-programmer** [comment]
@keshavnath You are assigned to this issue. Please proceed with the code.

**Comment by keshavnath** [comment]
I have made a Pull Request, please review it when you can!
Thanks

**Comment by amandp13** [comment]
@HarshCasper Can you please assign me this issue as a part of SWOC 2021

**Comment by keshavnath** [comment]
Hey, due to personal reasons, I was not able to work on these issues, and I doubt I will be able to in the near future. Sorry for the inconvenience.

**Comment by HarshCasper** [comment]
> Hey, due to personal reasons, I was not able to work on these issues, and I doubt I will be able to in the near future. Sorry for the inconvenience.

No issues, @keshavnath. The last Year was hard for all of us. Please let me know if you would still work on it.

@amandp13 I would take a second opinion from @keshavnath before assigning it to you.

**Comment by RohiniRG** [comment]
Hello! I would like to work on this issue if it is still available as a participant of GSSoC 21, as I have worked on similar wikipedia scraping projects before. If assigned, please change the tags accordingly.

**Comment by vybhav72954** [comment]
@RohiniRG Best of Luck!!!

**Comment by anandhu-eng** [comment]
hello....im a gssoc 21 participant and a python enthusiast.. i would like to contribute to this project.
please do assign it to me:)
