### ISSUE TITLE
Script to upload File as a Github Gist

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#47]
## AIM

Create a Script to upload a File as a Github Gist 

## Languages

- Python
- Javascript

## Details

In this Script, we wish to upload a specified file onto Github as a Private Gist straight from the Command Line Interface to be referenced later.

**Comment by seema1711** [comment]
I want to work on this.

**Comment by HarshCasper** [comment]
You have been assigned this Issue @seema1711
