### ISSUE TITLE
Counting days

### ISSUE THREAD

**Issue by seema1711** [HarshCasper/Rotten-Scripts#473]
# Description

Script for counting how many days there is left for any given date(birthday).

## Language

- [x] Python

**Comment by seema1711** [comment]
@HarshCasper I want to work on this issue. Kindly assign.

**Comment by vrbro** [comment]
@HarshCasper I want to work for this issue! Please assign

**Comment by vybhav72954** [comment]
@dcorriveau The guidelines clearly state that doesn't open a PR before the issue is assigned.

**Comment by dcorriveau** [comment]
Okay. Sorry. Could I have it assigned?

**Comment by dcorriveau** [comment]
great, thanks @seema1711 ! Should I close my PR and re-open it? Or can we use that one?

**Comment by seema1711** [comment]
Let me review that PR.
