### ISSUE TITLE
Python voice assistant to fetch and read news from NewsAPI

### ISSUE THREAD

**Issue by KmrAnish04** [HarshCasper/Rotten-Scripts#475]
# Description
A python script which will fetch news from newsapi.com and will speak that news with headlines and description.

## Language

- [ ] Bash
- [ ] Go
- [ ] Javascript
- [ ] Powershell
- [x] Python
- [ ] Other (Please specify)

## Type of issue

- [x] Feature
- [ ] Bug

## Checklist:

- **For Feature**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Python News Assistant | A python script which will fetch news from newsapi.com and will speak that news with headlines and description. Reading news and articles sometimes may too time consuming and boring .With the help of this python news reader you listen to top news while working on your other work.  | Python, Hacktoberfest2020, newsapi.com | @KmrAnish04 |

**Is your feature request related to a problem? Please describe.:**
Sometimes reading news articles or news papers may too time consuming and boring. So this issues I have solved by making python news reader with voice over feature. So now you can listen to your news while messing with other work which is very interesting and time saving.

**Describe the solution you'd like:**
A simple python program with voice over feature which can read news from newsapi.com.

**Comment by KmrAnish04** [comment]
@HarshCasper Hi, I would like to contribute to this issues. Please assign this issue to me. Thankful to you.

**Comment by vybhav72954** [comment]
@HarshCasper Is This Issue open?
