### ISSUE TITLE
Script to apply Gradient Mapping to an Image

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#48]
## AIM

Develop a Script to apply Gradient Mapping to an Image
## Languages

- Python

## Details

Make use of modules like ```numpy```, ```CV``` and ```Matplotlib``` to apply Gradient Mapping to an Image.

**Comment by AnkitaBIT** [comment]
I would like to work on this @HarshCasper

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @AnkitaBIT

**Comment by HarshCasper** [comment]
Are you working on this @AnkitaBIT ?

**Comment by AnkitaBIT** [comment]
Yes @HarshCasper
