### ISSUE TITLE
JS Script to post tweets using api

### ISSUE THREAD

**Issue by yerramsettysaimeghana** [HarshCasper/Rotten-Scripts#486]
# Description

A script to post tweets with media and caption using twitter api and twit npm package.

## Language
- [x] Javascript
## Type of issue

- [x] Feature

**Comment by yerramsettysaimeghana** [comment]
I have created a script for this, and i would like to be assigned to this issue. Thankyou!

**Comment by seema1711** [comment]
Assigned to you. 🚀Good luck.
