### ISSUE TITLE
Remove .DS_Store from git history

### ISSUE THREAD

**Issue by dhausser** [HarshCasper/Rotten-Scripts#487]
Remove .DS_Store from git history.

**Comment by shahbazalam07** [comment]
I would like to work on this issue

**Comment by dhausser** [comment]
This issue is actually already fixed but this PR https://github.com/dhausser/Rotten-Scripts/commit/3fcd16555782a0ff190c4428ca87a9847fb004af

**Comment by HarshCasper** [comment]
@dhausser Can you make a PR for the same? I possibly cannot find it on the Pull Requests Tab

**Comment by dhausser** [comment]
Here it is https://github.com/HarshCasper/Rotten-Scripts/pull/501
