### ISSUE TITLE
[MINOR] Reduce the `maxAge` Argument in README.md

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#488]
# Description

The `maxAge` argument in README.md is set to 30 days for fork and star badges, for that reason, the badge has a different value than the actual.
- At the time of writing
    - Actual Fork - 124
    - Actual Stars - 174
    - Badge (Fork) - 62
    - Badge (Star) - 137

## Language

- [x] Other (Markdown)

## Type of issue

- [x] Bug

## Checklist:

- **For Bug**

**Expected results**: The badges should show actual values and refresh either daily or once in two days.

**Actual results**: The values don't sync with actual values.

**Additional context**: In case `maxAge` argument is knowingly set to 30 days. Kindly close this issue.

**Comment by vybhav72954** [comment]
As this is a really Minor issue, any moderator can change the README.md, else it can be assigned to me as well.

**Comment by seema1711** [comment]
Assigned to you.
