### ISSUE TITLE
Script to track Data Usage

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#49]
## AIM

Create a Script to track Data Usage.

## Languages

- Python

## Details

Create a Python Script to keep a track of network usage and notify you if it exceeds a specified limit.

**Comment by seema1711** [comment]
I want to work on this. @HarshCasper

**Comment by HarshCasper** [comment]
I have assigned you the Issue @seema1711

**Comment by HarshCasper** [comment]
Are you working on this @seema1711 ?

**Comment by seema1711** [comment]
Yes.

**Comment by kaustubhgupta** [comment]
@HarshCasper can you reopen this issue under the CH20 label and assign it to me? I would like to work on this issue in python.

**Comment by kaustubhgupta** [comment]
@HarshCasper I think this is already done by Seema:
https://github.com/HarshCasper/Rotten-Scripts/tree/master/Track%20Data%20Usage
You can close this issue I will work on another one

**Comment by abhishekgupta368** [comment]
I would like to do it if you allow

**Comment by HarshCasper** [comment]
Thanks for the head-up @kaustubhgupta
