### ISSUE TITLE
Optimize Images in Multiple Code Directories.

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#499]
# Description

The Size of Repo is too large because of various images used in `README.md` files. Using lossless compression, the size of the images can be easily reduced. We can expect an approximate 25% reduction in aggregate image size.

- [x] Enhancement

**Comment by vybhav72954** [comment]
FOr the above purposes, apps like `ImageBot` can be used, or this can be assigned to me.

**Comment by dcorriveau** [comment]
Do you mind if I take it @vybhav72954 or would you rather have it?

**Comment by HarshCasper** [comment]
I guess both of you can work on this. 

@dcorriveau Actually @vybhav72954 is a part of `SLoP` Program and resolving every Issue brings points to the Leaderboard. Let me know @vybhav72954 if both of you would want to work on this.

**Comment by vybhav72954** [comment]
@HarshCasper Would be great if you can assign me

**Comment by vybhav72954** [comment]
> Do you mind if I take it @vybhav72954 or would you rather have it?

Hey man I actually opened it cause I wanted to work on it 😄

**Comment by dcorriveau** [comment]
haha understandable! no worries! :)

**Comment by vybhav72954** [comment]
@HarshCasper Assign me please so that I can start comparing results

**Comment by vybhav72954** [comment]
@HarshCasper Please Assign

**Comment by vybhav72954** [comment]
@HarshCasper Kindly see the changes 😀😀
