### ISSUE TITLE
Website Blocker

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#5]
## AIM

Create a Script that can block specific Websites like Instagram, YouTube, Facebook during Work Hours.

## Languages

- Python

## Details

In this Script, you have to make use of the hosts' file and block some of the Websites mentioned above during Work Hours.

**Comment by AnkitaBIT** [comment]
Can I work on this @HarshCasper ?

**Comment by HarshCasper** [comment]
You have been assigned this Issue @AnkitaBIT 

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also, reference this Issue in your PR so that it becomes easy for us to review.
