### ISSUE TITLE
Script to convert Video Files to MP3 Files

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#50]
## AIM

To create a Script to convert Video Files to MP3 Files.

## Languages

- Python

## Details

In this Script, you have to convert the Video Files to MP3 Files.

**Comment by srimani-programmer** [comment]
I want to work on this issue. Can you please assign it for me?

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @srimani-programmer
