### ISSUE TITLE
Add Caesar cipher. 

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#505]
# Description

I observed that we have a few Cipher techniques in this repo, but it's missing the most basic, yet most popular technique (i.e. `Caesar Cipher`)

It is a very basic Cipher Technique and is a usual learning part of every tech enthusiast. I suggest adding a script for the same.

## Language

- [x] Python

## Type of issue

_Please delete options that are not relevant._

- [x] Feature

## Checklist:

- **For Feature**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Caesar Cipher | The most basic yet prominent cipher method, Caesar Cipher definitely should be here | feature, SLoP | @vybhav72954  |

**Is your feature request related to a problem? Please describe.**: The learning curve starts at the bottom and I strongly believe that Caesar Cipher is one of the basic technique hence is a must-have.

**Describe the solution you'd like**: A clear and concise application of Cipher, property explain its working and show the proper results.

**Comment by vybhav72954** [comment]
I'll be adding a decipher code as well. @HarshCasper Hope that won't be an issue 🤔

**Comment by ashutosh007865** [comment]
if you don't mind can I work on this issue??

**Comment by vybhav72954** [comment]
@ashutosh007865 I have already made the PR in python. If @HarshCasper wants the code in JS as well and you have JS knowledge. You sure can but wait for him to confirm

**Comment by ashutosh007865** [comment]
That's really kind of you. i will definitely wait for my chance.
