### ISSUE TITLE
[SUGGESTION] A Slack or Discord Channel/Server for Rotten Script.

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#507]
# Description

This is just a Suggestion and open for discussions. Having a dedicated Discord or Slack channel (Preferably) will streamline things a lot, people can have healthy discussions there as well.

**Comment by HarshCasper** [comment]
I will be setting up a Slack Channel for the same quite soon.

**Comment by vybhav72954** [comment]
In case you need help, I can help. (Not for SLoP or anything), just genuine assistance 😄

**Comment by HarshCasper** [comment]
Sure @vybhav72954
