### ISSUE TITLE
Script to kill Ports

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#508]
# Description

Create a Script to kill Ports. 

Yesterday I had a weird issue while working with FastAPI + Neo4j where I stopped the Database and the APIs were still working. I came to understand that the Port was still working and had now occupied them, because of which I was not able to work on other stuff. In this Script, I would like to have a functionality to kill Ports given the Port Number.

## Language

- [X] Python
- [X] Javascript
- [X] BASH

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by vybhav72954** [comment]
I would like to apply for this only if my understanding is correct.

So what I believe is that you want a script, that will kill a port, and as an input, we provide a port number?

Or you also want to list the ports which are currently listening? 

If my understanding is correct *processes don't run on ports - processes can bind to specific ports*. then something like `os.kill` can achieve the task

**Comment by HarshCasper** [comment]
@vybhav72954 `os.kill` is sometimes not enough to terminate spawning processes. Only when we create a process group and use the Command would do the trick for the purpose. I wanted a singular Script that could manage this and hence the Issue.

**Comment by vybhav72954** [comment]
@HarshCasper Nog going to lie i cant still understand the problem. Let me put it this way.

A script that can determine which all the ports listening to something, and a script that can kill a port. A combination of these 2 can solve the problem?

**Comment by HarshCasper** [comment]
Exactly @vybhav72954

**Comment by vybhav72954** [comment]
Can you assign this to me? Can do this

**Comment by vybhav72954** [comment]
@HarshCasper I will be opening the PR for this today only, kindly put the "NJACK" Label

**Comment by vybhav72954** [comment]
@HarshCasper A separate script for Finding the active ports, and a subsequent one to kill them off by giving port number as an argument, will hopefully do the job. Right?

**Comment by vybhav72954** [comment]
Also, i prepared a shell script too XD
I was planning to call it from python XD.
I will also upload that, so in case you close it, can you reopen it again, so that I can upload the bash one
