### ISSUE TITLE
Automate Lyrics Downloading [Bulk Download]

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#517]
# Description

It's easy to find lyrics of one or two songs online, but what if you want to use some NLP algo and do some stuff over a bunch of lyrics? Copy Paste is not an option (obviously)
## Language

- [x] Javascript
- [x] Python

## Type of issue

_Please delete options that are not relevant._

- [x] Feature

## Checklist:

- **For Feature**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Lyrics Automation | Download Lyrics of a bunch of songs, save them locally | feature, SLoP | @vybhav72954  |

**Is your feature request related to a problem? Please describe.**: I love Songs, I love Audio Research, I love NLP. I don't love Copy Paste, and I do love Python. So a script that can dump lyrics sounds great.

**Describe the solution you'd like**: A script to download Lyrics of Multiple Songs (User won't write names of songs obviously) so a suitable input option is a must.

**Additional context**: Use APIs (if possible) 😉😉😉

**Comment by vybhav72954** [comment]
Hello @HarshCasper Considering a few of my PRs have been merged today, can you assign this to me now. 

PS - >Is the easy label correct though 😛

**Comment by HarshCasper** [comment]
Hello @vybhav72954 

Let me know if you are still working on it.

**Comment by vybhav72954** [comment]
Just about to finalize this
