### ISSUE TITLE
Implementing the Cryptocurrency price tracker using Python.

### ISSUE THREAD

**Issue by srimani-programmer** [HarshCasper/Rotten-Scripts#53]
<h2>AIM</h2>
Developing a Python Script to fetch all the cryptocurrency prices using Python.
<h3>Tools</h3>
1. Python <br>
2. Requests library <br>
3. JSON library

**Comment by srimani-programmer** [comment]
<h2>AIM</h2>
Developing a Python Script to fetch all the cryptocurrency prices using Python.
<h3>Tools</h3>
1. Python <br>
2. Requests library <br>
3. JSON library

**Comment by HarshCasper** [comment]
Already implemented here https://github.com/HarshCasper/Rotten-Scripts/issues/3

**Comment by srimani-programmer** [comment]
What should I do now? Shall i leave it.

**Comment by HarshCasper** [comment]
Yes
