### ISSUE TITLE
GitHub Action that checks, if a suitable Makrdown file is present or not, then look for errors in Markdown File.

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#534]
# Description

Just like #495 I believe that a similar Action fore `README.md` files can be a good enhancement for the Repo.

## Language

- [x] Javascript
- [x] Python
- [x] YAML

## Type of issue

- [x] Feature

## Checklist:

- **For Feature**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| MarkDown Lint Github Action | A GitHub action that can check and Lint `README.md` | feature, SLoP | @vybhav72954  |

**Is your feature request related to a problem? Please describe.**: Cross-checking the Markdown files must be a painful task for the Admins, and even after that, many times there are spelling mistakes and broken links in the `md` file.
**Describe the solution you'd like**: A JavaScript or Python code to Lint an `md` file. A Github action to trigger 2 scripts - 

- To check if there is `md` file.
- Lint that `md` file

**Additional context**: Ignore the `up-for-grabs` label.

**Comment by alphaX86** [comment]
@HarshCasper I think I'll take this issue as a NWoC participant. May I??

**Comment by alphaX86** [comment]
And I'll do it in YAML file of course, if you allow to do so

**Comment by vybhav72954** [comment]
@alphaX86 I am working on it already 😄

**Comment by alphaX86** [comment]
> @alphaX86 I am working on it already 😄 

Oh 😅 OK then. You carry on @vybhav72954

**Comment by vybhav72954** [comment]
@HarshCasper Add the NJACK Label please

**Comment by HarshCasper** [comment]
Hi @vybhav72954 

Are you still working on it?

**Comment by vybhav72954** [comment]
@HarshCasper Can you please check the Discussion tab :)

**Comment by vybhav72954** [comment]
@HarshCasper Can you check #401 and #672

**Comment by vybhav72954** [comment]
@HarshCasper Am opening a PR within 2 hours, meanwhile, I got some questions.

Would be great if you answer them!!!

- [ ] Shall I make Alt Text for images compulsory?
- [ ] Should I Allow inline HTML or Not?
- [ ] Do we need code fencing?

**Comment by HarshCasper** [comment]
> @HarshCasper Am opening a PR within 2 hours, meanwhile, I got some questions.
> 
> Would be great if you answer them!!!
> 
> * [ ]  Shall I make Alt Text for images compulsory?
> * [ ]  Should I Allow inline HTML or Not?
> * [ ]  Do we need code fencing?
> 
> Although I will put enough comments in the `YAML` script
> Do you separately need a list of possible warnings and errors?
> 
> And do check #672
> 
> Lastly, should I schedule that Action for once every day, or once with every new PR (preferred).

- Alt Texts are not compulsory. We will keep that thing with another Issue. 
- Inline HTML is a definite plus. 
- Code Fencing is all good.

A list of warnings and errors would help me in the later time. Keep the Action for every PR.

**Comment by vybhav72954** [comment]
Understood :D

Just one more doubt in that case, I will make a `README` explaining error messages, but where shall I save it? I believe having a README in workflows is not a problem, Right?

**Comment by HarshCasper** [comment]
> Understood :D
> 
> Just one more doubt in that case, I will make a `README` explaining error messages, but where shall I save it? I believe having a README in workflows is not a problem, Right?

It should not be. Or we can have some docs explaining about this.

**Comment by vybhav72954** [comment]
> > Understood :D
> > Just one more doubt in that case, I will make a `README` explaining error messages, but where shall I save it? I believe having a README in workflows is not a problem, Right?
> 
> It should not be. Or we can have some docs explaining about this.

docs explaining as in?

**Comment by HarshCasper** [comment]
> > > Understood :D
> > > Just one more doubt in that case, I will make a `README` explaining error messages, but where shall I save it? I believe having a README in workflows is not a problem, Right?
> > 
> > 
> > It should not be. Or we can have some docs explaining about this.
> 
> docs explaining as in?

Like a separate piece of documentation, telling them about various pitfalls they might land in. Also, we can highlight proper ways of contributions.
