### ISSUE TITLE
Script to export Twitter Bookmarks

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#538]
# Description

Create a Script to export Twitter Bookmarks. The script should do the following: 

- Crawl over the Twitter Bookmarks. 
- Save them in Markdown Format.
- Save them for Future Reference.

## Language

- [X] Python
- [X] Javascript
- [X] BASH 
- [X] Golang

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by Purvanshsingh** [comment]
I would like to work on this issue for SWOC,
Please assign me this issue.

**Comment by Blastoise** [comment]
Assign this to me, I will do this using BASH.

**Comment by HarshCasper** [comment]
Hello @Purvanshsingh, you can do this using Python/JS/Golang. @Blastoise On the other hand, would try to get it done using BASH.

**Comment by Purvanshsingh** [comment]
Sure will do it in Python,
Will create PR after 5th Jan :-)

**Comment by Blastoise** [comment]
@HarshCasper  Can you please elaborate what are the things you need in a tweet. Only the url of the tweets or get all the information from the tweet such name of the username who posted, date when published, main tweet, like and share count and then format it in a Markdown format?

**Comment by Blastoise** [comment]
Also it's relatively tough to do with BASH rather than using Python because BASH does not has Selenium like software, so I should get more points.

**Comment by HarshCasper** [comment]
> @HarshCasper Can you please elaborate what are the things you need in a tweet. Only the url of the tweets or get all the information from the tweet such name of the username who posted, date when published, main tweet, like and share count and then format it in a Markdown format?

The URL is just fine. I'm looking for any customizations.
