### ISSUE TITLE
Script to update Github Profile README with recent Blogs

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#540]
# Description

Create a Script to update Github Profile README with recent Blogs. I'm specifically looking at Hashnode Blogs for my purpose and having an implementation to show the recent Blogs that I have written on my Profile README would look awesome.

## Language

- [X] Python
- [X] Javascript
- [X] Golang 

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by mdPial** [comment]
I would like to work on that under GSSoC'21.

**Comment by mdPial** [comment]
What will be the frequency to check for new blogs? Like days or hours or minutes ?

**Comment by mdPial** [comment]
I am making with **JS** as it's in the language description. But you have labeled the issue `python`. Is JS is not acceptable anymore?

**Comment by vybhav72954** [comment]
> I am making with **JS** as it's in the language description. But you have labeled the issue `python`. Is JS is not acceptable anymore?

Feel free to make one in JS

**Comment by mdPial** [comment]
@vybhav72954 As I am using JS script, to run it I will need to install and run node.js while running GitHub action. To install and run in GitHub action a `package.json` file will be required for node.js. Where should I put the **package.json** file?. Currently, I have put it in `./JavaScript/Recent_Blogs_Bot` by creating a new folder **Recent_Blogs_Bot**
