### ISSUE TITLE
Script to parse the Resume and generate Meaningful Details

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#541]
# Description

Create a Script that can leverage the Lever’s API for Resume Parsing and to generate details about the same.

## Language

- [X] Python
- [X] Javascript
- [X] Golang
- [X] BASH

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by InfiniteVerma** [comment]
I'll like to work on this.

**Comment by Rahul555-droid** [comment]
I would want to work on this

**Comment by HarshCasper** [comment]
Hello @InfiniteVerma 

I'm assigning you this in Python. 

@Rahul555-droid Let me know if you would like to work on this using JS/Golang

**Comment by Rahul555-droid** [comment]
Can I get the python one I am not good with working in JS and golang using APIs?

**Comment by HarshCasper** [comment]
I guess @InfiniteVerma can tell about this. Are you fine @InfiniteVerma on working on this through JS/Golang?

**Comment by InfiniteVerma** [comment]
Yes. I can do it in js then.

**Comment by HarshCasper** [comment]
Assigned 💯 

Thanks @InfiniteVerma and @Rahul555-droid for taking it up.

**Comment by HarshCasper** [comment]
Hello @InfiniteVerma @Rahul555-droid 

Are you guys still working on it?

**Comment by Rahul555-droid** [comment]
Yup . Theres a problem with the lever site API though.

**Comment by Rahul555-droid** [comment]
the lever API doesn't seem to have a resmue parser anymore https://hire.lever.co/developer/documentation
https://jobs.lever.co/parseResume ,this was used before for parsing resumes through lever but it doesn't work anymore I tested it. I saw reddit post and that is where I found this older site

**Comment by tanishq-arya** [comment]
@vybhav72954 I would like to work on this in python if you could guide me.
