### ISSUE TITLE
(FLK-E741) Do not use variables named 'l', 'O', or 'I'

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#546]
## Description
Variables named `I`, `O`, and `l` can be very hard to read. This is because the letter `I` and the letter `l` are easily confused, and the letter `O` and the number `0` can be easily confused. Change the names of these variables to something more descriptive.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/HarshCasper/Rotten-Scripts/issue/FLK-E741/occurrences/](https://deepsource.io/gh/HarshCasper/Rotten-Scripts/issue/FLK-E741/occurrences/)

**Comment by vybhav72954** [comment]
Easy yet Important. Assign this, please and #545
