### ISSUE TITLE
Script to analyze Website Content

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#552]
# Description

Create a Script that can analyze the Website Content and generate results out of that. You can analyze for: 

- Bad Grammar
- Paragraph Separation
- Unnecessary Keywords 
- Percentage of Keywords

## Language

- [X] Python
- [X] Javascript
- [X] Golang
- [X] BASH

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by TrushaT** [comment]
> # Description
> Create a Script that can analyze the Website Content and generate results out of that. You can analyze for:
> 
> * Bad Grammar
> * Paragraph Separation
> * Unnecessary Keywords
> * Percentage of Keywords
> 
> ## Language
> * [x]  Python
 
Hello I would like to be assigned this issue for Python .

**Comment by TrushaT** [comment]
Hello , I would be like to be assigned this issue for Python .

**Comment by HarshCasper** [comment]
Assigned to you @TrushaT

**Comment by HarshCasper** [comment]
Are you still working on it @TrushaT ? 

If not, I will assign this to someone else.

**Comment by TrushaT** [comment]
Sorry, pls assign it to someone else.

**Comment by achalesh27022003** [comment]
is it similar to web scraping? @HarshCasper  sir.

**Comment by achalesh27022003** [comment]
[Reference](https://www.geeksforgeeks.org/reading-selected-webpage-content-using-python-web-scraping/)

**Comment by HarshCasper** [comment]
Hello @achalesh27022003 

Yes
