### ISSUE TITLE
Bug in /assign

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#559]
**Describe the bug**
The Stale issue action has a few bugs, which are non-breaking but still annoying.

**To Reproduce**
1. Go to any issue with `Up-For-Grabs` label.
2. Comment `/assign`
3. The bot will assign the issue, but the `Up-For-Grabs` label is still present.

**Expected behavior**
The bot should get rid of the prior label.

**Screenshots**
In issue #508
![issue](https://user-images.githubusercontent.com/49750343/100051062-ed5cd200-2e40-11eb-98c1-d7a09fe8287d.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version:  87.0.4280.66

**Additional context**
There are a few more questions regarding the issue which I hope @HarshCasper will answer.

1. Which label to put on the stale issue?
1. How many days would be given before a warning (right now 7) is sent?
1. After how many days of warning, should the issue be unassigned (right now 14 days after warning)
1. Shall I change `/assign` to `/Rotten` for assigning issues.
1. Who will make the respective change in the documentation, shall I do it?

**Comment by vybhav72954** [comment]
@HarshCasper Can you please answer those question that I have mentioned in **Additional Context**

**Comment by vybhav72954** [comment]
@HarshCasper I will solve this BUG by the weekend, the reason being I don't want it to have any more bugs, at the same time I will solve all the possible bugs in all the actions 😃

**Comment by HarshCasper** [comment]
Hello @vybhav72954 

Are you still working on the same?

**Comment by vybhav72954** [comment]
Tomorrow Night at max, if I won't be able to solve this, I will unassing my self for sure
