### ISSUE TITLE
Create a text summarizer using python

### ISSUE THREAD

**Issue by manish2202** [HarshCasper/Rotten-Scripts#563]
# Description

Please include a summary of the issue.

## Language

- [] Python

## Type of issue

_Please delete options that are not relevant._

- [ ] Feature

## Checklist:

- **For Feature**

| name            | about                                                  | labels  | assignees                                                      |
| --Text Summarizer------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Feature request | Details (Motivation behind) about your feature request | feature | self-assign if you want to work on this issue else leave blank |

**Is your feature request related to a problem? Please describe.**: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**: A clear and concise description of what you want to happen.

**Additional context**: Add any other context or screenshots about the feature request here.

**Steps to reproduce**: List out the steps to reproduce the steps

**Expected results**: What were the expected results

**Actual results**: What you got

**Additional context**: Add any other context or screenshots about the bug here.

**Comment by vybhav72954** [comment]
Isn't this open in #539?

**Comment by manish2202** [comment]
Okay. Can I work on that?

**Comment by vybhav72954** [comment]
That only @HarshCasper can decide 

> Okay. Can I work on that?

**Comment by manish2202** [comment]
> That only @HarshCasper can decide
> 
> > Okay. Can I work on that?

okay. I will be waiting.

**Comment by HarshCasper** [comment]
@manish2202 

Thanks for making the Issue. Currently @ag-hcoder is working on it. If 7 Days passes, without any visible updates, I will assign this Issue to you.
