### ISSUE TITLE
Rectify Major Typos, Update README.md

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#567]
This is regarding refactoring the Documentation.
It is that time again. Recently while going through a few Directories in the Repo, I found some typos again. I think they should be removed ASAP.

Also if @HarshCasper gives the green light, I think the `Language -> README.md` for Python, JS, and Go needs to be updated, would gladly do that, `although it's boring and hectic` 😞 **Just Kidding** 🌟

**Comment by vybhav72954** [comment]
@HarshCasper I auto-assigned this issue to me, but I would wait for the green light regarding the `README.md`s, moreover, Have you ever heard of something, by which we can automate that process, if you save some clue, just point me towards it, I will do the needful.

**Comment by vybhav72954** [comment]
@HarshCasper Can you see this, please meanwhile.

**Comment by HarshCasper** [comment]
Hello @vybhav72954 

You can take the ownership for this. If there is anything, that doesn't look right, I will let you know.

**Comment by vybhav72954** [comment]
Understood. Thanks

**Comment by vybhav72954** [comment]
@HarshCasper Can you assing "NJACK" Label as well
