### ISSUE TITLE
Traffic Analyzer for Rotten Script

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#569]
**Is your feature request related to a problem? Please describe.**
Considering Rotten Scripts is taking part in multiple programs, the viewership of the Repo is a thing that piques my interest.

**Describe the solution you'd like**
A script that can analyze the viewership of the Repo.

**Describe alternatives you've considered**
Maybe a GitHub bot can help. Not sure

**Additional context**
N/A

**Comment by vybhav72954** [comment]
@HarshCasper Assign me if you think it's useful.

**Comment by HarshCasper** [comment]
I would be highly interested in the Analytics Part. Let me know if you need any help!

**Comment by vybhav72954** [comment]
> I would be highly interested in the Analytics Part. Let me know if you need any help!

I really think this would be a great asset (Hopefully :P)

**Comment by HarshCasper** [comment]
Hello @vybhav72954

Are you still working on the same?

**Comment by vybhav72954** [comment]
Tomorrow Night at max, if I won't be able to solve this, I will unassing my self for sure

**Comment by vybhav72954** [comment]
> I would be highly interested in the Analytics Part. Let me know if you need any help!

I have made the PR
Would be really interested in knowing the results.
I can use the script to make a realtime graph as well if you would like that
