### ISSUE TITLE
TSV to CSV converter. 

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#571]
**Is your feature request related to a problem? Please describe.**
A CSV file is an ever-present format, a TSV, not so much, whenever I have to work with Music Datasets, TSV is mostly used. 

**Describe the solution you'd like**
A Script to convert TSV files to CSV files.

**Describe alternatives you've considered**
Online conversion or using MS Excel.

**Additional context**
I made a table to CSV converter once, I believe this would be similar to say the least.

**Comment by vybhav72954** [comment]
@HarshCasper Assign this to me under NJACK

**Comment by Siddhant-K-code** [comment]
Can we use `pandas` module

**Comment by Siddhant-K-code** [comment]
Or, isn't it a basic task of *`Replacing tabs with commas`* ?

**Comment by vybhav72954** [comment]
You don't even need `Pandas` it's a really simple script, 15 lines of code at max, but it's useful for people who are into music analysis, that's where it comes in handy. I already have the code ready, the reason I am waiting before making a PR is bcs I want him to be sure it's needed here.

**Comment by Siddhant-K-code** [comment]
> 
> 
> Or, isn't it a basic task of _`Replacing tabs with commas`_ ?

what about this ? @vybhav72954

**Comment by vybhav72954** [comment]
> > Or, isn't it a basic task of `Replacing tabs with commas`?
> 
> what about this ? @vybhav72954

If the encoding is similar, Yes, usually it's `utf-8` so yeah, mostly that.

**Comment by HarshCasper** [comment]
@Siddhant-K-code You need to wait for someone to assign this to you! 

The Issue was created by @vybhav72954 and he expressed his desire to work on it. Taking up an Issue without waiting to be assigned to you specifically, is simply unfair and goes against the best practices. 

@vybhav72954 Kindly let me know if you would still want to work on it, or shall I consider @Siddhant-K-code PR for this Issue.

**Comment by Siddhant-K-code** [comment]
> @Siddhant-K-code You need to wait for someone to assign this to you!
> 
> The Issue was created by @vybhav72954 and he expressed his desire to work on it. Taking up an Issue without waiting to be assigned to you specifically, is simply unfair and goes against the best practices.

Sorry, I think it is free to contribute. I will surely discuss it before contributing, Sorry Again!

**Comment by vybhav72954** [comment]
> @Siddhant-K-code You need to wait for someone to assign this to you!
> 
> The Issue was created by @vybhav72954 and he expressed his desire to work on it. Taking up an Issue without waiting to be assigned to you specifically, is simply unfair and goes against the best practices.
> 
> @vybhav72954 Kindly let me know if you would still want to work on it, or shall I consider @Siddhant-K-code PR for this Issue.

I mean its fine I guess, I will work on something else, in case if there is any bug or flaw in the code (Which i don't think there would be), I will refactor it, but for now, consider his PR. Its absolutely fine.

**Comment by vybhav72954** [comment]
@HarshCasper Meanwhile can you assign me #569 #572 #576 and #567
