### ISSUE TITLE
Set Up discussion feature for great conversion.

### ISSUE THREAD

**Issue by Vishal-raj-1** [HarshCasper/Rotten-Scripts#578]
@HarshCasper Sir , Did you see new feature on github ? We can set discussion on this repo. So what you have to do is just click this block in setting section of your repo. It's Amazing I guess. Have a try.

![discussion](https://user-images.githubusercontent.com/59874304/101589985-8c6ff500-3a0f-11eb-8756-48b53dfe1adf.JPG)

**Comment by vybhav72954** [comment]
@HarshCasper Great Idea

**Comment by HarshCasper** [comment]
@Vishal-raj-1 Added 🙌😄

I would request you to get your Introductions over there.

**Comment by Vishal-raj-1** [comment]
> I would request you to get your Introductions over there.
Sure.😃
