### ISSUE TITLE
Tweet Scraper with a Particular hashtag using Twint

### ISSUE THREAD

**Issue by Siddhant-K-code** [HarshCasper/Rotten-Scripts#579]
## **Is your feature request related to a problem? Please describe.**

A Short and Simple Python Script to Scrap Tweets of particular Hashtag **without** Twitter API (Tweepy)

## **Describe the solution you'd like**

Simple Python Script using [Twint](https://github.com/twintproject/twint)

## **Additional context**
Twint ⇒ https://github.com/twintproject/twint 

### **Do I Want to work on this ?** 
*Yes*

**Comment by HarshCasper** [comment]
Hello @Siddhant-K-code 

Are you working on this as part of NJACK Winter of Code or KWOC? Do let me know so that I can put apt tags and difficulty tags as well.

**Comment by Siddhant-K-code** [comment]
I will be work on this part of  a project for KWOC

**Comment by Siddhant-K-code** [comment]
Please add label KWOC'20 @HarshCasper

**Comment by HarshCasper** [comment]
Hello @Siddhant-K-code 

Are you still working on the same?

**Comment by Siddhant-K-code** [comment]
Yes, its almost done.

**Comment by vybhav72954** [comment]
@Siddhant-K-code Can you confirm the status!!!

**Comment by Siddhant-K-code** [comment]
> @Siddhant-K-code Can you confirm the status!!!

I tried it, but unable to implement this!!

**Comment by RohiniRG** [comment]
I would like to work on this issue using the python library of snscrape which would be a better alternative to tweepy. I would be glad ot give it a try.

**Comment by vybhav72954** [comment]
Awesome @RohiniRG Keep me posted in case you face any problem

**Comment by RohiniRG** [comment]
> Awesome @RohiniRG Keep me posted in case you face any problem

Hello! So I am almost done with the code, but what details associated with the hashtags should I add to the file (Eg.username, tweet, date, time, location, id, etc. or should I add them all?) And also, what file format should I go with (.txt, .csv, .json, .pdf) ?

**Comment by Siddhant-K-code** [comment]
> > Awesome @RohiniRG Keep me posted in case you face any problem
> 
> Hello! So I am almost done with the code, but what details associated with the hashtags should I add to the file (Eg.username, tweet, date, time, location, id, etc. or should I add them all?) And also, what file format should I go with (.txt, .csv, .json, .pdf) ?

Yes, you can add them all. in a `.csv` format { and, make user-defined fileNameProvidedByUser.csv => just ask for the input of fileName}

**Comment by RohiniRG** [comment]
@vybhav72954 @HarshCasper @seema1711 could you please have a look at the PR and let me know if there is something I need to work on

**Comment by vybhav72954** [comment]
@RohiniRG Kudos to you!!! Looking for more from you. @Siddhant-K-code Thank you for help

**Comment by RohiniRG** [comment]
> @RohiniRG Kudos to you!!! Looking for more from you. @Siddhant-K-code Thank you for help

Thanks a lot! @vybhav72954 @HarshCasper @Siddhant-K-code it was a great first experience! Looking forward!
