### ISSUE TITLE
Certificate Generator

### ISSUE THREAD

**Issue by Tejas1510** [HarshCasper/Rotten-Scripts#582]
**Is your feature request related to a problem? Please describe.**
Generating a ton of certificates for any occassion is quite tedious if you're not familiar with the concept of automation. Well, you won't have to worry anymore because this script will do all the heavy lifting for you.

**Describe the solution you'd like**
The Script takes a template of the certificate as input and the name to be written on the certificate and generate the certificate
**Describe alternatives you've considered**

**Additional context**

**Comment by Tejas1510** [comment]
@HarshCasper Can i work on this issue?

**Comment by HarshCasper** [comment]
Hello @Tejas1510 

We already have a script [here](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Bulk_Certificate_Generator). If you have additional enhancements in mind, do let me know.

**Comment by Tejas1510** [comment]
@HarshCasper I wasn't aware of the already present script
The script looks good so no changes from my side
I will work on some other issue
