### ISSUE TITLE
ReadMe generator

### ISSUE THREAD

**Issue by hr1shu** [HarshCasper/Rotten-Scripts#583]
**Is your feature request related to a problem? Please describe.**
Several developers or students build a portfolio website to showcase projects. But all the projects and stats are on Github. How about making your GitHub your portfolio?
![Screenshot (161)](https://user-images.githubusercontent.com/57145318/101815879-3a7dbb00-3b46-11eb-87c4-c85213e1c66e.png)

**Describe the solution you'd like**
I have a readme generator script that helps you to create ReadMe of your GitHub profile

**Describe alternatives you've considered**

**Additional context**
Pls look at the screenshot attached below

**Comment by hr1shu** [comment]
Just the tool you @HarshCasper have used for your gitHub profile😁

**Comment by shrey27tri01** [comment]
@hr1shu Can I work on this issue?

**Comment by HarshCasper** [comment]
Hello @hr1shu 

Are you working on this in-general or as part of an Open-Source Program? I would love to have an implementation since my README is a mess. If you are participating in KWOC or NJACK, let me know so that I can put apt tags.

@shrey27tri01 I can assign you this issue in a different language than @hr1shu is working in. @hr1shu Let me know the language you will be using.

**Comment by hr1shu** [comment]
Yes @HarshCasper, I'll be contributing as a part of KWOC.
The tool is scripted in javascript and to be honest, it isn't created by me, the creator is https://github.com/rahuldkjain.
I just want to add the link of the tool and the repository so that everyone could convert their respective Github profiles into portfolios.
If the guidelines of contributions are compromised, please let me know.
Thank u

**Comment by hr1shu** [comment]
Hey @HarshCasper, I wanna know the status of your opinion.
Should I proceed with it or not??

**Comment by HarshCasper** [comment]
Hello @hr1shu 

Go ahead with it! Good Luck!

**Comment by hr1shu** [comment]
Thanks mate.
