### ISSUE TITLE
Scrap Restaurants using the Zomato API

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#585]
## Description 

Scrap Restaurants using the Zomato API and store them in a CSV File for reference. You can additionally use Argument Parsers to pass necessary data on specific restaurants and filter the results. 

This Issue is open only for KWoC '2020 Participants. 

## Languages 

- Python
- Javascript
- BASH 
- Golang

**Comment by kritikaparmar-programmer** [comment]
Hey, @HarshCasper I want to work on this issue. I'm a participant in KWOC.

**Comment by Siddhant-K-code** [comment]
/Assign
I wanted to do this in python

**Comment by kritikaparmar-programmer** [comment]
Hey, @HarshCasper can we assign to us like this??

**Comment by HarshCasper** [comment]
Hello @Siddhant-K-code 

Are you still working on the same?

**Comment by Siddhant-K-code** [comment]
It is remaining with one more challenge, will fix by 31 Dec. 2020
