### ISSUE TITLE
Find Technologies used on a Web Application

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#586]
## Description 

Find the Technologies used in a Web Application. Take the input either as a Single Website URL or a CSV File. In the case of Former, generate the results on the CLI while in latter make use of a CSV File to store all the details. Make use of Argument Parsers for better usability.

This Issue is open only for KWoC '2020 Participants.

## Languages

- Python
- Javascript
- BASH
- Golang

**Comment by tanishq-arya** [comment]
@vybhav72954 I would like to work on this in python. Can you guide me how should I proceed with this.

**Comment by tanishq-arya** [comment]
Hey @HarshCasper I looked this on the web. So I have to make a simple program to just take the input and use the "builtwith" library in python or do I have to do this without the library ?
