### ISSUE TITLE
Extract Text from Images in Bulk

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#587]
## Description 

Extract Text from Images in Bulk. Make use of a directory with Images and pass the directory to your Script for Text Extraction which will be stored in a separate folder with the same filename as the Image Filename. 

## Languages 

- Python 
- Javascript
- Golang
- BASH

**Comment by vybhav72954** [comment]
It seems easy, can do Python and Bash.

You can assign me this but I already have a lot of issues, I will sort many of them today only, if its still up-for-grab, assign it to me.

**Comment by HarshCasper** [comment]
Hello @vybhav72954 

This is open for assignment only for KWOC Participants. Please make a PR for the Issues assigned to you, before I assign any new Issues.

**Comment by vybhav72954** [comment]
> Hello @vybhav72954
> 
> This is open for assignment only for KWOC Participants. Please make a PR for the Issues assigned to you, before I assign any new Issues.

Hey Harsh, am a KWOC participant as well 😨 
But yeah I understand that I need to first sort my assigned issues. I will sort them by tonight itself.

P.S. - Can an Issue have both KWOC and NJACK label though 😛

**Comment by HarshCasper** [comment]
Hello @vybhav72954 

Let me know if you would be willing to work on it!

**Comment by vybhav72954** [comment]
@HarshCasper Currently busy with my EndSems, assign this to me but I will make a PR on Tuesday (22nd Dec)

**Comment by sahebsunny** [comment]
Sir, I love to work on it.
I would be grateful if you can assign this issue to me for DWOC.
Thank you.

**Comment by vybhav72954** [comment]
@sahebsunny I am a bit preoccupied right now, if I cant sort this issue in 2 days I will unassign myself on its own. Thank you.

the simply assign it to you on its own.
P.S. What is DWOC?

**Comment by sahebsunny** [comment]
> @sahebsunny I am a bit preoccupied right now, if I cant sort this issue in 2 days I will unassign myself on its own. Thank you.
> 
> the simply assign it to you on its own.
> P.S. What is DWOC?
Understood Sir,
 this DWOC is DevScript winter of code

**Comment by HarshCasper** [comment]
> @sahebsunny I am a bit preoccupied right now, if I cant sort this issue in 2 days I will unassign myself on its own. Thank you.
> 
> the simply assign it to you on its own.
> P.S. What is DWOC?

Good Luck, @vybhav72954 for your Exams! 

@sahebsunny Let me know about any sitrep on the Discord. I will assign you then if not resolved.

**Comment by Blastoise** [comment]
Assign this to me I will do it using Python.

**Comment by sahebsunny** [comment]
Sir I have previously worked with a similar project let me work

**Comment by HarshCasper** [comment]
Right now, @vybhav72954 is working on this. Since he has been a valuable contributor in past, I would like him to take this time on the Issue.

**Comment by Blastoise** [comment]
> Right now, @vybhav72954 is working on this. Since he has been a valuable contributor in past, I would like him to take this time on the Issue. 
> 
> 

@HarshCasper Sure. If he is not able to complete the issue then assign this to me.

**Comment by sahebsunny** [comment]
@HarshCasper Sir I want to use Handwriting detection with Optical Character Recognition to get the notes from the image

**Comment by vybhav72954** [comment]
@HarshCasper Opening a PR within an hour or so
