### ISSUE TITLE
Send E-Mails through the G-Mail REST API via OAuth 2.0

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#588]
## Description 

Send E-Mails through the G-Mail REST API via OAuth 2.0

* Obtain a Gmail user's credentials using OAuth 2.0. The OAuth 2.0 process should be initiated by an API call to your server.
* Store the obtained credentials in a file.
* Have a Script to execute send email using the credentials previously stored.

## Languages 

- Python
- Javascript

**Comment by Sumit-Sahu** [comment]
I want to work on it. Can you assign it to me.

**Comment by Sumit-Sahu** [comment]
@HarshCasper Instead of storing credential in file we can store it as session variable at server side.

**Comment by HarshCasper** [comment]
@Sumit-Sahu You can try out different approaches and explain to me the rationale behind that. If it is a better way of doing stuff, we are always open to ideas.
