### ISSUE TITLE
Script to track Application Time Usage

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#589]
## Description 

Create a Script which will track user time used on Desktop Applications. The final result should be viewed as a Pie-Chart for better analysis.

## Languages

- Python
- Javascript
- Golang
- BASH

**Comment by abdallah1097** [comment]
Already working on that, Have a question: I wrote it in Python and Bash and I'm not so familiar with Javascript and Golang, Can I pull request only with Python and Bash?

**Comment by HarshCasper** [comment]
@abdallah1097 

You are supposed to make a PR with only one language. Also make sure that you are a KWOC Participant, because this Issue is open only for KWOC Participants.

**Comment by abdallah1097** [comment]
@HarshCasper  I'm not a KWOC Participant and already made a pull request :D :D I hope I can participate, also  may you tell me more about what is KWOC? (if possible) :D
