### ISSUE TITLE
Get Meaning of a Word

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#59]
## AIM

Create a Script to get the Meaning of a Word straight from CLI.

## Languages

- Python
- Javascript

## Details

In this Script, we have to make use of APIs to get the meaning of a word.

**Comment by mohitacecode** [comment]
Please assign this issue to me

**Comment by Namyalg** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
@mohitacecode You can work on this.

@Namyalg Issues tagged with ```SCI-2020``` are for SCI-Participants. Please take up Issues that have the ```PSOC-2020``` tag on them.
