### ISSUE TITLE
Add NJACK Winter of Code '20 to Open Source Events

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#591]
## Description

Add NJACK Winter of Code '20 to Open Source Events. Take a look at the templates already there and add a similar File which shows what NJACK Winter of Code is all about.

## Languages 

- Markdown

**Comment by vybhav72954** [comment]
I will do this right away. Should I add, that you were one of the top mentors in SLoP as well @HarshCasper?

**Comment by Vishal-raj-1** [comment]
@vybhav72954 Brother Are you working on this issue right now? I have seen you have multiple issues to work on. So could you please leave this issue for me. I will start working on this issue right now..

**Comment by Vishal-raj-1** [comment]
Thanks Buddy @vybhav72954 🔥
