### ISSUE TITLE
Pip upgrade via python script

### ISSUE THREAD

**Issue by hr1shu** [HarshCasper/Rotten-Scripts#597]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
All you have to do is run the code and click the button to upgrade PIP to the latest update

**Describe alternatives you've considered**
writing commands in cmd prompt is overwhelming

**Additional context**

**Comment by Rahul555-droid** [comment]
well to upgrade pip you only have to run one command.
I don't know how you will use python script to upgrade pip though.
Probably through subprocess module(to run bash commands) .

python -m pip install –upgrade pip
or
python -m pip install -U pip

this works most of the time.

**Comment by hr1shu** [comment]
I made it using tkinter, basically it just needs to be run and clicked

**Comment by vybhav72954** [comment]
Still, it is just one command, can I update any package I want?

**Comment by hr1shu** [comment]
Just the PIP

**Comment by HarshCasper** [comment]
Hello @hr1shu 

We don't have support for User Interfaces yet. So probably, as @vybhav72954 and @Rahul555-droid mentioned, it is best to go with one simple command for the purpose.
