### ISSUE TITLE
Vigenere Cipher

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#6]
## AIM

Create a Script to implement Vigenere Cipher

## Languages

- Python
- Javascript
- Go

## Details

In this Script, you have to implement the concept of Vigenere Cipher and encrypt/decrypt a text based on the User-choice.

**Comment by mohitacecode** [comment]
would like to work on this.

**Comment by HarshCasper** [comment]
You have been assigned this Issue @mbcse 

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by mbcse** [comment]
would like to work on this

**Comment by mohitacecode** [comment]
Working on it will soon submit a PR

**Comment by mohitacecode** [comment]
This issue can be closed I have already submitted a PR for this.
