### ISSUE TITLE
Get Stock Information

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#60]
## AIM

Create a Script to pick up Stock Information based on User Inputs and display on CLI.

## Languages

- Python
- Javascript
- BASH

## Details

You can make use of [Financial Modelling Prep API](https://financialmodelingprep.com/) to get access to various Stock Profiles and Stock Prices and display various details on the Command Line depending on the flags passed by the user.

**Comment by mohitacecode** [comment]
Please assign this issue to me

**Comment by HarshCasper** [comment]
I have assigned you the Issue @mohitacecode 

You can start working on this

**Comment by HarshCasper** [comment]
@mohitacecode Are you working on the same?

**Comment by mohitacecode** [comment]
Yes will soon submit a PR.
