### ISSUE TITLE
Merge Pdf using pyPDF

### ISSUE THREAD

**Issue by Tejas1510** [HarshCasper/Rotten-Scripts#604]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A python script which takes pdf file as input and merges them using pyPDF module

**Describe alternatives you've considered**

**Additional context**

**Comment by Tejas1510** [comment]
@HarshCasper Can I work on this issue

**Comment by Aashish3061** [comment]
@HarshCasper I would like to work on this

**Comment by HarshCasper** [comment]
Hello @Tejas1510

I have assigned you this Issue in Python. Let me know @Aashish3061 if you would like to work on this in JS/Golang

**Comment by Aashish3061** [comment]
I would be more comfortable in python as I am not well versed with JS Or Golang
