### ISSUE TITLE
Create a script which will encrypt and decrypt the contents of a given file accordingly using RSA

### ISSUE THREAD

**Issue by Rahul555-droid** [HarshCasper/Rotten-Scripts#605]
**Is your feature request related to a problem? Please describe.**
You can encrypt your data with cryptographic RSA algorithm say maybe a list of password or a something confidential like an image.

**Describe the solution you'd like**
*while encrypting:*
a script then would encrypt my input data file and with a command line argument "encrypt" then output a file with encrypted data and a file with keys at a desired location as per the user
*while decrypting:*
The script will take location a file with keys and of a file with encrypted data and a command line argument "decrypt"
After which it will output the decrypted file in the desired directory of the user.

**Describe alternatives you've considered**

**Additional context**

**Comment by Rahul555-droid** [comment]
Hi @HarshCasper Can you assign me this?

**Comment by SmritiAgrawal04** [comment]
Hi! Is this issue being worked upon? I'm a participant of GSSOC'21 and want to work on the same, please assign me this issue.

**Comment by vybhav72954** [comment]
Hey @SmritiAgrawal04 we have a script for the [same](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/RSA_Key_Generation)

KIndly go through this once, if you can make this script better, suggest me ideas and I will assign you the same.

**Comment by SmritiAgrawal04** [comment]
> Hey, @SmritiAgrawal04 we have a script for the [same](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/RSA_Key_Generation), although this script might be different from this feature request as well. If that's the case do let me know.
> 
> If the script satisfies the issue, go through the script and if you can make this script better, suggest me ideas and I will assign you the same.

Hey! I went through the script. It does store the public and private key files but does not do the actual encryption and decryption procedures on any file. Also these files(pem files) are not saved as per user requirements, can you please check? For further analysis,please assign me the issue.

**Comment by vybhav72954** [comment]
@HarshCasper What do you think? I think that the script we currently have is lacking the encryption part as well, and the idea is good to go from my side. @sohamsshah @seema1711

**Comment by seema1711** [comment]
Yes, @vybhav72954, these are different scripts, and I think @SmritiAgrawal04 can start working on the new one.

**Comment by vybhav72954** [comment]
@seema1711 Thank you for confirming!!!
@SmritiAgrawal04 You are on roll. Please feel free to ask me anything.

**Comment by SmritiAgrawal04** [comment]
> @seema1711 Thank you for confirming!!!
> @SmritiAgrawal04 You are on roll. Please feel free to ask me anything.

Hey! I'm done writing the script. Please look into it and suggest improvements.
