### ISSUE TITLE
A script to get a list of links related to a particular query (Google Search Rank wise)

### ISSUE THREAD

**Issue by shiveshchoudhary** [HarshCasper/Rotten-Scripts#608]
Is your feature request related to a problem? Please describe.
You can use this script to get the links related to a particular search query (rank wise), which can be used by the user to get to any link without scrolling down or using next to move to next page.

Describe the solution you'd like
Using a google api, beautifulsoup4 and urllib libraries in Python to store all the links in a list and displaying the list as output.

Describe alternatives you've considered

Additional context

**Comment by shiveshchoudhary** [comment]
@HarshCasper , can you assign me this issue.

**Comment by HarshCasper** [comment]
Good to go @shiveshchoudhary 👍 

Thanks for creating an Issue!

**Comment by HarshCasper** [comment]
Also, do let me know if you are participating in either NJACK or KWOC? I have put NJACK for now, but do let me know about it, so that points are properly allocated for the same.

**Comment by shiveshchoudhary** [comment]
Although I got to know about this repo through kwoc, but got late in registering for it, so I am contributing independently, you may remove the NJACK tag.

**Comment by shiveshchoudhary** [comment]
Hello @HarshCasper  I have opened a pull request, please check and update if any changes required.
