### ISSUE TITLE
Get Memes!

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#61]
## AIM

Create a Script to consume a REST API and get some cool Memes delivered straight on your Command-Line.

## Languages

- Python
- Javascript
- BASH
- Golang

## Details

Make use of the [Imgflip API](https://api.imgflip.com/) to consume REST endpoints and get some memes delivered to you straight from Command-Line.

**Comment by sanket143** [comment]
Can I work on this?

**Comment by Namyalg** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
I have assigned you the Issue @sanket143

**Comment by sanket143** [comment]
https://api.imgflip.com/get_memes is serving templates and not actual memes. Are we supposed to scrap
these?

**Comment by HarshCasper** [comment]
You can scrap the templates instead.
