### ISSUE TITLE
Pdf reordering using python script.

### ISSUE THREAD

**Issue by Rahul555-droid** [HarshCasper/Rotten-Scripts#610]
**Is your feature request related to a problem? Please describe.**
At times we get a pdf that is not ordered properly but we know the pages which have are out of order  and it is tough to reorder it.

**Describe the solution you'd like**
A python script that will take an input of pages which are unordered and where these unordered pages should go and parse it into dictionary.
Using this dictionary and a python library I will reorder the PDF.

**Describe alternatives you've considered**

I couldn't find any good free application on playstore for android or on the internet for windows.
Using this script I would be able to do the reordering with minimum hassle 

**Additional context**

**Comment by Rahul555-droid** [comment]
Hi Harsh I have the code and readme file ready and I see that I am still assigned to this issue,
 I can make the PR like before this time from my local git.

can you please count this for DWOC then?

Thanks.

**Comment by HarshCasper** [comment]
> Hi Harsh I have the code and readme file ready and I see that I am still assigned to this issue,
> I can make the PR like before this time from my local git.
> 
> can you please count this for DWOC then?
> 
> Thanks.

Sure. Please go ahead

**Comment by iamakkkhil** [comment]
I would like to work on this issue.
I am a GSSOC 21 participant. 
if assigned please change the tags accordingly.

**Comment by vybhav72954** [comment]
Assigned. Best of Luck!!!
