### ISSUE TITLE
Password checker

### ISSUE THREAD

**Issue by hr1shu** [HarshCasper/Rotten-Scripts#616]
**Is your feature request related to a problem? Please describe.**
My script checks how many times your password has been under a hacker radar 

**Describe the solution you'd like**
It also suggests changes required to make in your password

**Describe alternatives you've considered**

**Additional context**

**Comment by Siddhant-K-code** [comment]
> My script checks how many times your password has been under a hacker radar

how does this feature will work?

**Comment by hr1shu** [comment]
Using API of pawnedpasswords.com

**Comment by HarshCasper** [comment]
Go ahead @hr1shu

**Comment by hr1shu** [comment]
Thanks mate
