### ISSUE TITLE
Send your location to your loved ones

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [HarshCasper/Rotten-Scripts#619]
A python script to send location.

**Comment by Rishikeshrajrxl** [comment]
Assign me this issue.

**Comment by sahebsunny** [comment]
Sir, I love to work on it.
I would be grateful if you can assign this issue to me for DWOC.
Thank you.

**Comment by HarshCasper** [comment]
> A python script to send location.

Can you briefly explain to me on how your Script would work? And what are the brief functionalities are you looking for in the Script?

**Comment by pritamp17** [comment]
@HarshCasper I would like to work on this issue.

**Comment by pritamp17** [comment]
my script would work somewhat like this...                                                                          
first, through the request module, I would send IP to  https://whatismyipaddress.com/
then with the bs4 module, I will select the location ,
then I will send mail using SMTP lib.

**Comment by HarshCasper** [comment]
I would like to know the proper feature-set first before we actually finalize this Issue.

**Comment by vybhav72954** [comment]
> Hi @vybhav72954 I would like to work on this issue, please assign this to me.

I can do that for sure, but a small problem here.

As you can see, the issue doesn't explain what the script actually is. So what I suggest is, please tell me, here in the comments, what you will do in this script, explain to us a bit what kind of script will it be, and what would be the dependencies. I will assign you right away.

**Comment by SSHREYA71** [comment]
> > Hi @vybhav72954 I would like to work on this issue, please assign this to me.
> 
> I can do that for sure, but a small problem here.
> 
> As you can see, the issue doesn't explain what the script actually is. So what I suggest is, please tell me, here in the comments, what you will do in this script, explain to us a bit what kind of script will it be, and what would be the dependencies. I will assign you right away.

I have not done this in python, but i did make an app on flutter to get the location. But i know i need libraries like json and requests and get api's . And hope to learn more through the process of doing it.

**Comment by HarshCasper** [comment]
I'm still not very convinced with the base idea. Why do I need a script to send location to my "loved ones" when existing Apps do that really well. 

I'm closing this Issue as of now, because I don't really see any value in this.
