### ISSUE TITLE
Build a Twitter Bot using Python

### ISSUE THREAD

**Issue by seema1711** [HarshCasper/Rotten-Scripts#62]
# AIM
Create a Twitter bot that will be used to like and retweet some particular hashtags.  

# LANGUAGE

- Python

# DETAILS

To build a twitter bot, you can use [tweepy](https://github.com/tweepy/tweepy).

**Comment by seema1711** [comment]
@HarshCasper Can you consider this issue?

**Comment by Namyalg** [comment]
I would like to work on this

**Comment by seema1711** [comment]
I think it's for SCI. @Namyalg

**Comment by AnkitaBIT** [comment]
I would like to work on this @seema1711 @HarshCasper

**Comment by HarshCasper** [comment]
@seema1711 You can work on this Issue. I would consider @seema1711 would be working on Python, so @AnkitaBIT can you work on its implementation in NodeJS ?

**Comment by AnkitaBIT** [comment]
@HarshCasper I would like to work on Twitter bot's implementation in NodeJS
