### ISSUE TITLE
Add PowerShell and Bash Scripts

### ISSUE THREAD

**Issue by avinal** [HarshCasper/Rotten-Scripts#621]
**Is your feature request related to a problem? Please describe.**
Although the description suggests **PowerShell** there ain't one. 

**Describe the solution you'd like**
A new section for PowerShell and we can add scripts in that. At first, we can add those scripts which are already available in another language/platform. We add the PowerShell version (if doable).

**Additional context**
There are a lot of changes in PowerShell from Command Prompt, both in terms of syntax and strength, and PowerShell is often underlooked, so we may add basic scripts too.

**Comment by avinal** [comment]
Hello, I want to work on this issue.

**Comment by HarshCasper** [comment]
Hello @avinal 

I am all open for Powershell Scripts. Can you please let me know what Powershell Scripts are you looking to add initially?

**Comment by avinal** [comment]
Umm, I have been through the repository and saw the types of scripts it is hosting. Since bash and PowerShell are mostly associated with system control, I would like to add such scripts (now I see bash scripts are also less in numbers), I have significant experience with scripts that generally people search. I am listing a few for now and I will have a more exhaustive list soon. Needless to say, it will be somewhat different from the other languages(python , go, javascript) focusing more on system tasks, rather than an application because that is what PowerShell and bash is for :)

1. Tweak your PowerShell and bash prompt - git status, virtual environment, error, execution time, and a lot more
2.  A better ls command script - shows the type of file, group-wise, category wise, modified by, etc
3. cat with line numbers
4. modifying permissions
5. Webpage URL scraper 
6. GitHub stalker 

Will add more.

**Comment by HarshCasper** [comment]
Hello @avinal 

They look good to me! Can you create individual issues for all of them?

This would allow me to grade them individually and help you get the apt scores. Also let me know, if you are willing to work on it as part of any Open Source Program. For reference, this Project is a part of NJACK Winter of Code, KWoC, SWoC, DWoC.

**Comment by avinal** [comment]
Sure @HarshCasper, I will divide them into separate issues and add more as I get more of them. Should I rephrase this issue as one of them or just keep it as a tracker/discussion? 

I am doing it under SWoC. Didn't know that this is part of other programs too 😅

**Comment by HarshCasper** [comment]
> Sure @HarshCasper, I will divide them into separate issues and add more as I get more of them. Should I rephrase this issue as one of them or just keep it as a tracker/discussion?
> 
> I am doing it under SWoC. Didn't know that this is part of other programs too 😅

Let's keep this as our Discussion Thread. We have Discussions Tab enabled as well, but for some reasons I tend to talk right here. 

It would be great to have you work on this! Let me know if I can be of help in any ways.

**Comment by vybhav72954** [comment]
@avinal @HarshCasper Can i close this issue in case the you migrated to discussions?
