### ISSUE TITLE
Text Editior

### ISSUE THREAD

**Issue by saiharsha-22** [HarshCasper/Rotten-Scripts#622]
Text Editior,  Will allow the user to genrate text in a neat and clean manner. 

Prgramming languages used: JavaScript

Frontend: HTML,CSS

Features of the Project: 
 1. You align the whole text in center or middle or extreme end, according to user requirement
 2. User can underline the text if he/she wants 
 3. Make it bold 
 4. Make it Italic 
 5. The system will be side by side working,  it will be convient for the user to use these type of editors

**Comment by saiharsha-22** [comment]
@HarshCasper if you find it useful project, assign this issue to me. I am partcipan of Swoc 2021

**Comment by HarshCasper** [comment]
Hi @saiharsha-22 

Thanks for taking the time to create the Issue! However, this Repo supports only Scripts and not GUI Applications. 

I am closing this Issue as it doesn't align with the Project purpose.
