### ISSUE TITLE
Add new Issue Templates

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#624]
## Description 

Add new Issue Templates. 

I originally created an Issue for Issue+PR Templates and it was resolved here https://github.com/HarshCasper/Rotten-Scripts/pull/116. However, I over-rode the custom Issue Templates with the Issue Templates provided by Github, which in no way is helpful to the Project. 

Please have a good new Issue Templates for the purpose. Feel free to pick it up from the above PR and add customizations as per your own design.

**Comment by akrish4** [comment]
Hi @HarshCasper 
The issue template looks perfect , let me know what do you need ?

**Comment by HarshCasper** [comment]
Anything that you would like to add @akrish4 

Let me know if you would like to work on it.

**Comment by akrish4** [comment]
Hi @HarshCasper 
I would like to bring these below mentioned updates tothe PR template , which gives a better understanding of the pr made 

## Describe the changes you've made
A clear and concise description of what you have done ........

## Describe if there is any unusual behaviour of your code
A clear and concise description of it.........

## Additional context (OPTIONAL)
Add any other ........

## Test plan (OPTIONAL)
Add any other ........

**Comment by akrish4** [comment]
@HarshCasper  Let me know if you want to add the above mentioned changes to your pr template 
Kindly assign me

**Comment by HarshCasper** [comment]
> ### Hi @HarshCasper
> ### I would like to bring these below mentioned updates tothe PR template , which gives a better understanding of the pr made
> #### Describe the changes you've made
> A clear and concise description of what you have done ........
> 
> #### Describe if there is any unusual behaviour of your code
> A clear and concise description of it.........
> 
> #### Additional context (OPTIONAL)
> Add any other ........
> 
> #### Test plan (OPTIONAL)
> Add any other ........

This is the current Issue Template. It is not helping us in any way. 

Suggest you to take a look at this https://github.com/HarshCasper/Rotten-Scripts/pull/116 and find what's best for you.

**Comment by vybhav72954** [comment]
@HarshCasper Personally I prefer the old Issue template.

But I have one more suggestion.

How about having 3 Templates.

- New Script Template (similar to on in #116)
- Bug Template
- Feature Template

You can have the custom one also for sure.

Why this format?

The old template was really good for defining scripts, how they are supposed to work, and what to expect.

While the current template with some additions can work as a feature template, now new features can be differentiated from lists obviously, like this issue is a feature, a new GitHub action, changes in the README to make them more informative, etc are features.

I believe that having 3 templates will certainly help. Lastly, who ever is assigned kindly make sure there are multiple comments explaining how the template works, cause despite the best efforts, people still mess up the Markdown.

**Comment by HarshCasper** [comment]
@akrish4 This Comment by @vybhav72954 is rock-solid. Please try to see, if you can create something like that.

**Comment by himanshu007-creator** [comment]
i would like to work on this issue. Please assign me this issue.

**Comment by himanshu007-creator** [comment]
https://github.com/HarshCasper/Rotten-Scripts/pull/681 Done sir.

**Comment by vybhav72954** [comment]
@HarshCasper Consider me as your last option if no one asks to solve this.

> @HarshCasper Personally I prefer the old Issue template.
> 
> But I have one more suggestion.
> 
> How about having 3 Templates.
> 
> * New Script Template (similar to on in #116)
> * Bug Template
> * Feature Template
> 
> You can have the custom one also for sure.
> 
> Why this format?
> 
> The old template was really good for defining scripts, how they are supposed to work, and what to expect.
> 
> While the current template with some additions can work as a feature template, now new features can be differentiated from lists obviously, like this issue is a feature, a new GitHub action, changes in the README to make them more informative, etc are features.
> 
> I believe that having 3 templates will certainly help. Lastly, who ever is assigned kindly make sure there are multiple comments explaining how the template works, cause despite the best efforts, people still mess up the Markdown.
