### ISSUE TITLE
Update the Python's README

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#627]
## Description

Update Python's README. As it can be noticed, that there is a complete Table which consists of the Name of Script, Directory Link and the Author. Many of the Scripts don't exist on the Table. 

Find and hunt the Scripts that are not on the Table and update it. Make sure to change *all* the Directory Links to hyperlinks by using `[text](https://random.com)` instead of hard-coding it, which looks ugly. 

Also add a link for the [README Template](https://github.com/HarshCasper/Rotten-Scripts/blob/master/TEMPLATE_README.md), so that all the Contributors know what exactly has been worked on for preparing Script Docs. 

Also add a section to suggest Contributors actively use tools like PyLint to keep Code Quality in Check. Add some resources as well for Scripting in Python.

**Comment by Purvanshsingh** [comment]
@HarshCasper Is this issue for SWOC as well?
I would like to work on this issue, please assign me this issue.

**Comment by HarshCasper** [comment]
Hello @Purvanshsingh 

This Issue is for DWOC. If I don't get any Assignment Request, I will keep it for SWOC itself.

**Comment by Purvanshsingh** [comment]
ok, In case you sift it to SWOC please assign it to me.

**Comment by CharvyJain** [comment]
@HarshCasper Can I work on this ?

**Comment by vybhav72954** [comment]
@HarshCasper Am participating in DWOC as well. I can do this XD

**Comment by HarshCasper** [comment]
> @HarshCasper Can I work on this ?

Hello Charvy, 

If you are a participant at DWOC, let me know. I can assign it to you. 

@vybhav72954 You are already working on many Issues, so let everyone have an equal share of pie 😄

**Comment by vybhav72954** [comment]
Yes please @HarshCasper I definitely understand :D

**Comment by CharvyJain** [comment]
> > @HarshCasper Can I work on this ?
> 
> Hello Charvy,
> 
> If you are a participant at DWOC, let me know. I can assign it to you.
> 
> @vybhav72954 You are already working on many Issues, so let everyone have an equal share of pie

Yes, I am participating in DWOC.

**Comment by CharvyJain** [comment]
@HarshCasper Should I  "add a section to suggest Contributors actively use tools" in the table itself ?

**Comment by HarshCasper** [comment]
> @HarshCasper Should I have to add a new column for "suggesting Contributors actively use tools" in the table ?

It would look better 💯

**Comment by CharvyJain** [comment]
@HarshCasper **Is it fine ?**
![Untitled](https://user-images.githubusercontent.com/69421337/103887066-7e91ba80-5108-11eb-8cc4-bb1ed744b555.png)

**Comment by HarshCasper** [comment]
> @HarshCasper **Is it fine ?**
> ![Untitled](https://user-images.githubusercontent.com/69421337/103887066-7e91ba80-5108-11eb-8cc4-bb1ed744b555.png)

Good Work! 

One Question: Why do we have README template column right here? And what content does it point to?

**Comment by CharvyJain** [comment]
That column points to the ReadMe of that particular Script.
Any changes to make ?

**Comment by HarshCasper** [comment]
> That column points to the ReadMe of that particular Script.
> Any changes to make ?

I guess the directory link should open the directory, isn't it? Or are you referring the Code through it. 

Anyway, I guess you can remove the Column and let the Directory Link directly open the Directory. Also, make sure to use Local Reference instead of directly using links.

**Comment by CharvyJain** [comment]
Directory link will open the directory.

**Comment by CharvyJain** [comment]
What is local reference ?

**Comment by HarshCasper** [comment]
> Okay. I will remove that column.
> What is local reference ?

Don't use links directly. Refer [this](https://github.com/TesseractCoding/NeoAlgo/tree/master/Python) to better understand how local references are created.

**Comment by CharvyJain** [comment]
Okay. Thanks

**Comment by HarshCasper** [comment]
@CharvyJain Can you let me know how much time it would take you for making a PR?

**Comment by CharvyJain** [comment]
I will complete by tomorrow evening.

**Comment by CharvyJain** [comment]
@HarshCasper When local reference link is clicked, Should it open folder or direct script (.py) file ?

**Comment by HarshCasper** [comment]
> @HarshCasper When local reference link is clicked, Should it open folder or direct script (.py) file ?

Folder is preferred.

**Comment by CharvyJain** [comment]
PR - #696
Let me know if there are any changes to make ?
