### ISSUE TITLE
Update the Javascript README

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#628]
## Description

Update Javascript's README. As it can be noticed, that there is a complete Table which consists of the Name of Script, Directory Link and the Author. Many of the Scripts don't exist on the Table. 

Find and hunt the Scripts that are not on the Table and update it. Make sure to change *all* the Directory Links to hyperlinks by using `[text](https://random.com)` instead of hard-coding it, which looks ugly. 

Also add a link for the [README Template](https://github.com/HarshCasper/Rotten-Scripts/blob/master/TEMPLATE_README.md), so that all the Contributors know what exactly has been worked on for preparing Script Docs. 

Also, add a section to suggest Contributors actively use tools to keep Code Quality in Check. Add some resources as well for Scripting in Javascript.

**Comment by vybhav72954** [comment]
I can do this XD.
PS - Am also a part of `Script Winter and Devscript Winter` 
that is if `SWOC'20` label is for the same.

PPS - Shouldn't in be `SWOC21`

**Comment by HarshCasper** [comment]
> I can do this XD.
> PS - Am also a part of `Script Winter and Devscript Winter`
> that is if `SWOC'20` label is for the same.
> 
> PPS - Shouldn't in be `SWOC21`

I will update the labels soon. That's a lot of work (sadly). 

Assigning 🚀

**Comment by vybhav72954** [comment]
I know man, hopefully, your other maderators would be available soon

**Comment by vybhav72954** [comment]
> Also add a link for the [README Template](https://github.com/HarshCasper/Rotten-Scripts/blob/master/TEMPLATE_README.md), so that all the Contributors know what exactly has been worked on for preparing Script Docs.
> 
> Also, add a section to suggest Contributors actively use tools to keep Code Quality in Check. Add some resources as well for Scripting in Javascript.

Unable to understand these 2 points.

**Comment by vybhav72954** [comment]
@HarshCasper Is it possible that this can have DWOC label as well, DevScript Winter of Code?
