### ISSUE TITLE
Add SWoC to Open Source Events

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#629]
## Description

Add SWoC'20 to Open Source Events. Take a look at the templates already there and add a similar File which shows what SWoC is all about.

## Languages 

- Markdown

**Comment by imakash3011** [comment]
Sir, I would like to work on this issue. Kindly assign it to me.

**Comment by pritamp17** [comment]
Sir, I would like to work on this issue. could you assign it to me?

**Comment by imakash3011** [comment]
I have completed fixed this issue , just waiting for 5 January to make PR, otherwise it won't be counted in SWoC.
