### ISSUE TITLE
Add DWoC'20 to Open Source Events

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#630]
## Description

Add DWoC'20 to Open Source Events. Take a look at the templates already there and add a similar File which shows what DWoC is all about.

## Languages 

- Markdown

**Comment by shiveshchoudhary** [comment]
just for confirmation, is the below-mentioned website for the same DWOC we want to update in open source contributions.
https://delta.nitt.edu/
