### ISSUE TITLE
Add a Github Action to auto-assign reviewers

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#631]
## Description

With so many PRs kicking in, every week, its a definite pain to review each of them. What if we can have an Action to auto-assign reviewers, every time a PR is made? 

Make sure to add me ( @HarshCasper ) for the reviewers at the least.

**Comment by avinal** [comment]
I can help with such GitHub Action.

**Comment by avinal** [comment]
I will need the reviewer's list too.

**Comment by HarshCasper** [comment]
> I will need the reviewer's list too.

Just mention me for now. We have two more reviewers but they are not active right now.

**Comment by avinal** [comment]
I have already added you to the reviewers' section.
