### ISSUE TITLE
Add a powerful ls command alternative script

### ISSUE THREAD

**Issue by avinal** [HarshCasper/Rotten-Scripts#634]
By default `ls` command doesn't show file types or categories and almost no sorting option. This script will make the ls command more powerful with such options.

**Comment by avinal** [comment]
This will be for Bash first because Linux users mostly these types of scripts. Will add for PowerShell later. Please label it as Bash.

**Comment by abdus** [comment]
[`exa`](https://github.com/ogham/exa) is an enhanced version of `ls`.

**Comment by avinal** [comment]
Hello @abdus, `exa` is a full featured replacement for `ls`, here our goal is to provide a simple script that enhances `ls`,  it will be simple to understand and modify too according to your need.
