### ISSUE TITLE
Webpage URL scraper bash script

### ISSUE THREAD

**Issue by avinal** [HarshCasper/Rotten-Scripts#635]
Scrap all the links present in a webpage.

**Comment by Adarsh88** [comment]
Hey there, I want to contribute in this project.

**Comment by Adarsh88** [comment]
Hey there I want to contribute to this project. Can you assign this to me ?

**Comment by Purvanshsingh** [comment]
Please correct me if I am wrong,
means we have to write the python script to scrap all the links of the web page entred by the user right?

**Comment by avinal** [comment]
Hello @Purvanshsingh, no this is a bash script.

**Comment by avinal** [comment]
PR #719
