### ISSUE TITLE
GitHub Stalker bash script

### ISSUE THREAD

**Issue by avinal** [HarshCasper/Rotten-Scripts#636]
Get GitHub information of a user right from the terminal

**Comment by hackedak** [comment]
Please assign this to me

**Comment by Blastoise** [comment]
Please assign this to me.

**Comment by avinal** [comment]
Hello @Blastoise, this is already assigned :) see the label

**Comment by Blastoise** [comment]
Okay @avinal, I thought you were the one that will assign.

**Comment by avinal** [comment]
Work in progress

**Comment by avinal** [comment]
@vybhav72954, I forgot to add a pull request somehow. I think I have a working code, if you want I can send it.

**Comment by vybhav72954** [comment]
Would be a great addition :D

**Comment by iamakkkhil** [comment]
@avinal If you have the working code you can still make a PR :D

**Comment by avinal** [comment]
Hello @iamakkkhil, I tried searching the code on my computer, unfortunately, I have deleted the clone. I apologize for the delay. Right now I am busy with GSoC so won't be able to rewrite it any time sooner. Please feel free to reassign it. Thanks
