### ISSUE TITLE
Anime Tracker

### ISSUE THREAD

**Issue by hackedak** [HarshCasper/Rotten-Scripts#639]
###Script
-A script which checks for new episode release of a particular anime automatically

**Comment by hackedak** [comment]
Please assign this to me

**Comment by HarshCasper** [comment]
Hello @hackedak 

Let me know if you are participating in any Open-Source Programs, so that I can tag it aptly.

**Comment by hackedak** [comment]
No...only SWOC

**Comment by pritamp17** [comment]
@HarshCasper sir if nobody is working on this then could you please assign this to me..

**Comment by HarshCasper** [comment]
> @HarshCasper sir if nobody is working on this then could you please assign this to me..

It is already being worked on.

**Comment by srimontidutta** [comment]
Hello, can I please work on this issue as a part of GSSoC 21?

**Comment by manas221** [comment]
Hello there , can i work on this issue as a contributor for the gssoc'21 ?
If possible ,please assign this to me.
Thank you.

**Comment by vybhav72954** [comment]
@srimontidutta Sorry i missed this notification. YOu want to work on this?

@manas221 Srimoni asked first so I would like to wait for a response from her side, if there are n updates I can assign this to you for sure.

**Comment by vybhav72954** [comment]
@manas221 @srimontidutta 
The issue is already open in #771

Am closing this issue for the same reason.
A PR is open as well, but we haven't received any updates from the OP.

The issue will be marked open if there are no further updates.

**Comment by srimontidutta** [comment]
@vybhav72954 So then, can you please clarify if this issue is assigned or not?
