### ISSUE TITLE
Python-camscanner

### ISSUE THREAD

**Issue by djm-1** [HarshCasper/Rotten-Scripts#640]
I want to contribute a script written in python to convert images into camscanner like images. I have made that script using opencv-python. It can be used for making notes

**Comment by HarshCasper** [comment]
Hello @djm-1 

Let me know if you are participating in any Open-Source Programs, so that I can tag it aptly.

**Comment by djm-1** [comment]
Yes, Devscript winter of code

**Comment by SmritiAgrawal04** [comment]
Hi! Is this issue being worked upon? I'm a participant of GSSOC'21 and want to work on the same, please assign me this issue.

**Comment by vybhav72954** [comment]
@SmritiAgrawal04 Sure thing!!!

**Comment by SmritiAgrawal04** [comment]
> @SmritiAgrawal04 Sure thing!!!

Are you planning to assign this to me?

**Comment by vybhav72954** [comment]
This is awkward 😛 
My bad, I thought I assigned it to you already 😓

**Comment by vybhav72954** [comment]
Thanks for reminding

**Comment by SmritiAgrawal04** [comment]
> Thanks for reminding

haha, no issues. Will work on it. Thanks!

**Comment by SmritiAgrawal04** [comment]
Generated a PR, please review. Thanks!
