### ISSUE TITLE
Adding Contributors

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#641]
## Description 

I realized right now, that there are more than 60+ Contributors to the Project but the Contributor List has not been updated. If you have contributed to the Repo in any manner, please comment here. I will invoke the All Contributors Bot to have you on the Contributor List.

**Comment by HarshCasper** [comment]
@all-contributors please add @Pranav016 for Code

**Comment by HarshCasper** [comment]
@all-contributors please add @Pranav016 for Documentation

**Comment by HarshCasper** [comment]
@all-contributors please add @Vishal-raj-1 for Code

**Comment by HarshCasper** [comment]
@all-contributors please add @Vishal-raj-1 for Documentation

**Comment by HarshCasper** [comment]
@all-contributors please add @frbimo for Code

**Comment by HarshCasper** [comment]
@all-contributors please add @frbimo for Documentation

**Comment by HarshCasper** [comment]
@all-contributors please add @AdityaAshvin for Code

**Comment by HarshCasper** [comment]
@all-contributors please add @AdityaAshvin for Documentation

**Comment by HarshCasper** [comment]
@all-contributors please add @DevChoganwala for Code

**Comment by HarshCasper** [comment]
@all-contributors please add @DevChoganwala for Documentation

**Comment by HarshCasper** [comment]
@all-contributors please add @DevChoganwala for Code

**Comment by HarshCasper** [comment]
@all-contributors please add @DevChoganwala for Documentation

**Comment by HarshCasper** [comment]
@all-contributors please add @avinal for Code

**Comment by HarshCasper** [comment]
@all-contributors please add @dcorriveau for Code

**Comment by HarshCasper** [comment]
@all-contributors please add @dcorriveau for Documentation

**Comment by HarshCasper** [comment]
@all-contributors please add @vybhav72954 for Code

**Comment by HarshCasper** [comment]
@all-contributors please add @vybhav72954 for Documentation

**Comment by HarshCasper** [comment]
@all-contributors please add @vybhav72954 for Maintenance

**Comment by HarshCasper** [comment]
@all-contributors please add @sharur7 for Code

**Comment by HarshCasper** [comment]
@all-contributors please add @sharur7 for Documentation

**Comment by HarshCasper** [comment]
@all-contributors please add @kritikaparmar-programmer for code

**Comment by HarshCasper** [comment]
@all-contributors please add @kritikaparmar-programmer for documentation

**Comment by HarshCasper** [comment]
@all-contributors please add @Sumit-Sahu for code

**Comment by HarshCasper** [comment]
@all-contributors please add @Sumit-Sahu for documentation

**Comment by HarshCasper** [comment]
@all-contributors please add @howardshin1 for code

**Comment by HarshCasper** [comment]
@all-contributors please add @howardshin1 for documentation

**Comment by HarshCasper** [comment]
@all-contributors please add @twozero88 for code

**Comment by HarshCasper** [comment]
@all-contributors please add @twozero88 for documentation

**Comment by HarshCasper** [comment]
@all-contributors please add @GoswamiTushar for code

**Comment by HarshCasper** [comment]
@all-contributors please add @GoswamiTushar for documentation

**Comment by iamakkkhil** [comment]
@all-contributors please add @iamakkkhil  for documentation

**Comment by RohiniRG** [comment]
@all-contributors please add @RohiniRG for code

**Comment by rahulraikwar00** [comment]
@all-contributors please add @rahulraikwar00 for Code

**Comment by rahulraikwar00** [comment]
@all-contributors please add @rahulraikwar00 for Code

**Comment by vybhav72954** [comment]
@all-contributors please add @rahulraikwar00 for documentation

**Comment by vybhav72954** [comment]
@all-contributors please add @devRawnie for documentation

**Comment by vybhav72954** [comment]
@all-contributors please add @devRawnie for code

**Comment by vybhav72954** [comment]
@all-contributors please add @Rupa-421 for documentation

**Comment by vybhav72954** [comment]
XD
@HarshCasper Let's keep this open for all XD

**Comment by vybhav72954** [comment]
@all-contributors please add @mdPial for code

**Comment by vybhav72954** [comment]
@all-contributors please add @mdPial for documentation

**Comment by vybhav72954** [comment]
@all-contributors please add @Siddhant-K-code for code

**Comment by vybhav72954** [comment]
@all-contributors please add @Siddhant-K-code for documentation

**Comment by vybhav72954** [comment]
@all-contributors please add @sohamsshah for maintenance

**Comment by vybhav72954** [comment]
@all-contributors please add @sourabhkumar45  for code

**Comment by vybhav72954** [comment]
@all-contributors please add @jhamadhav for code

**Comment by vybhav72954** [comment]
@all-contributors please add @ireneelizabethsabu for documentation

**Comment by vybhav72954** [comment]
@all-contributors please add @ireneelizabethsabu for documentation

**Comment by vybhav72954** [comment]
@all-contributors please add @ireneelizabethsabu for documentation

**Comment by vybhav72954** [comment]
@all-contributors please add @tanishq-arya for code

**Comment by vybhav72954** [comment]
@all-contributors please add @RohiniRG for code

**Comment by vybhav72954** [comment]
@all-contributors please add @RohiniRG for documentation

**Comment by vybhav72954** [comment]
@all-contributors please add @Sukriti-sood for documentation

**Comment by vybhav72954** [comment]
@all-contributors please add @Sukriti-sood for code

**Comment by vybhav72954** [comment]
@all-contributors please add @ShubhamGupta577 for code

**Comment by HarshCasper** [comment]
@all-contributors bot please add @sudormrfbin for code
