### ISSUE TITLE
Creating a SSG website for this project.

### ISSUE THREAD

**Issue by avinal** [HarshCasper/Rotten-Scripts#656]
Hello @HarshCasper, 

There are lots of SSGs, some of the most popular are Sphinx, Jekyll, and a lot [more](https://scotch.io/tutorials/top-10-static-site-generators-in-2020). More or less they work on the same principle, that is converting Markdown or reStructured Text into HTML.

You may choose any SSG, but Jekyll has an additional advantage that it works natively with gh-pages, no CI/CD required. There are a plethora of themes. As per my experience, I can suggest two ways to create a website for this project.
1. Since every script in this project has a separate readme file. we can just modify them a bit to be included by the site generator recursively (just adding few keywords) and thus site will be generated, you can customize the home page. 
2. Create a whole new branch/repo for this purpose and add each script description separately. This gives us slightly more control but it needs huge efforts.

For example you can see these:-
- source: https://code.videolan.org/avinal/vlc-android-user generated-site: https://avinal.videolan.me/vlc-android-user (sphinx)
- https://avinal.is-a.dev (pelican)
- https://idratherbewriting.com/documentation-theme-jekyll/ (Jekyll)

**Comment by HarshCasper** [comment]
Hello @avinal 

Thanks a lot for this information. This made my general conception more clear. Would it be possible for you to work on this, or do I need to configure this from my side? 

I guess we can go ahead with a new branch and have the scripts separately. This would give us a lot more control.

**Comment by avinal** [comment]
Hi @HarshCasper, 
Since you want to create a whole new branch, we will need many people and remember whenever someone adds a new script he/she will need to add it to two places, script in main, and doc in another branch, if you are okay with it then we may start working. From your side,  you might want to decide the theme and generator and enable the gh-pages. Mostly sphinx with the read-the-docs theme is quite popular and you will see them everywhere.

**Comment by HarshCasper** [comment]
> Hi @HarshCasper,
> Since you want to create a whole new branch, we will need many people and remember whenever someone adds a new script he/she will need to add it to two places, script in main, and doc in another branch, if you are okay with it then we may start working. From your side, you might want to decide the theme and generator and enable the gh-pages. Mostly sphinx with the read-the-docs theme is quite popular and you will see them everywhere.

That's a sound opinion. We don't want to over-burden new contributors. I guess we can go with the other one right now. Let me know what theme we would like to finalize on. 

If you would like to get access to the repository, let me know.

**Comment by HarshCasper** [comment]
> I don't think access will be needed since I can open a pull request for any change, and its much safer when something goes through multiple eyes.
> 
> I would like to use Sphinx because it will be easy for newbies too and theme is not a problem, https://sphinx-themes.org/ , you can change themes anytime by changing few lines, without losing any content, since all themes have basic templates. Also to use all features all of the markdown will need to converted to reStructured Text, they work almost the same way,

Awesome. You can go ahead!

**Comment by avinal** [comment]
Hello @HarshCasper, I am starting to convert all readme files from `markdown` to `reStructuredText`. Just for safety purposes, I am keeping the actual Readme along with them. If everything works finally then we can remove all markdown in a pull request. But I am a bit confused, should I do this in a separate branch or main branch. First method will require newer files to be added again.

**Comment by avinal** [comment]
> 
> 
> Hello @HarshCasper, I am starting to convert all readme files from `markdown` to `reStructuredText`. Just for safety purposes, I am keeping the actual Readme along with them. If everything works finally then we can remove all markdown in a pull request.
> 
> Can you please create a new branch and enable GitHub pages and create another gh-pages branch?

@HarshCasper, please see this!

**Comment by avinal** [comment]
![image](https://user-images.githubusercontent.com/74113200/107414713-657d8e80-6b38-11eb-96ad-51b99490a8b4.png)

@HarshCasper, Please see if this looks right, I have converted all files to rst using bash scripting and pandoc, just need to connect and resolve issues, it will ready in  few days, I will soon be giving a live demo.

**Comment by HarshCasper** [comment]
> Hello @HarshCasper, I am starting to convert all readme files from `markdown` to `reStructuredText`. Just for safety purposes, I am keeping the actual Readme along with them. If everything works finally then we can remove all markdown in a pull request.
> 
> Can you please create a new branch and enable GitHub pages and create another gh-pages branch?

I will create the same by Evening. Apologies for missing this out in a drain of notifications.

**Comment by HarshCasper** [comment]
> ![image](https://user-images.githubusercontent.com/74113200/107414713-657d8e80-6b38-11eb-96ad-51b99490a8b4.png)
> 
> @HarshCasper, Please see if this looks right, I have converted all files to rst using bash scripting and pandoc, just need to connect and resolve issues, it will ready in few days, I will soon be giving a live demo.
> 
> P.S - This is a mobile version, just in case you wanted to see
> ![image](https://user-images.githubusercontent.com/74113200/107415177-0e2bee00-6b39-11eb-959a-5dfe3bcc9089.png)

Damn! This looks awesome 🚀

**Comment by avinal** [comment]
@HarshCasper, Thanks. This theme has more interesting features, one of the most awesome of them is inbuilt binder support, we can run scripts(mostly python) right on the website. I haven't tried them much but sounds cool.

**Comment by HarshCasper** [comment]
Hi @avinal 

Thanks for the efforts and contributions! 

I have created a branch named `rotten-scripts-website` and enabled GH-Pages over it. Let me know if you need anything else. 

Also as a gentle request, can you please create a new discussion thread and post all your progress over there? It would be easier, to take a look over the progress and let the other contributors share their opinions. Thanks for everything!

**Comment by avinal** [comment]
sure @HarshCasper, will do that by tomorrow.
