### ISSUE TITLE
Bash script to remove subtitles from Matroska files in a directory

### ISSUE THREAD

**Issue by KamalDGRT** [HarshCasper/Rotten-Scripts#658]
**Is your feature request related to a problem? Please describe.**
We tend to download video files. One of such container for video files is matroska or mkv. Sometimes the subtitles present in those mkv containers would be out of sync and it might be in language which we don't know. So, it would be cool to remove those subtitles and have a clean mkv file with just audio and video.

**Describe the solution you'd like**
A single bash script to traverse through the mkv files, remove the subtitles and meta tags and then place the clean mkv files in a separate folder.

**Describe alternatives you've considered**
 I considered using the MKVToolNixGUI, but when it come to batch removal, we have to manually add and remove each mkv file present in a directory. It was time consuming.

**Comment by KamalDGRT** [comment]
@HarshCasper, I would like to work on this issue.

**Comment by himanshu007-creator** [comment]
i would like to work on this issue
