### ISSUE TITLE
Email Validator using Powershell

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#661]
**Is your feature request related to a problem? Please describe.**
#633 motivated me to ponder with `.ps1` again. One of the first things I started using PowerShell for was Telnet, everyone should use Telnet actually as it a really powerful tool.

**Describe the solution you'd like**
A PowerShell script that can validate an email address. 

**Describe alternatives you've considered**
Python has a package for this, but it uses regex, which makes it an email format verifier, which in this case is useless.

**Comment by hack3r-0m** [comment]
this is not quite feasible out-of-the-box on most personal machines as port 25 is blocked by most ISPs, by probing MX records will only guarantee if the domain has some sort of mail server. An alternative solution can be to use the free version of some API like [mailboxlayer](https://mailboxlayer.com/documentation) which has a good rate limit on the free version

**Comment by vybhav72954** [comment]
I know that, in most client-server systems, port 25 and TELNET are considered vulnerable, so the argument that every email can not be verified stands, but if a email is verified, then it sure also exists is true at the same time.

**Comment by hack3r-0m** [comment]
i would also like to point out that every email verfied(using MX + VRFY(over port 25) ) does not imply it is deliverable
