### ISSUE TITLE
Merge 2 PDF using JS

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#662]
**Is your feature request related to a problem? Please describe.**
Recently a code to merge 2 pdf using Python was uploaded, following the same suite I believe we should have the same for 2 PDF as well.

**Describe the solution you'd like**
A `js` code to merge 2 PDFs.

**Describe alternatives you've considered**
There are multiple alternatives, but I believe that this code will maintain the aesthetics of the Repo.

**Comment by vybhav72954** [comment]
@HarshCasper Assign this if you think its good enough similarly #663

**Comment by kumarankm** [comment]
Hello,
Can I work on this issue?

**Comment by vybhav72954** [comment]
> Hello,
> Can I work on this issue?

This is after you already made a PR 8 hours ago 🤣 
Although as I completely forgot about this @HarshCasper assign him 😄 I will unassign myself

**Comment by kumarankm** [comment]
> > Hello,
> > Can I work on this issue?
> 
> This is after you already made a PR 8 hours ago 🤣
> Although as I completely forgot about this @HarshCasper assign him 😄 I will unassign myself

Sorry, I didn't read the guidelines properly😅. Later I come to know that first, we need to get assigned.
Anyway thanks😃

**Comment by vybhav72954** [comment]
@kumarankm Thank you for contributing, I did forget that this was assigned to me so it's my mistake too. There are many more unassinged issues, see if you can sort them.

Meanwhile, lets wait for @HarshCasper to review your PR

**Comment by kumarankm** [comment]
Thanks, @vybhav72954  . Sure I will check for unassigned issues. If you don't have a clear idea of what I did in this code you can check my blog in dev to. 
https://dev.to/kumarankm/merging-a-pdf-using-javascript-527i

**Comment by vybhav72954** [comment]
> @vybhav72954 Sure I will check for unassigned issues. If you don't have a clear idea of what I did in this code you can check my blog in dev to. 
> https://dev.to/kumarankm/merging-a-pdf-using-javascript-527i

Would love to through that :)

Although am not a maintainer nor a reviewer 😅
