### ISSUE TITLE
Amazon Price Tracker using JS

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#663]
**Is your feature request related to a problem? Please describe.**
There are multiple scripts in Python more suited for Javascript, this being one. Having scripts in multiple languages for similar problems makes a whole lot of sense and is definitely useful.

**Describe the solution you'd like**
An amazon scrapper/tracker for products.

**Comment by pritamp17** [comment]
sir, I would like to work on this issue. could you please assign it to me?

**Comment by HarshCasper** [comment]
> sir, I would like to work on this . could you please assign it to me?

Hello @pritamp17 

Issues are assigned on a First Come, First Serve Basis. There are plenty of Open Issues which you can take up.

**Comment by pritamp17** [comment]
@HarshCasper sir in the case when it is not assigned to anybody, then please assign this issue to me.

**Comment by vybhav72954** [comment]
@pritamp17 I will be opening a P for this today only, I doubt this will be assigned to you, sorry for that, you are encouraged to open more issues though

**Comment by haarsh01** [comment]
Hey, I am a GGSOC'21 participant. Can I work on this issue,? If it is open please assign it to me.

**Comment by vybhav72954** [comment]
@haarsh01 Sure thing!!!
