### ISSUE TITLE
Python Script to automatically add Captions to an image, using Deep learning

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#665]
**Is your feature request related to a problem? Please describe.**
Deep learning is an interesting field, so many useful things are possible.
A script to automatically come up with a sensible caption is always good.

**Describe the solution you'd like**
The `alt text` is an important attribute of an image, and every image should have one.
Using Deep learning/Machine learning it is possible to actually come up with that type of text automatically.

**Describe alternatives you've considered**
There are a few online caption suggestors, but they are either paid (after few free attempts) or straight-up nonsensical

**Additional context**
Deep Learning is preferred as it is faster for these kinds of activities.

**Comment by vybhav72954** [comment]
Lol this is so funny, Amazing Bug XD

**Comment by vybhav72954** [comment]
@HarshCasper Can you please see this PR, or else I will be unassigned once again XD. I will see whats causing this bug as well

**Comment by HarshCasper** [comment]
> @HarshCasper Can you please see this PR, or else I will be unassigned once again XD. I will see whats causing this bug as well

Sure. Reviewed and some tiny changes are suggested
