### ISSUE TITLE
Adding a Python script to find location of IP of Owner

### ISSUE THREAD

**Issue by pankaj892** [HarshCasper/Rotten-Scripts#666]
Hello @HarshCasper i would like to add a python script which finds the location of a user based on his IP adress
please assign me on this issue

**Comment by HarshCasper** [comment]
> Hello @HarshCasper i would like to add a python script which finds the location of a user based on his IP adress
> please assign me on this issue

Can you give more clarity on how would your script work?

**Comment by pankaj892** [comment]
My script would fetch the ip address of user and return the ip address along with details like city,timezone,postalcode etc..

**Comment by HarshCasper** [comment]
> My script would fetch the ip address of user and print the ip address along with details like city,timezone,postalcode etc..

Assigned the Issue. Let me know the Open-Source Program you are participating in, and I will put apt tags as well.

**Comment by pankaj892** [comment]
@HarshCasper I am participating in Dwoc as well as Swoc(Script winter of Code)
