### ISSUE TITLE
Make PyLint action more strict

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#674]
**Describe the bug**
Recently I noticed, that the moderators have started paying more emphasis on advanced styling techniques like `docstrings` and `shebang`, the current PyLint Action, made by me is deliberately more tolerant (I thought that we were ignoring advanced styling), considering maintainers are all in for Good staying, the PyLint action needs to be updated.

**To Reproduce**
1. Go to Any new PR
2. Check if Docstrongs, shebang, EOF are properly formatted or not
3. If not, see the PyLint Action Result
4. No error displayed

**Expected behavior**
Although this is expected, cause the Action was made to be tolerant, it's time we get rid of that, and make it more strict.

**Comment by vybhav72954** [comment]
@HarshCasper I will wait for you to assign me this as I want you to see this beforehand.

**Comment by HarshCasper** [comment]
@vybhav72954 Your Contribution to this Project has been unparalleled. You have helped me set up a lot of things and further enhance stuff, that I never expected. 

I trust your judgement enough so please feel free to take up any Issue you create by your ownself. Just make sure you don't have too much on your plate at one time.

**Comment by vybhav72954** [comment]
I know am having too many stale issues, fixing them ASAP
