### ISSUE TITLE
Remove all Images from the Repository

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#677]
## Description 

Remove all Images from the Repository. If you would have noticed, while `git clone`, that this repository is kinda HUGE. And if I look back at the reasons, it might due to some stupid requirements that I put over it in the initial stages. 

One of them included having Images and GIFs to show the Code Preview or the Script demonstration. As more Scripts were added, this became huge and redundant for us in the longer run. 

This Issue would require to remove all images from the Project and replace them with Imgur Links. Imgur has this nice interface [here](https://imgur.com/upload) to upload Images and then reference them on Markdown, for JPEG/PNG/GIF.

**Comment by sakshikhachane** [comment]
@HarshCasper I would like to work on this issue. Can you assign me this issue?

**Comment by Zircoz** [comment]
@HarshCasper I am also interested in doing this if @sakshikhachane wanna/needs to share the task

**Comment by HarshCasper** [comment]
Hi @sakshikhachane and @Zircoz 

Thanks for requesting to take up. Since the work-load is kind of huge, I don't want one to take care of the entire thing. So its best to split the work. 

I would suggest anyone of you find the directories which contain an Image and mention it here. And then you guys can split it up in batches and make PRs for them. Every PR would be individually marked, so be ensured that you will get ample points for all the manual work you are doing. 

Or perhaps you can write a script for that as well 😄

**Comment by a-k-r-a-k-r** [comment]
I would also like to work on this issue, incase it is not solved till now

**Comment by vybhav72954** [comment]
@HarshCasper I really wanted to do this but was out of the station, hence wasn't able to `assign` it to myself. Hopefully, this will reduce the size of the Repo

**Comment by Zircoz** [comment]
@sakshikhachane With python, I have created a log of files & folders which have images on this repo. Please ping me in any one of these places to discuss about division of work: Discord: Zircoz#1053 , [Telegram](https://t.me/Zircoz) , [Discord DWOC RottenScript Channel](https://discord.gg/T2YWhcGr) or lmk if any instant messaging platform you may prefer.

**Comment by Zircoz** [comment]
@HarshCasper I can edit the readme's text if it makes them better, right? Like in `python/heat your system` 's readme, the guy has only mentioned that it can drain battery; while doing that for longer periods can also reduce the life of hardware. So, i guess i can add it ?

**Comment by HarshCasper** [comment]
> @HarshCasper I can edit the readme's text if it makes them better, right? Like in `python/heat your system` 's readme, the guy has only mentioned that it can drain battery; while doing that for longer periods can also reduce the life of hardware. So, i guess i can add it ?

Feel free to do that 👍

**Comment by shivangisahay14** [comment]
I would like to work on this issue.

**Comment by vybhav72954** [comment]
@HarshCasper May I solve this, please?

I was going to hunt for dead code and the images are bugging me out 🤦🏻 

@Zircoz Else you can tell me whats the progress

**Comment by Zircoz** [comment]
> @HarshCasper May I solve this, please?
> 
> I was going to hunt for dead code and the images are bugging me out 🤦🏻 
> 
> @Zircoz Else you can tell me whats the progress

My bad, I will complete this in next 7 days or before. I have done around 76ish images and i have it marked somewhere on discord

**Comment by vybhav72954** [comment]
@Zircoz Would it be Ok, If you do the images, and I do the READMEs?

I was hunting for Deadcode anyways, and also as the website deployment is due, I can get the READMEs done by today only

**Comment by Zircoz** [comment]
@vybhav72954 what has to be done in readmes?

**Comment by vybhav72954** [comment]
As you can see in #755

Avinal has setup an awesome static website.

The READMEs which are not following the template of this Repo are causing problems.

I was planning to update the READMEs according to the Template

**Comment by HarshCasper** [comment]
@Zircoz and @vybhav72954 Please feel free to create a new discussion thread where you can coordinate the work!

**Comment by Zircoz** [comment]
Ah tiny update: the work is almost done and will be completed by tomm morning if everything in my life works as planned 😎

**Comment by vybhav72954** [comment]
@Zircoz That's awesome 👍🏻
