### ISSUE TITLE
Building a network scanner in python

### ISSUE THREAD

**Issue by pritamp17** [HarshCasper/Rotten-Scripts#678]
## This script will give IP and MAC-ADDRESS of devices connected to the same network as yours.

**Comment by pritamp17** [comment]
please assign this issue to me under SWOC

**Comment by ShristiJalan** [comment]
@pritamp17 you can work on this issue

**Comment by pritamp17** [comment]
![issue](https://user-images.githubusercontent.com/65030567/104085703-760bc200-5277-11eb-887f-c870b18360aa.png)

@HarshCasper sir while submitting PR I am getting these issues, could you please help me how to solve these?
