### ISSUE TITLE
Creating-Emoji-Using-Python

### ISSUE THREAD

**Issue by Ayush7614** [HarshCasper/Rotten-Scripts#682]
# Aim

- Creating different-different emojis using python module

# Details

Fortunately ,python have multiple way using which we can print emojis :
Unicode
CLDR names
emoji module
Unicodes:
To use Unicodes , we need to replace “+” with “000” from the list of unicodes .
For example :
“U+1F600” will become “U0001F600” and prefix the unicode with “\” and print it.
CLDR names:
Emojis have CLDR short names which can also be used.

![image](https://user-images.githubusercontent.com/67006255/103727358-199f6d00-5001-11eb-9549-fe03aaa6f7e7.png)
In above code , first line used CLDR names and second line used Unicode.

- emoji module:
Emojis can also be implemented by using the emoji module provided in Python. To install it run the following in the terminal.
pip install emoji
emojize() function requires the CLDR short name to be passed in it as the parameter. It then returns the corresponding emoji. Replace the spaces with underscore in the CLDR short name.
![image](https://user-images.githubusercontent.com/67006255/103727426-3d62b300-5001-11eb-9270-1991b533ce7c.png)

**Comment by Ayush7614** [comment]
@HarshCasper sir plss review it and assigned me this issue this is for this is for DWOC

**Comment by Ayush7614** [comment]
@HarshCasper plss sir review it and assigned me this issue

**Comment by Ayush7614** [comment]
@HarshCasper sir plss review it and assign me this issue

**Comment by HarshCasper** [comment]
Why is a Script needed for it?

**Comment by Ayush7614** [comment]
Sir so what you think it is a valid issue or not according to your project rotten scripts but emoji using python is a very common in python that is not in the project so thats why i will create a issue so if you are like it then plss assign me under DWOC

**Comment by Ayush7614** [comment]
Script like we have to use three module of python here to create a emoji

**Comment by anirudhsai20** [comment]
Hi @HarshCasper . Please allow me to work on this issue under SWOC .

**Comment by HarshCasper** [comment]
@Ayush7614 and @anirudhsai20 

I don't find any merit for having a script for creating emoji. Maybe I will tag other maintainers: @sohamsshah @seema1711 who can better find the purpose behind it.

**Comment by sohamsshah** [comment]
@Ayush7614 and @anirudhsai20 

I agree with Harsh. This piece of code might be used in some small chunk of an application; but independent script for implementation of this doesn't make much sense. Maybe you can brainstorm and modify the script so to provide value?
Eg. "A script that automatically adds emoji based on Sentiment of the text provided" - can be a legible script. You can find similar sort of projects based on this issue OR can work on some other interesting issues. Thanks for taking interest for this :)

**Comment by sohamsshah** [comment]
Since this script addition perhaps doesn't provide any utility to the project; I am closing this issue. There are a lot of other interesting issues OPEN on the repo; or you can also come up with idea and we can discuss as well for contributions.
