### ISSUE TITLE
Script to generate Fake Data

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#69]
## AIM

Python Script to create Fake Numerical Data for Data Modelling and save it into an ```npz``` File.

## Languages

- Python

## Details

Often during Data Modelling, we need to generate Fake Data to create Basic Models. You can automate this process by making use of ```Numpy``` and ```Random``` Modules to generate fake numerical data and save it into a ```npz``` file.

**Comment by mohitacecode** [comment]
Please assign this issue to me @HarshCasper

**Comment by HarshCasper** [comment]
I have assigned this to you @mohitacecode 

You can start working on this 🙌🤗

**Comment by HarshCasper** [comment]
Are you working on this @mohitacecode ?

**Comment by mohitacecode** [comment]
Will submit a pr soon @HarshCasper .
