### ISSUE TITLE
Create a Word Cloud

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#70]
## AIM

Create a Script to create a World Cloud

## Languages

- Python
- Javascript

## Details

Take a Text File, preprocess the Content by removing Stopwords and Punctuation and create a Wordcloud out of them. In Python, you can make use of `numpy`, `Pillow`, and `matplotlib` to create a Word Cloud and save it as a Picture.

**Comment by Prahitha** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
I have assigned you the Issue @Prahitha

You can start working on this
