### ISSUE TITLE
Develop a Script to download Quora Bookmarked Answers

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#71]
## AIM

Create a Script to scrap the Bookmarked Answers on Quora and save them as a PDF.

## Languages

- Python
- Javascript

## Details

I often Bookmark Answers on Quora which I can refer to later. It would be great for me if I can actually download all my Bookmarked Answers as PDFs which I can refer to later.

**Comment by Sanketwable** [comment]
I want to work on this

**Comment by HarshCasper** [comment]
I have assigned this to you @Sanketwable

**Comment by kaustubhgupta** [comment]
@HarshCasper I want to work on this issue. I have done the previously assigned issue of LinkedIn video download

**Comment by HarshCasper** [comment]
Assigned to you @kaustubhgupta

**Comment by kaustubhgupta** [comment]
@HarshCasper made PR #313
