### ISSUE TITLE
creation of discord bot using python

### ISSUE THREAD

**Issue by Sloth-Panda** [HarshCasper/Rotten-Scripts#710]
would like to make a discord bot using python @HarshCasper

**Comment by Dhriti-Roy** [comment]
Hey, Can I start working on it.

**Comment by HarshCasper** [comment]
Hello @Sloth-Panda and @Dhriti-Roy 

Appreciate your enthusiasm to work on this. Can you please let me know what would be the purpose of the Discord Bot?

**Comment by Sloth-Panda** [comment]
@HarshCasper my thought is quite generic about it like implementing that on a discord channel basically for moderating that server  or if you have any server can be implemented there too.

**Comment by pawankm21** [comment]
I would like to work on this issue, I am already half way through in making a discord bot
