### ISSUE TITLE
Add a python script to detect the edges of the image

### ISSUE THREAD

**Issue by vaishnavi-1** [HarshCasper/Rotten-Scripts#711]
I will add a python script that will act as canny edge detector and detect the edges of the images. I will use opencv for detecting the edges. I am a participant in DWOC and want to contribute. @HarshCasper Kindly, add the labels and please assign this issue to me.

**Comment by vaishnavi-1** [comment]
\assign

**Comment by HarshCasper** [comment]
> I will add a python script that will act as canny edge detector and detect the edges of the images. I will use opencv for detecting the edges. I am a participant in DWOC and want to contribute. @HarshCasper Kindly, add the labels and please assign this issue to me.

Looks interesting. Assigned you the Issue to see the final outcome

**Comment by shivangisahay14** [comment]
I would like to contribute to this issue.

**Comment by vaishnavi-1** [comment]
> I would like to contribute to this issue.
@shivangisahay14 I am already working on this issue and it will be done by tomorrow....Kindly, look at other issues.

**Comment by Dhanush2612** [comment]
@vybhav72954 
May I contribute to this issue?

**Comment by vybhav72954** [comment]
Sounds like a plan
Feel free to ping me in case you have troubles
**Assigned**

**Comment by Dhanush2612** [comment]
@vybhav72954 
Are there any specific guidelines like the files should be in .ipynb format or .py format.
Also to add a readme file?

**Comment by vybhav72954** [comment]
[Readme Template](https://github.com/HarshCasper/Rotten-Scripts/blob/master/TEMPLATE_README.md)

Raw python file is a must.
Notebook depends upon you, you can add one if you want to.

**Comment by Dhanush2612** [comment]
@vybhav72954 
Kindly check my PR #912

**Comment by Dhanush2612** [comment]
@vybhav72954 
I have created new PR as per your requirements.
Kindly check PR #937

**Comment by tanishq-arya** [comment]
Please assign me this issue under Gssoc.
