### ISSUE TITLE
Automation of Google Chrome Dino Game 

### ISSUE THREAD

**Issue by oshi36** [HarshCasper/Rotten-Scripts#713]
I will be using python and its libraries such as pyautogui  and pillow to automate chrome dinosaur game with NLP to teach dino about the hurdles coming in between.

**Comment by HarshCasper** [comment]
Thanks for taking up this Issue @oshi36 

Can you please let me know if you are participating on behalf of some OSS Program like SWoC or DWoC?

**Comment by oshi36** [comment]
@HarshCasper yes, I am a participant of DWoC.
