### ISSUE TITLE
Create a Contribution Guideline for Python

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#714]
## Description 

Create a Contribution Guideline for Python. The Contribution Guideline should help new Contributors to understand all the necessary steps before raising a PR. It should broadly cover these parts: 

- Using tools like PyLint for Code Quality Check 
- Making proper directories, naming conventions and making the Python README changes
- Adding Screenshot Images through Imgur 
- Formatting the Script README for a better purpose
- Usage of `.env` for API Keys and making proper commits 

The Doc should be named as `CONTRIBUTION-GUIDELINE.md` and would live in the Python directory. Adding screenshots for the above points would be helpful, but not needed.

**Comment by vybhav72954** [comment]
@HarshCasper Can i take this, rather make an extension here.

SO here is what my plan was ----

I was planning to make a new `styling guideline` for the repo, one thing I have noticed is, people don't use auto styling code tools, so the guideline I was planning to make was related to thin only.

Although your idea is a bit different, we can incorporate them together as well.

**Comment by vybhav72954** [comment]
The reason why i want to do this is, I have made several styling actions for this Repo, but users actually don't care a lot about failing actions (I have an idea to sort this as well), so it would be better to make a guide which will ensure that we reduce those errors in action in the first pplace.

**Comment by shivangisahay14** [comment]
I would like to contribute
