### ISSUE TITLE
Irregular Directory Names

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#718]
This is in relation to #688 

While looking for dead code, I found multiple Repos with names that don't align with the naming convention.

I think we should change them for the sake of aesthetics.
Considering we have a new `README` as well now, one will have to change the Links in it as well.

@HarshCasper If you think that we need to rectify them, you can assign me or anyone else for that matter, would be great if this is fixed ASAP as the last thing we need is merge conflicts because the name of directories has changed.

**Comment by HarshCasper** [comment]
> This is in relation to #688
> 
> While looking for dead code, I found multiple Repos with names that don't align with the naming convention.
> 
> I think we should change them for the sake of aesthetics.
> Considering we have a new `README` as well now, one will have to change the Links in it as well.
> 
> @HarshCasper If you think that we need to rectify them, you can assign me or anyone else for that matter, would be great if this is fixed ASAP as the last thing we need is merge conflicts because the name of directories has changed.

Feel free to raise a PR for the same. Also add the naming conventions in the Guidelines 👍

**Comment by vybhav72954** [comment]
@HarshCasper naming Conventions are in Guidelines already

Can i have SWOC or MWOC label as well?
