### ISSUE TITLE
Create a Script to scrap Wallpaper from Reddit and set your Desktop Wallpaper

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#72]
## AIM

Create a Script to scrap Wallpaper from Reddit and set your Desktop Wallpaper

## Languages

- Python

## Details

`r/wallpapers` host a wide collection of Wallpapers. In this Script, you can scrap the top-rated Wallpaper and set it as the Desktop Wallpaper.

**Comment by Aditya1001001** [comment]
I would like to work on this.

**Comment by HarshCasper** [comment]
Hello @Aditya1001001 

Thanks for your interest in this Issue. I just wanted to check if you are a participant in ```SCI-2020```

**Comment by Aditya1001001** [comment]
I am afraid I'm not, is this repo exclusively for ```SCI-2020```?

**Comment by HarshCasper** [comment]
@Aditya1001001 Issues tagged with ```SCI-2020``` is exclusive for the specific participants. This Repo is not exclusive.

If you want to work on any Issue, check for Issues that are `Open-to-All`. If you have something specific in mind, please make an Issue and I will promptly assign it to you.

**Comment by Prahitha** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
I have assigned this to you @Prahitha
