### ISSUE TITLE
Discovering Subdomains with Python

### ISSUE THREAD

**Issue by Ayush7614** [HarshCasper/Rotten-Scripts#723]
**Is your feature request related to a problem? Please describe.**
Discovering Subdomains with Python

**Details**
Python Script to List all the subdomains of a website and stored it in a CSV file.

**Comment by Ayush7614** [comment]
We need to create a subdomain.txt file and run a dictonary attack. We added a subdomain.txt file with popular 1000 subdomains and you can find more subdomain.txt files..

**Comment by Ayush7614** [comment]
@HarshCasper sir plss assign me this issue under DWOC

**Comment by vybhav72954** [comment]
@tanishq-arya update within 2 days please

**Comment by tanishq-arya** [comment]
@vybhav72954 Please review my PR. Let me know if any changes are required.
