### ISSUE TITLE
Find Unfollowers on Github

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#732]
## Description 

There are a lot of people who follow people and unfollow them as well, later. While we don't exactly know, under what circumstances is the `Unfollow` button clicked, but we for sure, don't know who unfollowed us. 

Build a Script/CLI that can track the Usernames who unfollowed you recently on Github. 

## Languages 

- Python
- Javascript
- Golang
- BASH

**Comment by vismitap** [comment]
Hey! I would like to work on this issue using javascript as part of SWoC and DWoC. Please assign this issue to me!

**Comment by vismitap** [comment]
Hey! The current directory structure is as follows for Javascript:
![image](https://user-images.githubusercontent.com/47056243/107823253-7e3eac00-6da5-11eb-969c-6af9b13234bf.png)
Should I make a new folder called Github Unfollowers or add the files in the Who_Don't_Follow_You directory itself which is actually for Instagram and edit the readme?
Current readme for Who_Don't_Follow_You:
![image](https://user-images.githubusercontent.com/47056243/107823419-c4940b00-6da5-11eb-8899-f84b5269a093.png)
Edited Readme can contain a sentence like :
`A Javascript Code which allows you to check who is not following you back on various socials.`

**Comment by vismitap** [comment]
Please add level-X tag also to this! 😅
