### ISSUE TITLE
Export Notion Page as a Website

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#733]
## Description 

Convert a Notion Page as a Static Website using a handy Script at use. Find some inspiration [here](https://benborgers.com/posts/50) and [here](https://github.com/leoncvlt/loconotion). 

## Languages 

- Python
- Javascript

**Comment by vybhav72954** [comment]
I can do this one @HarshCasper

**Comment by vybhav72954** [comment]
Justa small request beforehand, as am participating in MWoC, kindly see the labels accordingly. 

Moreover my 4  PRs are open, might be 5. Please Review them

**Comment by Nidhi-2000** [comment]
Hey, I am GSSOC'21 participant can you please assign me this issue

**Comment by vybhav72954** [comment]
@Nidhi-2000 Updates?

**Comment by ksonawat007** [comment]
Is this issue still open? I am a newbie and want to work on this.
