### ISSUE TITLE
Distance calculating app.

### ISSUE THREAD

**Issue by pritamp17** [HarshCasper/Rotten-Scripts#736]
Is your feature request related to a problem? Please describe.
An app that can show the distance between your current position(located using user's current IP) and user searched position on Map.

Additional context
This app will have a frontend too, to show searched position on the map.

**Comment by pritamp17** [comment]
please assign this to me in Python, under SWOC.

**Comment by HarshCasper** [comment]
> Is your feature request related to a problem? Please describe.
> An app that can show the distance between your current position(located using user's current IP) and user searched position on Map.
> 
> Additional context
> This app will have a frontend too, to show searched position on the map.

Why do we need a Frontend when we don't even have GUI Apps in the Project?

**Comment by Aayush-hub** [comment]
@HarshCasper Can I work on this under Mwoc and Swoc labels?
 I will make GUI using python which takes input of locations and give result of distance between locations.

**Comment by HarshCasper** [comment]
> @HarshCasper Can I work on this under Mwoc and Swoc labels?
> I will make GUI using python which takes input of locations and give result of distance between locations.

@Aayush-hub Can you see my above message which states: `Why do we need a Frontend when we don't even have GUI Apps in the Project?`

**Comment by Aayush-hub** [comment]
> > @HarshCasper Can I work on this under Mwoc and Swoc labels?
> > I will make GUI using python which takes input of locations and give result of distance between locations.
> 
> @Aayush-hub Can you see my above message which states: `Why do we need a Frontend when we don't even have GUI Apps in the Project?`

@HarshCasper  So, if project demands working on terminal, I can make a script which works on terminal. Can I go ahead sir?

**Comment by HarshCasper** [comment]
> > > @HarshCasper Can I work on this under Mwoc and Swoc labels?
> > > I will make GUI using python which takes input of locations and give result of distance between locations.
> > 
> > 
> > @Aayush-hub Can you see my above message which states: `Why do we need a Frontend when we don't even have GUI Apps in the Project?`
> 
> @HarshCasper So, if project demands working on terminal, I can make a script which works on terminal. Can I go ahead sir?

Can you give me a brief gist on how a CLI App will work in this case?

**Comment by Aayush-hub** [comment]
@HarshCasper The app I made is helpful is calculating distance between two geolocations in kilometers. It uses python geopy module. It asks user to enter starting and ending location, and converts it into locations longitude and latitude to calculate distance.

#### Sample Screenshot:
![Capture](https://user-images.githubusercontent.com/65889104/108699104-d9ea0180-752a-11eb-8d75-283b6ed6e957.png)

**Comment by Aayush-hub** [comment]
@HarshCasper Can I go ahead with this script??

**Comment by HarshCasper** [comment]
Sure @Aayush-hub
