### ISSUE TITLE
Script to display top posts from Hashnode

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#738]
# Description

Add a Script to display top posts from Hashnode. Take a look at the Hashnode API [here](https://engineering.hashnode.com/introducing-hashnode-graphql-api-public-beta-cjydzvp59001q2gs1b5zxaeaf) and the Playground [here](https://api.hashnode.com/). 

The Script should ideally fetch the top posts that are trending on Hashnode as of now. You can also use flags to pass arguments for various posts trending in specific topics on Hashnode.

## Language

- [X] Go
- [X] Javascript
- [X] Python

## Checklist:

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Hashnode Top Posts Script | Fetch top posts trending on Hashnode with Hashnode API | MWOC, Python, Javascript, Golang | |

**Is your feature request related to a problem? Please describe.**: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**: A clear and concise description of what you want to happen.

**Additional context**: Add any other context or screenshots about the feature request here.

**Comment by lopeselio** [comment]
Can I take this up  for Javascript?

**Comment by HarshCasper** [comment]
> Can I take this up for Javascript?

Just use `/assign` and a bot will assign you this.

**Comment by vybhav72954** [comment]
@lopeselio How are you? Any updates?
