### ISSUE TITLE
Script to generate GIF

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#74]
## AIM

Create a Script to generate GIFs.

## Languages

- Python
- Javascript
- Golang

## Details

Take a Video Input and a Query from a user highlighting the portion whose GIF has to be generated. Generate a GIF using that Query. You can make use of the `ffmpeg` and `pysrt` library for that purpose.

**Comment by Sanketwable** [comment]
I want to work on this.

**Comment by HarshCasper** [comment]
I have assigned this to you @Sanketwable 

You can start working on this 🙌🤗

**Comment by HarshCasper** [comment]
@Sanketwable Are you working on this?

**Comment by Sanketwable** [comment]
yes I will make PR by today

**Comment by Sanketwable** [comment]
close
