### ISSUE TITLE
Leaderboard update for MWoC

### ISSUE THREAD

**Issue by RutvikJ77** [HarshCasper/Rotten-Scripts#744]
# Description

Create a labels.yml file in github/workflow with the required code. Please check out this link for more reference https://mexili.github.io/winter_of_code/#/winter_of_code?id=scoring-system-for-winter-of-code-mentor-requirements

## Language

- [ ] Bash
- [ ] Go
- [ ] Javascript
- [ ] Powershell
- [ ] Python
- [x] Other (yml)

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| labels | Github workflow for leaderboard | feature | |

**Comment by vybhav72954** [comment]
@RutvikJ77 This is not an additional script but a feature, I know that you are an avid contributor. Feature Request template if used wouldn't have caused these cluttered labels 😄

**Comment by RutvikJ77** [comment]
Oh! My bad 😅. I get it now. One more thing, I have one more script to contribute. It basically creates stop-motion video from the input file. So that would be counted as an additional script right? Additionally, just a suggestion while creating this description I got a bit confused, maybe you can make them clutter-free? 😅

**Comment by RutvikJ77** [comment]
Now I get it unnecessary labels are being added. A grave mistake on my front 😓

**Comment by HarshCasper** [comment]
No worries @RutvikJ77 

We want everyone to learn here and contribute as well! 

I personally learn a lot from all your PRs so keep them coming. Coming to the other questions, please send PRs from different branches which makes it easy to track and mitigates merge conflicts.

**Comment by RutvikJ77** [comment]
> No worries @RutvikJ77
> 
> We want everyone to learn here and contribute as well!
> 
> I personally learn a lot from all your PRs so keep them coming. Coming to the other questions, please send PRs from different branches which makes it easy to track and mitigates merge conflicts.

Got it! Thanks 👍 so should I update the current ones?

**Comment by vybhav72954** [comment]
> Now I get it unnecessary labels are being added. A grave mistake on my front 😓

Its fine actually, cause o your contribution I noticed a small problem in the YML files that I have configured, thanks for that, keep contributing 😀
