### ISSUE TITLE
Script to collect Facebook Timeline Posts

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#745]
# Description

Add a Python Script to collect the links and details of all Facebook Timeline Posts using the [Facebook Graph API](https://developers.facebook.com/docs/graph-api/). Data should be stored in a CSV for better access and usage.

## Language

- [X] Python
- [X] Javascript
- [X] Golang

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Facebook Timeline Collector | Collect Details and Links of everything on your Facebook Timeline | MWOC, Python, Javascript, Golang, Medium |  |

**Comment by subhangi2731** [comment]
can you assign this issue to me?

**Comment by Riddhima-jain** [comment]
Hey, can you assign this issue to me?  ( I'm a participant of GSoc'21 )

**Comment by DiegoCaraballo** [comment]
I am waiting for the approval of the following PR: [#859](https://github.com/HarshCasper/Rotten-Scripts/pull/859)

I would like to solve the following challenge if possible.

Regards

**Comment by HarshCasper** [comment]
> I am waiting for the approval of the following PR: [#859](https://github.com/HarshCasper/Rotten-Scripts/pull/859)
> 
> I would like to solve the following challenge if possible.
> 
> Regards

Please go ahead! Thanks a lot for contributing.

**Comment by vybhav72954** [comment]
Hey @DiegoCaraballo Hope you are doing well. Any updates from your side?

**Comment by DiegoCaraballo** [comment]
Hello @vybhav72954 
Sorry, but I have little time.
You can leave it free for someone else to do it.
As soon as I have more time I will continue to collaborate.
Regards!

**Comment by HarshCasper** [comment]
Hi @DiegoCaraballo 

No worries at all :) 

You can have this issue and contribute once you are free with respect to your schedule. You have been a valued contributor and we truly appreciate your efforts and contributions!

**Comment by DiegoCaraballo** [comment]
Thanks @HarshCasper , I'll be back soon.
