### ISSUE TITLE
Add Mexili Winter of Code to Open_Source_Events

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#750]
## Description 

Add Mexili Winter of Code to `Open_Source_Events`.

**Comment by Saransh-cpp** [comment]
Hi there! I am new here:), I'd like to take this issue as a part of MWoC.

**Comment by HarshCasper** [comment]
> Hi there! I am new here:), I'd like to take this issue as a part of MWoC.

Sure. Next time, if you are the first on the Issue thread and would like to take up the Issue, just comment: `/assign` and a Bot will assign you that automatically :)

**Comment by Saransh-cpp** [comment]
Okay! Thanks for the tip! I'll start working.
