### ISSUE TITLE
Add Cross WOC to Open_Source_Events

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#751]
## Description 

Add Cross Winter of Code to `Open_Source_Events`.

**Comment by Ayush7614** [comment]
Plsss assign me this issue

**Comment by HarshCasper** [comment]
Are you a Cross Winter of Code Participants @Ayush7614 ? 

If yes, please use `/assign` to auto-assign the Issue 😉

**Comment by Ayush7614** [comment]
> Are you a Cross Winter of Code Participants @Ayush7614 ?
> 
> If yes, please use `/assign` to auto-assign the Issue 😉

Yess i am Participant

**Comment by vybhav72954** [comment]
@Ayush7614 You recently closed the PR, you need any help? or shall I assign this to somebody else?

**Comment by vybhav72954** [comment]
@HarshCasper Am doing this personally, the event has finished if am not wrong XD
