### ISSUE TITLE
Script to scrap Twitter Data

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#752]
# Description

Add a Script to scrap Twitter Data in a neat-CSV file with the following fields: 

1. Tweets 
2. Retweets
3. Likes
4. Pinned (if present)
5. Hashtags, Videos, Photos

## Language

- [X] Go
- [X] Javascript
- [X] Python

## Checklist:

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Twitter Scrapper | Scraps everything off your Twitter timeline | MWOC, Python, Javascript, Golang, enhancement | |

**Comment by Sukriti-sood** [comment]
I want to work in this issue , Still I only know javascript .

**Comment by HarshCasper** [comment]
> I want to work in this issue , Still I only know javascript .

You can work on it only using Javascript :) 

Please have a look at our [Style Guidelines](https://github.com/HarshCasper/Rotten-Scripts/blob/master/STYLE_GUIDELINES.md) if you are working on it!

**Comment by DiegoCaraballo** [comment]
Hello @HarshCasper 
I would like to work with this issue in Python.
Would the extraction be for a username?

**Comment by HarshCasper** [comment]
> Hello @HarshCasper
> I would like to work with this issue in Python.
> Would the extraction be for a username?

Sure. Yes. 

The extraction should be from the Username. Assigning you the same :)

**Comment by DiegoCaraballo** [comment]
Thanks @HarshCasper 
Can I work with selenium or does it have to be with a particular library?
Regards!

**Comment by HarshCasper** [comment]
> Thanks @HarshCasper
> Can I work with selenium or does it have to be with a particular library?
> Regards!

Please feel free to use anything :)

**Comment by Sukriti-sood** [comment]
@HarshCasper In the Twitter script do we need to download a video or need the link of video

**Comment by HarshCasper** [comment]
> @HarshCasper In the Twitter script do we need to download a video or need the link of video

Link is fine, since we are storing everything in a CSV.

**Comment by DiegoCaraballo** [comment]
Hello @HarshCasper @Sukriti-sood 
I am already working on this, but I have some confusion with the expected result.
What exactly would be the desired output for each of the fields?
Thanks

**Comment by HarshCasper** [comment]
> Hello @HarshCasper @Sukriti-sood
> I am already working on this, but I have some confusion with the expected result.
> What exactly would be the desired output for each of the fields?
> Thanks

Having a CSV file with these fields would be great: 

1. Tweets 
2. Retweets
3. Likes
4. Pinned (if present)
5. Hashtags, Videos, Photos

We don't need to download all of that. Having their URLs would simply do the trick

**Comment by DiegoCaraballo** [comment]
Hello @HarshCasper 
The only thing I am missing is the hashtag, what do you mean by that?
Is there a place on Twitter that shows the hashtags that a particular user has used?
Regards

**Comment by Sukriti-sood** [comment]
> Hello @HarshCasper
> The only thing I am missing is the hashtag, what do you mean by that?
> Is there a place on Twitter that shows the hashtags that a particular user has used?
> Regards

what I understand is In particular tweet what hashtags are used like #100daysofCode.

**Comment by Sukriti-sood** [comment]
@HarshCasper  In the tweet video , some of the video urls are not working @DiegoCaraballo  Do you also face this issue.

**Comment by DiegoCaraballo** [comment]
> > Hello @HarshCasper
> > The only thing I am missing is the hashtag, what do you mean by that?
> > Is there a place on Twitter that shows the hashtags that a particular user has used?
> > Regards
> 
> what I understand is In particular tweet what hashtags are used like #100daysofCode.

Hello @Sukriti-sood @HarshCasper 
Perhaps I have misunderstood the issue.
I start the solution from a user, example: @DiePyCar (Twitter)
From this user I extract the Tweets, Retweets, Likes, Pinned, Videos, Photos, but I don't understand the hashtag part.

**Comment by DiegoCaraballo** [comment]
> @HarshCasper In the tweet video , some of the video urls are not working @DiegoCaraballo Do you also face this issue else I am doing wrong.

For this part of Issue I use the Twitter API and had no problems with the Photos and Videos links. At least the ones I could review.

**Comment by HarshCasper** [comment]
Hi @DiegoCaraballo 

I was looking for a solution to have the Hashtags scrapped as well. This can be used to track and analyze the most common hashtags that the person uses. For example, many Developers use hashtags like #100DaysOfCode, #Javascript and more. 

If the Client or the API that you are using, does not provide that feature, you can skip that part. Or you can process the tweet and extract out the hashtags :)

**Comment by DiegoCaraballo** [comment]
@HarshCasper ahh ok.
But would the hashtag be in the same column of the CSV as the photos and videos?
¿O el hashtag, las fotos y los videos serían 3 columnas diferentes?
Example: 
**Hashtags, Videos, Photos**
Link Video
Link Video
Link Photo
#hashtag 
#hashtag
#hashtag

**Comment by HarshCasper** [comment]
> @HarshCasper ahh ok.
> But would the hashtag be in the same column of the CSV as the photos and videos?
> Or would the hashtag, photos, and videos be 3 different columns?
> Example:
> **Hashtags, Videos, Photos**
> Link Video
> Link Video
> Link Photo
> #hashtag
> #hashtag
> #hashtag

They can be different columns!

**Comment by DiegoCaraballo** [comment]
Hello @HarshCasper 
Before I submit the pull request, do I need to modify the Python README.md file?
Do I add it in alphabetical order?
And should I change the numbering of the following?
Thanks!

**Comment by HarshCasper** [comment]
> Hello @HarshCasper
> Before I submit the pull request, do I need to modify the Python README.md file?
> Do I add it in alphabetical order?
> And should I change the numbering of the following?
> Thanks!

Please don't update it now. I have realized that it is unfriendly for new contributors to update them. I will soon create a way to have it flexible without caring about alphabetical order and more. You can make the PR (Excited to have it) :)

**Comment by DiegoCaraballo** [comment]
Hello @HarshCasper 
I have uploaded my Pull Request, but I have had some errors. Could you clarify what it is?
Thanks

**Comment by HarshCasper** [comment]
> Hello @HarshCasper
> I have uploaded my Pull Request, but I have had some errors. Could you clarify what it is?
> Thanks

Please ignore them for now.
