### ISSUE TITLE
Github Actions: Auto-Close Issues if the PR is merged

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#757]
# Description

In many of the cases, I found that the Issues are not closed when the PR is merged. We can have a Github Action which can take care of closing the Issues when the PR is merged automatically. Few edge cases we can cover are: 

- Does the PR contain an Issue? If not, remind the contributor to link the Issue to the PR (You can add labels as well)
- Is the Issue assigned to more than one person? If yes, then we don't need to close the Issue pre-maturely.

| name            | problem/motivation                                                  | possible solution  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Auto-Close Bot | Close pending Issues automatically once the PR has been merged | Github Actions Marketplace have some pretty good actions for the same :) | |

**Comment by vybhav72954** [comment]
@HarshCasper I can do this and #758 too, but would be better if someone else takes them for now. I know there are people here who are better than me at that

**Comment by HarshCasper** [comment]
> @HarshCasper I can do this and #758 too, but would be better if someone else #758 for now. I know there are people here who are better than me at that

Assigning you this. Feel free to take #758 as well, if no one takes it up for a couple of days

**Comment by vybhav72954** [comment]
@HarshCasper Can you give me an idea by the way of what you want again?

I mean PR has the `fixes` and other related keywords

So it should automate that.

Do you want to close an issue even if a PR has no fixes thing in its body.

Reminding people to open an issue is definitely possible and straight forward

**Comment by HarshCasper** [comment]
> @HarshCasper Can you give me an idea by the way of what you want again?
> 
> I mean PR has the `fixes` and other related keywords
> 
> So it should automate that.
> 
> Do you want to close an issue even if a PR has no fixes thing in its body.
> 
> Reminding people to open an issue is definitely possible and straight forward

Apparently not. Take a look at your PR [here](https://github.com/HarshCasper/Rotten-Scripts/pull/699) and the corresponding Issue [here](https://github.com/HarshCasper/Rotten-Scripts/issues/660). 

Even though the PR was merged, the Issue was not closed automatically. So the prime responsibility of the Bot should be to close the Issue if the PR is merged. 

If there is no Issue linked, they should nudge the contributor to have one. We can have tags like `ready-to-review` if the Issue is linked or otherwise `dont-review-yet`.

**Comment by vybhav72954** [comment]
That makes sense. I can incorporate that one.

> > @HarshCasper Can you give me an idea by the way of what you want again?
> > I mean PR has the `fixes` and other related keywords
> > So it should automate that.
> > Do you want to close an issue even if a PR has no fixes thing in its body.
> > Reminding people to open an issue is definitely possible and straight forward
> 
> Apparently not. Take a look at your PR [here](https://github.com/HarshCasper/Rotten-Scripts/pull/699) and the corresponding Issue [here](https://github.com/HarshCasper/Rotten-Scripts/issues/660).
> 
> Even though the PR was merged, the Issue was not closed automatically. So the prime responsibility of the Bot should be to close the Issue if the PR is merged.
> 
> If there is no Issue linked, they should nudge the contributor to have one. We can have tags like `ready-to-review` if the Issue is linked or otherwise `dont-review-yet`.

**Comment by XZANATOL** [comment]
Hi, I'm a GSSOC participant and I am interested on help solving this issue. I've recently began learning Github Actions and I've read your requirments. I think I can help fullfil 2 out of 3 requirments.

## What I can fullfill
1) Build an action that can check whether or not the PR has a valid issue number linked to it. (with adding ReadyToReview tag)
2) Build an action to automatically close related linked issue on merge.

For what I think I can't fullfill is that edge case of checking whether the issue has more than 1 assignee. As far as I know Github Actions is meant to do actions on the same event/category of its trigger, So one way to avoid the auto-close on this case is to add a label to the PR for example "many-assignee" and filter it out in the action. I'm still researching if I can automate such a thing.

**Comment by vybhav72954** [comment]
Generally, we don't assign multiple people to the same issue in this repo so it wont be a problem.

> * Build an action that can check whether or not the PR has a valid issue number linked to it. (with adding ReadyToReview tag)
> * Build an action to automatically close related linked issue on merge.

How are you planning to fulfil these2 events, walk me through and I will assign this to you.

**Comment by XZANATOL** [comment]
First event will get triggered using any of the following triggers "edited, synchronize, opened, reopened", the event will be divided into 2 jobs.
1) check for valid issue links
2) If found, label it as "Ready_to_Review", If not: comment a message for the author of the PR to remind him to edit the PR.

Second event will get triggered on closing a PR and checking it subflag of .merged whether it's ture. If it is true then it will close the PR. if not merged, it will just skip.

**Comment by vybhav72954** [comment]
I like the idea. Do send me your `yaml` file here.

**Comment by XZANATOL** [comment]
I've one that i was testing this morning on this repo
https://github.com/XZANATOL/Github-actions-test/blob/main/.github/workflows/pr_issue_checker.yml
The other one didn't build it yet, but my algorithm to it is ready

**Comment by XZANATOL** [comment]
@vybhav72954 any updates?

**Comment by vybhav72954** [comment]
> @vybhav72954 any updates?

Sorry i was a bit busy with things. I will review this by tomorrow for sure.

**Comment by XZANATOL** [comment]
@vybhav72954 Any news?

**Comment by HarshCasper** [comment]
@XZANATOL It would be good if you make a PR

**Comment by vybhav72954** [comment]
@XZANATOL Oops, i wrote my thoughts on the action but forgot to post it. My bad.

So here is the thing, the action is good, but there is a small problem here, @HarshCasper I would leave this to you.

The thing is, in our PR bodies, what we actually prefer is this syntax:

`Fixes #<issue>`

Fixes can be replaced by anything like resolves, fix, etc.

But the action that you have proposed only looks for `#` character.

So apparently even with the PR body lacking the keyword, the action will run and do the trick.

Furthermore, I thought that this is something others would have faced as well, so I thought about checking the issues in the Repo, I found a similar thing there as well, though not exactly the same.

So @HarshCasper Am sorry but apparently without tweaking, the action wont do the job that we want, what I propose here is, as @XZANATOL seems to have experience with GitHub, we both can make a GitHub action for this Repo, (@XZANATOL I too have a separate repo for testing github actions XD, I keep it preivate though 🤣)

Sorry for the late review, I remember I did typed everything, must have forgot to post it.

**Comment by XZANATOL** [comment]
oh , all good @vybhav72954 :joy: I actually forgot that I commented here :rofl:. I have an edit for what's proposed here. The job which checks for a valid issue does look for the ``#`` character, However, the job which auto closes that related issue needs the `` Fixe* `` prefixes. (It can work with ``resolve* `` and ``close* `` too.)

Another thing I found a couple of days ago is that we can Deploy a docker container that contains a Python script and let it do the job using ``PyGithub`` library. I'm still searching about it and it seems like I need to learn Docker as well in order to not blindly copy & paste xd.  I'm gonna update here if I found anything by Sunday. If I didn't, then I will continue working with the previous proposal of deploying these tweaked actions. tell me what you think about it.

@vybhav72954 The repo should be private but I changed the settings for you to take a look at the Demo xD There are some unlogic commit titles in there that causes brain to 404 :joy:

**Comment by vybhav72954** [comment]
> oh , all good @vybhav72954 :joy: I actually forgot that I commented here :rofl:. I have an edit for what's proposed here. The job which checks for a valid issue does look for the ``#`` character, However, the job which auto closes that related issue needs the `` Fixe* `` prefixes. (It can work with ``resolve* `` and ``close* `` too.) So the prefix needs to be there don't worry.
> 
> Another thing I found a couple of days ago is that we can Deploy a docker container that contains a Python script and let it do the job using ``PyGithub`` library. I'm still searching about it and it seems like I need to learn Docker as well in order to not blindly copy & paste xd.  I'm gonna update here if I found anything by Sunday. If I didn't, then I will continue working with the previous proposal of deploying these tweaked actions. tell me what you think about it.
> 
> @vybhav72954 The repo should be private but I changed the settings for you to take a look at the Demo xD There are some unlogic commit titles in there that causes brain to 404 :joy: 
> 

Hey @XZANATOL, actually the `PyGithub` kind of is bad :P,  personal opinion

[Here](https://github3py.readthedocs.io/en/master/) is a better option. Docker is pretty simple, if you are planning to use a DOCKER image for github action that is.

Still unable to understand how you plan to incorporate `Fixes` keyword, have you did that in your repo :thinking:, i will surely have a look. Or maybe you are implying that there is another job 🤔🤔

**Comment by XZANATOL** [comment]
I mentioned that there'll be 2 workflows where each is triggered by a different event. The one which needs ``Open PR`` event and checks for valied issue links, checks for the ``#`` Character. But the one which auto closes the issue on merge is the second workflow (which is triggered by ``PR Closed`` event and have the ``.merged`` subflag true.) And it checks for fix, fixes, fixed prefixes (same with ``resolve & close``) followed ``#\<issue_no.\>``

You can check my repo. The last PR there is merged however the issue wasn't closed and the job suceeded as it skipped the ``#`` (There is an open issue there). This means that the auto-close workflow looks for the prefix not the ``#`` character.

The thing here is that I'm thinking to make a 1 action instead of 2.. That's why I was looking into Docker.

**Comment by vybhav72954** [comment]
> I mentioned that there'll be 2 workflows where each is triggered by a different event. The one which needs `Open PR` event and checks for valied issue links, checks for the `#` Character. But the one which auto closes the issue on merge is the second workflow (which is triggered by `PR Closed` event and have the `.merged` subflag true.) And it checks for fix, fixes, fixed prefixes (same with `resolve & close`) followed `#\<issue_no.\>`
> 
> You can check my repo. The last PR there is merged however the issue wasn't closed and the job suceeded as it skipped the `#` (There is an open issue there). This means that the auto-close workflow looks for the prefix not the `#` character.
> 
> The thing here is that I'm thinking to make a 1 action instead of 2.. That's why I was looking into Docker.

Ahhh makes sense, my bad!



> The thing here is that I'm thinking to make a 1 action instead of 2.. That's why I was looking into Docker. `github3` is also not a bad choice. But if you prefer it then no problems :D both do the same job at the end. xd

I can help with this thing for sure! But just a small problem, I have some commitments this weekend, in case you are able to sort it by then, wonderful. Else can think of something together.

**Comment by XZANATOL** [comment]
I'm also gonna be pretty busy from the upcoming Sunday to Tuesday because of college stuff xd. However, I manage to save some time to learn and test things. So, I think this will be a perfect period to me learn Docker and test basic stuff till we both are free, and then we can continue on with the rest. :p

**Comment by Shivani-001** [comment]
I want to work on this issue. I am new to open source could anyone tell me how i can assign it for myself ??

**Comment by HarshCasper** [comment]
@Shivani-001 It is being worked on now. Please pick up some other issues.

**Comment by XZANATOL** [comment]
@vybhav72954 @HarshCasper Hi there, sorry for the sudden cut. xd
Just gonna update what I've reached till now.

First of all, I was on scheduele I learned Docker basics on time and tested most of the basic implementations with GitHub Actions. While searching, I understode how to exchange inputs between GitHub Actions and my script which gave me another idea about how to implement the action on this repo. How about making a public Github Action and use it remotly from here? this will save some minimal code and will allow the reuse of the script by other open source projects.

Second is that I've already finished the part considering checking for valid Issue numbers inside a PR body. This includes the search & validation. But one thing is missing which is the GitHub API I'm still trying to figure out how it works when it comes to make a comment, or close an issue. should I use curl commands or the [library](https://github3py.readthedocs.io/en/master/) which @vybhav72954 suggested can do this work if I provided it with the GitHub token?

**Comment by XZANATOL** [comment]
@HarshCasper @vybhav72954 should have only refrenced the issue, not link it.. my bad xd. Can you reopen this so to continue on the auto closing action for PRs with issue number but not linked?

**Comment by vybhav72954** [comment]
> @HarshCasper @vybhav72954 should have only refrenced the issue, not link it.. my bad xd. Can you reopen this so to continue on the auto closing action for PRs with issue number but not linked?

Keep it linked

**Comment by XZANATOL** [comment]
didnt we agree on building 2 actions? or this one is good to close this issue? - check [this](https://github.com/HarshCasper/Rotten-Scripts/issues/757#issuecomment-812628952) -

**Comment by vybhav72954** [comment]
> didnt we agree on building 2 actions? or this one is good to close this issue? - check [this](https://github.com/HarshCasper/Rotten-Scripts/issues/757#issuecomment-812628952) -

Wait just so that we are clear, you want us to reopen the issue so that we can start with the second part of the action right?

**Comment by XZANATOL** [comment]
Ummm, yea xd
I'm researching about it in the meantime and it won't take long since we already know the needed approach to deal with PR bodies within GitHub actions.
