### ISSUE TITLE
Create a Script to track Issues on a Github Repo

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#76]
## AIM

Create a Script which can help me to track the Issue on a Github Repository.

## Languages

- Python
- Javascript
- Golang

## Details

You have to create a script that can log all the Issues (Opened and Closed) and display them straight on the CLI.

**Comment by Sanketwable** [comment]
I want to work on this

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on this @Sanketwable

**Comment by Sanketwable** [comment]
@HarshCasper Please review
