### ISSUE TITLE
Enforce PEP-8 guidelines in the Python Codebase

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#762]
@HarshCasper The name is obvious in itself, this is in conjunction with #688 

I will open a PR after I refactor at least 10 directories, so as not to simply clutter up the Issues and PRs.

Or shall I do it in one go?

**Comment by HarshCasper** [comment]
Please go ahead. Just use the `/assign` bot and feel free to work on any improvements 😄

**Comment by pganguli** [comment]
In pull request #804, @vybhav72954 mentioned that there are still around 50% formatting issues left to correct. If no further work is being done on this, I'd be happy to take over from where it was left off and (hopefully) close this issue. I'm asking for this assignment for GSOOC'21.

**Comment by vybhav72954** [comment]
@pganguli Thanks for reminding me, I will open a separate issue, say by tomorrow, explaining what is left, you can take that issue by using `/assign`.

@HarshCasper Does that sounds fine to you?

**Comment by pganguli** [comment]
> @pganguli Thanks for reminding me, I will open a separate issue, say by tomorrow, explaining what is left, you can take that issue by using `/assign`.
> 
> @HarshCasper How does this sounds to you, you can close this issue as well, while I will open a new one explaining what we are lacking.

Thanks. A description of what's left to be done will help me a lot.
