### ISSUE TITLE
Quantum Computing script to generate random numbers

### ISSUE THREAD

**Issue by RutvikJ77** [HarshCasper/Rotten-Scripts#765]
**This template is strictly for requesting New Scripts, if you want a new feature (automating this Repo,**
**a change in structure) in the Repo,** 
**or you want to report a Bug. There are other templates which you should follow**

# Description
The script will use Quantum gates to create random numbers.

## Language

- [ ] Bash
- [ ] Go
- [ ] Javascript
- [ ] Powershell
- [x] Python
- [ ] Other (Please specify)

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Quant_random | Generate random numbers using Quantum computing | feature | self-assign |

**Is your feature request related to a problem? Please describe.**: Quantum computing can be tough to understand unless you understand basic gates used in Quantum computation. This script will serve as an example for gate manipulation in Quantum Computing.

**Comment by HarshCasper** [comment]
Few questions: 

- What is the actual purpose of generating random numbers? Classic Computing does that quite well, isn't it? 
- What Quantum Computing language will you use? Are you planning to use Q# ? 
- What is the specific advantage it provides over other implementations?

**Comment by RutvikJ77** [comment]
> Few questions:
> 
>     * What is the actual purpose of generating random numbers? Classic Computing does that quite well, isn't it?
> 
>     * What Quantum Computing language will you use? Are you planning to use Q# ?
> 
>     * What is the specific advantage it provides over other implementations?

Great Questions! 
- Quantum Computing gates are quite different from the classical gates and require an intricate understanding of the matrix algebra. Nextly, anyone who is practising quantum computation may require a few examples as to how quantum gates can be used to manipulate the classical world. Thereby leveraging the power of both the quantum and classical worlds.
- My preferred choice would Qiskit package which is based on the python programming language.
- Not any advantage as such but for a better understanding of how things play in the quantum world using Hadmard or any such gates.
