### ISSUE TITLE
Anime tracker script 

### ISSUE THREAD

**Issue by pritamp17** [HarshCasper/Rotten-Scripts#771]
______________________________________________________________________________________________________________________
-->

# Description

Python Script that can give anime info such as
1. Number of episodes release
2. Genres
3. Date of release
4. Rating

## Language

- [ ] Bash
- [ ] Go
- [ ] Javascript
- [x] Python

**Comment by pritamp17** [comment]
Please assign this issue to me in python.

**Comment by pritamp17** [comment]
Please add SWOC label also,  u will solving this issue under SWOC.

**Comment by HarshCasper** [comment]
Hi @pritamp17 

You have been working on a lot of Issues and created many PRs. Can you drop me a mail [here](mailto:erbeusgriffincasper@gmail.com) and let me know all the PRs that you made and the apt points so that I can get the Leaderboard updated. 

Thanks!

**Comment by pritamp17** [comment]
> Hi @pritamp17
> 
> You have been working on a lot of Issues and created many PRs. Can you drop me a mail [here](mailto:erbeusgriffincasper@gmail.com) and let me know all the PRs that you made and the apt points so that I can get the Leaderboard updated.
> 
> Thanks!

@HarshCasper I have sent the email .

**Comment by telly-tubby** [comment]
Can I work on this as a GSSOC participant?

**Comment by HarshCasper** [comment]
> Can I work on this as a GSSOC participant?

A PR is pending for the same. If it sees no progress, take up the Issue with pleasure.

**Comment by srimontidutta** [comment]
@vybhav72954 What will the process be of reassigning this issue in case a PR is not made?

**Comment by vybhav72954** [comment]
@srimontidutta THere is a PR already #777

Although we have asked for a few changes but no response from OP. Lets wait for 2 more days, else we will close the PR cause of no updates and you can take this issue

**Comment by vybhav72954** [comment]
@srimontidutta @telly-tubby The Issue has been closed with the PR, if you want to work on JS or GO for the same issue, please mention here, else please find other issues
