### ISSUE TITLE
Dino Game Automater

### ISSUE THREAD

**Issue by Aayush-hub** [HarshCasper/Rotten-Scripts#775]
# Description

"Python Script to automate Dino Game(No-Internet game)." 

## Language

- [x] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Dino game Automater | Automate No internet game using python | MWOC , SWOC , feature | @Aayush-hub |

**Comment by Aayush-hub** [comment]
@HarshCasper Can I work on this issue under SWOC and MWOC labels?

**Comment by HarshCasper** [comment]
Hi @Aayush-hub 

Thanks for creating the Issue! 

Unfortunately, we already have an implementation for the same. Can you have a look on the same and suggest me ways in which you can improve it.

**Comment by Aayush-hub** [comment]
@HarshCasper I am unable to find dino script in the repo, can you please link it here?

**Comment by HarshCasper** [comment]
Find it [here](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Chrome_Dino_Script)

**Comment by Aayush-hub** [comment]
@HarshCasper Sir, the program is fine but, personally I think it's messed up and not beginner friendly as we don't need 3 `.py` files to automate game and its readme quick start file structure is not clear about how to start. The automation can be done in one file itself.
