### ISSUE TITLE
Voice Recorder Application Using Python

### ISSUE THREAD

**Issue by CharvyJain** [HarshCasper/Rotten-Scripts#779]
# Description

This Script is a voice recorder implemented using Tkinter.

## Language

- [ ] Bash
- [ ] Go
- [ ] Javascript
- [ ] Powershell
- [X] Python
- [ ] Other (Please specify)

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Voice Recorder| Recording Voice ( GUI ) | DWOC, feature, python | @CharvyJain

**Comment by achalesh27022003** [comment]
@CharvyJain mam  I would like to work on this. pls assign me this under DWoC.

**Comment by HarshCasper** [comment]
Hi @CharvyJain 

Thanks for creating the Issue. Please don't use Tkinter since we don't have a provision of a GUI-App in the Project. Instead use a CLI or a simple Script that can make it possible.

**Comment by CharvyJain** [comment]
@HarshCasper Sure! I can use CLI.

Assign me under DWOC

**Comment by HarshCasper** [comment]
> @HarshCasper Sure! I can use CLI.
> 
> Assign me under DWOC

DWOC is already over. If you plan to work on it go ahead. Otherwise, I can open this Issue for others

**Comment by CharvyJain** [comment]
@HarshCasper Can I do under SWOC ? I will make PR today.

**Comment by HarshCasper** [comment]
> @HarshCasper Can I do under SWOC ? I will make PR today.

Go ahead! I will be available the entire day for PR reviews.

**Comment by CharvyJain** [comment]
@HarshCasper You can open this Issue for others.

**Comment by abh33** [comment]
I would like to work on this under GSSOC'21

**Comment by kshittijagrawal** [comment]
Hey there!
I'd like to contribute to the project. I want to address and fix this issue. My implementation will be in python with a clean code and documentation. Kindly provide me with this issue.
I'm also a GSSOC'21 participant.

**Comment by vybhav72954** [comment]
@abh33 Am assigning this to you, kindly acknowledge ASAP as there are others as well

**Comment by abh33** [comment]
Hey thanks. I will start working on this.

**Comment by vybhav72954** [comment]
@abh33 Feel free to ask me anything in case you are stuck or facing issues

**Comment by varshith-k** [comment]
Is this issue still open @vybhav72954 ?

**Comment by abh33** [comment]
I am actually working on this.

**Comment by vybhav72954** [comment]
@abh33 Any update?

**Comment by vybhav72954** [comment]
Unassingining cause of lack of updates

**Comment by vybhav72954** [comment]
@kshittijagrawal @varshith-k Feel free to take this

**Comment by harshita2319** [comment]
Hey, I'd like to work on this, please assign!
(GSSOC participant)
