### ISSUE TITLE
Real Time Image/Marker tracker Augmented Reality based Web Script 

### ISSUE THREAD

**Issue by sohamsshah** [HarshCasper/Rotten-Scripts#786]
# Description

A Script to track Image/Markers in Real Time Web Application. 
In Augmented Reality applications, a particular element/event is triggered/shown based on some defined `Image` or a `Marker`. Once Image or a Marker is tracked, some object/event can be shown to the user in order to give an acknowledgement of the functionality. 

This Script can be a good start-point for anyone who wants to refer the implementation of such AR tasks in Web. 

## Language

- [X] Javascript

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| -------------------------------------------------------------- | --------------------------------------------------------------  | ------- | -------------------------------------------------------------- |
| Real Time Image/Marker Tracker AR-based Web Script | A web script that can perform Image tracking using AR tech | Augmented Reality, Hard, Javascript, good first issue |  |

### Additional Context:
This Script must detect an Image/Marker via Laptop Webcam or Phone Camera. Once detected, some action such as showing an object to the screen, playing music or similar can be triggered (creativity appreciated). Importantly, this script must **NOT** be application specific but more reusable and general (comment accordingly while writing code) and thus try keeping it short and crisp. 

[AR.js](https://github.com/AR-js-org/AR.js) or similar JS libraries can be used for solving this issue.

**Comment by priyanshu20** [comment]
I'd like to work on this as a GSSOC '21 Participant.

**Comment by sohamsshah** [comment]
@priyanshu20 I have assigned this issue to you. Let me know if any help is needed from my end.

**Comment by priyanshu20** [comment]
@sohamsshah If I use Ar.js , their starter code basically does the required task, what specifically do I have to create?

**Comment by sohamsshah** [comment]
@priyanshu20 You can take a set of images/markers and show an AR object on the screen and trigger event based on each detection. For example, you take markers representing a location (like AruCo Markers are used in Drones); when a marker is detected, show an object and trigger that specifies that location.

This addition isn't application specific but an enhancement for AR development. So, you can come up with your creative implementations as well.

**Comment by priyanshu20** [comment]
I'm afraid I wont be able to work on it right now. Sorry for inconvenience.
