### ISSUE TITLE
BITCOIN Price Tracker

### ISSUE THREAD

**Issue by pritamp17** [HarshCasper/Rotten-Scripts#789]
Track Bitcoin Price In Real-Time.

## Language

- [ ] Bash
- [ ] Go
- [ ] Javascript
- [ ] Powershell
- [x] Python

**Comment by pritamp17** [comment]
@HarshCasper please assign this issue to me under SWOC.

**Comment by HarshCasper** [comment]
@pritamp17 : Just a heads-up. Today is the last day for SWoC

**Comment by pritamp17** [comment]
ok👍

**Comment by manas221** [comment]
Hi, I would like to work on the go implementation of the issue for gssoc.

**Comment by manas221** [comment]
@vybhav72954 Assign me this issue for the GOlang implementation, thank you..

**Comment by vybhav72954** [comment]
Assigning @manas221 for `GO`
