### ISSUE TITLE
Enhancement of README.md file

### ISSUE THREAD

**Issue by anirudhsai20** [HarshCasper/Rotten-Scripts#790]
**This template is strictly for requesting New Scripts, if you want a new feature (automating this Repo,**
**a change in structure) in the Repo,** 
**or you want to report a Bug. There are other templates which you should follow**

README.md enhancement

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| README.md enhancement | Mentioning the list of open source programs and research papers that this project has been listed in. | feature | anirudhsai20| Anirudh Sai S B|
 ______________________________________________________________________________________________________________________
 

_________________________________________________THESE ARE COMMENTS____________________________________________________

The lack of automation in GitHub README.md always triggers me, so is your problem similar? Tell us about it.
______________________________________________________________________________________________________________________
--> No. I will just make a list of all the open source programs that this project has been listed in and also make a list of all the research papers that have cited this project in the README.md file. 

**Describe the solution you'd like**: A clear and concise description of what you want to happen.

It will just be a list of all the open source programs and research papers. 

/assign

**Comment by anirudhsai20** [comment]
Hi @HarshCasper . Please assign me this issue under SWOC.

**Comment by HarshCasper** [comment]
@anirudhsai20 

Thanks for making the Issue and detailing a lot about it! 

We already list our Open Source Events [here](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Open_Source_Events). 

Coming to the second part, can you tell me which research papers have cited this project? I am generally curious to know if someone is actually using it in some way or the other.

**Comment by vybhav72954** [comment]
@anirudhsai20 Kindly update!!

**Comment by anirudhsai20** [comment]
Hi! I'm afraid this repo has not been cited by a research paper yet. I wish that reserach papers do make use of this useful repo.

**Comment by vybhav72954** [comment]
I understand, thank you for contributing though!!! Have a look at open issues as well.
