### ISSUE TITLE
Propose a new Python README

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#796]
## Description 

Propose a new Python README for contributors. You can take some inspiration from the presentation method followed in [NeoAlgo](https://github.com/TesseractCoding/NeoAlgo) to present the scripts in an easy to go manner, without making a lot of changes and edits. 

Currently the Python README is hard to edit and make sense of. New Contributors always face a problem while editing the README to have their script in it.

**Comment by deepthiteki** [comment]
HI @HarshCasper,
Can I work on this under GSSOC'21

**Comment by SSHREYA71** [comment]
Hi @vybhav72954  , Could i be assigned this for contribution

**Comment by vybhav72954** [comment]
@deepthiteki Am sorry I missed your comment, u still want to work on the README?

**Comment by vybhav72954** [comment]
@SSHREYA71 am sorry but @deepthiteki was first, but i have a solution, just like a Python Readme, we do have a JavaScript Readme, with the same problem, I can assign that to you if you want to.

**Comment by SSHREYA71** [comment]
@vybhav72954  I have messaged you more one more issue, "send your location" one, if You can assign me to that, it will be great else, javascript readme will also be fine. I can learn it and then do it.

**Comment by vybhav72954** [comment]
@SSHREYA71 I can assign both to you, for #619, kindly tell us what you propose, and I will assign you right away, moreover, I will make a new issue for JS README and I will assign you that, how does that sound?

**Comment by deepthiteki** [comment]
hi @vybhav72954 
Yeah, I still want to work on this.
Thank you

**Comment by vybhav72954** [comment]
@deepthiteki Any updates?
