### ISSUE TITLE
NMap Scanner

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#8]
## AIM

Create a NMap Scanner using Python Programming Language.

## Languages

- Python

## Details

Create a Script to scan the Host's IP Address and the Hostname (If Present) using NMap by creating a script to automate the process. You can make use of [this](https://pypi.org/project/python-nmap/) library for your purpose and ease.

**Comment by seema1711** [comment]
Can I work on this?

**Comment by HarshCasper** [comment]
You have been assigned this Issue @seema1711 

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also, reference this Issue in your PR so that it becomes easy for us to review.
