### ISSUE TITLE
Get WIFI Passwords

### ISSUE THREAD

**Issue by pritamp17** [HarshCasper/Rotten-Scripts#800]
**This template is strictly for requesting New Scripts, if you want a new feature (automating this Repo,**
**a change in structure) in the Repo,** 
**or you want to report a Bug. There are other templates which you should follow**

# Description
A Python Script which when Executed on the target machine will send all the WIFI names and their respective passwords stored in it, through Given Email.

## Language
- [x] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| Get WIFI Passwords | A Python Script which when Executed on the target machine will send all the WIFI names and their respective passwords stored in it, through Given Email. |SWOC| @pritamp17 |

**Comment by get-satyam** [comment]
@vybhav72954 I would like to work on this issue, please assign me this issue.

**Comment by vybhav72954** [comment]
@get-satyam You got it, Best oof Luck!
