### ISSUE TITLE
Remove the Project Admin Portion from README

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#805]
## Description 

Remove the Project Admin Portion from the README file. As of now, my picture and details are displayed on the README as the Project Admin. 

As the Project has grown, it would be better if the term "Project Admin" is replaced by "Maintainers". As of now, these are the official maintainers of the Project: 

- Harsh Mishra ( @harshcasper ) 
- Soham Shah ( @sohamsshah ) 
- Seema Saharan ( @seema1711 )
- Vybhav Chaturvedi ( @vybhav72954 )

Create a new section in the README by replacing the existing one, and add all their details in a similar format that exists right now.

**Comment by subhamagrawal7** [comment]
I would like to try this. Could you assign it to me?? Also, should I just put the Linkedin links below images or do you want any other links as well??

**Comment by vybhav72954** [comment]
@subhamagrawal7 The image should redirect to GitHub Profile, while the name should be linked to LinkedIn Profile.

I will provide the Linked-In links here soon, kindly confirm once again so that  I can assign this to you.

**Comment by haripriya9647** [comment]
Hey I would like to work on this issue

**Comment by vybhav72954** [comment]
> Hey I would like to work on this issue

I will assign this to you if @subhamagrawal7 doesn't respond by evening.

**Comment by vybhav72954** [comment]
@haripriya9647 Am assigning this to you

**Comment by subhamagrawal7** [comment]
Really sorry for the delay..was little busy yesterday...let me know if this issue still remains unresolved.

**Comment by vybhav72954** [comment]
@haripriya9647 You are working on this?

**Comment by haripriya9647** [comment]
Hey yes I am GSSoc participant and I am working on this issue.

**Comment by vybhav72954** [comment]
Sure thing.

For Discussion, we can use the GitHub discussion tab for now. Link - https://github.com/HarshCasper/Rotten-Scripts/discussions

LinkedIn

Harsh: https://www.linkedin.com/in/harshcasper/
Soham: https://www.linkedin.com/in/soham-shah-a97b5917b/
Seema: https://www.linkedin.com/in/seemasaharan/
Vybhav: https://www.linkedin.com/in/vybhav-chaturvedi-0ba82614a/
