### ISSUE TITLE
Delete Tweets automatically

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#806]
# Description

Delete Tweets automatically. For an active Twitter user, there is a lot of ramblings that people do, and it is always best to keep the timeline sacred, to prevent any controversy. As a Twitter User, I would like to have a script that can delete the tweets automatically. But then again, it should not be a dumb delete. We can customize it to have a few features like: 

- Passing the timeframe between which the tweets should be deleted 
- Having a threshold of minimum Likes/RTs upon which the tweet should be deleted 
- Deleting only replies and RTs instead of timeline tweets 
- Deleting all tweets having some media file (Picture/GIF/Video) 

You are free to have your own customization as part of it and come up with your own unique ideas.

## Language
- [X] Go
- [X] Javascript
- [X] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Tweet Delete | Automatically delete tweets in a customized manner | Up-for-Grab, Hard, good first issue | |

**Comment by devRawnie** [comment]
I am a gssoc'21 participant and would like to work on this issue. I have some intermediate knowledge of python and javascript. Please assign this to me.

**Comment by vybhav72954** [comment]
Sure thing.

**Comment by devRawnie** [comment]
Alright. Thank you. Will try to deliever a good script

**Comment by devRawnie** [comment]
I was able to make one functionality. I am working towards adding more along with a command line interface for the same
