### ISSUE TITLE
Script to crawl Web Browser History and generate meaningful insights

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#808]
# Description

Create a Script that can crawl up my Internet Browser History (Chrome/Firefox) and generate useful insights on the websites I visited and the time spent on each of them. As an end output, you can generate a graph to show the time distribution across the various apps and a CSV file listing down all the websites (excluding the subdomains) to understand the time spent on each of the platforms. 

To further customize this you can add the following options: 

- Feature to crawl the history for only a specific time range. 
- Feature to crawl up a specific website and track the time spent on them (including the subdomains)
- Store the data on a lightweight Database (PickleDB is a good choice) and compare present data with previous iterations
- Exclude some websites from the crawling operation (permanently/temporarily) 

## Language
- [X] Golang
- [X] Javascript
- [X] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Web History Crawler | Crawl up Web browser history and generate meaningful insights | Up-for-Grab, Hard, good first issue | |

**Comment by pganguli** [comment]
How do you suggest to calculate the amount of time spent on a particular domain (including subdomains)? As far as I can tell, the browsing history DBs of both Firefox and Chrome/Chromium store the time of access only, not the time of leaving the website. Even if we try to gague the time spent on a website A1, given that the history entry for website A1 is followed by website A2, by subtracting the timestamp of A1 from A2, there is no guarantee that the browser was not shut down by the user between those two visits. This could leave us with impractically long usage times for websites after which the browser is closed, and a long time later, the browser is reopened and another website is visited.

**Comment by HarshCasper** [comment]
That's a very good question. Thanks for bringing this up @pganguli ! 

Maybe as a walk around, we can ideate on a Chrome Extension that can help simplify few things for us. The extension can track the websites we are visiting and using a simple API endpoint, we can communicate this data to a script.

However this whole implementation would be an overkill for the current scope of the Issue and Project. I guess we can leave out the time tracking feature and instead store the timestamps. I would like to take your suggestion as well @vybhav72954 @sohamsshah

**Comment by vybhav72954** [comment]
> How do you suggest to calculate the amount of time spent on a particular domain (including subdomains)? As far as I can tell, the browsing history DBs of both Firefox and Chrome/Chromium store the time of access only, not the time of leaving the website. Even if we try to gague the time spent on a website A1, given that the history entry for website A1 is followed by website A2, by subtracting the timestamp of A1 from A2, there is no guarantee that the browser was not shut down by the user between those two visits. This could leave us with impractically long usage times for websites after which the browser is closed, and a long time later, the browser is reopened and another website is visited.
> As a workaround this though, we can reject consideration of entries that have a difference of x hours (let's say, x = 6) between their timestamps. This however, can introduce false negatives.

Once made an extension for a different purpose, but am pretty sure special-purpose APIs like `chrome.idle`, `chrome.runtime` can solve these problems.

Again you will need an `eventListener` along with `FocuseWindows` i imagine.

If you are planning to use JS, that would probably be the way to go.

If you are planning in Python like @HarshCasper Said, an extension on a framework can help

**Comment by sohamsshah** [comment]
> How do you suggest to calculate the amount of time spent on a particular domain (including subdomains)? As far as I can tell, the browsing history DBs of both Firefox and Chrome/Chromium store the time of access only, not the time of leaving the website. Even if we try to gague the time spent on a website A1, given that the history entry for website A1 is followed by website A2, by subtracting the timestamp of A1 from A2, there is no guarantee that the browser was not shut down by the user between those two visits. This could leave us with impractically long usage times for websites after which the browser is closed, and a long time later, the browser is reopened and another website is visited.
> As a workaround this though, we can reject consideration of entries that have a difference of x hours (let's say, x = 6) between their timestamps. This however, can introduce false negatives.

Yes, this might be a challenging feature. Though, it is one of many features/things we can track by browsing history. To start, one can keep it agile and implement the must-haves and then along the way keep adding and brainstorming others.

By browser history crawling we can:
- Which sites are most visited 
- Explains users' intent
- Browsing Time can be used to sort content
- In turn can be a productivity tool if data is analyzed well
- Like, spotify gave "Favourite Songs" of the year and people were amazed, proving Data has power. 
- Most social media apps aren't the "High browsing time" but "Higher click/visit frequency". Can track that as well, what the productivity apps for mobile phone does.
