### ISSUE TITLE
Preventing reporting the Project as a "Jupyter Notebook" Repo

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#809]
## Description 

Majority of the Scripts on the project are either in Python, Javascript and Golang. Some of the contributors started contributing Jupyter Notebooks as well, in a bid to have a better visualization for the scripts that they wrote. It not only enhanced the understanding for a user but for scripts that relied on AI/ML, it gave a better insight into the functionality.

However, Jupyter Notebooks are notorious to have a lot of metadata associated with the files. And now with a lot of Notebooks, there are a lot of metadata and it has inflated the lines of code so much, that the project is now classified in `Jupyter Notebook` category. 

This behaviour can be fixed, by adding a  `*.ipynb linguist-vendored` to the `.gitattributes` file.

**Comment by pganguli** [comment]
I'd like to work on this for GSSOC'21.

**Comment by saaalik** [comment]
You have added `.gitattributes` in python folder, I think it is supposed to be added in the main directory

**Comment by pganguli** [comment]
> You have added `.gitattributes` in python folder, I think it is supposed to be added in the main directory

It can be added it the root of any directory that contains the files that are to be acted upon. Since the Python dir contains all the *.ipynb files, I think it is better to put our .gitattributes file in the root of that dir, rather than the repo root.

**Comment by HarshCasper** [comment]
Why do we have two Pull Requests for the same issue :sweat_smile: 

I would generally advise for everyone to wait until the maintainer assigns someone for the Issue. If the Issue has been assigned to someone only then you can make a PR.
