### ISSUE TITLE
[Proposal] Scripts in Rust

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#811]
## Description 

Rotten Scripts traditionally hosts scripts around Python, Javascript and Golang. It comes as a no surprise since these languages have a community centered around them, with some awesome packages and libraries for almost every development needs. 

However, since we are looking at things from a more diverse point of view, we would love to have scripts in various languages as well. And the one, that tops the list is Rust. And it comes as a no-surprise: Rust is feature-rich, incredible fast and has a lot of interesting components that we can play with. 

So now the Issue begs: Why don't we have contributors play around with Rust and contribute to the same? 

## Deliverable 

Instead of just creating Issues for Rust, I would like to first gauge the interest of those who would like to contribute towards it. There is no dearth of ideas: Rotten Scripts hosts nearly 200+ Scripts from various domains. You can rework on them using Rust and I have some awesome resources to share as well. 

But rather than creating an Issue, I would like to have a proposal: The proposal should document your experience with Rust (Its fine if you don't have any) and the list of scripts that you would like to work on. Prepare a Markdown proposal and post on the [Discussions](https://github.com/HarshCasper/Rotten-Scripts/discussions) and tag me. 

Once we have a nice discussion about the deliverable, I will create a project board and you can start working on the same. 

## Resources 

- [Starting Rust From A Scripting Background](https://rust-from-a-scripting-background.readthedocs.io/en/latest/)
- [The Rust Programming Language](https://doc.rust-lang.org/book/)

**Comment by vybhav72954** [comment]
This is one great idea.

**Comment by subhangi2731** [comment]
can you please assign me this?

**Comment by gokulsoumya** [comment]
I've started a discussion on #838 regarding rust programs.

P.S. I'd like to work on this as part of GSSoC'21.

**Comment by vybhav72954** [comment]
@gokulsoumya Thank you for showing interest, I will get back to you ASAP
