### ISSUE TITLE
Add banner of crosswoc to the readme file

### ISSUE THREAD

**Issue by kmryashasvi** [HarshCasper/Rotten-Scripts#817]
I will add banner of crosswoc to the readme file so that, people will know it is associated to crosswoc.
 Moreover, I will associate link of the crosswoc website to its banner such that, if someone clicks the banner on readme file, it will redirect them to the website of crosswoc.

**Comment by HarshCasper** [comment]
> I will add banner of crosswoc to the readme file so that, people will know it is associated to crosswoc.
> Moreover, I will associate link of the crosswoc website to its banner such that, if someone clicks the banner on readme file, it will redirect them to the website of crosswoc.

This Project is a part of CrossWOC but we don't need to add the banner on the main README. This project is also a part of other FOSS Programs, and it would be counter intuitive in that case.

**Comment by kmryashasvi** [comment]
Okay then I am closing this issue
Thank you
