### ISSUE TITLE
Script for random giveaways on Twitter

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#818]
# Description

Create a Script for a random giveaway on Twitter. I recently noticed Daily.dev organizing a giveaway [here](https://twitter.com/dailydotdev/status/1367807241466871810). Being one of the winners (or a random selection, I would say), I was really interested if we can have such a giveaway script that can randomly pick up people from RTs or Replies and randomly pass us a batch of people, that we can pass the giveaway too. 

The Script should ideally scrap everyone who Retweeted/Quote Retweeted and Replied to a specific tweet and stores them in a CSV File. We can then use arguement parsers to randomly select a batch of people from the people depending on whether they RTed or replied. 

You are free to have your own customization as part of it and come up with your own unique ideas.

## Language
- [X] Go
- [X] Javascript
- [X] Python

**Comment by Itsaadarsh** [comment]
Hey there @HarshCasper, I'd like to work on this feature. So if it's not already assigned to anyone I'd like you it assign it to me so that I could get started right away.

Language : `JavaScript`

**Comment by HarshCasper** [comment]
Please have a start. Let me know on this thread if you need assistance with any part.

**Comment by RituCs** [comment]
Hello , I would like to contribute on this issue.If no one is working on this issue then please assign me.

**Comment by Itsaadarsh** [comment]
Hey @RituCs, yes please go ahead I'm caught up in some work at the moment.

**Comment by vybhav72954** [comment]
> Hey @RituCs, yes please go ahead I'm caught up in some work at the moment.

Thnks for confirming

**Comment by vybhav72954** [comment]
@RituCs Any update?

**Comment by RituCs** [comment]
> @RituCs Any update?

Sorry!! Not much.Due to final sem exam I am not able to work right now.If you give time then I will do this.

**Comment by HarshCasper** [comment]
> > @RituCs Any update?
> 
> Sorry!! Not much.Due to final sem exam I am not able to work right now.If you give time then I will do this.

Please take your own sweet time! Let us know if we can be of any help.
