### ISSUE TITLE
Color Picker from Image/Video feed using Python

### ISSUE THREAD

**Issue by sohamsshah** [HarshCasper/Rotten-Scripts#819]
# Description

Pick the color from the pixel of the image which is mouse-clicked and print the RGB value of the color. Color Picker is one of the fundamental snippet widely used during Computer vision applications. Anyone who is interested to explore Computer Vision can take this issue.

## Language
- [X] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Color Picker using Python | Pick a color on a mouse click from an image picture and display on console | Python, good-first-issue |  |

**Is your feature request related to a problem? Please describe.**: 
Color picker script is quite fascinating thing to implement as this has wide spectrum of use cases in video/image editing apps, extract color themes from the website layout, eye-dropper etc. 

**Describe the solution you'd like**:
When an image is clicked, trigger a callback which takes a pixel with [x,y,z]. All pixels are in RGB form and so the color can be extracted and printed in the console.

[This](https://www.youtube.com/watch?v=kdLM6AOd2vc&list=PLS1QulWo1RIa7D1O6skqDQ-JZ1GGHKK-K) is a good reference to learn basics of OpenCV apart from the official docs.

**Comment by TITHI007** [comment]
I would like to work on it
Pl.  Assign it

**Comment by sohamsshah** [comment]
@TITHI007 Sure! Let me know if you need any assistance re: solving the issue.

**Comment by sohamsshah** [comment]
@TITHI007 are you working on this? Do let me know if you are facing any roadblocks while implementing this.

**Comment by TITHI007** [comment]
@sohamsshah yeah 
Did the Pull request 
Pl. Do check it out and let me know if anything to be improved .

**Comment by vybhav72954** [comment]
Oops mybad... Nevermind

**Comment by vybhav72954** [comment]
@TITHI007 Please confirm if you are GSoC participant

**Comment by TITHI007** [comment]
> @TITHI007 Please confirm if you are GSoC participant

I am not the GSoC participant.

**Comment by vybhav72954** [comment]
> > @TITHI007 Please confirm if you are GSoC participant
> 
> I am not the GSoC participant.

I am sorry I meant GSSoC (GirlScript  SoC)

**Comment by TITHI007** [comment]
No neither of any
