### ISSUE TITLE
Optical Character Recognition (OCR): Recognize the text content in different languages from Images

### ISSUE THREAD

**Issue by sohamsshah** [HarshCasper/Rotten-Scripts#820]
# Description

OCR is a popular text recognition technology to detect text from the images. It is widely used in automation of billing, documentation, scanning, etc. applications.

## Language Preferred but not limited to

- [X] Javascript
- [X] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| OCR detection | Detect text from Images using OCR | Python, Medium |  |

**Is your feature request related to a problem? Please describe.**

OCR detection can be a good addition to the project. 
**Describe the solution you'd like**: 

There are various libraries available for implementing this. For Python [pytesseract](https://pypi.org/project/pytesseract/) is quite enough for implementing this. JavaScript also has [tesseract.js](https://www.npmjs.com/package/tesseract.js/v/2.1.1) which is an npm package that can detect text in browser as well.

If someone is trying to implement in multiple languages, feel free to raise seperate PRs for corresponding languages and make sure you follow the Coding Style for the same.

**Comment by abh33** [comment]
I would like to work on this issue. I am a GSSOC'21 participant.
Is there any specific use-case OCR that needs to be applied?? For example identifying billboards, etc.

**Comment by sohamsshah** [comment]
Sure, I am assigning this issue to you. Not specific but yes as an example test-case it is a good practice to add meaningful applications to the project. Billboards, paper bills, hard copy of documents etc. can be included. Make sure if you are using an image reference, you give credits/refs from where you are using.

**Comment by sohamsshah** [comment]
@abh33 are you working on this?

**Comment by abh33** [comment]
Yes. I am working on this. I will create a Pull request by tomorrow.

**Comment by vybhav72954** [comment]
@abh33 Please update, eagerly waiting for this script

**Comment by abh33** [comment]
Hey. Sorry for the late reply. Actually, I have been facing some problems with pytesseract. The accuracy does not seem very good. It fails to detect most of the simpler images.

**Comment by HarshCasper** [comment]
> Hey. Sorry for the late reply. Actually, I have been facing some problems with pytesseract. The accuracy does not seem very good. It fails to detect most of the simpler images.

Can you please make a PR and post your results over there?

**Comment by vybhav72954** [comment]
@abh33 Updates?

**Comment by vybhav72954** [comment]
Unassigned @abh33 For lack of response
