### ISSUE TITLE
Remove Background from an Image using Python

### ISSUE THREAD

**Issue by sohamsshah** [HarshCasper/Rotten-Scripts#821]
# Description

Remove the background from an image in python using image manipulation libraries such as scikit-image, opencv etc.

## Language

- [X] Python
## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Background Remover | Remove the background from an image using Python Image Processing | Python, Medium, Up For Grabs |  |

**Is your feature request related to a problem? Please describe.**: 
Many times we want the background to be removed from the image and the available background remover websites aren't generally free. Isn't it cool to make our own background remover script that can extract only the subject from the image?

This can be implemented by using Scikit image or Open CV like image processing libraries.

[This](https://chris-s-park.medium.com/image-background-removal-using-opencv-part-1-da3695ac66b6) and [this](https://flothesof.github.io/removing-background-scikit-image.html) briefs about the implementation but not limited to. 

If working on this, make sure the PR contains well-documented `README.md` explaining the working of the script in detail along with examples for the users to understand. Also follow the Coding Style of the project without fail.

Let me know if any assistance is required for the same.

**Describe the solution you'd like**: A clear and concise description of what you want to happen.

**Additional context**: Add any other context or screenshots about the feature request here.

**Comment by pi-squared-4** [comment]
I am GSSOC'21 participant and I would love to work on this issue, can you assign me this?

**Comment by sohamsshah** [comment]
Okay great. Let me know if you need any assistance for implementing this. Make sure you follow the styling guidelines :)

**Comment by sohamsshah** [comment]
@pi-squared-4 Any specific reasons why you deleted the PR?

**Comment by pi-squared-4** [comment]
I did not.

**Comment by pi-squared-4** [comment]
I am sorry, I am contributing for the first time. So I may have messed up something, can you help me out ?

**Comment by vybhav72954** [comment]
@pi-squared-4 You deleted the PR by mistake i assume, and then rather than reopening the PR, you restored the branch, I have opened  the PR so @sohamsshah PLease review the PR

**Comment by vybhav72954** [comment]
> I am sorry, I am contributing for the first time. So I may have messed up something, can you help me out ?

Don't worry man, I have done similar things a lot of times XD, I even recently had to make a clone of a PR because I messed up git logs, it happens 😆

**Comment by pi-squared-4** [comment]
Alright, alright.

**Comment by vybhav72954** [comment]
> Thank you for so much support, I was afraid I will be kicked out after messing up so many times. ><

LOL Never XD

**Comment by sohamsshah** [comment]
@pi-squared-4 You did good work man. I have reviewed your PR. Make the changes and its good to be merged! And this is best part of OSS, collaboration. Never hesitate to ask questions :)

**Comment by RavjotSandhu** [comment]
Is it still open?

**Comment by vybhav72954** [comment]
> Is it still open?

A PR for this is open!

**Comment by vybhav72954** [comment]
@RavjotSandhu The issue is pen in case you want to take it

**Comment by iamakkkhil** [comment]
I have good knowledge of opencv and python to implement this issue and I have worked on similar projects as well. I would like to work on this issue if it is available. @vybhav72954 @sohamsshah 
I am a GSSoC'21 participant.

**Comment by sohamsshah** [comment]
@iamakkkhil Assigning you this issue. Feel free to ask any queries and raise a PR!
