### ISSUE TITLE
Welcome to GirlScript Summer of Code '2021

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#822]
Hello, Everyone ✨, Hope you guys are doing fine! 🙌

Thanks for showing your interest in being a part of the [GirlScript Summer of Code](https://gssoc.girlscript.tech/) 💥

We are super delighted to have you on board for your Contributions in [Rotten Scripts](https://github.com/HarshCasper/Rotten-Scripts) 🙌

We would be floating the links of communication challenges as soon as possible, where we will introduce ourselves and get to know each other. We can connect over social media channels as well, so Open Source is all about meeting awesome people and making important connections.

During this coming tenure of 3 months, we would focus on these fundamental objectives:

- Dead code/Bounty Hunting.
- Improve Documentation.
- Developing and enhancing our very own Static Website.
- Awesome scripts in multiple languages.

If you have any other ideas, features or a recommendation, we welcome you to start a discussion over [here](https://github.com/HarshCasper/Rotten-Scripts/discussions) or on our official channels (links to be posted soon).

We follow a specific workflow here at Rotten-Scripts:

- Search for issues that are `open-for-all`, i.e. No Assignees. OR Open an issue.
- Wait till the issue is assigned to you.
- **Only after** the issue is assigned to you, start working, we would be waiting for the Pull Request.
- Open the PR, every **Pull Request requires a review** from Maintainers and Admin. (It can take some time).
- Make changes if required. 
- And _voila_, your would-be merged asap.
- Important: Kindly ensure that the issue assigned to you has `GSSoC'21` label, if not ask the maintainers to do the same.

Here are some important documents, that we strongly request you to read:

- [CONTRIBUTING GUIDELINES](https://github.com/HarshCasper/Rotten-Scripts/blob/master/CONTRIBUTING.md)
- [STYLING GUIDELINES](https://github.com/HarshCasper/Rotten-Scripts/blob/master/STYLE_GUIDELINES.md)
- [PYTHON GUIDE](https://github.com/HarshCasper/Rotten-Scripts/blob/master/Python/CONTRIBUTION-GUIDELINE.md)

Finally, here are **must-follow** some rules:

- **Be Nice, Be Respectful** (BNBR)
- **Check** if the Issue you created, exists or not.
- Make **proper commit messages** and document your PR well.
- Always **add Comments** in your Code and explain it at points.
- **Dynamic Input is always preferred** over static Driver Code.
- **Squash your commits** before you push them.
- Always create a Pull Request from a Branch; **Never from the Master**.
- Follow proper Code conventions. Using` i`, `j` in Loops shows a poor understanding of Code Quality. **Use proper Variable, Function Names**.
- Issues would be served on **First Come, First Serve** basis.
- Issues would be tagged as `Level0`, `Level1`, `Level2` & `Level3`. Scores would be assigned on the **difficulty of the Issue you solve**.
- Code would be reviewed by Mentors before they are merged. **Every PR requires 3 Reviews**.

<b>Regards,</b>
<i>Harsh Mishra (@harshcasper), Project Administrator</i> 
<i>Vybhav Chaturvedi (@vybhav72954 ), Project Maintainer</i>
<i>Soham Shah ( @sohamsshah ), Project Miantainer</i>
<i>Seema Saharan ( @seema1711 ), Project Maintainer</i>

Happy Coding 🤗

**Comment by Supriya1702** [comment]
@vybhav72954  I am a GSSOC'21 Participant. I would like to contribute to this. Could you specify the changes needed in the documentation?

**Comment by AdityaRaj-ar** [comment]
Hello, I am Aditya one of the participants of GSSOC'21. Actually I am a beginner and don't have much knowledge about contributing to the project. But I really want to contribute and would give my level best to complete and contribute to the project. Therefore I request to assign this issue to me.
