### ISSUE TITLE
Script to keep PC awake 

### ISSUE THREAD

**Issue by Ayushjain2205** [HarshCasper/Rotten-Scripts#824]
# Description

A script to make the PC avoid going into standby mode.
The script will automatically perform mouse clicks and keystrokes which will keep the PC awake and the user need not worry about the PC entering into standby mode.

## Language

- [ ] Bash
- [ ] Go
- [ ] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Keep PC awake | This script will make sure the PC avoids getting into standby mode | GSSoC'21 | @ayushjain2205 |

**Comment by vybhav72954** [comment]
@Ayushjain2205 Updates please

**Comment by Ayushjain2205** [comment]
@vybhav72954  almost done with the code will make a PR in a days time
