### ISSUE TITLE
Update README Template

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#825]
# Intro

Recently we removed all the Images from the Repository, the images mostly lie in the READMEs, we now prefer using Image Hosting websites in order to keep the repo size in check.

# Problem

The [Readme Template](https://github.com/HarshCasper/Rotten-Scripts/blob/master/TEMPLATE_README.md) still hasn't been updated accordingly.

# Solution

A small GIF, explaining how an image can be hosted on a platform like `imgur`, along with generating the link and pasting it in a Markdown file.

Any other solution is also acceptable, but we will prefer a visual means so that it is easy to comprehend.

**Comment by pi-squared-4** [comment]
I am a gssoc'21 participant. 
Can you assign me this issue. I would love to work on it.

**Comment by vybhav72954** [comment]
Sure thing. As this is an easy documentation change, I am sure 2 days are enough? Try to Report by 12th March?

**Comment by pi-squared-4** [comment]
Okay, I'll do my best.

**Comment by pi-squared-4** [comment]
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/66795444/110646065-8808d300-81dc-11eb-9cd3-ff45ee0489d0.gif)

This will do?

**Comment by pi-squared-4** [comment]
Sure, will do.

**Comment by pi-squared-4** [comment]
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/66795444/110652201-28152b00-81e2-11eb-843a-2fc3da6f5b0b.gif)

This works?

**Comment by vybhav72954** [comment]
@pi-squared-4 If am not wrong, we are missing the online hosting part in this GIF

> ![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/66795444/110652201-28152b00-81e2-11eb-843a-2fc3da6f5b0b.gif)
> 
> This works?

**Comment by pi-squared-4** [comment]
![update_readme](https://user-images.githubusercontent.com/66795444/110653568-63fcc000-81e3-11eb-9581-92d61aaaa475.gif)

Sorry, my bad. Glitched on my end. Now?

**Comment by vybhav72954** [comment]
LGTM, Open a Pull Request please, and remember to host this GIF as well XD

**Comment by pi-squared-4** [comment]
XD. Yes sure.

**Comment by pi-squared-4** [comment]
![image](https://user-images.githubusercontent.com/66795444/110654884-8c38ee80-81e4-11eb-8ad4-0701a3d3e762.png)


This is a part of CONTRIBUTING.md and looks like this.

**Comment by vybhav72954** [comment]
I need a few changes, but before anything, please see if the branch from which you made the PR, is a branch from master or any other branch?

**Comment by pi-squared-4** [comment]
Sorry, sorry. This is my first time contributing to open souce.
I will fix it .

**Comment by vybhav72954** [comment]
> Sorry, sorry. This is my first time contributing to open souce.
> I will fix it .

Take your time, there is always a first time.

**Comment by pi-squared-4** [comment]
I created a new PR, check if everything works accordingly.

**Comment by HarshCasper** [comment]
@pi-squared-4 

Great work. Please take your time and its good to make mistakes at first so that some concepts become clear from the latter. Let us know if you are having any difficulties.

**Comment by pi-squared-4** [comment]
Did you merge my pr ?

**Comment by vybhav72954** [comment]
@pi-squared-4 Great Job, Just a pointer:

- It is always preferable to make changes in as few commits as possible.
- So next time, try to make all the changes in 1 commit.
- Also, i believe you can write better commit messages, cause you did that in some cases.

Thank you contributing, would love to see you again on this project, look for other issues as well if you want 👍🏻
