### ISSUE TITLE
New JavaScript README

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#826]
As proposed in #796

We need a new JS template as well. The details have been mentioned in #796 already, using the guidelines provided n that issue, propose a new JS template.

**Comment by vybhav72954** [comment]
@SSHREYA71 I can assign this to you!!!

**Comment by SSHREYA71** [comment]
> @SSHREYA71 I can assign this to you!!!

Sure! It will be a great start. I am eager to work on this.

**Comment by HarshCasper** [comment]
Good Luck @SSHREYA71 

@vybhav72954 is a great mentor and please reach out to him, if you have any difficulty solving this.

**Comment by SSHREYA71** [comment]
> Good Luck @SSHREYA71 
> 
> @vybhav72954 is a great mentor and please reach out to him, if you have any difficulty solving this.

Thank you so much. Surely i will reach out to him.

**Comment by sohamsshah** [comment]
@SSHREYA71 [This](https://github.com/ryanmcdermott/clean-code-javascript) might be useful for your implementation of documentation. Let me or any of the mentors know if you want any assistance for this.

**Comment by vybhav72954** [comment]
@sohamsshah @HarshCasper @SSHREYA71 Ok so this an error on my side. What I actually wanted was a JavaScript README which is easily editable, but by mistake, I wrote Template.

Though I have made this clear to Shreya over discord, I wanted to notify you guys as well. 

My Bad!!!

**Comment by sohamsshah** [comment]
> @sohamsshah @HarshCasper @SSHREYA71 Ok so this an error on my side. What I actually wanted was a JavaScript README which is easily editable, but by mistake, I wrote Template.
> 
> Though I have made this clear to Shreya over discord, I wanted to notify you guys as well.
> 
> My Bad!!!
> 
> Soham Thank you for the clean code guidelines though, soon I will open an issue for the same as well

Ah, gotcha. No worries ;)

**Comment by SSHREYA71** [comment]
> @SSHREYA71 [This](https://github.com/ryanmcdermott/clean-code-javascript) might be useful for your implementation of documentation. Let me or any of the mentors know if you want any assistance with this.

Sure,  Thank you.
