### ISSUE TITLE
Broken Link and Name in Python Folder

### ISSUE THREAD

**Issue by sohamsshah** [HarshCasper/Rotten-Scripts#830]
# Description 
In the `/Python` folder, the dir - [Merge_2_PFDs](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Merge_2_PFDs) is misspelled accidentally. This has perhaps caused error while accessing the link from the `README.md` file list of the scripts in Python.

Please look into this and resolve:
- Rename the Directory as `Merge_2_PDFs`
- In that folder, there is a file named `Readme.MD`. Change it to `README.md` to follow good naming style.
- Check and confirm that this Script has a reference listed properly in the table of README.md in the Python Directory.
- If not, then please resolve accordingly.

Feel free to ask any queries re: issue. This must a quick fix.

**Comment by Priya730** [comment]
Hey! I would like to work on this issue, kindly assign it to me.

**Comment by vybhav72954** [comment]
> Hey! I would like to work on this issue, kindly assign it to me.

Hi Priya, this is a very small change, can you do this by evening 4 p.m.?

**Comment by Priya730** [comment]
> > Hey! I would like to work on this issue, kindly assign it to me.
> 
> Hi Priya, this is a very small change, can you do this by evening 4 p.m.?

Yes!

**Comment by vybhav72954** [comment]
I willl review it soon

**Comment by Priya730** [comment]
> I willl review it soon

Sure! Thanks!
