### ISSUE TITLE
Add GSSoC'21 in Open_Source_Events

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#831]
Add GSSoC'21 in Open_Source_Events

Link to the [directory](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Open_Source_Events)

**Comment by vybhav72954** [comment]
Best of Luck, You can ask for help if required.

**Comment by Subhangini** [comment]
Is there any deadline for submitting PR for this issue

**Comment by vybhav72954** [comment]
This is not a major change, so I think, by today evening is an ample amount of time?
