### ISSUE TITLE
Translator Script in Python

### ISSUE THREAD

**Issue by NEERAJAP2001** [HarshCasper/Rotten-Scripts#834]
# Description
It's a python script to translate one language to another.
Uses Google Trans Library so requires : ```pip install googletrans==3.1.0a0```

## Language
- [x] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees  |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| TransLang  | A python script to translate languages  | GSSOC-21 | @NEERAJAP2001|

**Comment by vybhav72954** [comment]
@HarshCasper What do you think about the viability of the Issue?

**Comment by NEERAJAP2001** [comment]
@vybhav72954 Can This issue get GSSOC Tag?

**Comment by vybhav72954** [comment]
> @vybhav72954 Can This issue get GSSOC Tag?

Please wait till @HarshCasper can confirm the viability of the issue. I suggest not starting a PR

**Comment by NEERAJAP2001** [comment]
any updates @vybhav72954?

**Comment by vybhav72954** [comment]
> any updates @vybhav72954?

I will get this done by tonight for sure

**Comment by HarshCasper** [comment]
I don't think translator scripts hold much value. My reasoning being: 

- People generally prefer Web-based Translators
- Translation Script essentially here is as easy as installing a module and calling it
- People generally would not use a CLI for this

Thanks for creating the Issue!
