### ISSUE TITLE
Word cloud generator using python

### ISSUE THREAD

**Issue by Rupa-421** [HarshCasper/Rotten-Scripts#841]
needed **This template is strictly for requesting New Scripts, if you want a new feature (automating this Repo,**
**a change in structure) in the Repo,** 
**or you want to report a Bug. There are other templates which you should follow**

# Description

 I want to add python scripts for generating word cloud which is a famous data visualization technique used.

## Language

- [ ] Bash
- [ ] Go
- [ ] Javascript
- [ ] Powershell
- [x] Python
- [ ] Other (Please specify)

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Wordcloud_Generator | Adding new feature | GSSOC21 | @Rupa-421 |

**Is your feature request related to a problem? Please describe.**: No it's not about fixing any bug.It's just a new additional feature that is cool to implement.

**Describe the solution you'd like**: I'm going to use pandas to read the data needed. Then I will use word cloud module to generate word cloud. Then I will display output using matplotlib.

**Additional context**: Word clouds are widely used for analyzing data from social network websites.

**Comment by vybhav72954** [comment]
@Rupa-421 Welcome to Rotten-Scripts.

We have this script [already](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Create_Word_Cloud).

Can you make this better, if yes tell us how and I will assign this to you

**Comment by Rupa-421** [comment]
Yeah ,I can make it better it take input of only text file according to present code but I can add feature to add even Excel and CSV file's then I will read the data from those files and convert them to string by that I can generate wordcloud.So if you like this feature you can assign me 😁

**Comment by vybhav72954** [comment]
Excel and CSV files sound good to me, @HarshCasper What do you think?

**Comment by HarshCasper** [comment]
Looks good to me! Assigned 🎉

**Comment by rahulraikwar00** [comment]
@Rupa-421  any update?

**Comment by Rupa-421** [comment]
@rahulraikwar00 Updated...
