### ISSUE TITLE
Tech Stack Update ( LOGO add )

### ISSUE THREAD

**Issue by rohank2502** [HarshCasper/Rotten-Scripts#842]
I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

**Comment by vybhav72954** [comment]
@HarshCasper Over to you

**Comment by rohank2502** [comment]
Thanks !

**Comment by vybhav72954** [comment]
> Thanks !

Kindly note that the issue hasn't been assigned.  Please wait for the PA to check the viability of the issue, then only start working on it.

**Comment by HarshCasper** [comment]
I don't think we need it as of such. We are expanding more by adding new languages like Rust, Elixir so they would need to expand dynamically. On the other hand, if you have ideas to make the README more flexible and beautiful, you can create an Issue for sure.
