### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohank2502** [HarshCasper/Rotten-Scripts#843]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by vybhav72954** [comment]
@rohank2502 The script follows `all-contributors` specification. How is your suggestion better?

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 The script follows `all-contributors` specification. How is your suggestion better?

Means ?

**Comment by vybhav72954** [comment]
This project follows [this](https://allcontributors.org/) method for updating the contributors' list. How is the solution that you want to provide is better than the one we are already using

**Comment by vybhav72954** [comment]
@rohank2502 Please update

**Comment by HarshCasper** [comment]
I don't think we need a new contributor section.
