### ISSUE TITLE
Make PyLint ignore Module Docstring

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#849]
# Description 
The PyLint report generates an error ```C0114 (missing-module-docstring)``` for most of the Python files.

We don't need this sanity check for our Repo.

So we can make sure that PyLint ignores it.

**Expected behavior**
PyLint should ignore Missing DocString.

**Additional context**
The solution is rather simple and requires some small edits it in this [config file](https://github.com/HarshCasper/Rotten-Scripts/blob/master/.github/linters/.python-lint.yml)

For reference here is a [thread](https://stackoverflow.com/questions/7877522/how-do-i-disable-missing-docstring-warnings-at-a-file-level-in-pylint).

**Comment by priyanshu20** [comment]
Hey @vybhav72954 in the config file under Message controls there is a list of codes that are disabled. To fix the issue do we have to add C0114 do the list?

**Comment by vybhav72954** [comment]
@priyanshu20 You just need to add the ID there, yes!!!

**Comment by priyanshu20** [comment]
Thank you , I was confused by the level2 tag, and thought I did not understand the issue completely.

**Comment by vybhav72954** [comment]
Yeah, I labeled it by mistake. SMH
