### ISSUE TITLE
Script for BitCoin Mining in Python

### ISSUE THREAD

**Issue by NEERAJAP2001** [HarshCasper/Rotten-Scripts#856]
# Description

It's a script to mine bitcoin but It actually won't reward any bitcoin as the difficulty level is 20 which requires huge processors for rewarding.
So, It's a fun project to understand how hashing, etc works.
I will give complete details in a pdf file to understand everything from scratch.
I would Like to work on this issue as well as part of GSSOC-21.
Thanks

## Language

- [ ] Bash
- [ ] Go
- [ ] Javascript
- [ ] Powershell
- [x] Python
- [ ] Other (Please specify)

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| BitCoin_Mining | A Script for mining BitCoin| feature | @NEERAJAP2001|

**Comment by NEERAJAP2001** [comment]
@HarshCasper is this issue viable for GSSOC-21
Thanks

**Comment by vybhav72954** [comment]
This looks good, you can start working @NEERAJAP2001
