### ISSUE TITLE
Heart disease prediction

### ISSUE THREAD

**Issue by aaadddiii** [HarshCasper/Rotten-Scripts#861]
**This template is strictly for requesting New Scripts, if you want a new feature (automating this Repo,**
**a change in structure) in the Repo,** 
**or you want to report a Bug. There are other templates which you should follow**

# Description

Please include a summary of the issue. 
This is machine learning model trained using ucl heart disease dataset , the script predicts whether a person has heart disease or not by inputing health condition of the patient
## Language

- [x] Python

## Checklist:

- **Details on the Script**

The script predicts whether a person is affected from heart disease or not

heart disease predictor

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Heart disease predictor | predicts whether a person has heart disease or not | gssoc'21 | @aaadddiii |

**Is your feature request related to a problem? Please describe.**: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**: A clear and concise description of what you want to happen.

**Additional context**: Add any other context or screenshots about the feature request here.

**Comment by sagniknayak** [comment]
I am a GSSOC '21 participant.
I would like to work on this issue.
Please assign me for this.

**Comment by sagniknayak** [comment]
How do I self-assign this issue?

**Comment by sagniknayak** [comment]
I cannot assign myself this issue because it has already been assigned you @aaadddiii. Could you please help me with this?

**Comment by vybhav72954** [comment]
@sagniknayak Author mentioned their GitHub handle in the body of the issue, so its assigned to him, please take other issue
