### ISSUE TITLE
Markdown to HTML converter 

### ISSUE THREAD

**Issue by sohamsshah** [HarshCasper/Rotten-Scripts#869]
# Description

This Script would convert markdown files into HTML. Can be extremely useful for developers who are implementing modern text enhancement features as most blog sites, note apps etc. are adapting markdown support.

## Language

- [X] Javascript
- [X] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Markdown to HTML converter | Easily convert Markdown to HTML by use of available parsing libraries | Python, JavaScript, good-first-issue | self-assign if you want to work on this issue else leave blank |

**Describe the solution you'd like**: A clear and concise description of what you want to happen.

There are various PyPI libraries or npm packages available for this implementation. The idea is to add an automation script that can demonstrate how this can be done.

This has a lot of utility and thus this can be a good start point for anyone who wants to explore libraries. And of course, this is not limited to just conversion, but on top of it some good use-cases can be added as examples, that can be good.

This can be a good script to work on for beginners. Would work closely with the assignees for this implementation.

**Comment by sohamsshah** [comment]
@divyanshu887 Do let me know if you need any assistance while working on this.

**Comment by Pretty-19** [comment]
@sohamsshah  new to open-source was interested in contributing.

**Comment by sohamsshah** [comment]
> @sohamsshah new to open-source was interested in contributing.

Thank you for the interest. If Divyanshu isnt working, I will assign this issue to you. Else, there are many open issues on the Repo, you can work on those as well or if you have some good automation script idea, feel free to create an issue and lets discuss.

**Comment by varshith-k** [comment]
@sohamsshah I'm Interested in this. If no one is picking up it in time, Please assign this to me.

**Comment by divyanshu887** [comment]
> @divyanshu887 Are you working on this?

yes i am on it @sohamsshah

**Comment by sohamsshah** [comment]
> > @divyanshu887 Are you working on this?
> 
> yes i am on it @sohamsshah

Okay great. 🙌

**Comment by vybhav72954** [comment]
> > @divyanshu887 Are you working on this?
> 
> yes i am on it @sohamsshah

Can you confirm if you are a GSSOC participant

**Comment by divyanshu887** [comment]
> > > @divyanshu887 Are you working on this?
> > 
> > 
> > yes i am on it @sohamsshah
> 
> Can you confirm if you are a GSSOC participant

yes i am gssoc participant

**Comment by N-Shar-ma** [comment]
Can I please be assigned to work on this issue?
