### ISSUE TITLE
Broken Image link [Documentation]

### ISSUE THREAD

**Issue by BJSwaroop** [HarshCasper/Rotten-Scripts#870]
# Description 
As I am new to open source. I am contributing in documentation first.

About - The image link has been broken in the file Automate_Telegram[Python]. I want to change the link and fix that.

"Found a bug in Automate_Telegram[Python]."

I am participating in GSSoC '21 
I need label of GSSoC '21

Assignees - @vybhav72954 @HarshCasper Can I work On this issue?

**screenshots**
![image](https://user-images.githubusercontent.com/72175383/111715916-ef78ef80-887a-11eb-8042-20fe88c3fdca.png)

**Comment by BJSwaroop** [comment]
I want to work on this.

**Comment by vybhav72954** [comment]
Cool! Please go through the whole Repo. And try to find a few more broken link, update them as well in the same PR, accordingly, I will put the difficulty label.
