### ISSUE TITLE
Change the spell checking action!

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#872]
So some of you might have noticed, the spell-checking action is a bit of a mess.

It creates too much noise, and is usually ignored by the contributors and maintainers.

I want to change the action (I made it in the first place and it's not up to the mark).

Go to the [action](https://github.com/HarshCasper/Rotten-Scripts/actions/workflows/md_spell.yml), figure out the problems, search for solutions, tell me the possibilities and then only make a PR.

**Comment by DiegoCaraballo** [comment]
Hello @vybhav72954 

The documentation says the following:

When and if the run finds spelling errors, you have two options:

- Correct spelling mistakes in relevant files

- Add the relevant words to a custom word list, to be ignored

If you do the latter, you must add the following to the spell checker settings, in the dictionary:

       word lists:
       - .wordlist.tx

In my opinion, words should be added to this dictionary.

Regards

**Comment by vybhav72954** [comment]
@DiegoCaraballo Thanks for having a look at this, but here you can see, we have a [wordlist](https://github.com/HarshCasper/Rotten-Scripts/blob/master/.github/linters/.wordlist.txt)

**Comment by DiegoCaraballo** [comment]
@vybhav72954 
Yes, I understand it, but the ones that give an error are others:

![1](https://user-images.githubusercontent.com/21015263/111830382-9d60ba00-88cc-11eb-8fba-a934138db61f.PNG)

**Comment by vybhav72954** [comment]
Oh, wait!
I haven't mentioned the wordlist in the YAML file.

That's my mistake!

But there is another problem in the action, As you might have noticed, all the MD files in the codebase are being checked for every PR.

`wordlist` can solve a small part of the problem, but the major problem will remain the same.

In case you want you can add the wordlist in the action workflow.

**Comment by Nidhi-2000** [comment]
Hey, I am a GSSOC'21 participant . can you please assign this issue to me @vybhav72954

**Comment by vybhav72954** [comment]
> Hey, I am a GSSOC'21 participant . can you please assign this issue to me @vybhav72954

Sure thing, how do you propose to solve this out?

**Comment by Nidhi-2000** [comment]
We can add word list in the action flow itself so that it can solve the issue @vybhav72954

**Comment by vybhav72954** [comment]
> We can add word list in the action flow itself so that it can solve the issue @vybhav72954

That might be a start, add it in the workflow.

It won't help us a lot but yeah, you can do that.

**Comment by vybhav72954** [comment]
@Nidhi-2000 Updates

**Comment by vybhav72954** [comment]
@Nidhi-2000 Updates?
