### ISSUE TITLE
Notify Real Time Stock Market Updates via a Slack Bot using Slack API

### ISSUE THREAD

**Issue by sohamsshah** [HarshCasper/Rotten-Scripts#881]
# Description

This Script must add a Slack Bot to the workspace which notifies the user whenever there is an update in the Stock Market Prices. 
This Slack Bot will help the user be notified. Idea is to make this Script handy for the people investing in Stock Market. Moreover, this script isn't limited to just this idea. On Brain storming an amalgamation of multiple APIs to serve a specific need can also be extended. Eg. Along with Stock Market, we also provide updates for Rupee value, Gold rate etc. which can be extremely handy for the traders. 

## Language

- [X] Javascript
- [X] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Slack Notifier | Real Time Notifier Slack Bot that keeps the user updated for Stock Market Prices  | feature | self-assign if you want to work on this issue else leave blank |

**Describe the solution you'd like**: A clear and concise description of what you want to happen.

[SLACK API](https://api.slack.com/) provides various functionalities for implementing this feature. IMO, webhooks can be a simpler way for this; though many other ways are available for the implementation.

Third Party APIs are required for fetching the Real Time Stock Market Price Update for a particular stock or multiple. Can keep that variable. Also, according to the opinions and creativity from the assignee for this feature, other APIs can be appended. 

**Additional context**: 
This is a good issue to work on if you wanna explore SLACK API. Slack integration is highly used in various applications such as ChatBots, Analytics etc. tools in order to track and interract with the users on the fly.

Let me know if you want to work on this. First, before assignment; would love to know what will be your work flow and overall clarity on implementation. Would love to work closely with the assignees for this particular task!

**Comment by sohamsshah** [comment]
@vybhav72954 @HarshCasper @seema1711 any views upon this?

**Comment by TITHI007** [comment]
Pl. Assign it to me

**Comment by vybhav72954** [comment]
@TITHI007 Are u a GSSOC participant?

**Comment by TITHI007** [comment]
> @TITHI007 Are u a GSSOC participant?
No

**Comment by Nidhi-2000** [comment]
hey, i am a GSSOC '21 participant. can younplease assign this issue to ,me

**Comment by Nidhi-2000** [comment]
hey, i am a GSSOC '21 participant. can younplease assign this issue to ,me

**Comment by Nidhi-2000** [comment]
hey, i am a GSSOC '21 participant. can younplease assign this issue to ,me @vybhav72954

**Comment by Nidhi-2000** [comment]
hey, i am a GSSOC '21 participant. can younplease assign this issue to ,me @vybhav72954

**Comment by sohamsshah** [comment]
@TITHI007 are you working on this?

**Comment by TITHI007** [comment]
> @TITHI007 are you working on this?

You can assign it to other 
As it will take time for me to complete ..

**Comment by sohamsshah** [comment]
@Nidhi-2000 Assigning you this issue. Feel free to reach out for any queries, doubts or discussions related to its implementation. Just make sure that this should be a CLI app that uses Node.js or similar. Frontend is not needed for this.
Thanks,
S.

**Comment by vybhav72954** [comment]
@Nidhi-2000 Updates?

**Comment by vybhav72954** [comment]
@Nidhi-2000 Updates?
