### ISSUE TITLE
Initialize a HTTP Server

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#9]
## AIM

Create a Script to initialize an HTTP Server.

## Languages

- Python
- Javascript

## Details

In this Script, you have to initialize an HTTP Server straight from the Command-Line.

**Comment by seema1711** [comment]
Can I work on this?

**Comment by HarshCasper** [comment]
You have been assigned this Issue @seema1711 

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also, reference this Issue in your PR so that it becomes easy for us to review.
