### ISSUE TITLE
Simple Python IDE using Tkinter

### ISSUE THREAD

**Issue by Priyadarshan2000** [HarshCasper/Rotten-Scripts#904]
**This template is strictly for requesting New Scripts, if you want a new feature (automating this Repo,**
**a change in structure) in the Repo,** 
**or you want to report a Bug. There are other templates which you should follow**

# Description

In this project, I will deploy a simple Python IDE application with the help of the Tkinter module. This application just like a python IDE. we can save our code and run this IDE. we can open our exciting Project in this IDE.

## Language

- [ ] Bash
- [ ] Go
- [ ] Javascript
- [ ] Powershell
- [x] Python
- [ ] Other (Please specify)

## Checklist:

- **Details on the Script**
- This python script will create a Simple Python IDE using Tkinter
- Modules used will be:-
   1.tkintertable
    2. subprocess.run

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Simple Python IDE using Tkinter | A Simple Python IDE | GSSoC'21 | @priyadarshan2000 |

## A demo of the script:-
![image](https://user-images.githubusercontent.com/62868878/112881685-9ebe8d80-90e9-11eb-8ecb-6677896f3640.png)

@HarshCasper I am a GSSoC'21 participant and I think this is an interesting python script of the GUI domain. Kindly allow me to work on this issue and contribute to this project!

**Comment by vybhav72954** [comment]
@Priyadarshan2000 The idea is defined good, but generally, GUI scripts arent preferred in Rotten-Scripts, still I would leave this to @HarshCasper to decide

**Comment by Priyadarshan2000** [comment]
Ok sir

**Comment by HarshCasper** [comment]
We don't need GUI-Apps. Thanks for creating the Issue!
