### ISSUE TITLE
Update Invisibility Cloak (See comments)

### ISSUE THREAD

**Issue by Dhanush2612** [HarshCasper/Rotten-Scripts#915]
Python Program to perform invisibility cloak

**Comment by Dhanush2612** [comment]
@vybhav72954 @HarshCasper 
Kindly assign me this issue.

**Comment by vybhav72954** [comment]
Already exists [here](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Invisible_Cloak)

But as the there is no proper documentation for the file, feel free to do the same

**Comment by vybhav72954** [comment]
If you can enhance the script feel free to do so, a proper README is a must in any case.

**Comment by Harshil-Gupta** [comment]
Can I work on this and give it a proper README as it is not yet assigned to anyone? @vybhav72954

**Comment by vybhav72954** [comment]
> @vybhav72954
> Do you want me do the project or only add readme file to the existing one?

@Dhanush2612 Do you want to work on this, please confirm

**Comment by Dhanush2612** [comment]
@HarshCasper 
I will work on it

**Comment by vybhav72954** [comment]
> Can I work on this and give it a proper README as it is not yet assigned to anyone? @vybhav72954 

Hey Harshil, Dhanush opened the issue so according to guidelines, he should have a say here. Am assigning the issue to him, feel free to take others

**Comment by vybhav72954** [comment]
@Dhanush2612 Update?

**Comment by tanishq-arya** [comment]
@vybhav72954 please assign me this issue. I will add the proper readme.
