### ISSUE TITLE
Document to Handwritting 

### ISSUE THREAD

**Issue by Priyadarshan2000** [HarshCasper/Rotten-Scripts#921]
**This template is strictly for requesting New Scripts, if you want a new feature (automating this Repo,**
**a change in structure) in the Repo,** 
**or you want to report a Bug. There are other templates which you should follow**

# Description

I would like to add a Document to the Handwriting javascript app. This application helps convert document to handwriting.
this is made with the help of **Google Font API**

## Language

- [ ] Bash
- [ ] Go
- [x] Javascript
- [ ] Powershell
- [ ] Python
- [ ] Other (Please specify)

## Checklist:

- **Details on the Script**
- This Javascript script will be created Document to Handwritting Website
- Google font API
## Functionalities:

- Convert to Document to the handwriting
- 10 different type of font
- Dark mode
- Download your work in png Format.
- change font size, font width.

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Document to Handwriting  | Text to handwriting converter | GSSoC'21 | @priyadarshan2000 |

## A demo of the script:-
![image](https://user-images.githubusercontent.com/62868878/113031028-d857cd00-91ab-11eb-84d5-1b8475d29246.png)

@HarshCasper I am a GSSoC'21 participant and I think this is an interesting Javascript script of the javascript domain. Kindly allow me to work on this issue and contribute to this project!

**Comment by vybhav72954** [comment]
That's weird, It should be working 😞 
@HarshCasper Please see the viability of this JS issue

**Comment by Priyadarshan2000** [comment]
@vybhav72954 vybhav72954 sir can I started this project.

**Comment by vybhav72954** [comment]
No `sir` here, please.
And please wait for the PA to review this issue,

**Comment by Priyadarshan2000** [comment]
ok.

**Comment by vybhav72954** [comment]
Cool it worked, i as worried XD
@Priyadarshan2000 The issue has been assigned to you but please wait for a bit before start working on this.

**Comment by Priyadarshan2000** [comment]
ok @vybhav72954

**Comment by Priyadarshan2000** [comment]
sir can I started this project or still, I hold @HarshCasper,@vybhav72954 sir.

**Comment by HarshCasper** [comment]
@Priyadarshan2000 

You can go ahead. Remember one thing: No GUI Apps. Only Scripts. Make something that can be launched from the terminal itself.

**Comment by Priyadarshan2000** [comment]
Sir this project has a html file i can use html to build this project ..?

**Comment by HarshCasper** [comment]
> @HarshCasper Sir this project has a html file i can use html to build this project ..?

Nope. Not at all. 

I have closed many past PRs that were deviant from our purpose.

**Comment by vybhav72954** [comment]
@Priyadarshan2000 Update?
