### ISSUE TITLE
Add verbose mode for PR_workflow script  

### ISSUE THREAD

**Issue by rahulraikwar00** [HarshCasper/Rotten-Scripts#923]
# Description

Update PR_workflow script. As you might have noticed, there is option for verbose mode but the feature is missing 
i want to work on this and want to add verbose mode in it.

@vybhav72954 
@HarshCasper 

| name            | problem/motivation                                                  | possible solution  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| verbose mode | missing verbose mode | by using graphQL query | @rahulraikwar00  |

**Comment by rahulraikwar00** [comment]
@vybhav72954 what do you think ?

**Comment by vybhav72954** [comment]
Sure thing, that would be a great idea, verbose messages will help for sure!

**Comment by rahulraikwar00** [comment]
@vybhav72954  can you add some other tags like level and python  ?
