### ISSUE TITLE
URGENT: Add/Update a greetings github action.

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#924]
# Description

Update/Add a new Github action for greeting purposes.

| name            | problem/motivation                                                  | possible solution  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| GitHub Action for Greetings | Current Greeting action can be far better | Explained Below | up for grabs |

**Possible Solution**

The current greetings action bot only triggers whenever a new contributor makes a new Issue/PR, we no longer need that, with the increasing contributor retention, I believe we can change the action to be triggered on every new  Issue/PR.

**Describe alternatives you've considered**

There is multiple actions/bot that one can play with for this case.

**Additional context**

The bot should actually print a meaningful message, link to contribution and styling guidelines is a must, but if you can think of something more creative, feel free to suggest.

**Comment by vybhav72954** [comment]
The Reason I added the `documentation` label was because I want to use this action/bot/workflow to direct people to actually go through the `Contribution Guidelines/Styling Guideline's` for once. Also as this might involve changing the internal documentation of the repo or the configurations.

**Comment by vybhav72954** [comment]
Talking about solving the issue, see this [YAML](https://github.com/HarshCasper/Rotten-Scripts/blob/master/.github/workflows/greetings.yml) file. We need to either update this, or change this completely so that it is triggered on every issue rather than the first issues by a participant!

**Comment by himanshu007-creator** [comment]
Hi , i would like to work on this issue

**Comment by sshiv5768** [comment]
Hi, I want to work on this issue. Assign me

**Comment by vybhav72954** [comment]
> Hey @vybhav72954, I want to work on this issue. Assign me

Sure why not! But kindly tell me what are your plans related to this first

**Comment by sshiv5768** [comment]
First, we will create a new workflow in Github actions and choose greetings workflow. Okay, @vybhav72954?

**Comment by vybhav72954** [comment]
Am sorry but as i mentioned we already have that workflow. @sshiv5768

**Comment by sshiv5768** [comment]
Can you elaborate on it in deep? I think we also need changes to the YAML file that you shared?

**Comment by sshiv5768** [comment]
I think currently we are focusing on the master branch right? @vybhav72954. If so then we need this:
`  on:  pull_request:
           push:
                   branches:
                                  - master   `

**Comment by vybhav72954** [comment]
No its not that simple ib this case.

As you can see, the action specifically filters the first time contributors. We no longer need that.

**Comment by sshiv5768** [comment]
What if we change the action and use another. I found this as an alternative: [.](https://github.com/marketplace/actions/greet-contributors-action) @vybhav72954

**Comment by vybhav72954** [comment]
@sshiv5768 Can you look for something more subtle please, lets keep it in back of our minds, and look for better options.

**Comment by vybhav72954** [comment]
@sshiv5768 
Found anything interesting?

**Comment by Sukriti-sood** [comment]
@vybhav72954  If we want to add comments when a pull request/issue opened, we could use  action [create or update comment](https://github.com/marketplace/actions/create-or-update-comment) to implement this. Possible ?

**Comment by vybhav72954** [comment]
@Sukriti-sood Hey the implementation looks good, not sure how this will help us though, can you suggest me what you have in mind.

**Comment by Sukriti-sood** [comment]
@vybhav72954  It will compare github events and moroever I find good resource [Link](https://github.community/t/can-we-greet-with-message-on-every-new-issue-created-opened-not-just-the-first-one/18082/2) and I have tried it is working.

**Comment by vybhav72954** [comment]
> @vybhav72954 It will compare github events and moroever I find good resource [Link](https://github.community/t/can-we-greet-with-message-on-every-new-issue-created-opened-not-just-the-first-one/18082/2) and I have tried it is working.

Hey, that's cool. Would you like to take this issue?

**Comment by Sukriti-sood** [comment]
> > @vybhav72954 It will compare github events and moroever I find good resource [Link](https://github.community/t/can-we-greet-with-message-on-every-new-issue-created-opened-not-just-the-first-one/18082/2) and I have tried it is working.
> 
> Hey, that's cool. Would you like to take this issue?
Ya , interested

**Comment by vybhav72954** [comment]
> > > @vybhav72954 It will compare github events and moroever I find good resource [Link](https://github.community/t/can-we-greet-with-message-on-every-new-issue-created-opened-not-just-the-first-one/18082/2) and I have tried it is working.
> > 
> > 
> > Hey, that's cool. Would you like to take this issue?
> 
> Ya , interested

Sure thing!

[Here](https://github.com/Karthik-Nayak98/Greeting-action) is a solution which I had found, I like the idea, and to be honest it solves the purpose for me. But I opened this issue so that I can have a look at other possibilities as well.

Now I want you to do 2 things. Compare your idea to the action I found. Suggest me the better option, and make a PR.

**Comment by Sukriti-sood** [comment]
> > > > @vybhav72954 It will compare github events and moroever I find good resource [Link](https://github.community/t/can-we-greet-with-message-on-every-new-issue-created-opened-not-just-the-first-one/18082/2) and I have tried it is working.
> > > 
> > > 
> > > Hey, that's cool. Would you like to take this issue?
> > 
> > 
> > Ya , interested
> 
> Sure thing!
> 
> [Here](https://github.com/Karthik-Nayak98/Greeting-action) is a solution which I had found, I like the idea, and to be honest it solves the purpose for me. But I opened this issue so that I can have a look at other possibilities as well.
> 
> Now I want you to do 2 things. Compare your idea to the action I found. Suggest me the better option, and make a PR.

Ook , Will give updates soon.

**Comment by vybhav72954** [comment]
@Sukriti-sood Updates?
