### ISSUE TITLE
YouTube downloader in rust

### ISSUE THREAD

**Issue by gokulsoumya** [HarshCasper/Rotten-Scripts#930]
# Description

Proposal to build a simple YouTube video downloader in rust.

## Language

Rust

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| ytdl | Download videos from YouTube from the commandline | GSSOC21 | @gokulsoumya |

**Additional context**: 

#811, #838

**Comment by vybhav72954** [comment]
@gokulsoumya Hey there, any updates?

**Comment by gokulsoumya** [comment]
@vybhav72954 Sorry for the delay; I was caught up with college work. I'll try to get a working script up by tomorrow :)

**Comment by gokulsoumya** [comment]
@vy

**Comment by gokulsoumya** [comment]
@vybhav72954 completed the script and squashed the commits :) Sorry again for the delay 😅
