### ISSUE TITLE
Script to fetch all Issues/PRs and store them in a CSV/JSON File

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#932]
# Description

Create a Script to fetch all Issues/PRs and store them in a CSV/JSON File. It should ideally work as a handy CLI tool that can allow the maintainers to capture the data trends of the repository. For the Issues, capture the following data points: 

- Issue Creator
- Issue Assignee 
- Corresponding PR (if any)
- Issue Open/Close Date 
- People who commented on the Issue (Numbers and their Username) 
- Issue Content

For the PRs capture the following data points: 

- PR Creator
- Merged/Closed 
- PR Open/Close/Merge Date 
- Reviewers (Numbers and their Username) 
- Who merged the PR? 
- PR Content
- Files changed

## Language

- [x] Go
- [x] Javascript
- [x] Python

**Comment by Naman-1234** [comment]
@HarshCasper Sir I would like to work on Issue Part with Javascript, I have worked with Javascript Before,So I know how to approach this. I am a Gssoc Participant.
Also Could you add a label of level in it .Thanks.

**Comment by Jaideep07** [comment]
@HarshCasper, I would like to do this in python can I proceed 😀

**Comment by Naman-1234** [comment]
@HarshCasper, Pls kindly check why have I not recieved points for this PR.  Please check sir, I nearly worked for 15 days on this issue to merge this. It would be great if I could get the points for that. Looking forward for a reply.
