### ISSUE TITLE
Script to fetch Linux Package Information and save them to a CSV/JSON

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#934]
# Description

Create a Script to fetch Linux Package Information and save them to a CSV/JSON. We would like to collect these data points: 
- Name of the Package
- Size of the Package
- Licences Information
- Source Code Link 

We can use the command(s) provided by each Linux distribution to handle their packages and collect the information.

## Language

- [X] Golang
- [X] Javascript
- [X] Python

**Comment by haarsh01** [comment]
Hey, I am a GSSOC 21 participant. Please assign me this issue.

**Comment by vybhav72954** [comment]
@haarsh01 Updates?
