### ISSUE TITLE
Script to find Twitter Unfollowers

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#935]
# Description

Create a Script to find Twitter Unfollowers. You can use a client library to fetch all Twitter followers and store them on a lightweight database, and on being invoked the next time, compare the followers and find the ones who unfollowed you.

## Language

- [X] Golang
- [X] Python
- [X] JavaScript

**Comment by jhamadhav** [comment]
Can I work on this using javascript, as of GSSOC'21?

**Comment by vybhav72954** [comment]
Sure thing 😄

**Comment by jhamadhav** [comment]
Thank you! I will start working on it ASAP.
Out of curiosity, what is the deadline to complete this?

**Comment by vybhav72954** [comment]
> Thank you! I will start working on it ASAP.
> Out of curiosity, what is the deadline to complete this?

How much do you think you will need 🤔

**Comment by jhamadhav** [comment]
I'm not familiar with Twitter API yet, so I might take some time is one week okay?

**Comment by vybhav72954** [comment]
> I'm not familiar with Twitter API yet, so I might take some time is one week okay?

1 week it is!

**Comment by jhamadhav** [comment]
cool thanks a bunch 😃
