### ISSUE TITLE
Pomodoro Timer / Tomato Clock along with Website Blocker

### ISSUE THREAD

**Issue by RohiniRG** [HarshCasper/Rotten-Scripts#942]
# Description

<b>Pomodoro Timer</b> : It’s a hyper-productivity method that focuses on dividing your working time into chunks of 25 minutes of intense work combined with 5 minute breaks.

| name            | problem/motivation                                                  | possible solution  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Pomodoro Timer | Increasing Productivity by using this timer | By using <b>Python</b> will create a command-line based Pomodoro timer which will set the timer for 25 minutes and all block all the distracting websites during that time. | @RohiniRG |

**Comment by RohiniRG** [comment]
@HarshCasper @vybhav72954 could you please have a look and add the GSSoC'21 labels

**Comment by vybhav72954** [comment]
@RohiniRG This will be done by tonight for sure, thank you for patience

**Comment by RohiniRG** [comment]
> @RohiniRG This will be done by tonight for sure, thank you for patience

@vybhav72954 @HarshCasper could you please let me know
