### ISSUE TITLE
Domain name availability

### ISSUE THREAD

**Issue by iamakkkhil** [HarshCasper/Rotten-Scripts#943]
# Description

Using Python web scraping tool like beautiful soup this script scrapes domain name from godaddy.com and let you know the available domain names regarding the specific keyword.

| name            | problem/motivation                                                  | possible solution  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Domain Name Availability | Checking available names with a specific brand name or keyword | By using Python and Beautiful soup, this script will scrape available domain names from godaddy.com and save them into a text file. | @iamakkkhil  |

**Comment by iamakkkhil** [comment]
I am a GSSOC 21 participant .
@HarshCasper @vybhav72954 can you add a GSSOC 21 label and level tag

**Comment by vybhav72954** [comment]
@HarshCasper Please check the viability of the issue, i like the idea

**Comment by HarshCasper** [comment]
> @HarshCasper Please check the viability of the issue, i like the idea

Its good. Awaiting the PR now!

**Comment by iamakkkhil** [comment]
Fine I was waiting for your conformation only, will submit the PR ASAP

**Comment by iamakkkhil** [comment]
Hey, 
I am stuck 
link: https://in.godaddy.com/domainsearch/find?checkAvail=1&domainToCheck=akhil

soup.find() is always returning None. I am in search of <div class="domain-name" > which is deep inside <div id='search-app>
Can you help me out 

OR
I have an alternate solution for the same can I take a scrolling screenshot by using selenium.
is it fine?

@HarshCasper @vybhav72954 @sohamsshah

**Comment by rahulraikwar00** [comment]
> Hey, 
> I am stuck 
> link: https://in.godaddy.com/domainsearch/find?checkAvail=1&domainToCheck=akhil
> 
> soup.find() is always returning None. I am in search of  < div class="domain-name" > which is deep inside < div id='search-app'>
> Can you help me out 
> 
> OR
> I have an alternate solution for the same can I take a scrolling screenshot by using selenium.
> is it fine?
> 
- > @HarshCasper @vybhav72954 @sohamsshah 
> 
> 

I would say ,you don't need to scrape any perticular website.
Same functionality for this script can be achieve by using any free available API like "Whois Lookup API".
Check out their documentation [here](
https://www.domaintools.com/resources/api-documentation/whois-lookup)
Or @sohamsshah can help you👍🏻
