### ISSUE TITLE
Python Script to download large files from the internet.

### ISSUE THREAD

**Issue by noviicee** [HarshCasper/Rotten-Scripts#944]
# Description

This python script will help users to download any kind of files, irrespective of their size from the internet.

## Language

- [x] Python

## Checklist:

- **Details on the Script**

This script can be used to download any kind of files (files of any format), irrespective of their size from the internet.
You just need to have the url and you are good to go!

* **All_Files_Downloader**

"A script to download large files from the internet."

* GSSOC21

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Name of Script | Details of the script | feature (You can add acronyms of open source events as well) | self-assign if you want to work on this issue else leave blank |
| All_Files_Downloader | Download all kind of files from the internet, irrespective of their size. | GSSOC21 | @noviicee |

**Comment by HarshCasper** [comment]
We can do this simply using [BASH](https://unix.stackexchange.com/questions/83926/how-to-download-a-file-using-just-bash-and-nothing-else-no-curl-wget-perl-et) and some external packages. 

Are you suggesting something else here?

**Comment by noviicee** [comment]
I was thinking of doing it in Python with the help of requests and tqdm module.
The script will also display the *current download status* of the file as it gets downloaded.

**Comment by noviicee** [comment]
Can I work on this? @HarshCasper

**Comment by vybhav72954** [comment]
> I was thinking of doing it in Python with the help of requests and tqdm module.
> The script will also display the _current download status_ of the file as it gets downloaded.

Nearly every downloader has your above-said features, If you want to work on this, kindly confirm if you can incorporate pipelining, and how? I will assign you the issue after that

**Comment by vybhav72954** [comment]
@noviicee Any update regarding this?

**Comment by noviicee** [comment]
@vybhav72954 
I am sorry but I did not completely understand the issue. Like for the use of pipeline, are you asking me to do that in the script which I wanted to implement, or use it in a different script?

**Comment by vybhav72954** [comment]
> @vybhav72954 
> I am sorry but I did not completely understand the issue. Like for the use of pipeline, are you asking me to do that in the script which I wanted to implement, or use it in a different script?

The thing is, the script you mentioned, is a must have feature for any kind of downloder. It can be easily implemented using Bash, and python as well.

Can you come up with a new feature or something. Something unique or novel.

**Comment by noviicee** [comment]
> > @vybhav72954
> > I am sorry but I did not completely understand the issue. Like for the use of pipeline, are you asking me to do that in the script which I wanted to implement, or use it in a different script?
> 
> The thing is, the script you mentioned, is a must have feature for any kind of downloder. It can be easily implemented using Bash, and python as well.
> 
> Can you come up with a new feature or something. Something unique or novel.

Hmm. Yes surely! I will think of and will try to add something extra to this script to make it different from other scripts.

**Comment by vybhav72954** [comment]
> > > @vybhav72954
> > > I am sorry but I did not completely understand the issue. Like for the use of pipeline, are you asking me to do that in the script which I wanted to implement, or use it in a different script?
> > 
> > The thing is, the script you mentioned, is a must have feature for any kind of downloder. It can be easily implemented using Bash, and python as well.
> > 
> > Can you come up with a new feature or something. Something unique or novel.
> 
> Hmm. Yes surely! I will think of and will try to add something extra to this script to make it different from other scripts.

Tell me what you have in mind, then only the issue will get assigned.

**Comment by noviicee** [comment]
> > > @vybhav72954
> > > I am sorry but I did not completely understand the issue. Like for the use of pipeline, are you asking me to do that in the script which I wanted to implement, or use it in a different script?
> > 
> > 
> > The thing is, the script you mentioned, is a must have feature for any kind of downloder. It can be easily implemented using Bash, and python as well.
> > Can you come up with a new feature or something. Something unique or novel.
> 
> Hmm. Yes surely! I will think of and will try to add something extra to this script to make it different from other scripts.


> > > > @vybhav72954
> > > > I am sorry but I did not completely understand the issue. Like for the use of pipeline, are you asking me to do that in the script which I wanted to implement, or use it in a different script?
> > > 
> > > 
> > > The thing is, the script you mentioned, is a must have feature for any kind of downloder. It can be easily implemented using Bash, and python as well.
> > > Can you come up with a new feature or something. Something unique or novel.
> > 
> > 
> > Hmm. Yes surely! I will think of and will try to add something extra to this script to make it different from other scripts.
> 
> Tell me what you have in mind, then only the issue will get assigned.

A script to easily/quickly download files from webpages, provided the link..?
It will let the user choose whether they want to manually verify which files to save/download, during the script, or just "blindly" download all the links that the webpage contains.
It will also let the user quit in between if they want to.

**Comment by vybhav72954** [comment]
I think we are going round and round now. As stated already, the idea is not novel. THank you! please open another issue or maybe  try one of the open issues
