### ISSUE TITLE
Automated Noise Removal

### ISSUE THREAD

**Issue by owlrana** [HarshCasper/Rotten-Scripts#947]
# Description
The fundamental aim of this script is to automate the process of Audio Extraction, Profiling and Cleaning before the Mixing Stage for Voice-Overs or Audio Recordings in videos that is adjustable according to the user using Python. This is achieved with the help of the following open-sourced software:
FFmpeg
Sox
Audacity

## Language
- [x] Python

| name            | about                                                  | labels  | assignees                                                      |
| Automated Noise Removal | Extract Audio from multiple video files and de-noise them automatically | Python, NewFunctionality, opensource | @owlrana |

**Is your feature request related to a problem? Please describe.**: 

I'm always frustrated when I need to denoise a number of audio files at once. One needs to first extract each audio file from videos, then create a noise profile separately for each audio file and export them separately after this process.
The whole job takes me more than an hour for 5-7 audio files.  Below is the solution that I propose to this problem.

**Describe the solution you'd like**: 
The solution is to automate the process of extraction, creating a noise profile for each audio file separately using python and then de-noise it using Audacity's already developed open algorithms, then also export it. 
This should take no more than 2-3 minutes for 10+ audio files, which will be a huge improvement from 1 hour.

**Comment by owlrana** [comment]
Can you please assign this issue to me as a GSSoC '21 Participant? I would like to work on this and contribute to this issue.

**Comment by vybhav72954** [comment]
@HarshCasper I have worked on this field, though it's not useful for me, I like the idea, using `opensmile` this can be turned into a full-fledged project by the OP as well.

**Comment by vybhav72954** [comment]
@owlrana Updates?

**Comment by vybhav72954** [comment]
GUI scripts are something that we don't have here. Only CLI implementations.

**Comment by owlrana** [comment]
It's alright, no problem! :')

**Comment by owlrana** [comment]
Please verify and accept: https://github.com/HarshCasper/Rotten-Scripts/pull/1014
I also need to update it later with the readMe.md file and screenshots for everyone to understand it.

**Comment by owlrana** [comment]
Merge #1014 , close this.

**Comment by owlrana** [comment]
Close by mistake, please merge.
https://github.com/HarshCasper/Rotten-Scripts/pull/1014
