### ISSUE TITLE
Script that automatic Spell-checking / correcting for a given input file/text

### ISSUE THREAD

**Issue by sohamsshah** [HarshCasper/Rotten-Scripts#948]
# Description

A script to implement spell checking and rectifying for a given input text in PDF form, Word Doc or other popular format. A great feature that can be used for automated software that does answer-sheet checking, Resume anaylsis or a tool to improve language.

## Language

- [X] Go
- [X] Javascript
- [X] Python

## Checklist:

 

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| -------------------------------------------------------------- | -------------------------------------------------------------- | -------------------------------------------------------------- | -------------------------------------------------------------- |
| Spell-checker | Script to perform a spell checking/ correcting for the text | JavaScript, Python, good-first-issue, medium |  |

**Describe the solution you'd like**: 
Spell checking tools are a quite helpful for various tasks especially in language-based applications. This script can provide much value for implementing such feature.

**Additional context**: 

The must-have features: Spell Checking, logging the mistaken words etc.
Good to have features: Grammatical mistakes also checked and suggests changes.

Not needed to change those words in the file. As the first iteration, just logging/telling the use where one can improve and what to improve can be a good start. Make sure the line numbers are logged along as well. There are various `npm` packages and python Libs available for doing this. 

Though, it is not limited to this. Would love to discuss how and what can be done. Feel free to ping me re: this feature implementation.

**Comment by tanishq-arya** [comment]
Can I work on this in python under gssoc?

**Comment by sohamsshah** [comment]
> Can I work on this in python under gssoc?

Sure. Excited to see your implementation and script. Feel free to seek help, will be active on responses :) Good luck!

**Comment by tanishq-arya** [comment]
Can you tell me if I am going in the right direction here ? @sohamsshah 
![Screenshot (1143)](https://user-images.githubusercontent.com/77333275/114184258-4053a380-9962-11eb-9712-82c06439f1b7.png)

**Comment by sohamsshah** [comment]
@tanishq-arya I suppose you are on the right track. For the punctuation marks, there might be some method in `nltk` that can be used; or if you are stuck for that; since it is only for spelling checks, only `alphanum` is required for this purpose as special chars won't be considered in this. Hope this helps!

**Comment by sohamsshah** [comment]
@tanishq-arya are you working on this?

**Comment by tanishq-arya** [comment]
@sohamsshah Yes. Will make a PR by Sunday.

**Comment by sohamsshah** [comment]
Awesome
