### ISSUE TITLE
Python script sort the images according to resolution

### ISSUE THREAD

**Issue by RJ535315** [HarshCasper/Rotten-Scripts#955]
# Description

 A python script to sort the images in our pc folders according to the resolution and group them by the resolution, by creating separate folders

## Language

- [ ] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Name of Script | Details of the script | feature (You can add acronyms of open source events as well) | self-assign if you want to work on this issue else leave blank |
| Image-Sorting | A python script to sort the images in our pc folders according to the resolution and group them by the resolution, by creating separate folders | gssoc21 | @rj535315 |

**Is your feature request related to a problem? Please describe.**: 

Yes, We always have the problem of finding a desired resolution containing image in a bunch of images within a folder.

**Describe the solution you'd like**: 

 In order to find a solution to this problem, this is a python script which sorts images according to resolution and group them into sub folders according to resolution 

please assign this issue to me.
Thanks in advance

**Comment by RJ535315** [comment]
Hi @vybhav72954 , I just made the PR realted to this issue. Please check and review it. Thank  you.

**Comment by HarshCasper** [comment]
> Hi @vybhav72954 , I just made the PR realted to this issue. Please check and review it. Thank you.

Can you please link it to this issue?
