### ISSUE TITLE
GUI based BMI calculator

### ISSUE THREAD

**Issue by geekymeeky** [HarshCasper/Rotten-Scripts#956]
# Aim

- A simple python GUI based BMI calculator

# Motivation

Maintaining a healthy weight is important for overall health and can help to prevent and control many diseases and conditions.  Excess weight or obesity increases the risk of developing serious health problems, including heart disease, high blood pressure, type 2 diabetes and various other diseases.  Therefore, it is important to maintain a healthy weight.  It helps to reduce the risk of developing these issues, helps to feel good, and gives more energy to enjoy life.

**Comment by geekymeeky** [comment]
I would like to work on this issue. Please assign this to me under GSSoC'21

**Comment by vybhav72954** [comment]
Hey @geekymeeky Welcome to Rotten Scripts. GUI-based scripts aren't included here in Rotten-Scripts. Am pretty sure you will some other issues. Sorry but will have to close this one!

**Comment by geekymeeky** [comment]
> Hey @geekymeeky Welcome to Rotten Scripts. GUI-based scripts aren't included here in Rotten-Scripts. Am pretty sure you will some other issues. Sorry but will have to close this one!

I can create a CLI based BMI calculator.  Let me know if it works.

**Comment by vybhav72954** [comment]
I will reopen your issue. Personally i don't know if we need a BMI calculator cause its a simple formula after all, though I will leave this to @HarshCasper

**Comment by geekymeeky** [comment]
@HarshCasper Please let me know, if this can be added in your repo.

> > Hey @geekymeeky Welcome to Rotten Scripts. GUI-based scripts aren't included here in Rotten-Scripts. Am pretty sure you will some other issues. Sorry but will have to close this one!
> 
> I can create a CLI based BMI calculator. Let me know if it works.

**Comment by HarshCasper** [comment]
Hi @geekymeeky 

Its not my repo. Its our repository :smile:  

With that said, we do have a strict maintenance to allow only the useful stuff coming up here. Unfortunately, I don't see the point of having a BMI Script for that. I'm closing this issue but there are many open issues which you can take up.
