### ISSUE TITLE
Go Port Scanner Syntax Errors

### ISSUE THREAD

**Issue by VanTekken** [HarshCasper/Rotten-Scripts#957]
# Description 
The Go port scanner returns syntax error when using the instructions to execute with go version `go1.16.3 linux/amd64`

**To Reproduce**
1. `$ wget https://raw.githubusercontent.com/HarshCasper/Rotten-Scripts/master/Go/Port_Scanner/port_scanner.go`
2. `go run ./port_scanner.go`
3. Syntax error:
```
$ go run ./port_scanner.go
# command-line-arguments
./port_scanner.go:39:17: syntax error: unexpected :, expecting {
./port_scanner.go:41:15: syntax error: unexpected {, expecting for loop condition
./port_scanner.go:42:19: syntax error: missing statement after label
./port_scanner.go:46:16: syntax error: unexpected :, expecting := or = or comma
./port_scanner.go:52:9: syntax error: non-declaration statement outside function body
./port_scanner.go:61:10: syntax error: missing statement after label
```
**Expected behavior**
Successful execution of the port scanner file

**Additional context**
System: Linux
Go Version: 1.16.3

**Comment by vybhav72954** [comment]
@VanTekken Thnks for pointing this out 😄

**Comment by NovusEdge** [comment]
I would like to take this one up if no one's assigned

**Comment by vybhav72954** [comment]
@NovusEdge Good to go
