### ISSUE TITLE
Edge_Detection_of_any_image

### ISSUE THREAD

**Issue by ShubhamGupta577** [HarshCasper/Rotten-Scripts#958]
# Description

In this Script, we going to detect the edges of an image using a python script.
In our script, the user has to just upload a picture and as an output, he/she will get an edge-detected picture. For this purpose, we are going to use OpenCV.
It is very useful because edges are the points in images where the color or brightness has great changes.

## Language

- [x] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Edge Detection of an image | In this Script, we going to detect the edges of an image using `OpenCV` | GSSOC Python | @ShubhamGupta577 |

**Comment by ShubhamGupta577** [comment]
I want to work on this issue under GSSOC'21. Please assign me this issue.

**Comment by vybhav72954** [comment]
Open in #937

**Comment by vybhav72954** [comment]
@ShubhamGupta577 
let me put this in simple terms.

The CONTRIBUTION GUIDELINES are meant to be viewed before contributing, If an issue is open, making a duplicate issue is a wastage of your time.

Making a PR for an issue marked duplicate is a bigger wastage of time.

I don't know, why you made the PR, but there is no use in spamming in this Repo.

Please go through the guidelines of GSSOC and Rotten Scripts. Feel free to take valid issues, but another but we don't appreciate spam.
