### ISSUE TITLE
Implementing SIFT for detect local features of image.

### ISSUE THREAD

**Issue by ShubhamGupta577** [HarshCasper/Rotten-Scripts#967]
# Description

- In this script, we are going to implement SIFT(Scale Invariant Feature Transform) algorithm of `Open CV`.
- The SIFT features are local and based on the appearance of the object at particular interest points, and are invariant to image scale and rotation.

## Language

- [x] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| SIFT algorithm | We use Python to implement SIFT algorithm of Open CV to detect the feature of image | GSSOC21 Python | @ShubhamGupta577 |

**Comment by ShubhamGupta577** [comment]
Under the GSSOC'21, I want to work on this. Please assign me this issue.

**Comment by vybhav72954** [comment]
@HarshCasper

**Comment by HarshCasper** [comment]
Interesting one. Assigned :+1:
