### ISSUE TITLE
Instagram Liker Bot

### ISSUE THREAD

**Issue by sayantani11** [HarshCasper/Rotten-Scripts#968]
# Description

- This script will allow liking of all visible posts by another.
- This script can be used while creating a auto liker site

## Language

- [x] Python

| name             | about                                           | label| assignees    
| ------------- |:-------------:| :-----:|:-----:|
| Instagram Liker Bot      | Will auto like visible instagram post of an user | GSSOC21 , Python | @sayantani11 |

**Comment by sayantani11** [comment]
Under GSSOC'21 please assign me this issue

**Comment by devRawnie** [comment]
Hi, I created a command line script for twitter, using Python. I am confident that I would be able to do this too using python. Please assign this to me under GSSOC'21

**Comment by sayantani11** [comment]
@HarshCasper Please assign this to me

**Comment by vybhav72954** [comment]
@devRawnie Cant assign you this, as the issue was opened by @sayantani11 in the first place.
@HarshCasper I like the idea. What do you think?

**Comment by HarshCasper** [comment]
We have already this script, I guess in JavaScript. I'm still assigning the same, to see what is the net result.

**Comment by sayantani11** [comment]
I tried to fix the errors but I am unable to
