### ISSUE TITLE
Track Stargazers, save the info in JSON/CSV.

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#973]
# Description

So recently our _Project has been trending on GitHub!!!_, Kudos 🥳  

We are about to touch 500 ⭐s as well!
First and foremost, thank you, everyone, it's the cumulative efforts of every contributor to date.

I was really interested in the upward trend and wanted to do some analysis of the recent upsurge. I found a few good projects (see references) for the same.

Those projects are full-fledged codebases consisting of multiple functionalities. I think a simpler script (maybe even a wrapper around GitHub API), that can **list out recent (or all) Stargazers**, **those who unstarred recently**, **Location** (if possible), **email** (we have a good script for that in this repo prepared by @rahulraikwar00) would be a good fit for this project.

## Language

- [x] Go
- [x] Javascript
- [x] Python

## Checklist:

- **Details on the Script**

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Track Stargazers | See Description | feature, gssoc21 |  |

**Additional context**: 

Refernces:
- [1](https://github.com/marius92mc/github-stargazers)
- [2](https://github.com/kiok46/Track-Stargazers)
- [3](https://docs.github.com/en/rest/reference/activity)

**Comment by jhamadhav** [comment]
So the goal is to 
1. List out all the people who have starred this repo
2. List out all the people who have recently unstarred
3. Their name, location *(if possible)* and their email
correct ?

**Comment by vybhav72954** [comment]
> So the goal is to
> 
> 1. List out all the people who have starred this repo
> 2. List out all the people who have recently unstarred
> 3. Their name, location _(if possible)_ and their email
>    correct ?

Yes

**Comment by jhamadhav** [comment]
Can I work on this?

**Comment by vybhav72954** [comment]
Sure thing. All the best

**Comment by jhamadhav** [comment]
Thanks 😄 , I will get it done as soon as possible 👍
