### ISSUE TITLE
Social-Media-Launcher-Chrome-Extension

### ISSUE THREAD

**Issue by neha07kumari** [HarshCasper/Rotten-Scripts#975]
# Description

Simple Chrome Extension for a quick launcher to your all social media profiles at one click.

## Language

- [x] HTML
- [x] Javascript
- [x] json

| name            | about                                                  | labels  | assignees                                                      |
|-----------------------------------------------|-------------------------------------------------------------------------------------------|-------------------------------------------|-----------------------|
| Social-Media_launcher-Chrome-Extension |Simple Chrome Extension for a quick launcher to your all social media profiles at one click.  | GSSOC'21  ,  Javascript |@neha07kumari |

/assign

**Comment by neha07kumari** [comment]
@HarshCasper  Please assign me.

**Comment by vybhav72954** [comment]
GUI-based scripts are not a part of Rotten-Script. And I don't think a CLI version of this is possible. Feel free to comment here for any dispute though.
