### ISSUE TITLE
Meditation_Website

### ISSUE THREAD

**Issue by neha07kumari** [HarshCasper/Rotten-Scripts#976]
# Description

 a website which will help you to meditate according to the time duration you want.

## Language

- [x] HTML
- [x] Javascript
- [x] CSS

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
|Meditation_Website |  a website which will help you to meditate according to the time duration you want.| GSSOC'21,  javascript |neha07kumari |

/assign

**Comment by neha07kumari** [comment]
@HarshCasper Please assign me.

**Comment by vybhav72954** [comment]
GUI-based scripts are not a part of Rotten-Script. And I don't think a CLI version of this is possible.
