### ISSUE TITLE
Time series forecasting covid 19 case 

### ISSUE THREAD

**Issue by ayush-raj8** [HarshCasper/Rotten-Scripts#977]
# AIM
Predicting number of covid 19 cases for next 21 days

What is the objective of the Script
It uses daily updated data to forecast number of fresh, death and recovered covid 19 cases for next 21 days.

Languages
[*] Python

| name            | problem/motivation                                                  | possible solution  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Forecasting Covid 19 cases for near future | This can help the administration have an idea about the number of cases they might face in say next 21 days. This will give them time to prepare themselves.|A python  script that uses daily upadated live data to predict no of fresh , deaths and recoveries in near future. | @ayush-raj8 |

**Comment by ayush-raj8** [comment]
Under the GSSOC'21, I want to work on this. Please assign me this issue.

**Comment by vybhav72954** [comment]
@HarshCasper Have a look please.

**Comment by ayush-raj8** [comment]
@HarshCasper or @vybhav72954  Plz confirm if I can  start working on this ???

**Comment by HarshCasper** [comment]
I'm sorry but we don't need scripts that don't specify any particular use-case. In this case, the algorithms and tools would be highly subjective and debatable. Thanks for contributing!
