### ISSUE TITLE
Update Python Script List

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/Rotten-Scripts#978]
# Description

Recently the markdown file for the `Python` directory was reformatted, since then the list hasn't been updated.
Follow the same structure as of the README, update the list alphabetically.

**Comment by iamansoni** [comment]
I would like to work on this task. You can assign it to me!

**Comment by vybhav72954** [comment]
I can do that, but why don't you try commenting `/assign` @iamansoni 😉

**Comment by iamansoni** [comment]
`assign` @iamansoni

**Comment by vybhav72954** [comment]
Not like that. I will assign you myself this time XD

**Comment by vybhav72954** [comment]
@iamansoni Updates?

**Comment by vybhav72954** [comment]
@iamansoni Please confirm the status ASAP, A week is more than enough for this.

**Comment by vybhav72954** [comment]
@ireneelizabethsabu Can you have a look at this as well?

**Comment by ireneelizabethsabu** [comment]
> @ireneelizabethsabu Can you have a look at this as well?

Sure :)
