### ISSUE TITLE
Object Detection using python

### ISSUE THREAD

**Issue by neha07kumari** [HarshCasper/Rotten-Scripts#982]
# Description

The script will detect the objects in the picture.

## Language

- [x] Python

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| object detection using python |the script will detect the objects from the pictures displayed | GSSOC'21, python |@neha07kumari |

/assign

**Comment by neha07kumari** [comment]
@HarshCasper  Please assign this issue to me.

**Comment by vybhav72954** [comment]
Try typing the `assign` keyword in the comments. Just like the way you did in the body of PR (with the backslash). I cant write it here, else it would be assigned to me XD

**Comment by neha07kumari** [comment]
@vybhav72954  Can i work on this issue?

**Comment by vybhav72954** [comment]
What it didnt worked. Why

> /assign

**Comment by vybhav72954** [comment]
> @vybhav72954 Can i work on this issue?

As you can see the issue has been assigned to you. But a word of caution. What you are proposing is a fairly general script. Please don't indulge in any plagiarism, we are strictly against that.

All the best, feel free to ask me anything if needed.

**Comment by neha07kumari** [comment]
> > @vybhav72954 Can i work on this issue?
> 
> As you can see the issue has been assigned to you. But a word of caution. What you are proposing is a fairly general script. Please don't indulge in any plagiarism, we are strictly against that.
> 
> All the best, feel free to ask me anything if needed.

Sure ☺

**Comment by neha07kumari** [comment]
@vybhav72954  I have created a PR #985 . Please review it and let me know if  any changes are needed.
