### ISSUE TITLE
Password Checker 

### ISSUE THREAD

**Issue by RohiniRG** [HarshCasper/Rotten-Scripts#993]
# Description

Describe the new feature you are proposing.

| name            | possible solution  | assignees                                                      |
| --------------- |------- | -------------------------------------------------------------- |
| Password Checker | This script uses API of https://haveibeenpwned.com/ and checks how many times your password has been hacked | @RohiniRG  |

I am a GSSOC21 Participant @HarshCasper kindly assign me the same

**Comment by vybhav72954** [comment]
Hey @RohiniRG, this exactly isn't a password checker right?

Name the script properly whenever you make the PR.

**Comment by RohiniRG** [comment]
@vybhav72954 could have a look at this PR.
