### ISSUE TITLE
Doc/ppt file to pdf convertor 

### ISSUE THREAD

**Issue by immanishbainsla** [HarshCasper/Rotten-Scripts#994]
# Description
It converts your doc and ppt files to pdf files

| name            | problem/motivation                                                  | possible solution  | assignees    

| DoctoPdf and PpttoPdf Convertor | It doesn't require internet connection and it's super easy to use with just 1 command | I will be implementing it in python | Manish Bainsla (self-assign)

**Comment by vybhav72954** [comment]
@HarshCasper The issue is rather simple, but last I checked we lack this functionality in the Repo, this looks good to me. But still have a look.
