### ISSUE TITLE
Script to Accept all friend requests on Facebook

### ISSUE THREAD

**Issue by SalmaZakaria** [HarshCasper/Rotten-Scripts#998]
# Description

Script to Accept all friend requests on Facebook using js

## Language

Javascript

**Comment by SalmaZakaria** [comment]
I am a GSSOC'21 Participant

**Comment by SalmaZakaria** [comment]
@vybhav72954 Add GSSOC21 label please

**Comment by tanyalava** [comment]
Can you please assign this issue to me, I will solve it clearly

**Comment by Sukriti-sood** [comment]
@HarshCasper Can I write code script in Other Language or only in Javascript.

**Comment by HarshCasper** [comment]
> @HarshCasper Can I write code script in Other Language or only in Javascript.

Whatever you wish in.
